import type { DashboardEvent, DashboardUser } from "./types";

export const currentUser: DashboardUser = {
  name: "Jake Hamann",
  email: "jake@momentify.com",
  initials: "JH",
};

export const workspaceName = "ENTEVATE";

const gradients = [
  "linear-gradient(135deg, #6B21D4, #9333EA)",
  "linear-gradient(135deg, #1A2E73, #3257D9)",
  "linear-gradient(135deg, #00BBA5, #0CF4DF)",
  "linear-gradient(135deg, #F25E3D, #F59E0B)",
  "linear-gradient(135deg, #3A2073, #6B21D4)",
  "linear-gradient(135deg, #0B0B3C, #1A2E73)",
  "linear-gradient(135deg, #F2B33D, #F59E0B)",
  "linear-gradient(135deg, #5FD9C2, #00BBA5)",
  "linear-gradient(135deg, #7C316D, #E5484D)",
  "linear-gradient(135deg, #254FE5, #0CF4DF)",
  "linear-gradient(135deg, #1F3395, #3257D9)",
  "linear-gradient(135deg, #F25E3D, #7C316D)",
];

export const mockEvents: DashboardEvent[] = [
  {
    id: "1",
    name: "Global Tech Summit 2026",
    startDate: "2026-06-15",
    endDate: "2026-06-18",
    location: "San Francisco, CA",
    coverGradient: gradients[0],
    sessionsCount: 24,
    status: "upcoming",
    assignee: { name: "Jake Hamann", initials: "JH" },
  },
  {
    id: "2",
    name: "Industry Connect 2026",
    startDate: "2026-05-10",
    endDate: "2026-05-12",
    location: "Chicago, IL",
    coverGradient: gradients[1],
    sessionsCount: 12,
    status: "upcoming",
    assignee: { name: "Sarah Chen", initials: "SC" },
  },
  {
    id: "3",
    name: "Builder Expo West",
    startDate: "2026-04-01",
    endDate: "2026-04-04",
    location: "Las Vegas, NV",
    coverGradient: gradients[2],
    sessionsCount: 0,
    status: "upcoming",
    assignee: { name: "Mike Torres", initials: "MT" },
  },
  {
    id: "4",
    name: "Talent Acquisition Live",
    startDate: "2026-03-20",
    endDate: "2026-03-22",
    location: "Austin, TX",
    coverGradient: gradients[3],
    sessionsCount: 8,
    status: "live",
    roxScore: 78,
    assignee: { name: "Jake Hamann", initials: "JH" },
  },
  {
    id: "5",
    name: "Manufacturing Summit",
    startDate: "2026-02-16",
    endDate: "2026-02-20",
    location: "Las Vegas, NV",
    coverGradient: gradients[4],
    sessionsCount: 12,
    status: "past",
    roxScore: 34,
    assignee: { name: "Anna Kim", initials: "AK" },
  },
  {
    id: "6",
    name: "Campus Career Fair",
    startDate: "2026-02-10",
    endDate: "2026-02-12",
    location: "Boston, MA",
    coverGradient: gradients[5],
    sessionsCount: 38,
    status: "past",
    roxScore: 82,
    assignee: { name: "Sarah Chen", initials: "SC" },
  },
  {
    id: "7",
    name: "Field Sales Kickoff",
    startDate: "2026-01-25",
    endDate: "2026-01-27",
    location: "Dallas, TX",
    coverGradient: gradients[6],
    sessionsCount: 15,
    status: "past",
    roxScore: 67,
    assignee: { name: "Mike Torres", initials: "MT" },
  },
  {
    id: "8",
    name: "Experiential Marketing Conf",
    startDate: "2025-12-08",
    endDate: "2025-12-10",
    location: "Miami, FL",
    coverGradient: gradients[7],
    sessionsCount: 18,
    status: "past",
    roxScore: 45,
    assignee: { name: "Jake Hamann", initials: "JH" },
  },
  {
    id: "9",
    name: "Facilities Management Expo",
    startDate: "2025-11-15",
    endDate: "2025-11-17",
    location: "Orlando, FL",
    coverGradient: gradients[8],
    sessionsCount: 22,
    status: "past",
    roxScore: 71,
    assignee: { name: "Anna Kim", initials: "AK" },
  },
  {
    id: "10",
    name: "Innovation Showcase",
    startDate: "2025-10-20",
    endDate: "2025-10-22",
    location: "Denver, CO",
    coverGradient: gradients[9],
    sessionsCount: 8,
    status: "past",
    roxScore: 22,
    assignee: { name: "Sarah Chen", initials: "SC" },
  },
  {
    id: "11",
    name: "Energy Conference 2025",
    startDate: "2025-09-14",
    endDate: "2025-09-16",
    location: "Houston, TX",
    coverGradient: gradients[10],
    sessionsCount: 10,
    status: "past",
    roxScore: 58,
    assignee: { name: "Mike Torres", initials: "MT" },
  },
  {
    id: "12",
    name: "Community Engagement Summit",
    startDate: "2025-08-05",
    endDate: "2025-08-07",
    location: "Portland, OR",
    coverGradient: gradients[11],
    sessionsCount: 6,
    status: "past",
    roxScore: 41,
    assignee: { name: "Jake Hamann", initials: "JH" },
  },
];
