import type { CalendarTask } from "./calendar-types"

export const defaultCalendarTasks: CalendarTask[] = [
  // ── Week 1 (Mar 24-27): Trade Shows + Recruiting focus ──────────────

  // Tuesday Mar 24
  {
    id: "task-001",
    title: "LinkedIn post: 3 ROX metrics every booth manager should track",
    category: "linkedin-post",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Publish thought leadership post highlighting Lead Capture Efficiency, Engagement Quality, and Conversion Effectiveness as the three pillars of trade show ROX.",
    sortOrder: 1,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-002",
    title: "Cold email: Manufacturing sector ROX Audit outreach",
    category: "cold-email",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Send personalized outreach to 15 manufacturing VP-level contacts offering a complimentary ROX Audit for their upcoming trade show season.",
    sortOrder: 2,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-003",
    title: "Content creation: Draft recruiting ROX one-pager",
    category: "content-creation",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Write first draft of the one-pager showing how badge scanning at career fairs improves candidate follow-up speed by 3x.",
    sortOrder: 3,
    roxTouchpoint: "Follow-Up Speed",
  },

  // Tuesday Mar 24
  {
    id: "task-004",
    title: "LinkedIn post: Why career fair badge scanning beats paper sign-ups",
    category: "linkedin-post",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Share a short story about a recruiter who cut candidate follow-up time from 5 days to same-day using digital capture.",
    sortOrder: 1,
    roxTouchpoint: "Follow-Up Speed",
  },
  {
    id: "task-005",
    title: "Cold email: University recruiting teams outreach",
    category: "cold-email",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Target 10 university talent acquisition leads with ROX data on digital vs. paper candidate capture at campus events.",
    sortOrder: 2,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-006",
    title: "Internal review: Trade show campaign messaging alignment",
    category: "internal-review",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 45,
    completed: false,
    description: "Review all trade show outbound messaging with the team to ensure consistent ROX language and value props.",
    sortOrder: 3,
    roxTouchpoint: "Conversion Effectiveness",
  },

  // Wednesday Mar 25
  {
    id: "task-007",
    title: "Partner outreach: AV rental companies for trade show co-marketing",
    category: "partner-outreach",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 40,
    completed: false,
    description: "Reach out to three AV rental companies about co-branded content on maximizing booth engagement with interactive displays.",
    sortOrder: 1,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-008",
    title: "Lead magnet: Outline ROX Calculator landing page copy",
    category: "lead-magnet",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Create the copy outline for the ROX Calculator landing page, focusing on the value prop of measuring real event returns.",
    sortOrder: 2,
    roxTouchpoint: "Conversion Effectiveness",
  },
  {
    id: "task-009",
    title: "Social post: Share recruiting success stat carousel",
    category: "social-post",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 25,
    completed: false,
    description: "Post a carousel graphic on Instagram and Twitter showing key stats on digital candidate capture at career fairs.",
    sortOrder: 3,
    roxTouchpoint: "Lead Capture Efficiency",
  },

  // Thursday Mar 26
  {
    id: "task-010",
    title: "Cold email: Energy sector ROX Audit outreach",
    category: "cold-email",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Send targeted outreach to 12 energy sector marketing directors offering a free ROX Audit for their Q2 conference schedule.",
    sortOrder: 1,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-011",
    title: "Discovery call: TechHire Inc. recruiting workflow demo",
    category: "discovery-call",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Walk TechHire through badge scanning at campus recruiting events, focusing on their pain point of slow candidate data entry.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },
  {
    id: "task-012",
    title: "Content creation: Trade show ROX infographic draft",
    category: "content-creation",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Design the first draft of a visual infographic comparing traditional vs. digital lead capture ROX at trade shows.",
    sortOrder: 3,
    roxTouchpoint: "Engagement Quality",
  },

  // Friday Mar 27
  {
    id: "task-013",
    title: "LinkedIn post: 5 questions to ask before your next trade show",
    category: "linkedin-post",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Publish a short listicle-style post to drive engagement and position Momentify as a thought leader in trade show optimization.",
    sortOrder: 1,
    roxTouchpoint: "Conversion Effectiveness",
  },
  {
    id: "task-014",
    title: "Follow-up: Manufacturing outreach replies from Monday",
    category: "follow-up",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 30,
    completed: false,
    description: "Respond to any replies from the Monday manufacturing cold email batch and schedule discovery calls where appropriate.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },

  // ── Week 2 (Mar 30 - Apr 3): Trade Shows + Recruiting continued ─────

  // Monday Mar 30
  {
    id: "task-015",
    title: "Cold email: Healthcare recruiting teams outreach",
    category: "cold-email",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Target 12 healthcare system talent acquisition managers with data on reducing time-to-hire through digital event capture.",
    sortOrder: 1,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-016",
    title: "LinkedIn post: The hidden cost of slow candidate follow-up",
    category: "linkedin-post",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Share a data-driven post about how each day of follow-up delay reduces candidate acceptance rates by 10%.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },
  {
    id: "task-017",
    title: "Lead magnet: Finalize ROX Calculator landing page copy",
    category: "lead-magnet",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Finalize all headlines, body copy, and CTA text for the ROX Calculator landing page based on team feedback.",
    sortOrder: 3,
    roxTouchpoint: "Conversion Effectiveness",
  },

  // Tuesday Mar 31
  {
    id: "task-018",
    title: "Event prep: Compile demo script for IMTS trade show",
    category: "event-prep",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Build out the live demo flow for the IMTS booth, including badge scan, real-time dashboard, and ROX score walkthrough.",
    sortOrder: 1,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-019",
    title: "Partner outreach: Staffing agency co-webinar pitch",
    category: "partner-outreach",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Pitch two staffing agencies on co-hosting a webinar about modernizing candidate capture at job fairs.",
    sortOrder: 2,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-020",
    title: "Content creation: Blog post on trade show lead scoring",
    category: "content-creation",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 75,
    completed: false,
    description: "Draft a 1,200-word blog post on how real-time lead scoring at trade shows transforms follow-up prioritization.",
    sortOrder: 3,
    roxTouchpoint: "Conversion Effectiveness",
  },

  // Wednesday Apr 1
  {
    id: "task-021",
    title: "Social post: Before/after booth engagement graphic",
    category: "social-post",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 25,
    completed: false,
    description: "Post a visual comparison showing booth engagement metrics before and after implementing digital lead capture.",
    sortOrder: 1,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-022",
    title: "Discovery call: NovaTech recruiting platform demo",
    category: "discovery-call",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Demo the badge scanning and candidate pipeline integration for NovaTech's campus recruiting team.",
    sortOrder: 2,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-023",
    title: "Internal review: Recruiting one-pager final review",
    category: "internal-review",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 30,
    completed: false,
    description: "Final team review of the recruiting ROX one-pager before it goes to design for layout.",
    sortOrder: 3,
    roxTouchpoint: "Follow-Up Speed",
  },

  // Thursday Apr 2
  {
    id: "task-024",
    title: "Cold email: Automotive trade show organizers",
    category: "cold-email",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Send outreach to 10 automotive industry event organizers about partnering on ROX-driven booth experiences.",
    sortOrder: 1,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-025",
    title: "Follow-up: Healthcare recruiting replies",
    category: "follow-up",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 30,
    completed: false,
    description: "Follow up on healthcare recruiting outreach from Monday and log responses in the CRM.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },

  // Friday Apr 3
  {
    id: "task-026",
    title: "LinkedIn post: Career fair ROX benchmark data",
    category: "linkedin-post",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Share aggregated benchmark data on digital candidate capture rates vs. paper-based methods at career fairs.",
    sortOrder: 1,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-027",
    title: "Content creation: Trade show ROX checklist PDF",
    category: "content-creation",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Create a downloadable pre-show checklist covering tech setup, staffing plan, and ROX measurement framework.",
    sortOrder: 2,
    roxTouchpoint: "Conversion Effectiveness",
  },

  // ── Week 3 (Apr 6-10): Add Field Sales ──────────────────────────────

  // Monday Apr 6
  {
    id: "task-028",
    title: "Cold email: Field sales teams at industrial distributors",
    category: "cold-email",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Launch outreach to 15 regional sales managers at industrial distribution companies about mobile lead capture during site visits.",
    sortOrder: 1,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-029",
    title: "LinkedIn post: How field reps lose leads between jobsite and CRM",
    category: "linkedin-post",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Publish a relatable post about the gap between capturing interest on-site and getting that data into the CRM the same day.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },
  {
    id: "task-030",
    title: "Content creation: Field sales mobile capture use case brief",
    category: "content-creation",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Write a two-page use case brief on how mobile badge scanning helps field reps capture and sync leads during client visits.",
    sortOrder: 3,
    roxTouchpoint: "Lead Capture Efficiency",
  },

  // Tuesday Apr 7
  {
    id: "task-031",
    title: "Partner outreach: CRM integration partners for field sales",
    category: "partner-outreach",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 40,
    completed: false,
    description: "Reach out to two CRM vendors about co-marketing on seamless field data sync from mobile capture to pipeline.",
    sortOrder: 1,
    roxTouchpoint: "Conversion Effectiveness",
  },
  {
    id: "task-032",
    title: "Cold email: Recruiting agencies for Q2 hiring push",
    category: "cold-email",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Target 10 recruiting agencies ramping up for Q2 hiring events with data on ROX improvements from digital capture.",
    sortOrder: 2,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-033",
    title: "Internal review: Field sales messaging and positioning",
    category: "internal-review",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 45,
    completed: false,
    description: "Align the team on field sales value props, personas, and competitive differentiators before scaling outreach.",
    sortOrder: 3,
    roxTouchpoint: "Engagement Quality",
  },

  // Wednesday Apr 8
  {
    id: "task-034",
    title: "LinkedIn post: Trade show season Q2 prep tips",
    category: "linkedin-post",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Post a Q2 trade show prep guide covering booth tech, lead capture goals, and pre-show outreach best practices.",
    sortOrder: 1,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-035",
    title: "Discovery call: Acme Industrial field sales workflow demo",
    category: "discovery-call",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Walk through how Acme's field reps can capture leads on-site and have them in Salesforce before they leave the parking lot.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },
  {
    id: "task-036",
    title: "Follow-up: Industrial distributor cold email replies",
    category: "follow-up",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 30,
    completed: false,
    description: "Respond to replies from Monday's field sales outreach and book demos for interested prospects.",
    sortOrder: 3,
    roxTouchpoint: "Follow-Up Speed",
  },

  // Thursday Apr 9
  {
    id: "task-037",
    title: "Social post: Field sales before/after data sync graphic",
    category: "social-post",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 25,
    completed: false,
    description: "Post a visual comparing manual lead entry vs. instant mobile sync for field sales teams.",
    sortOrder: 1,
    roxTouchpoint: "Follow-Up Speed",
  },
  {
    id: "task-038",
    title: "Lead magnet: Draft field sales ROX playbook outline",
    category: "lead-magnet",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Outline a downloadable playbook covering mobile lead capture, same-day follow-up, and ROX measurement for field teams.",
    sortOrder: 2,
    roxTouchpoint: "Conversion Effectiveness",
  },

  // Friday Apr 10
  {
    id: "task-039",
    title: "Event prep: Prepare for SaaS recruiting fair booth",
    category: "event-prep",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Finalize demo devices, badge scanner setup, and talking points for the upcoming SaaS recruiting fair appearance.",
    sortOrder: 1,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-040",
    title: "Content creation: Edit trade show ROX blog post",
    category: "content-creation",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 45,
    completed: false,
    description: "Incorporate team feedback on the trade show lead scoring blog post and prepare it for publication next week.",
    sortOrder: 2,
    roxTouchpoint: "Conversion Effectiveness",
  },

  // ── Week 4 (Apr 13-17): Trade Shows + Recruiting + Field Sales ──────

  // Monday Apr 13
  {
    id: "task-041",
    title: "Cold email: Construction sector field sales outreach",
    category: "cold-email",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Send outreach to 12 construction company sales directors about capturing jobsite leads with mobile scanning.",
    sortOrder: 1,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-042",
    title: "LinkedIn post: What your trade show booth data is telling you",
    category: "linkedin-post",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Post about the insights hidden in booth traffic patterns and how ROX dashboards surface them in real time.",
    sortOrder: 2,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-043",
    title: "Follow-up: Recruiting agency Q2 outreach replies",
    category: "follow-up",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 30,
    completed: false,
    description: "Follow up on recruiting agency emails sent last week and schedule demos for interested contacts.",
    sortOrder: 3,
    roxTouchpoint: "Follow-Up Speed",
  },

  // Tuesday Apr 14
  {
    id: "task-044",
    title: "Discovery call: BuildRight field sales pilot discussion",
    category: "discovery-call",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Discuss a 30-day pilot program with BuildRight's regional sales team to test mobile lead capture on jobsites.",
    sortOrder: 1,
    roxTouchpoint: "Conversion Effectiveness",
  },
  {
    id: "task-045",
    title: "Content creation: Recruiting case study draft",
    category: "content-creation",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 75,
    completed: false,
    description: "Write the first draft of a case study featuring a client who improved candidate follow-up speed by 4x using digital capture.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },

  // Wednesday Apr 15
  {
    id: "task-046",
    title: "Partner outreach: Event tech vendors for trade show integrations",
    category: "partner-outreach",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 40,
    completed: false,
    description: "Connect with two event tech platforms about data integration partnerships for seamless booth-to-CRM workflows.",
    sortOrder: 1,
    roxTouchpoint: "Conversion Effectiveness",
  },
  {
    id: "task-047",
    title: "Social post: Share field sales ROX stat highlight",
    category: "social-post",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 25,
    completed: false,
    description: "Post a key stat about same-day lead follow-up rates for field sales teams using mobile capture tools.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },
  {
    id: "task-048",
    title: "Internal review: Field sales playbook draft review",
    category: "internal-review",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 45,
    completed: false,
    description: "Team review of the field sales ROX playbook outline to finalize structure and identify any missing sections.",
    sortOrder: 3,
    roxTouchpoint: "Engagement Quality",
  },

  // Thursday Apr 16
  {
    id: "task-049",
    title: "Cold email: Tech companies for campus recruiting",
    category: "cold-email",
    solution: "recruiting",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Outreach to 10 mid-size tech companies with active campus recruiting programs about digital candidate capture.",
    sortOrder: 1,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-050",
    title: "Lead magnet: Write field sales ROX playbook chapter 1",
    category: "lead-magnet",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 75,
    completed: false,
    description: "Write the first chapter of the field sales playbook covering mobile capture setup and same-day sync workflows.",
    sortOrder: 2,
    roxTouchpoint: "Lead Capture Efficiency",
  },

  // Friday Apr 17
  {
    id: "task-051",
    title: "LinkedIn post: Why your field reps need real-time lead capture",
    category: "linkedin-post",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Publish a post about the competitive advantage of real-time lead capture for field sales teams visiting multiple sites per day.",
    sortOrder: 1,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-052",
    title: "Follow-up: Construction sector field sales replies",
    category: "follow-up",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 30,
    completed: false,
    description: "Review and respond to replies from construction sector outreach. Book demos for warm leads.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },

  // ── Week 5 (Apr 20-24): All 5 solutions ─────────────────────────────

  // Monday Apr 20
  {
    id: "task-053",
    title: "Cold email: Facilities management companies outreach",
    category: "cold-email",
    solution: "facilities",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Launch outreach to 12 facilities management directors about visitor tracking and contractor badge scanning at commercial properties.",
    sortOrder: 1,
    roxTouchpoint: "Lead Capture Efficiency",
  },
  {
    id: "task-054",
    title: "LinkedIn post: Visitor management is the new front desk",
    category: "linkedin-post",
    solution: "facilities",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Post about how digital visitor check-in transforms facility operations and creates a data-rich engagement layer.",
    sortOrder: 2,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-055",
    title: "Content creation: Events and venues ROX overview deck",
    category: "content-creation",
    solution: "events-venues",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Build the first draft of a slide deck showing how venues can measure attendee engagement and conversion across event types.",
    sortOrder: 3,
    roxTouchpoint: "Conversion Effectiveness",
  },

  // Tuesday Apr 21
  {
    id: "task-056",
    title: "Cold email: Concert and sports venue operators",
    category: "cold-email",
    solution: "events-venues",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Target 10 venue operations managers with data on how digital attendee capture improves sponsor ROI reporting.",
    sortOrder: 1,
    roxTouchpoint: "Conversion Effectiveness",
  },
  {
    id: "task-057",
    title: "Partner outreach: Facilities software vendors",
    category: "partner-outreach",
    solution: "facilities",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 40,
    completed: false,
    description: "Reach out to two IWMS platform vendors about integrating visitor data from badge scanning into their dashboards.",
    sortOrder: 2,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-058",
    title: "Internal review: All-solution messaging consistency check",
    category: "internal-review",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 45,
    completed: false,
    description: "Cross-check messaging across all five solution verticals to ensure ROX language and value props are consistent.",
    sortOrder: 3,
    roxTouchpoint: "Conversion Effectiveness",
  },

  // Wednesday Apr 22
  {
    id: "task-059",
    title: "LinkedIn post: How venues turn attendee data into sponsor renewals",
    category: "linkedin-post",
    solution: "events-venues",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Publish a post on how digital attendee capture helps venues prove sponsor value and increase renewal rates.",
    sortOrder: 1,
    roxTouchpoint: "Conversion Effectiveness",
  },
  {
    id: "task-060",
    title: "Discovery call: Premier Properties facilities demo",
    category: "discovery-call",
    solution: "facilities",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Demo visitor and contractor badge scanning for Premier Properties, highlighting compliance reporting and real-time occupancy data.",
    sortOrder: 2,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-061",
    title: "Content creation: Facilities visitor tracking one-pager",
    category: "content-creation",
    solution: "facilities",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Draft a one-page overview of visitor and contractor tracking benefits for commercial property managers.",
    sortOrder: 3,
    roxTouchpoint: "Lead Capture Efficiency",
  },

  // Thursday Apr 23
  {
    id: "task-062",
    title: "Social post: Venue attendee engagement stat graphic",
    category: "social-post",
    solution: "events-venues",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 25,
    completed: false,
    description: "Post an eye-catching stat graphic about the impact of digital attendee capture on sponsor satisfaction scores.",
    sortOrder: 1,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-063",
    title: "Event prep: Facilities management conference booth plan",
    category: "event-prep",
    solution: "facilities",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 45,
    completed: false,
    description: "Plan the booth layout, demo flow, and staffing for the upcoming facilities management industry conference.",
    sortOrder: 2,
    roxTouchpoint: "Engagement Quality",
  },

  // Friday Apr 24
  {
    id: "task-064",
    title: "Follow-up: Facilities management outreach replies",
    category: "follow-up",
    solution: "facilities",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Respond to replies from facilities management outreach and schedule demos for interested prospects.",
    sortOrder: 1,
    roxTouchpoint: "Follow-Up Speed",
  },
  {
    id: "task-065",
    title: "Follow-up: Venue operator cold email responses",
    category: "follow-up",
    solution: "events-venues",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 30,
    completed: false,
    description: "Process replies from venue operator outreach and prioritize high-interest leads for discovery calls next week.",
    sortOrder: 2,
    roxTouchpoint: "Follow-Up Speed",
  },

  // ── Week 6 (Apr 27 - May 1): All 5 solutions, deepening ────────────

  // Monday Apr 27
  {
    id: "task-066",
    title: "LinkedIn post: The ROX framework across all five verticals",
    category: "linkedin-post",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Publish a thought leadership post explaining how ROX applies differently across trade shows, recruiting, field sales, facilities, and venues.",
    sortOrder: 1,
    roxTouchpoint: "Conversion Effectiveness",
  },
  {
    id: "task-067",
    title: "Cold email: Multi-location retailers for field sales + facilities",
    category: "cold-email",
    solution: "field-sales",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 45,
    completed: false,
    description: "Target 10 multi-location retail chains about combining field sales capture with facilities visitor management across their locations.",
    sortOrder: 2,
    roxTouchpoint: "Lead Capture Efficiency",
  },

  // Tuesday Apr 28
  {
    id: "task-068",
    title: "Discovery call: CityStage Venues attendee tracking demo",
    category: "discovery-call",
    solution: "events-venues",
    date: "2026-04-30",
    timeSlot: "morning",
    duration: 30,
    completed: false,
    description: "Walk CityStage through attendee badge scanning, real-time engagement dashboards, and sponsor ROI reporting.",
    sortOrder: 1,
    roxTouchpoint: "Engagement Quality",
  },
  {
    id: "task-069",
    title: "Lead magnet: Events and venues ROX guide outline",
    category: "lead-magnet",
    solution: "events-venues",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 60,
    completed: false,
    description: "Outline a downloadable guide for venue operators covering attendee engagement measurement and sponsor value reporting.",
    sortOrder: 2,
    roxTouchpoint: "Conversion Effectiveness",
  },

  // Wednesday Apr 29
  {
    id: "task-070",
    title: "Content creation: Cross-vertical ROX comparison infographic",
    category: "content-creation",
    solution: "trade-shows",
    date: "2026-04-30",
    timeSlot: "afternoon",
    duration: 75,
    completed: false,
    description: "Design a comprehensive infographic comparing ROX metrics, touchpoints, and outcomes across all five solution verticals.",
    sortOrder: 1,
    roxTouchpoint: "Engagement Quality",
  },
]
