// Explorer Config — AirPro Fan & Blower
// USA-made industrial fans, blowers, and custom engineered airflow solutions

import type { ExplorerConfig, ThemeColors } from '../types';

const AIRPRO_DARK: ThemeColors = {
  bg: '#0A0A08',
  bgGradient: 'linear-gradient(135deg, #1A1800 0%, #0A0A08 55%, #141200 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#FFD940',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(255,217,64,0.20)',
};

const AIRPRO_LIGHT: ThemeColors = {
  bg: '#F5F4EE',
  bgGradient: 'linear-gradient(180deg, #F5F4EE 0%, #F0EFE8 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#C4A000',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(196,160,0,0.12)',
};

export const AIRPRO_CONFIG: ExplorerConfig = {
  id: 'airpro',
  name: 'AirPro Fan & Blower Explorer',
  version: 1,
  createdAt: '2026-06-17T00:00:00.000Z',
  updatedAt: '2026-06-17T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/airpro-logo-dark.png',
      light: '/brand/assets/airpro-logo-light.png',
    },
    icon: '/brand/assets/airpro-icon.png',
    colors: {
      primary: '#FFD940',
      secondary: '#F0C200',
      teal: '#FFD940',
      blue: '#C4A000',
      deepBlue: '#8A6F00',
      navy: '#151200',
      midnight: '#0D0B00',
      plum: '#8A7000',
      bgDark: '#0A0A08',
      dark: AIRPRO_DARK,
      light: AIRPRO_LIGHT,
    },
    font: "Inter, -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(255,217,64,0.15)',
      orb2: 'rgba(240,194,0,0.12)',
      orb3: 'rgba(200,160,0,0.08)',
    },
    ctaGradient: 'linear-gradient(135deg, #FFD940, #F0C200)',
    ctaTextColor: '#000000',
    gradientWord: 'linear-gradient(135deg, #FFD940, #F0C200)',
    roleBackgrounds: {
      'operations-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,217,64,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(240,194,0,0.10) 0%, transparent 55%)',
      'maintenance-super': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(240,194,0,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(255,217,64,0.10) 0%, transparent 55%)',
      'engineer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,217,64,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(196,160,0,0.12) 0%, transparent 55%)',
      'procurement': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(240,194,0,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(255,217,64,0.08) 0%, transparent 55%)',
      'safety-officer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(196,160,0,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(255,217,64,0.15) 0%, transparent 55%)',
      'executive': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,217,64,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(196,160,0,0.12) 0%, transparent 55%)',
      'hvac-contractor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(240,194,0,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(138,111,0,0.12) 0%, transparent 55%)',
      'oem': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,217,64,0.14) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(240,194,0,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Share your contact info so we can follow up with personalized resources.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to AirPro processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Company name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role or title', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Industrial Airflow,',
      gradientWord: 'Engineered Right.',
      subtitle: "Discover the AirPro difference — USA-made industrial fans and blowers backed by the industry's best 3-year warranty.",
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes your role?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'operations-manager', label: 'Operations Manager', icon: 'settings-2', iconType: 'lucide' },
        { value: 'maintenance-super', label: 'Maintenance Superintendent', icon: 'wrench', iconType: 'lucide' },
        { value: 'engineer', label: 'Process / Plant Engineer', icon: 'cpu', iconType: 'lucide' },
        { value: 'procurement', label: 'Procurement / Purchasing', icon: 'package', iconType: 'lucide' },
        { value: 'safety-officer', label: 'Environmental / Safety Officer', icon: 'shield-check', iconType: 'lucide' },
        { value: 'executive', label: 'Executive / Plant Manager', icon: 'briefcase', iconType: 'lucide' },
        { value: 'hvac-contractor', label: 'HVAC / Mechanical Contractor', icon: 'hammer', iconType: 'lucide' },
        { value: 'oem', label: 'OEM / Equipment Builder', icon: 'factory', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you most focused on?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'reliability', label: 'Equipment Reliability & Uptime', icon: 'activity', iconType: 'lucide' },
        { value: 'high-temp', label: 'High-Temperature Applications', icon: 'thermometer', iconType: 'lucide' },
        { value: 'custom', label: 'Custom Engineered Solutions', icon: 'pencil-ruler', iconType: 'lucide' },
        { value: 'dust-control', label: 'Dust Collection & Pollution Control', icon: 'wind', iconType: 'lucide' },
        { value: 'energy', label: 'Energy Efficiency', icon: 'zap', iconType: 'lucide' },
        { value: 'fast-delivery', label: 'Fast Delivery & Emergency Response', icon: 'truck', iconType: 'lucide' },
        { value: 'retrofit', label: 'Reverse Engineering & Retrofits', icon: 'refresh-cw', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        {
          id: 'learn',
          label: 'Learn',
          icon: 'book-open',
          filters: [
            { label: 'All', value: 'all' },
            { label: 'Video', value: 'video' },
            { label: 'PDF', value: 'pdf' },
            { label: 'Blog', value: 'blog' },
            { label: 'Webinar', value: 'webinar' },
          ],
        },
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Our team will be in touch with personalized resources soon.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: '3-Year Gold Standard Warranty',
      cardType: 'outcome',
      icon: 'shield-check',
      iconType: 'lucide',
      stat: '3 Year',
      description: {
        small: "Best-in-industry 3-year warranty on every unit.",
        medium: "AirPro's Gold Standard Warranty covers every fan and blower for 3 full years — the best in the industry.",
        large: "Every AirPro fan and blower ships with the industry's best 3-Year Gold Standard Warranty. This comprehensive coverage reflects AirPro's confidence in its manufacturing quality and commitment to minimizing your downtime.",
        overlay: "AirPro's 3-Year Gold Standard Warranty isn't just a policy — it's a performance statement. While competitors offer 12-18 months, AirPro backs every product with three full years of coverage. This is the direct result of ISO 9001:2015 certified manufacturing, premium materials included as standard, and an employee-owner culture that takes quality personally.",
      },
      tags: ['reliability'],
      targetRoles: ['operations-manager', 'maintenance-super', 'procurement', 'executive'],
    },
    {
      id: 'o2',
      title: '100% Employee-Owned Since 2016',
      cardType: 'outcome',
      icon: 'users',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: "Employee-owned since 2016 — quality is personal.",
        medium: "AirPro has been 100% employee-owned since 2016, creating a culture where quality and customer outcomes are personal.",
        large: "As a 100% employee-owned company since 2016, every person at AirPro has a direct stake in the quality of what they build. This ownership culture drives tighter tolerances, faster response times, and a deeper commitment to customer success.",
        overlay: "When you buy from AirPro, you're buying from the people who make the fans. Employee ownership since 2016 means everyone on the shop floor and in the office has equity in the outcome. This drives a fundamentally different quality culture: higher-grade materials as standard (not upgrades), rigorous inspection at every stage, and a service-first attitude that persists long after the sale.",
      },
      tags: ['reliability', 'custom'],
      targetRoles: ['executive', 'procurement', 'operations-manager'],
    },
    {
      id: 'o3',
      title: 'ISO 9001:2015 Certified Manufacturing',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: 'ISO 9001',
      description: {
        small: "Certified quality management across every product.",
        medium: "ISO 9001:2015 certification ensures consistent, audited quality standards across all AirPro manufacturing.",
        large: "AirPro's ISO 9001:2015 certification demonstrates a rigorous quality management system governing every stage of manufacturing — from raw materials to final air performance testing and delivery.",
        overlay: "ISO 9001:2015 certification isn't a badge on the wall — it's a documented, audited system governing how AirPro designs, manufactures, and tests every product. For procurement and engineering teams specifying equipment, this certification provides verifiable assurance that meets international standards, reducing specification risk and simplifying vendor qualification.",
      },
      tags: ['reliability', 'custom'],
      targetRoles: ['engineer', 'procurement', 'safety-officer', 'executive'],
    },
    {
      id: 'o4',
      title: '18-Hour/Day Production Uptime',
      cardType: 'outcome',
      icon: 'activity',
      iconType: 'lucide',
      stat: '18 hrs/day',
      description: {
        small: "Built for operations running 18 hours a day.",
        medium: "AirPro fans reliably support operations running 18 hours a day, 6 days a week without downtime.",
        large: "AirPro fans are engineered for continuous industrial demands. Customers in food processing, glass manufacturing, and asphalt production run AirPro equipment 18 hours a day, six days a week, trusting it to keep production moving.",
        overlay: "Industrial processes don't stop for equipment failures. AirPro's heavy-duty construction, premium bearing selection, and precision-balanced impellers are designed for exactly the environments where continuous uptime is non-negotiable. Customers run AirPro fans 18+ hours per day and rely on the durability and warranty backing to protect their production investment.",
      },
      tags: ['reliability', 'high-temp'],
      targetRoles: ['operations-manager', 'maintenance-super', 'engineer'],
    },
    {
      id: 'o5',
      title: 'USA Manufacturing — Faster Lead Times',
      cardType: 'outcome',
      icon: 'truck',
      iconType: 'lucide',
      stat: 'USA Made',
      description: {
        small: "Domestically manufactured for faster delivery.",
        medium: "USA-based manufacturing enables faster quotes, shorter lead times, and rapid emergency response when production can't wait.",
        large: "AirPro manufactures exclusively in the USA, giving customers faster turnaround on quotes, competitive lead times, and expedited delivery options when an unplanned equipment failure threatens production.",
        overlay: "Sourcing industrial fans overseas means 12-20 week lead times, customs delays, and no emergency response capability. AirPro's USA-only manufacturing delivers fast quotes, competitive lead times, and expedited options when a critical fan failure threatens your production schedule. For operations where downtime has a real dollar cost, domestic manufacturing isn't just preference — it's risk management.",
      },
      tags: ['fast-delivery', 'reliability'],
      targetRoles: ['operations-manager', 'procurement', 'maintenance-super'],
    },
    {
      id: 'o6',
      title: 'ATEX & CE Certified Options',
      cardType: 'outcome',
      icon: 'flame',
      iconType: 'lucide',
      stat: 'ATEX/CE',
      description: {
        small: "Certified for hazardous and international environments.",
        medium: "ATEX-rated and CE-marked options for hazardous area compliance and international project specifications.",
        large: "AirPro offers ATEX-rated and CE-marked fan and blower options for hazardous environments, international installations, and industries with strict safety certification requirements.",
        overlay: "For applications in potentially explosive atmospheres — chemical processing, grain handling, paint spray booths, and flammable gas environments — ATEX certification isn't optional. AirPro's certified equipment meets ATEX and CE standards, providing the documentation and rating plates required for hazardous area compliance and simplifying international project specifications.",
      },
      tags: ['high-temp', 'custom', 'safety-officer'],
      targetRoles: ['engineer', 'safety-officer', 'procurement'],
    },
    {
      id: 'o7',
      title: 'Custom Engineering Quotes in 48 Hours',
      cardType: 'outcome',
      icon: 'pencil-ruler',
      iconType: 'lucide',
      stat: '48 hrs',
      description: {
        small: "Custom fan quotes delivered within 48 hours.",
        medium: "AirPro's engineering team delivers custom fan specifications and quotes within 48 hours of your request.",
        large: "For non-standard applications, sizes, or materials, AirPro's engineering team responds with custom specifications within 48 hours — keeping your project timeline on track without the multi-week wait typical of custom orders.",
        overlay: "Most custom fan orders require 2-4 weeks just for a quote. AirPro's experienced engineering team can turn around custom specifications — including non-standard sizes, high-temperature materials, special coatings, and unique arrangements — within 48 hours. This speed advantage is critical for engineers working against project deadlines where every day of delay has a real cost.",
      },
      tags: ['custom', 'fast-delivery'],
      targetRoles: ['engineer', 'procurement', 'oem'],
    },

    // ── Learn (8) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Industrial Fan Selection Guide',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'book-open',
      iconType: 'lucide',
      url: 'https://airprofan.com/',
      description: {
        small: "Match the right fan type to your application.",
        medium: "AirPro's fan selection guide covers all fan types and the application criteria for choosing correctly.",
        large: "This guide walks through AirPro's complete fan and blower lineup — backward curved, radial tip, high-pressure blowers, axial fans, and more — with criteria to help engineers match the right solution to each application.",
        overlay: "Choosing the wrong fan type is costly in both performance and efficiency. AirPro's Fan Selection Guide covers the key criteria — pressure requirement, volume flow, temperature, material handling, and efficiency targets — and maps them to the correct fan type. Includes typical performance curves, application examples, and material of construction considerations for demanding environments.",
      },
      tags: ['custom', 'reliability'],
      targetRoles: ['engineer', 'procurement', 'oem'],
    },
    {
      id: 'l2',
      title: 'Behind the Gold Standard Warranty',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://airprofan.com/',
      description: {
        small: "Why AirPro's warranty leads the industry.",
        medium: "Learn how AirPro's employee-owned quality culture and manufacturing standards underpin the industry's best warranty.",
        large: "This post breaks down what goes into the AirPro 3-Year Gold Standard Warranty: ISO 9001:2015 processes, premium materials as standard, and the quality inspection procedures that back every unit shipped.",
        overlay: "A warranty is only as good as the manufacturing behind it. This post pulls back the curtain on AirPro's Gold Standard Warranty: the ISO 9001:2015 quality system that governs production, the premium bearing and material selections that are standard (not upgrades), the air performance testing every unit undergoes before shipping, and how 100% employee ownership creates accountability at every stage.",
      },
      tags: ['reliability'],
      targetRoles: ['operations-manager', 'maintenance-super', 'procurement'],
    },
    {
      id: 'l3',
      title: 'Industrial Fan Applications Overview',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://airprofan.com/',
      description: {
        small: "See AirPro fans in action across industries.",
        medium: "Video overview of AirPro fan and blower applications from food processing to glass manufacturing.",
        large: "This video walks through the wide range of industrial applications AirPro fans serve: asphalt production, boiler systems, dust collection, food processing, high-temperature drying, and pollution control.",
        overlay: "From the intense heat of glass furnace combustion air to the aggressive material-laden streams of dust collection, AirPro fans perform across the harshest industrial environments. This video provides an overview of applications by industry, highlighting the fan types and material selections AirPro recommends for each, with real installation examples and performance context.",
      },
      tags: ['reliability', 'high-temp', 'dust-control'],
      targetRoles: ['engineer', 'operations-manager', 'oem'],
    },
    {
      id: 'l4',
      title: 'Backward Curved vs. Radial Tip Fans',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://airprofan.com/',
      description: {
        small: "Compare the two most common industrial fan designs.",
        medium: "A technical comparison of backward curved and radial tip fan designs for industrial applications.",
        large: "This guide covers performance differences between backward curved and radial tip fans — efficiency curves, material handling capability, pressure profiles, and which applications favor each design.",
        overlay: "Backward curved and radial tip fans are the workhorses of industrial airflow, but they serve different masters. Backward curved fans deliver higher efficiency and self-limiting power curves, ideal for clean-air applications. Radial tip fans handle abrasive, sticky, or fiber-laden air streams where buildup on blades would rapidly degrade other designs. This guide helps engineers choose correctly the first time.",
      },
      tags: ['custom', 'reliability', 'dust-control'],
      targetRoles: ['engineer', 'oem', 'procurement'],
    },
    {
      id: 'l5',
      title: 'Air Performance Testing: What It Means for You',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://airprofan.com/',
      description: {
        small: "How AirPro tests every fan before shipment.",
        medium: "Webinar walkthrough of AirPro's air performance testing procedures and what the data means for your application.",
        large: "This recorded webinar covers AirPro's air performance testing: AMCA standards, how tests are conducted, how fan curves are generated and validated, and what that data means for your installation.",
        overlay: "AirPro tests every fan before it ships. This webinar walks through the air performance test process: AMCA test standards, test rig setup, measurement points, how fan curves are generated from measured data, and how to interpret variance from catalog specifications. For engineers specifying equipment for critical applications, understanding the testing process provides confidence that what's specified is what's delivered.",
      },
      tags: ['reliability', 'custom'],
      targetRoles: ['engineer', 'safety-officer', 'oem'],
    },
    {
      id: 'l6',
      title: 'Reverse Engineering & Fan Retrofits',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'globe',
      iconType: 'lucide',
      url: 'https://airprofan.com/',
      description: {
        small: "Replace legacy fan components without full replacement.",
        medium: "How AirPro's reverse engineering service replaces obsolete components and extends equipment life.",
        large: "AirPro's reverse engineering service allows plants to replace worn or obsolete fan components — wheels, shafts, bearings, housings — without procuring a full replacement unit, extending equipment life at a fraction of the cost.",
        overlay: "When an older fan fails or becomes obsolete, the traditional options are limited: replace from an OEM that may no longer support the product, or invest in a full replacement. AirPro's reverse engineering service offers a third path: precise measurement and replication of existing components updated with current materials and tolerances. This approach preserves the original installation infrastructure while delivering new-unit performance at significantly lower cost and lead time.",
      },
      tags: ['retrofit', 'reliability'],
      targetRoles: ['maintenance-super', 'operations-manager', 'engineer'],
    },
    {
      id: 'l7',
      title: 'Fan Maintenance Best Practices',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://airprofan.com/',
      description: {
        small: "Extend fan life and prevent costly failures.",
        medium: "Whitepaper on industrial fan maintenance intervals, inspection protocols, and common failure modes to prevent.",
        large: "This whitepaper covers fan maintenance best practices: vibration monitoring schedules, bearing inspection intervals, impeller balance checks, housing corrosion management, and early warning signs of imminent failure.",
        overlay: "Unplanned fan failure in a production environment can cost tens of thousands in downtime. This whitepaper outlines AirPro's recommended maintenance program: vibration baseline establishment and trending, bearing temperature monitoring, impeller balance verification schedules, seal and gasket inspection intervals, and the early warning signs — unusual noise, vibration shifts, temperature spikes — that predict failure before it happens.",
      },
      tags: ['reliability', 'energy'],
      targetRoles: ['maintenance-super', 'operations-manager', 'engineer'],
    },
    {
      id: 'l8',
      title: 'Energy Efficiency in Industrial Fans',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'zap',
      iconType: 'lucide',
      url: 'https://airprofan.com/',
      description: {
        small: "Reduce energy costs with the right fan design.",
        medium: "How fan selection, impeller design, and system resistance affect energy consumption in industrial applications.",
        large: "This guide explores the relationship between fan design and energy efficiency: how backward curved impellers reduce power draw, how operating point selection impacts efficiency, and how system changes affect consumption over time.",
        overlay: "Industrial fans are among the largest energy consumers in a plant. This guide examines the efficiency levers available at specification time: fan type selection (backward curved fans operate at 75-85% efficiency vs. 55-65% for radial), impeller sizing for the correct operating point, VFD integration, and how system changes over time — fouling, damper position, ductwork modifications — push the fan off its design point and increase energy consumption.",
      },
      tags: ['energy', 'custom'],
      targetRoles: ['engineer', 'safety-officer', 'operations-manager'],
    },

    // ── Solutions (7) ─────────────────────────────────
    {
      id: 's1',
      title: 'Backward Curved Fans',
      cardType: 'solution',
      icon: 'wind',
      iconType: 'lucide',
      url: 'https://airprofan.com/products/',
      description: {
        small: "High-efficiency fans for clean-air applications.",
        medium: "AirPro backward curved fans deliver maximum efficiency for HVAC, ventilation, and process air applications.",
        large: "AirPro's backward curved fans offer superior efficiency for clean-air applications, featuring self-limiting power curves that protect motor investments and making them the preferred choice for HVAC, general ventilation, and clean process air.",
        overlay: "Backward curved fans represent the efficiency benchmark in centrifugal fan design. AirPro's lineup covers a broad range of flow and pressure requirements, with self-limiting power curves that protect motor investments even when operating conditions shift. Available in multiple materials of construction, coatings, and arrangements to match your specific installation requirements.",
      },
      tags: ['energy', 'reliability'],
      targetRoles: ['engineer', 'oem', 'hvac-contractor'],
    },
    {
      id: 's2',
      title: 'Radial Tip Fans',
      cardType: 'solution',
      icon: 'wind',
      iconType: 'lucide',
      url: 'https://airprofan.com/products/',
      description: {
        small: "Built tough for abrasive and material-laden applications.",
        medium: "Radial tip fans for demanding material handling, dust collection, and abrasive process air streams.",
        large: "AirPro radial tip fans handle abrasive, sticky, or fiber-laden air streams that would rapidly wear standard fan designs — the workhorse of dust collection, material handling, and heavy industrial applications.",
        overlay: "When your air stream carries material — abrasive particles, fibrous waste, sticky process byproducts — a standard backward curved fan will wear or build up rapidly. AirPro's radial tip design keeps blades self-cleaning and wear-resistant, delivering reliable performance in the most demanding conditions across wood, paper, grain, food processing, and industrial applications.",
      },
      tags: ['dust-control', 'reliability', 'high-temp'],
      targetRoles: ['engineer', 'operations-manager', 'maintenance-super'],
    },
    {
      id: 's3',
      title: 'High Pressure Blowers',
      cardType: 'solution',
      icon: 'gauge',
      iconType: 'lucide',
      url: 'https://airprofan.com/products/',
      description: {
        small: "High-static pressure for demanding process applications.",
        medium: "AirPro high pressure blowers deliver the static pressure required for combustion air, spray drying, and process gas.",
        large: "AirPro's high pressure blower lineup is designed for applications requiring high static pressure: combustion air supply, spray drying, rotary dryers, boilers, and pressurization systems where standard fans fall short.",
        overlay: "High-pressure applications require a fundamentally different fan design than standard ventilation. AirPro's high pressure blowers deliver static pressures from 10 to 100+ inches W.G., covering combustion air supply for industrial burners, spray drying chambers, rotary drum dryers, and pressurization for process vessels. Available in multiple impeller profiles to match your specific flow and pressure curve requirements.",
      },
      tags: ['high-temp', 'reliability'],
      targetRoles: ['engineer', 'operations-manager', 'oem'],
    },
    {
      id: 's4',
      title: 'Custom Engineered Solutions',
      cardType: 'solution',
      icon: 'pencil-ruler',
      iconType: 'lucide',
      url: 'https://airprofan.com/products/',
      description: {
        small: "Non-standard application? AirPro engineers it.",
        medium: "From high-temperature alloys to ATEX configurations, AirPro engineers custom fan solutions for unique requirements.",
        large: "AirPro's custom engineering capability covers non-standard sizes, special materials of construction, high-temperature alloys, special coatings, ATEX-rated configurations, and unique arrangements for applications no standard catalog unit can address.",
        overlay: "When your application falls outside catalog boundaries — extreme temperatures, corrosive environments, space-constrained installations, or strict regulatory requirements — AirPro's engineering team works from your specifications. Custom capabilities include exotic alloys (Inconel, Hastelloy, titanium), custom coatings, non-standard impeller geometries, and ATEX-rated configurations for hazardous locations. Quotes within 48 hours from USA manufacturing.",
      },
      tags: ['custom', 'high-temp', 'fast-delivery'],
      targetRoles: ['engineer', 'procurement', 'oem', 'safety-officer'],
    },
    {
      id: 's5',
      title: 'Reverse Engineering & Retrofits',
      cardType: 'solution',
      icon: 'refresh-cw',
      iconType: 'lucide',
      url: 'https://airprofan.com/services/',
      description: {
        small: "Replace aging fan components without full replacement.",
        medium: "AirPro reverse engineers and retrofits obsolete or failed fan components to extend equipment life.",
        large: "AirPro's reverse engineering service replaces wheels, housings, shafts, and bearings for obsolete equipment, restoring original performance without requiring a full unit replacement.",
        overlay: "Legacy equipment becomes a liability when original manufacturers discontinue support. AirPro's reverse engineering team measures, models, and replicates existing fan components with updated materials and tolerances — delivering new-performance replacement parts that fit existing installations. This saves significant capital, reduces installation disruption, and extends equipment life by decades when applied to well-maintained housings and frames.",
      },
      tags: ['retrofit', 'reliability', 'fast-delivery'],
      targetRoles: ['maintenance-super', 'operations-manager', 'engineer'],
    },
    {
      id: 's6',
      title: 'On-Site Startup & Troubleshooting',
      cardType: 'solution',
      icon: 'wrench',
      iconType: 'lucide',
      url: 'https://airprofan.com/services/',
      description: {
        small: "AirPro's field service team comes to you.",
        medium: "On-site startup assistance and troubleshooting from AirPro's service team to minimize downtime.",
        large: "AirPro's field service team provides on-site commissioning support for new installations and emergency troubleshooting for existing equipment, ensuring you're not managing complex fan issues alone.",
        overlay: "Complex fan installations benefit from manufacturer involvement at startup. AirPro's field team provides on-site commissioning support: vibration verification, alignment checks, performance validation against specification, and operator training. For existing equipment issues — unexplained vibration, noise complaints, performance degradation — AirPro's troubleshooting service dispatches experienced engineers to diagnose and correct root causes rather than just swap components.",
      },
      tags: ['reliability', 'fast-delivery'],
      targetRoles: ['maintenance-super', 'operations-manager', 'engineer'],
    },
    {
      id: 's7',
      title: 'Air Performance Testing',
      cardType: 'solution',
      icon: 'gauge',
      iconType: 'lucide',
      url: 'https://airprofan.com/services/',
      description: {
        small: "Every unit tested before it leaves AirPro.",
        medium: "AMCA-standard air performance testing validates every AirPro fan against specified performance before shipping.",
        large: "AirPro conducts air performance testing on every unit before shipment, verifying the delivered product meets the specified fan curve and eliminating performance surprises at installation.",
        overlay: "Fan performance testing is the final quality gate before shipment. AirPro's testing facility conducts AMCA-standard air performance tests that generate actual fan curves for your specific unit — not catalog curves, but measured performance data. This documentation provides engineers and procurement teams with verifiable proof that the delivered fan meets specification, simplifying commissioning and providing a performance baseline for future maintenance comparisons.",
      },
      tags: ['reliability', 'custom'],
      targetRoles: ['engineer', 'procurement', 'safety-officer'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
