// Explorer Config: Carter Machinery
// Recruiting kiosk for Virginia's premier Caterpillar dealer.
// Flow: Role → Graduation Year → Current Level → Major → Results.

import type { ExplorerConfig, ThemeColors } from '../types';

// Subtle dot pattern overlay (stacked above the gradient via CSS background layers).
// Encoded as a data URL so it renders without any component changes.
const CARTER_DOTS_DARK = "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='1.2' fill='%23FFCC00' fill-opacity='0.10'/%3E%3C/svg%3E\")";
const CARTER_DOTS_LIGHT = "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='1.2' fill='%231A1A1A' fill-opacity='0.09'/%3E%3C/svg%3E\")";

const CARTER_DARK: ThemeColors = {
  bg: '#0A0A0A',
  bgGradient: `${CARTER_DOTS_DARK} repeat, linear-gradient(135deg, #1A1A1A 0%, #0A0A0A 55%, #2A2A2A 100%)`,
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#FFCC00',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(255,204,0,0.20)',
};

const CARTER_LIGHT: ThemeColors = {
  bg: '#F4F5F9',
  bgGradient: `${CARTER_DOTS_LIGHT} repeat, linear-gradient(180deg, #F4F5F9 0%, #F2F3F8 100%)`,
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#1A1A1A',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(26,26,26,0.12)',
};

export const CARTER_MACHINERY_CONFIG: ExplorerConfig = {
  id: 'carter-machinery',
  name: 'Carter Machinery Careers Explorer',
  version: 1,
  createdAt: '2026-05-05T00:00:00.000Z',
  updatedAt: '2026-05-05T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/carter-machinery-logo.jpg',
      light: '/brand/assets/carter-machinery-logo.jpg',
    },
    icon: '/brand/assets/carter-machinery-logo.jpg',
    colors: {
      primary: '#FFCC00',
      secondary: '#000000',
      teal: '#FFD633',
      blue: '#FFB800',
      deepBlue: '#404040',
      navy: '#1A1A1A',
      midnight: '#0A0A0A',
      plum: '#FF8C00',
      bgDark: '#0A0A0A',
      dark: CARTER_DARK,
      light: CARTER_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(255,204,0,0.16)',
      orb2: 'rgba(255,140,0,0.14)',
      orb3: 'rgba(255,184,0,0.12)',
    },
    ctaGradient: 'linear-gradient(135deg, #FFCC00, #FFB800)',
    ctaTextColor: '#000000',
    gradientWord: 'linear-gradient(135deg, #FFCC00, #FF8C00)',
    gradientWordLight: 'linear-gradient(135deg, #B8930A, #FF8C00)',
    roleBackgrounds: {
      'student': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,204,0,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(255,140,0,0.10) 0%, transparent 55%)',
      'advisor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,184,0,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(255,204,0,0.10) 0%, transparent 55%)',
      'parent': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,140,0,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(255,184,0,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'form',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Help us match you with the right Carter career path.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Carter Machinery contacting you about career opportunities, programs, and events.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@email.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'school', label: 'School / Organization', type: 'text', placeholder: 'High school, college, or trade school', required: false, halfWidth: false },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Power Your',
      gradientWord: 'Future.',
      subtitle: "Discover careers at Carter Machinery, Virginia's premier Caterpillar dealer powering industries since 1929.",
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'Who are you exploring careers for?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'student', label: 'Student', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'advisor', label: 'Advisor / Counselor', icon: 'users', iconType: 'lucide' },
        { value: 'parent', label: 'Parent', icon: 'heart', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'graduation-year',
      selectionMode: 'single',
      title: 'When are you (or your student) graduating?',
      subtitle: 'This helps us match you with timely opportunities.',
      showGreeting: false,
      showSelectAll: false,
      options: [
        { value: '2026', label: 'Class of 2026', icon: 'calendar', iconType: 'lucide' },
        { value: '2027', label: 'Class of 2027', icon: 'calendar', iconType: 'lucide' },
        { value: '2028', label: 'Class of 2028', icon: 'calendar', iconType: 'lucide' },
        { value: '2029', label: 'Class of 2029', icon: 'calendar', iconType: 'lucide' },
        { value: 'graduated', label: 'Already Graduated', icon: 'check-circle-2', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'current-level',
      selectionMode: 'single',
      title: "What's your current education level?",
      subtitle: 'Select your current school setting.',
      showGreeting: false,
      showSelectAll: false,
      options: [
        { value: 'high-school', label: 'High School', icon: 'school', iconType: 'lucide' },
        { value: 'trade-school', label: 'Trade School', icon: 'wrench', iconType: 'lucide' },
        { value: 'college', label: 'College / University', icon: 'building-2', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'circle', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'major',
      selectionMode: 'multi',
      title: 'What are you studying?',
      subtitle: "Select all that apply, we'll match you to relevant Carter roles.",
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'diesel-heavy-equipment', label: 'Diesel / Heavy Equipment', icon: 'truck', iconType: 'lucide' },
        { value: 'industrial-maintenance', label: 'Industrial Maintenance', icon: 'settings', iconType: 'lucide' },
        { value: 'welding', label: 'Welding', icon: 'flame', iconType: 'lucide' },
        { value: 'electrical-hydraulics', label: 'Electrical / Hydraulics', icon: 'zap', iconType: 'lucide' },
        { value: 'engineering', label: 'Engineering', icon: 'cog', iconType: 'lucide' },
        { value: 'power-generation', label: 'Power Generation', icon: 'battery-charging', iconType: 'lucide' },
        { value: 'business-sales', label: 'Business / Sales', icon: 'briefcase', iconType: 'lucide' },
        { value: 'computer-science', label: 'Computer Science / IT', icon: 'monitor', iconType: 'lucide' },
        { value: 'undecided', label: 'Other / Undecided', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Carter Career Match',
      subtitle: 'Personalized roles, programs, and resources based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Why Carter', icon: 'sparkles' },
        { id: 'solutions', label: 'Positions', icon: 'briefcase' },
        { id: 'learn', label: 'Benefits', icon: 'gift', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Website', value: 'website' },
        ]},
      ],
      cardsPerPage: 6,
      defaultView: 'medium',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated Carter career path.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Career Library',
      subtitle: 'Browse all Carter Machinery career content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: "We appreciate your interest in Carter Machinery. Your personalized career packet will be sent to you shortly.",
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (Why Carter) - 8 cards ──────────────────────
    {
      id: 'wc1',
      title: 'Powering Industries Since 1929',
      cardType: 'outcome',
      icon: 'landmark',
      iconType: 'lucide',
      stat: '95+ yrs',
      description: {
        small: '95+ years as Virginia\'s Cat dealer.',
        medium: 'Carter Machinery has powered Virginia\'s industries as the authorized Caterpillar dealer for over 95 years.',
        large: "Founded in 1929, Carter Machinery has been Virginia's authorized Caterpillar dealer for nearly a century, serving construction, power, mining, and industrial customers across the Commonwealth.",
        overlay: "Founded in 1929, Carter Machinery is the authorized Caterpillar dealer for Virginia, parts of West Virginia, and Maryland's Eastern Shore. For nearly a century, Carter has powered the region's construction, mining, marine, and industrial operations, and built generations of careers along the way.",
      },
      tags: ['heritage', 'culture'],
      targetRoles: ['student', 'advisor', 'parent'],
    },
    {
      id: 'wc2',
      title: 'Industry-Leading Starting Wages',
      cardType: 'outcome',
      icon: 'dollar-sign',
      iconType: 'lucide',
      stat: 'Top Pay',
      description: {
        small: 'Competitive starting wages from day one.',
        medium: 'New Carter technicians and engineers start at industry-leading wages with regular merit increases.',
        large: 'Carter offers some of the strongest starting wages in the Cat dealer network, with regular merit-based increases as you build skills and certifications. Tool allowances, signing bonuses, and relocation packages available for select roles.',
        overlay: 'Carter Machinery offers industry-leading starting wages for technicians, engineers, and sales professionals, with structured pay increases tied to certifications, tenure, and performance. New hires also receive tool allowances, signing bonuses for select roles, and relocation packages where applicable.',
      },
      tags: ['compensation', 'benefits'],
      targetRoles: ['student', 'parent', 'advisor'],
    },
    {
      id: 'wc3',
      title: 'Paid Caterpillar Training',
      cardType: 'outcome',
      icon: 'graduation-cap',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: '100% paid Cat-certified training.',
        medium: 'Earn while you learn with paid factory-certified training from Caterpillar.',
        large: "Carter invests heavily in your development with 100% employer-paid Caterpillar factory training. Earn nationally recognized certifications that travel with you for life, all while drawing a full paycheck.",
        overlay: "Carter sends new technicians, engineers, and product specialists through Caterpillar's renowned factory-certified training programs at no cost to the employee. You earn certifications recognized across every Cat dealership in North America, all while drawing your regular paycheck and benefits.",
      },
      tags: ['training', 'development'],
      targetRoles: ['student', 'advisor', 'parent'],
    },
    {
      id: 'wc4',
      title: '15+ Locations Across Virginia',
      cardType: 'outcome',
      icon: 'map-pin',
      iconType: 'lucide',
      stat: '15+',
      description: {
        small: '15+ locations across the Commonwealth.',
        medium: '15+ branches across Virginia mean you can build a career close to home.',
        large: 'With 15+ branches across Virginia, parts of West Virginia, and Maryland\'s Eastern Shore, Carter offers career opportunities close to wherever you call home, from coastal Norfolk to the mountains of Roanoke.',
        overlay: "Carter Machinery operates 15+ full-service branches across Virginia, parts of West Virginia, and Maryland's Eastern Shore. Whether you're rooted in Hampton Roads, Richmond, Northern Virginia, the Shenandoah Valley, or Southwest VA, there's a Carter location nearby where you can grow your career.",
      },
      tags: ['locations', 'culture'],
      targetRoles: ['student', 'parent'],
    },
    {
      id: 'wc5',
      title: 'Promote-from-Within Culture',
      cardType: 'outcome',
      icon: 'trending-up',
      iconType: 'lucide',
      stat: '80%+',
      description: {
        small: '80%+ of leaders started in the field.',
        medium: 'Most Carter managers and leaders started as technicians, sales reps, or apprentices.',
        large: "More than 80% of Carter's branch managers, regional leaders, and senior technicians started their careers in entry-level field, shop, or sales roles. Your first job here is rarely your last.",
        overlay: "Career growth at Carter is real, not just a slogan. More than 80% of branch managers, regional leaders, and senior technicians started their careers in entry-level field, shop, or sales roles. Service writers become managers. Apprentices become master technicians. Sales reps become account executives.",
      },
      tags: ['career-growth', 'culture'],
      targetRoles: ['student', 'advisor', 'parent'],
    },
    {
      id: 'wc6',
      title: 'Award-Winning Cat Dealer',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: '★★★★★',
      description: {
        small: 'Top-rated Cat dealer in North America.',
        medium: 'Carter consistently ranks among the top Cat dealers in North America for service and customer experience.',
        large: 'Carter has earned multiple Caterpillar Dealer of Excellence awards and consistently ranks in the top tier for service quality, customer experience, and parts availability across the Cat dealer network.',
        overlay: "Carter Machinery has earned Caterpillar's Dealer of Excellence designation multiple times, ranking among the highest-performing Cat dealers in North America for service quality, customer satisfaction, parts availability, and operational excellence, a direct result of the team that makes it happen.",
      },
      tags: ['heritage', 'culture'],
      targetRoles: ['student', 'advisor', 'parent'],
    },
    {
      id: 'wc7',
      title: 'Veterans Welcomed & Valued',
      cardType: 'outcome',
      icon: 'shield',
      iconType: 'lucide',
      stat: 'V3 Cert',
      description: {
        small: 'Virginia Values Veterans certified employer.',
        medium: 'Carter is V3-certified and actively recruits transitioning service members.',
        large: 'Carter is a Virginia Values Veterans (V3) certified employer with structured pathways for transitioning service members. Military skills in mechanics, electrical, hydraulics, and leadership translate directly to Carter careers.',
        overlay: "Carter Machinery is a Virginia Values Veterans (V3) certified employer with dedicated pathways for transitioning service members. Military experience in mechanics, electrical systems, hydraulics, fleet management, and leadership translates directly into high-paying Carter careers, with skills-translation support, accelerated training credit, and a culture that respects service.",
      },
      tags: ['veterans', 'culture'],
      targetRoles: ['student', 'parent', 'advisor'],
    },
    {
      id: 'wc8',
      title: 'Apprenticeship Pays From Day One',
      cardType: 'outcome',
      icon: 'hammer',
      iconType: 'lucide',
      stat: 'Earn + Learn',
      description: {
        small: 'Earn a paycheck while learning a trade.',
        medium: "Carter's apprenticeship program pays you from day one, no student debt required.",
        large: 'Skip the student debt. Carter\'s registered apprenticeship program pays you a full wage from day one while you earn nationally recognized credentials, combining paid on-the-job training with classroom instruction.',
        overlay: "Carter's registered apprenticeship program is the smart alternative to four-year debt. Apprentices earn a full paycheck plus benefits from day one while completing structured paid on-the-job training and classroom instruction. Graduates leave debt-free with nationally portable credentials, certifications, and a guaranteed career path.",
      },
      tags: ['apprenticeship', 'training'],
      targetRoles: ['student', 'advisor', 'parent'],
    },

    // ── Solutions (Positions) - 11 cards ─────────────────────
    {
      id: 'p1',
      title: 'Electric Power Generation Technician',
      cardType: 'solution',
      icon: 'battery-charging',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/power-system/',
      description: {
        small: 'Service Cat generators powering data centers, hospitals, and more.',
        medium: 'Service and maintain Caterpillar generator sets that power data centers, hospitals, and critical infrastructure.',
        large: 'Power Generation Technicians install, commission, service, and troubleshoot Cat generator sets and switchgear at data centers, hospitals, federal facilities, and industrial sites across Virginia. High-demand role with strong wage growth.',
        overlay: 'Power Generation Technicians install, commission, service, and troubleshoot Caterpillar generator sets and switchgear that keep data centers, hospitals, federal facilities, and industrial customers running. This is one of the fastest-growing roles at Carter as Virginia\'s data center demand explodes, with strong wage growth, paid Cat training, and a clear path to senior technician and lead positions.',
      },
      tags: ['power-systems', 'technician'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['diesel-heavy-equipment', 'electrical-hydraulics', 'power-generation', 'industrial-maintenance'],
    },
    {
      id: 'p2',
      title: 'Power Systems Engineer',
      cardType: 'solution',
      icon: 'cpu',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/power-system/',
      description: {
        small: 'Design and engineer custom power solutions for major projects.',
        medium: 'Engineer custom Cat power solutions for data centers, healthcare, and industrial customers.',
        large: 'Power Systems Engineers design, size, and integrate Cat generator and switchgear solutions for major customer projects, combining electrical engineering, applications expertise, and customer consulting in a high-impact role.',
        overlay: "Power Systems Engineers at Carter design and integrate Caterpillar generator, switchgear, and standby/prime power solutions for major customer projects, from hyperscale data centers to hospitals to manufacturing plants. The role blends electrical engineering, application engineering, and customer consulting, with a clear ladder into senior engineering and technical sales leadership.",
      },
      tags: ['power-systems', 'engineering'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['engineering', 'electrical-hydraulics', 'power-generation'],
    },
    {
      id: 'p3',
      title: 'Sales Engineer (Power Systems)',
      cardType: 'solution',
      icon: 'presentation',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/power-system/',
      description: {
        small: 'Sell engineered Cat power solutions to industry leaders.',
        medium: "Pair technical depth with customer relationships to sell Carter's power solutions.",
        large: 'Sales Engineers combine technical depth with customer relationship skills to sell Cat generator and power solutions to data centers, hospitals, government, and industrial buyers. High-earning role with strong base + commission.',
        overlay: 'Sales Engineers in the Power Systems group combine technical depth with consultative selling to win and grow major accounts, data centers, hospitals, federal customers, and industrial buyers. This is a high-earning career with strong base salary plus commission, company vehicle, and a clear path to senior sales and account executive roles.',
      },
      tags: ['power-systems', 'sales', 'engineering'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['engineering', 'business-sales', 'power-generation'],
    },
    {
      id: 'p4',
      title: 'Field Service Technician',
      cardType: 'solution',
      icon: 'wrench',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Service Cat equipment on customer job sites across Virginia.',
        medium: 'Travel to job sites in a fully equipped Carter service truck to repair Cat equipment in the field.',
        large: "Field Service Technicians work from a fully equipped Carter service truck, traveling to customer job sites to diagnose and repair Cat construction equipment. Includes take-home vehicle, tool allowance, and overtime opportunity.",
        overlay: "Field Service Technicians work out of a fully equipped Carter service truck, your office is the open road and the customer's job site. You'll diagnose, repair, and maintain Cat construction and earthmoving equipment in real-world conditions, with a take-home vehicle, tool allowance, paid Cat training, and strong overtime opportunity. Independence, variety, and high earning potential.",
      },
      tags: ['technician', 'field-service'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['diesel-heavy-equipment', 'industrial-maintenance', 'electrical-hydraulics'],
    },
    {
      id: 'p5',
      title: 'Shop Service Technician',
      cardType: 'solution',
      icon: 'hard-hat',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Rebuild and repair Cat equipment in our state-of-the-art shops.',
        medium: 'Diagnose and repair Cat equipment in modern Carter service shops with full tooling and lift access.',
        large: "Shop Technicians work in modern Carter service facilities with full lifts, diagnostic tooling, and senior tech mentorship. Ideal for technicians who prefer shop work over field travel, with rebuild specialization tracks available.",
        overlay: "Shop Service Technicians diagnose and repair Caterpillar machines in Carter's modern, climate-controlled service shops, with full overhead lifts, the latest diagnostic tooling, OEM parts, and senior technician mentorship. Specialization tracks include component rebuild, hydraulics, transmissions, and engines, with strong wage progression as you certify.",
      },
      tags: ['technician', 'shop-service'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['diesel-heavy-equipment', 'welding', 'industrial-maintenance', 'electrical-hydraulics'],
    },
    {
      id: 'p6',
      title: 'Welding & Fabrication Specialist',
      cardType: 'solution',
      icon: 'flame',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Weld, fabricate, and rebuild Cat machine components.',
        medium: 'Apply welding skills to Cat component repair, rebuild, and custom fabrication work.',
        large: "Carter's welding specialists rebuild Cat buckets, blades, frames, and components, combining MIG, TIG, stick, and hardfacing techniques. Strong demand role with certification pay-bumps and overtime opportunity.",
        overlay: "Welding & Fabrication Specialists at Carter handle component rebuild, structural repair, and custom fabrication for Cat machines, buckets, blades, booms, frames, and undercarriages. The work blends MIG, TIG, stick, and hardfacing with diagnostic skill, in a role that rewards certifications with pay bumps and steady overtime.",
      },
      tags: ['technician', 'welding'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['welding', 'industrial-maintenance', 'diesel-heavy-equipment'],
    },
    {
      id: 'p7',
      title: 'Hydraulics Technician',
      cardType: 'solution',
      icon: 'droplets',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Specialize in Cat hydraulic system rebuild and repair.',
        medium: "Rebuild Cat hydraulic pumps, cylinders, and motors in Carter's specialty hydraulics shops.",
        large: "Hydraulics Technicians specialize in rebuilding and testing Cat hydraulic pumps, cylinders, valves, and motors. High-skill role with strong certification-driven pay growth and limited national supply of qualified techs.",
        overlay: "Hydraulics Technicians at Carter specialize in rebuilding, testing, and certifying Cat hydraulic pumps, cylinders, valves, and motors, using factory test stands and OEM specs. It's a deep-skill role with steep pay growth as you certify, and the national talent shortage means strong job security and mobility.",
      },
      tags: ['technician', 'hydraulics'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['electrical-hydraulics', 'diesel-heavy-equipment', 'industrial-maintenance'],
    },
    {
      id: 'p8',
      title: 'Rental Sales Representative',
      cardType: 'solution',
      icon: 'truck',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Match contractors with the right Cat rental fleet.',
        medium: 'Build relationships with contractors and match them to the right Cat rental equipment.',
        large: 'Rental Sales Reps build trust with contractors across their territory, matching them to the right Cat Rental Store equipment for every job. High-energy customer-facing role with strong base + commission and company vehicle.',
        overlay: "Rental Sales Reps own a territory of contractor and industrial customers, building trusted relationships and matching them to the Cat Rental Store fleet, from compact equipment to large earthmovers, generators, and air compressors. The role is high-energy and customer-facing, with strong base salary, commission, company vehicle, and a clear path into senior sales and rental management.",
      },
      tags: ['rental', 'sales'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['business-sales', 'diesel-heavy-equipment'],
    },
    {
      id: 'p9',
      title: 'Inside Sales Representative',
      cardType: 'solution',
      icon: 'phone-call',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Support customers with parts, quotes, and account growth.',
        medium: 'Work with customers by phone and email to source Cat parts, build quotes, and grow accounts.',
        large: 'Inside Sales Reps work the phones and inbox to source Cat parts, build quotes, troubleshoot orders, and grow customer accounts. Strong onboarding role for grads moving toward outside sales or product specialty paths.',
        overlay: "Inside Sales Reps are Carter's customer-facing front line, sourcing Cat parts, building quotes, troubleshooting orders, and growing customer accounts by phone, email, and online channels. It's a strong onboarding role for new grads and career-changers, with clear pathways into outside sales, product specialty roles, and account management.",
      },
      tags: ['sales', 'parts'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['business-sales', 'computer-science', 'undecided'],
    },
    {
      id: 'p10',
      title: 'Apprenticeship Program',
      cardType: 'solution',
      icon: 'graduation-cap',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Earn a paycheck while you learn a Cat trade.',
        medium: "Carter's registered apprenticeship combines paid on-the-job training with classroom instruction.",
        large: "Carter's registered apprenticeship program pays you a full wage with benefits from day one while you earn nationally recognized Cat certifications through structured on-the-job training and classroom instruction.",
        overlay: "Carter's registered apprenticeship program is the smart alternative to four-year debt. Earn a full wage with benefits from day one while completing structured paid on-the-job training and classroom instruction. Graduates leave with nationally recognized Cat certifications, zero debt, and a guaranteed career path. Tracks include heavy equipment tech, power generation tech, hydraulics, and welding.",
      },
      tags: ['apprenticeship', 'training'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['diesel-heavy-equipment', 'industrial-maintenance', 'welding', 'electrical-hydraulics', 'power-generation', 'undecided'],
    },
    {
      id: 'p11',
      title: 'Veterans Pathway',
      cardType: 'solution',
      icon: 'shield',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Translate military skills into a Carter career.',
        medium: 'Carter is V3-certified with structured pathways for transitioning service members.',
        large: "Carter's Veterans Pathway translates military mechanic, electrical, hydraulics, and leadership experience into accelerated Carter career tracks, with skills credit, dedicated mentors, and V3-certified support.",
        overlay: "Carter Machinery is a Virginia Values Veterans (V3) certified employer with a structured Veterans Pathway. Military experience in mechanics, electrical systems, hydraulics, fleet management, generator operations, and small-unit leadership translates directly into Carter careers, with formal skills credit, accelerated certification pacing, dedicated veteran mentors, and a culture that respects service.",
      },
      tags: ['veterans', 'training'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['diesel-heavy-equipment', 'industrial-maintenance', 'electrical-hydraulics', 'power-generation', 'business-sales', 'undecided'],
    },

    // ── Learn (Benefits) - 8 cards ───────────────────────────
    {
      id: 'b1',
      title: 'Health & Wellness Benefits',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'heart-pulse',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Medical, dental, vision, and wellness programs.',
        medium: 'Comprehensive medical, dental, vision, and behavioral health coverage from day one.',
        large: 'Carter offers comprehensive medical, dental, vision, behavioral health, and wellness programs starting at day one. Multiple plan options, HSA/FSA support, and dependent coverage available.',
        overlay: "Carter's health benefits package includes comprehensive medical, dental, vision, behavioral health, and wellness programs starting on your first day of full-time employment. You'll choose from multiple medical plan options including HSA-eligible high-deductible plans, with employer HSA contributions, FSA support, and dependent coverage available. Onsite or telemedicine options keep care convenient.",
      },
      tags: ['health-benefits', 'compensation'],
      targetRoles: ['student', 'advisor', 'parent'],
    },
    {
      id: 'b2',
      title: 'Financial Benefits & 401(k)',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'piggy-bank',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: '401(k) match, profit sharing, and financial wellness.',
        medium: 'Strong 401(k) match plus profit sharing and financial wellness resources.',
        large: 'Carter offers a competitive 401(k) match, annual profit sharing, life and disability insurance, and dedicated financial wellness resources to help you build long-term wealth from day one.',
        overlay: "Carter's financial benefits include a competitive 401(k) match with immediate participation eligibility, annual profit sharing tied to company performance, employer-paid life and disability insurance, and access to dedicated financial wellness resources, planning tools, and education sessions. Build long-term wealth alongside your career growth.",
      },
      tags: ['financial-benefits', 'compensation'],
      targetRoles: ['student', 'advisor', 'parent'],
    },
    {
      id: 'b3',
      title: 'Time Off & Holidays',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'calendar-days',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Generous PTO, paid holidays, and flexible time off.',
        medium: 'Generous PTO that grows with tenure plus paid holidays and parental leave.',
        large: 'Carter offers generous paid time off that grows with tenure, paid company holidays, paid parental leave, bereavement leave, and jury duty pay. Time off you can actually use.',
        overlay: "Carter's time-off package includes generous paid vacation time that increases with tenure, paid company holidays including the day after Thanksgiving, paid parental leave for new mothers and fathers, paid bereavement leave, and paid jury duty. Carter is committed to time off you can actually use, you won't get pressured to skip the time you've earned.",
      },
      tags: ['time-off', 'culture'],
      targetRoles: ['student', 'advisor', 'parent'],
    },
    {
      id: 'b4',
      title: 'Tool Allowance & Uniforms',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'wrench',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Tool allowance, uniforms, and PPE provided.',
        medium: 'Annual tool allowance, company-provided uniforms, and full PPE package for technicians.',
        large: "Technicians receive an annual tool allowance, company-provided uniforms with laundry service, and a full personal protective equipment package, meaning your wages aren't eaten by gear.",
        overlay: "Carter technicians receive an annual tool allowance to build out their personal tool set, company-provided uniforms with weekly laundry service, full personal protective equipment (steel-toe boots, safety glasses, hearing protection, gloves), and access to factory diagnostic tooling and lifting equipment. Your wages don't get eaten by required gear and uniforms.",
      },
      tags: ['additional-perks', 'compensation'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['diesel-heavy-equipment', 'industrial-maintenance', 'welding', 'electrical-hydraulics', 'power-generation'],
    },
    {
      id: 'b5',
      title: 'Tuition & Certification Reimbursement',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'book-open',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Tuition reimbursement and paid certifications.',
        medium: 'Continue your education with Carter-paid tuition and certifications.',
        large: 'Carter reimburses tuition for approved degree and certificate programs and pays for industry certifications, keep growing your career while keeping your paycheck.',
        overlay: "Carter offers tuition reimbursement for approved associate, bachelor's, and certificate programs, plus full payment for industry certifications relevant to your role, Cat factory training, ASE, EGSA, NICET, and more. Keep building your skills and credentials while keeping your full paycheck and benefits.",
      },
      tags: ['training', 'additional-perks'],
      targetRoles: ['student', 'advisor', 'parent'],
    },
    {
      id: 'b6',
      title: 'Day in the Life: Field Technician',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Ride along with a Carter field technician.',
        medium: 'Watch what a typical day looks like for a Carter field service technician.',
        large: 'Spend a day in the field with a Carter Service Technician, from morning truck check to job site diagnostics to wrapping up a successful repair. Real work, real people, real career.',
        overlay: "This day-in-the-life video follows a Carter field service technician through a typical workday, morning truck inventory check, dispatch to a job site, on-site diagnostic work using Cat ET diagnostic tools, the actual repair, and customer wrap-up. Hear directly from techs about what they love, what's hard, and how the role grew their career.",
      },
      tags: ['day-in-the-life', 'technician'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['diesel-heavy-equipment', 'industrial-maintenance', 'electrical-hydraulics'],
    },
    {
      id: 'b7',
      title: 'Day in the Life: Power Systems Engineer',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/power-system/',
      description: {
        small: 'See what a Carter Power Systems Engineer does daily.',
        medium: 'Follow a Power Systems Engineer through customer projects and design reviews.',
        large: "Spend a day with a Carter Power Systems Engineer, from morning customer site walks to afternoon design reviews to evening commissioning support. See where engineering meets real-world impact.",
        overlay: "This day-in-the-life video follows a Carter Power Systems Engineer through a typical project workflow, customer site walks, generator and switchgear sizing, application engineering reviews, factory acceptance testing, and commissioning support. See how Cat power solutions get built into the data centers, hospitals, and infrastructure that keep Virginia running.",
      },
      tags: ['day-in-the-life', 'engineering'],
      targetRoles: ['student', 'advisor', 'parent'],
      targetInterests: ['engineering', 'electrical-hydraulics', 'power-generation'],
    },
    {
      id: 'b8',
      title: 'How to Apply at Carter',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'send',
      iconType: 'lucide',
      url: 'https://www.careersatcarter.com/',
      description: {
        small: 'Step-by-step guide to applying to Carter Machinery.',
        medium: 'A clear step-by-step guide to the Carter Machinery application and interview process.',
        large: 'This guide walks you through every step of applying to Carter, finding the right job, building a strong application, what to expect in the interview, and tips for new grads and career-changers.',
        overlay: "This step-by-step guide walks you through every stage of the Carter Machinery hiring process: finding the right opening on careersatcarter.com, building a strong application, what to expect in phone screens and on-site interviews, the typical hiring timeline, and specific tips for new graduates, trade school students, military veterans, and career-changers, including what to wear, what questions to ask, and what success looks like in your first 90 days.",
      },
      tags: ['how-to-apply', 'tips'],
      targetRoles: ['student', 'advisor', 'parent'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
