// Explorer Config — CDK Global
// Automotive retail technology platform powering nearly 15,000 dealer locations

import type { ExplorerConfig, ThemeColors } from '../types';

const CDK_DARK: ThemeColors = {
  bg: '#0A0A0A',
  bgGradient: 'linear-gradient(135deg, #1A1A1A 0%, #0A0A0A 55%, #141414 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#FFFFFF',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(255,255,255,0.15)',
};

const CDK_LIGHT: ThemeColors = {
  bg: '#F4F5F7',
  bgGradient: 'linear-gradient(180deg, #F4F5F7 0%, #F0F1F3 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(0,0,0,0.10)',
  borderFocus: '#000000',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(0,0,0,0.10)',
};

export const CDK_CONFIG: ExplorerConfig = {
  id: 'cdk',
  name: 'CDK Global Explorer',
  version: 1,
  createdAt: '2026-04-08T00:00:00.000Z',
  updatedAt: '2026-04-08T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/cdk-logo-reverse.png',
      light: '/brand/assets/cdk-logo.png',
    },
    icon: '/brand/assets/cdk-icon.jpeg',
    colors: {
      primary: '#FFFFFF',
      secondary: '#000000',
      teal: '#CCCCCC',
      blue: '#505150',
      deepBlue: '#333333',
      navy: '#1A1A1A',
      midnight: '#0A0A0A',
      plum: '#505150',
      bgDark: '#0A0A0A',
      dark: CDK_DARK,
      light: CDK_LIGHT,
    },
    font: 'Montserrat',
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(255,255,255,0.08)',
      orb2: 'rgba(204,204,204,0.06)',
      orb3: 'rgba(80,81,80,0.10)',
    },
    ctaGradient: 'linear-gradient(135deg, #333333, #000000)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #FFFFFF, #CCCCCC)',
    roleBackgrounds: {
      'dealer-principal': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,255,255,0.08) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(204,204,204,0.06) 0%, transparent 55%)',
      'general-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(204,204,204,0.08) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(255,255,255,0.05) 0%, transparent 55%)',
      'fixed-ops-director': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,255,255,0.07) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(204,204,204,0.06) 0%, transparent 55%)',
      'sales-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(204,204,204,0.06) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(255,255,255,0.04) 0%, transparent 55%)',
      'fi-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(204,204,204,0.08) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(255,255,255,0.06) 0%, transparent 55%)',
      'it-director': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,255,255,0.06) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(204,204,204,0.05) 0%, transparent 55%)',
      'oem-partner': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(204,204,204,0.06) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(80,81,80,0.08) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(204,204,204,0.05) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(255,255,255,0.04) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Please fill in the form to continue.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to CDK Global processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@dealership.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Dealership Name', type: 'text', placeholder: 'Dealership or group name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Dealership',
      gradientWord: 'Xperience.',
      subtitle: 'Discover how CDK Global powers nearly 15,000 dealer locations with connected technology that drives sales, service, and profitability.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes your role?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'dealer-principal', label: 'Dealer Principal / Owner', icon: 'building-2', iconType: 'lucide' },
        { value: 'general-manager', label: 'General Manager', icon: 'briefcase', iconType: 'lucide' },
        { value: 'fixed-ops-director', label: 'Fixed Ops / Service Director', icon: 'wrench', iconType: 'lucide' },
        { value: 'sales-manager', label: 'Sales Manager', icon: 'handshake', iconType: 'lucide' },
        { value: 'fi-manager', label: 'F&I Manager', icon: 'file-check', iconType: 'lucide' },
        { value: 'it-director', label: 'IT Director', icon: 'server', iconType: 'lucide' },
        { value: 'oem-partner', label: 'OEM / ISV Partner', icon: 'network', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'message-circle', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What challenges are you looking to solve?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'dms-operations', label: 'DMS & Dealership Operations', icon: 'layout-dashboard', iconType: 'lucide' },
        { value: 'digital-retail', label: 'Digital Retailing', icon: 'monitor-smartphone', iconType: 'lucide' },
        { value: 'fixed-ops', label: 'Fixed Ops & Service Lane', icon: 'wrench', iconType: 'lucide' },
        { value: 'crm-engagement', label: 'CRM & Customer Engagement', icon: 'users', iconType: 'lucide' },
        { value: 'fi-compliance', label: 'F&I & Compliance', icon: 'shield-check', iconType: 'lucide' },
        { value: 'inventory-pricing', label: 'Inventory & Pricing', icon: 'car', iconType: 'lucide' },
        { value: 'analytics-ai', label: 'Analytics & AI', icon: 'brain', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'PDF', value: 'pdf' },
          { label: 'Webinar', value: 'webinar' },
        ]},
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: '$540B in Annual Commerce',
      cardType: 'outcome',
      icon: 'dollar-sign',
      iconType: 'lucide',
      stat: '$540B',
      description: {
        small: '$540 billion in annual auto commerce flows through CDK systems.',
        medium: 'CDK Global technology powers over $540 billion in annual automotive commerce across sales, service, and F&I.',
        large: 'CDK Global is the backbone of automotive retail, with over $540 billion in annual commerce flowing through its connected platform, from vehicle sales and F&I to service operations and parts.',
        overlay: 'The scale of CDK\'s platform is unmatched in automotive retail. Over $540 billion in annual commerce runs through CDK systems, giving the company unparalleled data insights, integration depth, and the ability to optimize every transaction across sales, service, parts, and F&I for nearly 15,000 dealer locations.',
      },
      tags: ['dms-operations', 'digital-retail'],
      targetRoles: ['dealer-principal', 'general-manager'],
    },
    {
      id: 'o2',
      title: 'Nearly 15,000 Dealer Locations',
      cardType: 'outcome',
      icon: 'map-pin',
      iconType: 'lucide',
      stat: '15K',
      description: {
        small: 'Trusted by nearly 15,000 dealer locations.',
        medium: 'Nearly 15,000 dealerships across the US and Canada rely on CDK to run their operations.',
        large: 'CDK Global serves nearly 15,000 dealer locations with integrated technology spanning DMS, CRM, digital retail, F&I, fixed operations, and business intelligence.',
        overlay: 'Nearly 15,000 dealer locations trust CDK Global as their technology backbone. This vast network creates a powerful ecosystem effect where best practices, integrations, and innovations developed across the network benefit every dealer. CDK\'s 50+ year track record in automotive retail means deep domain expertise that general-purpose software cannot match.',
      },
      tags: ['dms-operations', 'crm-engagement'],
      targetRoles: ['dealer-principal', 'general-manager', 'oem-partner'],
    },
    {
      id: 'o3',
      title: '5-10 Days Faster Inventory Turn',
      cardType: 'outcome',
      icon: 'timer',
      iconType: 'lucide',
      stat: '5-10 days',
      description: {
        small: 'Dealers turn inventory 5-10 days faster with CDK.',
        medium: 'CDK\'s Vehicle Inventory Suite helps dealers reduce days-to-turn by 5-10 days through smarter pricing and merchandising.',
        large: 'Dealers using CDK\'s Vehicle Inventory Suite report 5-10 days faster inventory turn through AI-powered pricing, automated merchandising, and real-time market intelligence that keeps their lots competitive.',
        overlay: 'Every day a vehicle sits on the lot costs money. CDK\'s Vehicle Inventory Suite combines real-time market data, AI-driven pricing recommendations, and automated photo and merchandising tools to help dealers move inventory 5-10 days faster. The Garlyn Shelton dealership group validated these results, demonstrating significant improvement in turn rate after implementing CDK\'s inventory tools.',
      },
      tags: ['inventory-pricing', 'analytics-ai'],
      targetRoles: ['general-manager', 'sales-manager', 'dealer-principal'],
    },
    {
      id: 'o4',
      title: '88% Recall Service Completion',
      cardType: 'outcome',
      icon: 'check-circle',
      iconType: 'lucide',
      stat: '88%',
      description: {
        small: '88% of customers complete recall service when notified.',
        medium: 'CDK data shows 88% of customers service their recalls when notified, driving significant service revenue.',
        large: 'CDK research reveals that 88% of customers complete recall service when proactively notified, and 40% of those customers purchase additional services during the visit, creating a major revenue opportunity for service departments.',
        overlay: 'Recall management is an untapped revenue engine. CDK\'s data shows 88% of customers service their recalls when notified. Even more compelling, 40% of recall customers purchase additional services during the visit. CDK\'s connected platform enables proactive recall notifications, automated scheduling, and service advisor prompts that turn recall visits into full-service appointments.',
      },
      tags: ['fixed-ops', 'crm-engagement'],
      targetRoles: ['fixed-ops-director', 'general-manager', 'dealer-principal'],
    },
    {
      id: 'o5',
      title: '40% Upsell on Recall Visits',
      cardType: 'outcome',
      icon: 'trending-up',
      iconType: 'lucide',
      stat: '40%',
      description: {
        small: '40% of recall customers buy additional services.',
        medium: '40% of customers who come in for a recall purchase additional services, a revenue opportunity CDK helps dealers capture.',
        large: 'CDK\'s service lane technology helps dealers capture the 40% upsell opportunity on recall visits by giving service advisors real-time vehicle history, maintenance recommendations, and customer communication tools.',
        overlay: 'When a customer comes in for a recall, it\'s the dealership\'s chance to re-engage them with the service department. CDK data shows 40% of recall customers purchase additional services. CDK\'s fixed operations platform equips service advisors with vehicle history, predictive maintenance alerts, and inspection workflows that make it easy to present relevant service recommendations at the right moment.',
      },
      tags: ['fixed-ops', 'analytics-ai'],
      targetRoles: ['fixed-ops-director', 'sales-manager', 'general-manager'],
    },
    {
      id: 'o6',
      title: '50+ Years of Automotive Expertise',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: '50+',
      description: {
        small: 'Over 50 years powering automotive retail.',
        medium: 'CDK Global has been building dealership technology for over 50 years, longer than any competitor.',
        large: 'With over 50 years in automotive retail technology, CDK Global brings unmatched domain expertise to every product, integration, and support interaction, from DMS to digital retail to AI-powered analytics.',
        overlay: 'CDK Global\'s 50+ year history in automotive retail is not just a number. It represents decades of deep domain knowledge, OEM relationships, regulatory expertise, and industry partnerships that inform every product decision. This longevity means CDK understands the nuances of dealership operations, from franchise compliance to state-specific F&I regulations, in ways that newer entrants simply cannot.',
      },
      tags: ['dms-operations', 'fi-compliance'],
      targetRoles: ['dealer-principal', 'oem-partner', 'it-director'],
    },
    {
      id: 'o7',
      title: 'Connected Platform Efficiency',
      cardType: 'outcome',
      icon: 'plug',
      iconType: 'lucide',
      stat: '1',
      description: {
        small: 'One connected platform for your entire dealership.',
        medium: 'CDK\'s Dealership Xperience platform connects every department on a single, integrated system.',
        large: 'CDK\'s Dealership Xperience platform eliminates data silos by connecting sales, service, F&I, parts, and back office on one integrated system, reducing duplicate entry and improving cross-department visibility.',
        overlay: 'Disconnected systems cost dealerships time and money. CDK\'s Dealership Xperience platform is purpose-built to connect every department: sales floor to service lane, F&I to accounting, parts to procurement. The result is a single source of truth that eliminates redundant data entry, speeds up deal processing, improves customer handoffs between departments, and gives management real-time visibility into the entire operation.',
      },
      tags: ['dms-operations', 'digital-retail', 'analytics-ai'],
      targetRoles: ['dealer-principal', 'general-manager', 'it-director'],
    },

    // ── Learn (8) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Friction Points Study 2026',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com/insights',
      description: {
        small: 'CDK\'s annual study on dealership friction points.',
        medium: 'The 2026 Friction Points Study identifies the top pain points in the car buying and service experience.',
        large: 'CDK\'s annual Friction Points Study surveys thousands of consumers and dealers to identify where the automotive retail experience breaks down, from online research to in-store negotiation to service scheduling.',
        overlay: 'The Friction Points Study is CDK\'s flagship research publication, surveying thousands of consumers and dealership professionals annually. The 2026 edition reveals where buyers and service customers experience the most friction, how expectations have shifted, and what technology investments deliver the highest impact on customer satisfaction and dealership profitability.',
      },
      tags: ['digital-retail', 'crm-engagement'],
      targetRoles: ['dealer-principal', 'general-manager', 'sales-manager'],
    },
    {
      id: 'l2',
      title: 'How AI Is Reshaping Service',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com/insights',
      description: {
        small: 'Video on AI adoption in fixed operations.',
        medium: 'Industry leaders discuss how AI is transforming service departments, with only 25% of dealers currently using it.',
        large: 'This video panel features dealership operators and technology leaders discussing how AI is reshaping fixed operations, from automated repair order writing to predictive maintenance and smart scheduling.',
        overlay: 'Only 25% of dealerships currently use AI in their fixed operations, leaving massive untapped potential. This video features insights from industry leaders on practical AI applications in the service lane: automated repair order documentation, predictive maintenance alerts, intelligent scheduling, customer communication automation, and service advisor coaching tools. Learn where early adopters are seeing the biggest returns.',
      },
      tags: ['analytics-ai', 'fixed-ops'],
      targetRoles: ['fixed-ops-director', 'general-manager', 'it-director'],
    },
    {
      id: 'l3',
      title: 'From Recalls to Revenue',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com/insights',
      description: {
        small: 'Turn recall visits into service revenue.',
        medium: 'How dealers can capture additional services when 88% of customers complete their recalls.',
        large: 'This article breaks down CDK\'s recall data showing that 88% of customers service recalls when notified, and provides strategies for capturing the 40% who are willing to purchase additional services during the visit.',
        overlay: 'Recalls bring customers back to the dealership, but most service departments miss the upsell opportunity. This article details CDK\'s research showing 88% recall completion rates and 40% additional service capture rates. It covers best practices for recall notification timing, service advisor scripts, inspection workflow integration, and technology tools that help advisors present relevant recommendations at the right moment.',
      },
      tags: ['fixed-ops', 'crm-engagement'],
      targetRoles: ['fixed-ops-director', 'general-manager', 'sales-manager'],
    },
    {
      id: 'l4',
      title: 'Service Shopper Study',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com/insights',
      description: {
        small: 'How service customers choose where to go.',
        medium: 'CDK\'s research on what drives customers to choose a dealership service department over independents.',
        large: 'The Service Shopper Study examines consumer behavior in choosing between dealership service departments and independent shops, revealing the factors that drive loyalty, defection, and retention.',
        overlay: 'Dealership service departments face growing competition from independent shops, mobile mechanics, and DIY options. CDK\'s Service Shopper Study reveals what actually drives the consumer decision: scheduling convenience, price transparency, wait time expectations, digital communication preferences, and the role of trust in repeat visits. Use these insights to optimize your service lane experience and recapture lost customers.',
      },
      tags: ['fixed-ops', 'crm-engagement'],
      targetRoles: ['fixed-ops-director', 'general-manager', 'dealer-principal'],
    },
    {
      id: 'l5',
      title: '2026 Affordability Tracker',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'globe',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com/insights',
      description: {
        small: 'Track vehicle pricing and affordability trends.',
        medium: 'CDK\'s monthly tracker on transaction prices, incentives, and affordability trends across the market.',
        large: 'The 2026 Affordability Tracker provides monthly updates on vehicle transaction prices, manufacturer incentives, interest rate impacts, and consumer affordability metrics for both new and used vehicles.',
        overlay: 'Understanding market pricing dynamics is critical for inventory strategy and customer conversations. CDK\'s Affordability Tracker delivers monthly data on transaction prices by segment, incentive trends (car incentives spiked 58% while truck incentives fell 13%), interest rate impacts on monthly payments, and affordability indices that help dealers align their inventory and pricing strategies with real market conditions.',
      },
      tags: ['inventory-pricing', 'analytics-ai'],
      targetRoles: ['sales-manager', 'general-manager', 'dealer-principal'],
    },
    {
      id: 'l6',
      title: 'NADA 2026: AI & Talent Panel',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com/insights',
      description: {
        small: 'NADA panel on AI adoption and talent retention.',
        medium: 'Industry leaders at NADA 2026 discuss balancing AI investment with talent development in dealerships.',
        large: 'This NADA 2026 panel features dealership operators and CDK leaders discussing the intersection of AI technology adoption and workforce development, including how to upskill teams while implementing automation.',
        overlay: 'AI is transforming dealership operations, but technology alone is not enough. This NADA 2026 panel brings together dealer principals, GMs, and technology leaders to discuss the human side of digital transformation: upskilling service advisors to use AI tools, training F&I managers on digital workflows, retaining top talent during organizational change, and building a culture that embraces technology without losing the personal touch customers value.',
      },
      tags: ['analytics-ai', 'dms-operations'],
      targetRoles: ['dealer-principal', 'general-manager', 'fixed-ops-director'],
    },
    {
      id: 'l7',
      title: 'Digital Retailing Best Practices',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com/insights',
      description: {
        small: 'Best practices for online-to-showroom buying.',
        medium: 'A guide to creating seamless digital retail experiences that connect online shopping to in-store delivery.',
        large: 'This whitepaper covers CDK\'s approach to digital retailing: connecting online vehicle shopping, trade-in appraisals, F&I product selection, and credit applications to a seamless in-store delivery experience.',
        overlay: 'Today\'s car buyers start online but most still finish in the dealership. The challenge is making that transition seamless. This whitepaper details CDK\'s digital retail framework: online vehicle merchandising, integrated trade-in valuation tools, digital credit applications, F&I product presentation, and the technology infrastructure needed to ensure that everything a customer does online carries into the showroom without re-entry or lost data.',
      },
      tags: ['digital-retail', 'crm-engagement'],
      targetRoles: ['sales-manager', 'general-manager', 'dealer-principal'],
    },
    {
      id: 'l8',
      title: 'F&I Compliance in a Digital World',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com/insights',
      description: {
        small: 'Stay compliant as F&I goes digital.',
        medium: 'How to maintain regulatory compliance as F&I processes move from the finance office to online channels.',
        large: 'This article addresses the compliance challenges dealerships face as F&I moves online: digital disclosure requirements, e-signature regulations, state-specific rules, and how to audit digital F&I workflows.',
        overlay: 'As F&I processes increasingly move online, compliance risks multiply. This article covers the regulatory landscape for digital F&I: electronic disclosure requirements by state, e-signature validity, truth-in-lending disclosures in digital formats, data privacy obligations, and how CDK\'s platform maintains audit trails and compliance guardrails across both in-store and online F&I transactions.',
      },
      tags: ['fi-compliance', 'digital-retail'],
      targetRoles: ['fi-manager', 'dealer-principal', 'general-manager'],
    },

    // ── Solutions (7) ─────────────────────────────────
    {
      id: 's1',
      title: 'Dealership Xperience Platform',
      cardType: 'solution',
      icon: 'layout-dashboard',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com',
      description: {
        small: 'The connected DMS built for modern dealerships.',
        medium: 'CDK\'s flagship Dealer Management System connects every department on one integrated platform.',
        large: 'The Dealership Xperience Platform is CDK\'s next-generation DMS that unifies sales, service, F&I, parts, and back office with real-time data flow, eliminating silos and streamlining operations across the entire dealership.',
        overlay: 'The Dealership Xperience Platform represents CDK\'s vision for connected automotive retail. Built on a modern architecture, it provides a single data layer that connects every department: CRM to desking, F&I to accounting, service scheduling to parts ordering. Real-time data flow means no duplicate entry, instant visibility for managers, and a seamless experience for customers moving between online and in-store touchpoints.',
      },
      tags: ['dms-operations', 'digital-retail', 'analytics-ai'],
      targetRoles: ['dealer-principal', 'general-manager', 'it-director'],
    },
    {
      id: 's2',
      title: 'CDK Digital Retail',
      cardType: 'solution',
      icon: 'monitor-smartphone',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com',
      description: {
        small: 'Connect online shopping to in-store delivery.',
        medium: 'A seamless digital retailing experience that bridges online vehicle shopping with showroom delivery.',
        large: 'CDK Digital Retail connects the online shopping journey with in-store operations, letting customers research, price, value their trade, apply for credit, and select F&I products online before completing the deal at the dealership.',
        overlay: 'CDK Digital Retail eliminates the gap between online and in-store by connecting consumer-facing tools directly to the DMS. Customers can browse inventory, get real payments, value their trade-in, submit credit applications, and select F&I products from any device. When they arrive at the dealership, every piece of data flows into the deal jacket, eliminating re-entry and cutting deal time dramatically.',
      },
      tags: ['digital-retail', 'crm-engagement'],
      targetRoles: ['sales-manager', 'general-manager', 'dealer-principal'],
    },
    {
      id: 's3',
      title: 'CDK Service',
      cardType: 'solution',
      icon: 'wrench',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com',
      description: {
        small: 'Optimize your service lane from write-up to delivery.',
        medium: 'End-to-end service lane technology covering scheduling, inspections, repair orders, and customer communication.',
        large: 'CDK Service streamlines fixed operations with online scheduling, digital multi-point inspections, automated repair order processing, parts integration, technician dispatching, and proactive customer communication.',
        overlay: 'CDK Service transforms the service lane experience for both customers and staff. The platform covers the full service lifecycle: online scheduling and appointment reminders, mobile check-in, digital multi-point inspections with photos and video, automated repair order writing, real-time parts availability, technician dispatch optimization, status updates via text, and digital payment processing. Integration with the DMS means service history, warranty, and recall data is always at the advisor\'s fingertips.',
      },
      tags: ['fixed-ops', 'crm-engagement'],
      targetRoles: ['fixed-ops-director', 'general-manager', 'dealer-principal'],
    },
    {
      id: 's4',
      title: 'CDK CRM',
      cardType: 'solution',
      icon: 'users',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com',
      description: {
        small: 'Manage every customer relationship in one place.',
        medium: 'A dealership-specific CRM that connects sales, service, and marketing communications across the customer lifecycle.',
        large: 'CDK CRM provides a unified view of every customer interaction across sales and service, enabling personalized follow-up, automated campaigns, lead management, and equity mining to drive loyalty and repeat business.',
        overlay: 'Generic CRMs don\'t understand dealership workflows. CDK CRM is built for automotive retail, connecting internet leads, showroom ups, service appointments, and marketing campaigns in a single customer record. Features include AI-powered lead scoring, automated follow-up sequences, equity mining alerts, service-to-sales handoff tools, and campaign analytics that tie marketing spend directly to closed deals and service ROs.',
      },
      tags: ['crm-engagement', 'analytics-ai'],
      targetRoles: ['sales-manager', 'general-manager', 'dealer-principal'],
    },
    {
      id: 's5',
      title: 'CDK Intelligence Suite',
      cardType: 'solution',
      icon: 'brain',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com',
      description: {
        small: 'AI and analytics built for dealership decisions.',
        medium: 'Data intelligence powered by AI and machine learning that helps dealers make smarter operational decisions.',
        large: 'The CDK Intelligence Suite uses AI and machine learning to deliver actionable insights across sales, service, and inventory, from predictive analytics to automated reporting to anomaly detection.',
        overlay: 'CDK\'s Intelligence Suite leverages the company\'s unmatched dataset spanning nearly 15,000 dealerships to power AI-driven insights. Capabilities include predictive demand forecasting for parts and inventory, automated financial reporting, service appointment no-show prediction, customer churn risk scoring, market pricing intelligence, and anomaly detection that flags issues before they become problems. All insights are delivered in role-specific dashboards for dealer principals, GMs, and department heads.',
      },
      tags: ['analytics-ai', 'dms-operations'],
      targetRoles: ['dealer-principal', 'general-manager', 'it-director'],
    },
    {
      id: 's6',
      title: 'Vehicle Inventory Suite',
      cardType: 'solution',
      icon: 'car',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com',
      description: {
        small: 'Price, merchandise, and move inventory faster.',
        medium: 'AI-powered inventory management that helps dealers price competitively and turn vehicles 5-10 days faster.',
        large: 'The Vehicle Inventory Suite combines AI-powered pricing, automated photo and merchandising tools, and real-time market intelligence to help dealers optimize their lot, reduce days-to-turn, and maximize gross profit.',
        overlay: 'Inventory is a dealership\'s largest investment. CDK\'s Vehicle Inventory Suite protects that investment with AI-driven market pricing that updates in real time, automated photo capture and background enhancement, VIN-decoded merchandising descriptions, syndication to all major listing sites, and performance analytics that show which vehicles need price adjustments. Dealers using the suite report 5-10 days faster turn rates and improved front-end gross.',
      },
      tags: ['inventory-pricing', 'analytics-ai'],
      targetRoles: ['sales-manager', 'general-manager', 'dealer-principal'],
    },
    {
      id: 's7',
      title: 'F&I Solutions',
      cardType: 'solution',
      icon: 'file-check',
      iconType: 'lucide',
      url: 'https://www.cdkglobal.com',
      description: {
        small: 'Streamline F&I from desking to delivery.',
        medium: 'Digital F&I tools that speed up deal processing while maintaining compliance across every transaction.',
        large: 'CDK\'s F&I Solutions digitize the entire finance process from desking and menu presentation to lender submission, e-contracting, and compliance documentation, reducing deal time while improving product penetration.',
        overlay: 'The F&I office is where deals are won or lost. CDK\'s F&I Solutions streamline every step: intelligent desking that pulls real lender programs, digital menu presentation with customer-facing screens, one-click multi-lender submission, e-contracting with automated compliance checks, and digital deal jacket assembly. The result is faster deal processing, higher product penetration, fewer kickbacks, and a compliance audit trail that protects the dealership.',
      },
      tags: ['fi-compliance', 'digital-retail'],
      targetRoles: ['fi-manager', 'general-manager', 'dealer-principal'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
