// Explorer Config — Clarium Health
// Healthcare supply chain resiliency platform

import type { ExplorerConfig, ThemeColors } from '../types';

const CLARIUM_DARK: ThemeColors = {
  bg: '#0A0B1E',
  bgGradient: 'linear-gradient(135deg, #1E1B4B 0%, #0A0B1E 55%, #172554 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#818CF8',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(79,70,229,0.20)',
};

const CLARIUM_LIGHT: ThemeColors = {
  bg: '#F0F2F8',
  bgGradient: 'linear-gradient(160deg, #ECEEF6 0%, #F0F2F8 40%, #EDE9FE 100%)',
  surface: 'rgba(255,255,255,0.55)',
  surfaceHover: 'rgba(255,255,255,0.75)',
  border: 'rgba(6,19,65,0.08)',
  borderFocus: '#4F46E5',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.60)',
  text3: 'rgba(15,23,42,0.42)',
  inputBg: 'rgba(255,255,255,0.8)',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(79,70,229,0.12)',
};

export const CLARIUM_CONFIG: ExplorerConfig = {
  id: 'clarium',
  name: 'Clarium Health Explorer',
  version: 1,
  createdAt: '2026-04-07T00:00:00.000Z',
  updatedAt: '2026-04-07T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/clarium-dark.png',
      light: '/brand/assets/clarium-light.png',
    },
    icon: '/brand/assets/clarium-icon.png',
    colors: {
      primary: '#4F46E5',
      secondary: '#005AFF',
      teal: '#818CF8',
      blue: '#005AFF',
      deepBlue: '#3730A3',
      navy: '#1E1B4B',
      midnight: '#0A0B1E',
      plum: '#6D28D9',
      bgDark: '#0A0B1E',
      dark: CLARIUM_DARK,
      light: CLARIUM_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(79,70,229,0.12)',
      orb2: 'rgba(0,90,255,0.14)',
      orb3: 'rgba(109,40,217,0.10)',
    },
    ctaGradient: 'linear-gradient(135deg, #4F46E5, #005AFF)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #818CF8, #005AFF)',
    roleBackgrounds: {
      'csco': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(79,70,229,0.45) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(0,90,255,0.3) 0%, transparent 55%)',
      'vp-supply-chain': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,90,255,0.4) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(129,140,248,0.25) 0%, transparent 55%)',
      'supply-chain-director': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(129,140,248,0.35) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(79,70,229,0.2) 0%, transparent 55%)',
      'cfo-finance': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(109,40,217,0.4) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(79,70,229,0.3) 0%, transparent 55%)',
      'clinical-leader': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,90,255,0.35) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(109,40,217,0.25) 0%, transparent 55%)',
      'it-leadership': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(79,70,229,0.3) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(0,90,255,0.35) 0%, transparent 55%)',
      'procurement': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(129,140,248,0.35) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(109,40,217,0.3) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(109,40,217,0.3) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(129,140,248,0.2) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'scan',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Please fill in the form to continue.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Clarium Health processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@health.org', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Organization', type: 'text', placeholder: 'Health system or company', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Supply Chain',
      gradientWord: 'Resiliency.',
      subtitle: 'Discover how Astra OS gives your health system end-to-end visibility, predictive intelligence, and proactive disruption management.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes your role?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'csco', label: 'Chief Supply Chain Officer', icon: 'shield', iconType: 'lucide' },
        { value: 'vp-supply-chain', label: 'VP / Director, Supply Chain', icon: 'presentation', iconType: 'lucide' },
        { value: 'supply-chain-director', label: 'Supply Chain Manager', icon: 'boxes', iconType: 'lucide' },
        { value: 'cfo-finance', label: 'CFO / Finance', icon: 'banknote', iconType: 'lucide' },
        { value: 'clinical-leader', label: 'Clinical / Value Analysis', icon: 'heart-pulse', iconType: 'lucide' },
        { value: 'it-leadership', label: 'IT / Integration Lead', icon: 'server', iconType: 'lucide' },
        { value: 'procurement', label: 'Procurement Specialist', icon: 'shopping-cart', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'message-circle', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What challenges are you looking to solve?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'disruption-visibility', label: 'Disruption Visibility', icon: 'alert-triangle', iconType: 'lucide' },
        { value: 'substitute-management', label: 'Substitute Management', icon: 'repeat', iconType: 'lucide' },
        { value: 'cost-reduction', label: 'Cost Reduction', icon: 'trending-down', iconType: 'lucide' },
        { value: 'preference-cards', label: 'Procedure Card Optimization', icon: 'clipboard-list', iconType: 'lucide' },
        { value: 'data-visibility', label: 'Data Unification / Visibility', icon: 'eye', iconType: 'lucide' },
        { value: 'erp-migration', label: 'ERP Migration Support', icon: 'database', iconType: 'lucide' },
        { value: 'demo', label: 'See a Demo', icon: 'play-circle', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Website', value: 'website' },
        ]},
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'medium',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: '50% Faster Disruption Resolution',
      cardType: 'outcome',
      icon: 'zap',
      iconType: 'lucide',
      stat: '50%',
      description: {
        small: 'Resolve supply disruptions twice as fast.',
        medium: 'Cut disruption resolution time in half with real-time alerts and prescriptive workflows.',
        large: 'Clarium\'s Disruption Monitor converts network signals into predictive alerts and actionable workflows, enabling health systems to resolve supply chain disruptions 50% faster than manual processes.',
        overlay: 'Health systems face an average of 65 supply chain disruptions per week. Clarium\'s AI-powered Disruption Monitor aggregates signals across your entire supply network, automatically prioritizes by clinical criticality, and prescribes resolution workflows that cut response time by 50%.',
      },
      tags: ['disruption-visibility', 'efficiency'],
      targetRoles: ['csco', 'vp-supply-chain', 'supply-chain-director', 'procurement'],
    },
    {
      id: 'o2',
      title: '$10M+ Average Cost Savings',
      cardType: 'outcome',
      icon: 'trending-down',
      iconType: 'lucide',
      stat: '$10M+',
      description: {
        small: 'Drive eight-figure supply chain savings.',
        medium: '$10M+ average savings per health system through visibility, standardization, and waste reduction.',
        large: 'Clarium customers achieve $10M+ in annual savings by eliminating overnight shipping costs, reducing expired inventory, standardizing procedure cards, and optimizing supplier contracts.',
        overlay: 'Healthcare overspends on supply chain by $25B+ annually. Clarium\'s unified data platform reveals hidden waste across procurement, inventory, and clinical usage, delivering $10M+ in average savings per health system through automated optimization.',
      },
      tags: ['cost-reduction'],
      targetRoles: ['csco', 'cfo-finance', 'vp-supply-chain'],
    },
    {
      id: 'o3',
      title: '88% Faster Substitute Approvals',
      cardType: 'outcome',
      icon: 'repeat',
      iconType: 'lucide',
      stat: '88%',
      description: {
        small: 'Approve clinical substitutes nearly 9x faster.',
        medium: 'Accelerate substitute approvals by 88% with crowdsourced clinical equivalency data.',
        large: 'Clarium\'s Substitute Manager draws on a validated, crowdsourced database built with value analysis teams across dozens of health systems, cutting substitute approval time by 88%.',
        overlay: 'When a critical supply is disrupted, finding and approving a clinically equivalent substitute can take days or weeks. Clarium\'s crowdsourced Substitute Manager provides pre-validated alternatives from peer health systems, reducing approval time by 88% while maintaining clinical safety.',
      },
      tags: ['substitute-management', 'disruption-visibility'],
      targetRoles: ['clinical-leader', 'supply-chain-director', 'procurement'],
    },
    {
      id: 'o4',
      title: '4-Week Platform Go-Live',
      cardType: 'outcome',
      icon: 'rocket',
      iconType: 'lucide',
      stat: '4 wks',
      description: {
        small: 'Go live in approximately 4 weeks.',
        medium: 'Deploy Astra OS in 4 weeks with minimal IT burden and automated data ingestion.',
        large: 'Unlike legacy supply chain tools requiring 12-18 month implementations, Clarium\'s Astra OS goes live in approximately 4 weeks through automated data ingestion from EHRs, ERPs, and existing systems.',
        overlay: 'Clarium\'s platform-agnostic architecture connects to your existing systems (EHR, ERP, GPO, EDI, WMS) through automated data ingestion. With 7M+ items in the Universal Item Master, data normalization happens automatically, enabling a 4-week go-live with minimal IT resources.',
      },
      tags: ['data-visibility', 'erp-migration'],
      targetRoles: ['it-leadership', 'csco', 'vp-supply-chain'],
    },
    {
      id: 'o5',
      title: 'Real-Time Supply Chain Visibility',
      cardType: 'outcome',
      icon: 'eye',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: 'Full visibility across your entire supply chain.',
        medium: 'Gain a single pane of glass view across all supply chain data sources in real time.',
        large: 'Astra OS unifies data from EHRs, ERPs, GPOs, distributors, and point-of-use systems into a single real-time view, eliminating blind spots that lead to stockouts and patient safety risks.',
        overlay: 'Most health systems operate with fragmented supply chain data across dozens of disconnected systems. Clarium\'s Astra OS provides a single pane of glass that unifies procurement, inventory, clinical usage, and supplier performance data in real time, giving every stakeholder the visibility they need.',
      },
      tags: ['data-visibility', 'disruption-visibility'],
      targetRoles: ['csco', 'vp-supply-chain', 'supply-chain-director', 'cfo-finance'],
    },
    {
      id: 'o6',
      title: '74% Substitute Coverage in Crises',
      cardType: 'outcome',
      icon: 'shield',
      iconType: 'lucide',
      stat: '74%',
      description: {
        small: 'Pre-approved substitutes ready for emergencies.',
        medium: '74% of items affected by major disruptions already have approved substitutes in the Clarium network.',
        large: 'During Hurricane Helene, 74% of affected items had pre-approved clinical substitutes available through Clarium\'s crowdsourced network, enabling rapid response while other systems scrambled.',
        overlay: 'When Hurricane Helene disrupted healthcare supply chains, Clarium\'s network intelligence showed that 74% of affected items already had approved clinical substitutes available. This crowdsourced resilience meant Clarium customers could respond in minutes rather than days, protecting patient care and avoiding costly emergency procurement.',
      },
      tags: ['substitute-management', 'disruption-visibility'],
      targetRoles: ['csco', 'clinical-leader', 'supply-chain-director'],
    },
    {
      id: 'o7',
      title: 'Continuous Analytics Through ERP Migration',
      cardType: 'outcome',
      icon: 'database',
      iconType: 'lucide',
      stat: '0%',
      description: {
        small: 'Zero analytics downtime during ERP transitions.',
        medium: 'Maintain continuous supply chain analytics even during major ERP migrations.',
        large: 'Health systems typically lose months of analytics visibility during ERP transitions. Clarium provides continuous data normalization and insights throughout the migration, with full transition completed in 12 weeks.',
        overlay: 'ERP migrations are one of the most disruptive events in a health system\'s lifecycle. Clarium\'s platform-agnostic architecture maintains continuous supply chain analytics throughout the transition. One academic medical center completed their full ERP data migration in 12 weeks with zero gaps in supply chain visibility.',
      },
      tags: ['erp-migration', 'data-visibility'],
      targetRoles: ['it-leadership', 'csco', 'cfo-finance'],
    },

    // ── Learn (8) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'From Reactive to Resilient',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/newsroom/reactive-to-resilient-ochsner-health-allina-health',
      description: {
        small: 'Ochsner Health and Allina Health discuss strategy.',
        medium: 'A discussion on supply chain strategy with Ochsner Health and Allina Health leadership.',
        large: 'Leaders from Ochsner Health and Allina Health share how they are shifting from reactive firefighting to proactive supply chain resilience, with real examples from their Clarium implementation.',
        overlay: 'In this in-depth discussion, supply chain leaders from Ochsner Health and Allina Health share their journey from reactive supply chain management to building true resilience. They discuss the challenges of disruption management, the role of data and AI, and how Clarium\'s platform enabled a strategic transformation.',
      },
      tags: ['disruption-visibility', 'substitute-management'],
      targetRoles: ['csco', 'vp-supply-chain'],
    },
    {
      id: 'l2',
      title: 'ERP Transition Case Study',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/newsroom/supply-chain-erp-case-study',
      description: {
        small: 'Protecting visibility through an ERP transition.',
        medium: 'How a large academic health system maintained supply chain visibility during a major ERP migration.',
        large: 'This case study details how a large academic medical center used Clarium to maintain continuous supply chain analytics and visibility during a complex ERP transition, completing migration in 12 weeks.',
        overlay: 'When a major academic health system embarked on an ERP migration, they faced the risk of losing months of supply chain analytics. By deploying Clarium\'s platform-agnostic data layer, they maintained continuous visibility throughout the transition, completed data migration in 12 weeks, and actually gained new insights during the process.',
      },
      tags: ['erp-migration', 'data-visibility'],
      targetRoles: ['it-leadership', 'csco', 'vp-supply-chain'],
    },
    {
      id: 'l3',
      title: 'Building Supply Chain Resilience',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/newsroom/national-health-system-supply-chain-resilience',
      description: {
        small: 'How a national health system built resilience.',
        medium: 'Case study on how a national health system is building long-term supply chain resilience with Clarium.',
        large: 'A national health system shares their journey implementing Clarium to build proactive supply chain resilience, moving from reactive disruption management to predictive intelligence.',
        overlay: 'This case study explores how a national health system transformed their supply chain operations by implementing Clarium\'s Astra OS platform. They detail the measurable improvements in disruption response time, cost savings, and clinical safety outcomes achieved through proactive resilience strategies.',
      },
      tags: ['disruption-visibility', 'cost-reduction'],
      targetRoles: ['csco', 'vp-supply-chain', 'cfo-finance'],
    },
    {
      id: 'l4',
      title: 'Iran War: Supply Chain Impact',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'globe',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/newsroom/iran-war-disrupting-healthcare-supply-chain',
      description: {
        small: 'Geopolitical disruption and healthcare supply.',
        medium: 'How the Iran conflict is creating a 1,000% increase in supplier rejections across healthcare.',
        large: 'Clarium\'s network intelligence tracked a 1,000% increase in supplier rejections during the Iran/Strait of Hormuz crisis, demonstrating why real-time monitoring is critical for healthcare supply chains.',
        overlay: 'The Iran conflict created immediate ripple effects through healthcare supply chains via the Strait of Hormuz. Clarium\'s Disruption Monitor tracked a 1,000% increase in supplier rejections in real time, enabling connected health systems to activate pre-approved substitutes and secure alternative sources before shortages hit.',
      },
      tags: ['disruption-visibility'],
      targetRoles: ['csco', 'vp-supply-chain', 'supply-chain-director'],
    },
    {
      id: 'l5',
      title: '6 Ways to Evaluate Resiliency Platforms',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'list-checks',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/newsroom/evaluate-supply-chain-resiliency-platforms',
      description: {
        small: 'Framework for evaluating supply chain tools.',
        medium: 'A practical guide to evaluating supply chain resiliency platforms for your health system.',
        large: 'This guide outlines six critical evaluation criteria for supply chain resiliency platforms, from data integration depth to network intelligence and clinical safety features.',
        overlay: 'Choosing the right supply chain resiliency platform is a high-stakes decision for health systems. This guide walks through six essential evaluation criteria: data integration breadth, real-time analytics capability, network intelligence, clinical safety features, implementation speed, and total cost of ownership.',
      },
      tags: ['data-visibility', 'cost-reduction'],
      targetRoles: ['csco', 'vp-supply-chain', 'it-leadership'],
    },
    {
      id: 'l6',
      title: 'Ochsner Health: Real-World Strategies',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/newsroom/ochsner-health-supply-chain-resilience',
      description: {
        small: 'Ochsner Health shares their resilience playbook.',
        medium: 'Real-world strategies from Ochsner Health on building supply chain resilience with Clarium.',
        large: 'Ochsner Health\'s supply chain leadership details their practical strategies for building resilience, including how Clarium\'s network intelligence and predictive alerts transformed their operations.',
        overlay: 'Ochsner Health, one of the largest health systems in the Gulf South, shares their detailed playbook for building supply chain resilience. Their leadership discusses how Clarium\'s platform enabled them to shift from reactive disruption management to proactive strategies that protect patient care and reduce costs.',
      },
      tags: ['disruption-visibility', 'substitute-management'],
      targetRoles: ['csco', 'vp-supply-chain', 'supply-chain-director'],
    },
    {
      id: 'l7',
      title: 'Winter Storm Fern: Cost Structure Impact',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'cloud-snow',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/newsroom/winter-storm-fern-supply-chain-cost-structure',
      description: {
        small: 'How severe weather impacts supply chain costs.',
        medium: 'Analyzing how Winter Storm Fern impacted a health system\'s entire cost structure beyond just supply disruptions.',
        large: 'This analysis goes beyond direct supply disruptions to examine how severe weather events like Winter Storm Fern cascade through a health system\'s entire cost structure, from emergency procurement to staffing.',
        overlay: 'Severe weather events impact far more than just product availability. This analysis of Winter Storm Fern tracks the cascading cost impact across emergency procurement, overnight shipping, staffing, clinical workflow disruptions, and revenue loss, making the case for proactive resiliency investment.',
      },
      tags: ['disruption-visibility', 'cost-reduction'],
      targetRoles: ['cfo-finance', 'csco', 'vp-supply-chain'],
    },
    {
      id: 'l8',
      title: 'Why Resiliency Is a Strategic Imperative',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'shield',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/newsroom/why-supply-chain-resiliency-is-now-a-strategic-imperative-for-health-systems',
      description: {
        small: 'The case for strategic supply chain investment.',
        medium: 'Why supply chain resiliency has become a board-level strategic imperative for health systems.',
        large: 'Supply chain resiliency has moved from an operational concern to a board-level strategic imperative. This article outlines why health systems that fail to invest in modern supply chain technology face growing financial and clinical risks.',
        overlay: 'With $250B+ spent annually on healthcare supply chain and disruptions increasing in frequency and severity, resiliency has become a C-suite strategic imperative. This article outlines the financial, clinical, and operational risks of maintaining legacy approaches and the ROI case for modern resiliency platforms.',
      },
      tags: ['cost-reduction', 'data-visibility'],
      targetRoles: ['csco', 'cfo-finance', 'vp-supply-chain'],
    },

    // ── Solutions (7) ─────────────────────────────────
    {
      id: 's1',
      title: 'Disruption Monitor',
      cardType: 'solution',
      icon: 'alert-triangle',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/',
      description: {
        small: 'Supply chain control tower with predictive alerts.',
        medium: 'Real-time supply chain control tower that converts network signals into predictive alerts and resolution workflows.',
        large: 'Disruption Monitor is Clarium\'s supply chain control tower, aggregating signals from across the healthcare network to deliver predictive disruption alerts, automated prioritization by clinical criticality, and prescriptive resolution workflows.',
        overlay: 'The Disruption Monitor serves as your supply chain command center, continuously monitoring signals from suppliers, distributors, weather systems, geopolitical events, and peer health systems. It automatically prioritizes disruptions by clinical criticality and patient impact, then prescribes specific resolution workflows including pre-approved substitutes and alternative sourcing options.',
      },
      tags: ['disruption-visibility'],
      targetRoles: ['csco', 'vp-supply-chain', 'supply-chain-director', 'procurement'],
    },
    {
      id: 's2',
      title: 'Substitute Manager',
      cardType: 'solution',
      icon: 'repeat',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/',
      description: {
        small: 'Crowdsourced clinical substitute database.',
        medium: 'Find clinically equivalent substitutes instantly using a validated, crowdsourced database from peer health systems.',
        large: 'Substitute Manager provides instant access to clinically equivalent alternatives validated by value analysis teams across the Clarium network, reducing approval time by 88% while maintaining clinical safety standards.',
        overlay: 'When a critical supply is disrupted, every minute counts. Substitute Manager draws on a crowdsourced database of clinically validated substitutes contributed by value analysis teams across dozens of leading health systems. Each substitute is mapped with clinical equivalency data, pricing comparisons, and peer utilization metrics.',
      },
      tags: ['substitute-management', 'disruption-visibility'],
      targetRoles: ['clinical-leader', 'supply-chain-director', 'procurement'],
    },
    {
      id: 's3',
      title: 'Card Optimizer',
      cardType: 'solution',
      icon: 'clipboard-list',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/',
      description: {
        small: 'AI-driven procedure card management.',
        medium: 'Standardize OR supply usage and reduce waste with AI-powered procedure card optimization.',
        large: 'Card Optimizer uses AI to analyze procedure card utilization patterns across your system, identifying opportunities to standardize surgical supply usage, reduce waste, and lower per-case costs while maintaining clinical quality.',
        overlay: 'Procedure card variability is one of the largest hidden costs in healthcare supply chain. Card Optimizer analyzes utilization patterns across surgeons, specialties, and facilities, using AI to recommend standardization opportunities. It identifies unused items, overstock patterns, and substitution opportunities that reduce per-case costs without impacting clinical outcomes.',
      },
      tags: ['preference-cards', 'cost-reduction'],
      targetRoles: ['clinical-leader', 'supply-chain-director', 'cfo-finance'],
    },
    {
      id: 's4',
      title: 'Oculus AI Assistant',
      cardType: 'solution',
      icon: 'bot',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/',
      description: {
        small: 'AI assistant for cross-system supply chain insights.',
        medium: 'AI-powered assistant that answers questions, delivers insights, and executes tasks across your supply chain data.',
        large: 'Oculus AI is Clarium\'s intelligent assistant that answers natural language questions about your supply chain, delivers cross-system insights, and can execute user-directed tasks like running analyses and generating reports.',
        overlay: 'Oculus AI sits on top of all your unified supply chain data and serves as an intelligent interface for every stakeholder. Ask questions in natural language, get instant cross-system insights, run what-if analyses, generate reports, and execute workflows without needing to navigate multiple systems or export data to spreadsheets.',
      },
      tags: ['data-visibility', 'disruption-visibility'],
      targetRoles: ['csco', 'vp-supply-chain', 'supply-chain-director', 'cfo-finance'],
    },
    {
      id: 's5',
      title: 'Resiliency Monitor',
      cardType: 'solution',
      icon: 'activity',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/',
      description: {
        small: 'Real-time supplier performance tracking.',
        medium: 'Monitor supplier metrics in real time: disruption rates, fulfillment, OTIF, lead times, and compliance.',
        large: 'Resiliency Monitor provides real-time visibility into supplier performance across your entire network, tracking disruption rates, order fulfillment, OTIF scores, lead times, and compliance metrics to identify risks before they become disruptions.',
        overlay: 'Resiliency Monitor continuously tracks every supplier in your network across key performance metrics: disruption frequency and severity, order fulfillment rates, on-time in-full (OTIF) scores, lead time variability, and compliance status. It uses AI to identify deteriorating trends and predict potential disruptions before they impact your operations.',
      },
      tags: ['disruption-visibility', 'data-visibility'],
      targetRoles: ['procurement', 'supply-chain-director', 'vp-supply-chain'],
    },
    {
      id: 's6',
      title: 'Universal Item Master',
      cardType: 'solution',
      icon: 'database',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/',
      description: {
        small: '7M+ item database for data normalization.',
        medium: 'Automated data mapping and normalization across all your supply chain systems with 7M+ items.',
        large: 'Clarium\'s Universal Item Master contains 7M+ healthcare items with normalized data, enabling automated mapping across your EHR, ERP, GPO, and distributor systems for a single source of truth.',
        overlay: 'Data fragmentation is the root cause of most supply chain blind spots. Clarium\'s Universal Item Master normalizes 7M+ items across every data source in your ecosystem, automatically mapping item identifiers, pricing, clinical categories, and supplier relationships. This creates the unified data foundation that powers all of Clarium\'s analytics and AI capabilities.',
      },
      tags: ['data-visibility', 'erp-migration'],
      targetRoles: ['it-leadership', 'supply-chain-director', 'vp-supply-chain'],
    },
    {
      id: 's7',
      title: 'Astra OS Platform',
      cardType: 'solution',
      icon: 'layout-dashboard',
      iconType: 'lucide',
      url: 'https://www.clariumhealth.com/',
      description: {
        small: 'The healthcare supply chain resiliency platform.',
        medium: 'Astra OS: a unified platform connecting health systems and suppliers in a two-sided resiliency network.',
        large: 'Astra OS is the world\'s first healthcare supply chain resiliency platform, providing a unified data layer that connects health systems with suppliers and leverages crowdsourced network intelligence for predictive insights.',
        overlay: 'Astra OS is Clarium\'s flagship platform, purpose-built for healthcare supply chain resiliency. It unifies data from every source in your ecosystem (EHR, ERP, GPO, EDI, WMS, revenue cycle), creates a single source of truth through the Universal Item Master, and layers AI-powered analytics on top. The platform\'s two-sided network connects health systems with suppliers, enabling crowdsourced intelligence that benefits the entire community.',
      },
      tags: ['data-visibility', 'disruption-visibility', 'cost-reduction'],
      targetRoles: ['csco', 'vp-supply-chain', 'cfo-finance', 'it-leadership'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
