// Explorer Config — DealRoom
// M&A management platform for corporate development and integration teams

import type { ExplorerConfig, ThemeColors } from '../types';

const DEALROOM_DARK: ThemeColors = {
  bg: '#02111D',
  bgGradient: 'linear-gradient(135deg, #012B52 0%, #010E1F 55%, #01183A 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#288CE1',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(2,120,219,0.20)',
};

const DEALROOM_LIGHT: ThemeColors = {
  bg: '#F4F6F9',
  bgGradient: 'linear-gradient(180deg, #F4F6F9 0%, #EEF2F8 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#0278DB',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(2,120,219,0.12)',
};

export const DEALROOM_CONFIG: ExplorerConfig = {
  id: 'dealroom',
  name: 'DealRoom Explorer',
  version: 1,
  createdAt: '2026-04-26T00:00:00.000Z',
  updatedAt: '2026-04-26T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/dealroom-logo-reverse.svg',
      light: '/brand/assets/dealroom-logo.svg',
    },
    icon: '/brand/assets/dealroom-icon.png',
    colors: {
      primary: '#0278DB',
      secondary: '#288CE1',
      teal: '#38BDF8',
      blue: '#0278DB',
      deepBlue: '#0156A2',
      navy: '#03243F',
      midnight: '#021322',
      plum: '#1E3A8A',
      bgDark: '#021322',
      dark: DEALROOM_DARK,
      light: DEALROOM_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(2,120,219,0.14)',
      orb2: 'rgba(40,140,225,0.10)',
      orb3: 'rgba(30,58,138,0.12)',
    },
    ctaGradient: 'linear-gradient(135deg, #0278DB 0%, #288CE1 100%)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #38BDF8, #0278DB)',
    roleBackgrounds: {
      'corp-dev': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(2,120,219,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(40,140,225,0.10) 0%, transparent 55%)',
      'integration-leader': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(40,140,225,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(56,189,248,0.10) 0%, transparent 55%)',
      'ma-advisor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(1,86,162,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 20% 20%, rgba(2,120,219,0.10) 0%, transparent 55%)',
      'private-equity': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(30,58,138,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 80% 20%, rgba(2,120,219,0.12) 0%, transparent 55%)',
      'executive': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(2,120,219,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(30,58,138,0.10) 0%, transparent 55%)',
      'finance-legal': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(56,189,248,0.12) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(2,120,219,0.12) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'scan',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Please fill in the form to continue.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to DealRoom processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Your organization', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'M&A Done',
      gradientWord: 'Right.',
      subtitle: 'Discover how DealRoom unifies your pipeline, diligence, and integration workflows so your team can execute more deals, faster.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes your role?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'corp-dev', label: 'Corporate Development', icon: 'building-2', iconType: 'lucide' },
        { value: 'integration-leader', label: 'Integration Leader', icon: 'git-merge', iconType: 'lucide' },
        { value: 'ma-advisor', label: 'M&A Advisor / Banker', icon: 'handshake', iconType: 'lucide' },
        { value: 'private-equity', label: 'Private Equity / Roll-Up', icon: 'trending-up', iconType: 'lucide' },
        { value: 'executive', label: 'CEO / Executive', icon: 'crown', iconType: 'lucide' },
        { value: 'finance-legal', label: 'Finance & Legal', icon: 'scale', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you looking to solve?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'pipeline', label: 'Deal Pipeline', icon: 'kanban', iconType: 'lucide' },
        { value: 'diligence', label: 'Due Diligence', icon: 'file-search', iconType: 'lucide' },
        { value: 'integration', label: 'Post-Merger Integration', icon: 'layers', iconType: 'lucide' },
        { value: 'ai-automation', label: 'AI & Automation', icon: 'bot', iconType: 'lucide' },
        { value: 'data-room', label: 'Data Room & Security', icon: 'lock', iconType: 'lucide' },
        { value: 'reporting', label: 'Reporting & Visibility', icon: 'bar-chart-2', iconType: 'lucide' },
        { value: 'team-collaboration', label: 'Team Collaboration', icon: 'users', iconType: 'lucide' },
        { value: 'just-browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        {
          id: 'learn', label: 'Learn', icon: 'book-open', filters: [
            { label: 'All', value: 'all' },
            { label: 'Video', value: 'video' },
            { label: 'Webinar', value: 'webinar' },
            { label: 'Blog', value: 'blog' },
            { label: 'Podcast', value: 'podcast' },
          ],
        },
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'medium',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────────────────────────────
    {
      id: 'o1',
      title: '$255B+ in Transactions Powered',
      cardType: 'outcome',
      icon: 'dollar-sign',
      iconType: 'lucide',
      stat: '$255B+',
      description: {
        small: 'Trusted to power over $255 billion in M&A.',
        medium: 'DealRoom has been the platform of record for over $255 billion in M&A transactions globally.',
        large: 'From sub-$10M tuck-ins to billion-dollar transformational deals, DealRoom has powered over $255 billion in transactions. Teams trust DealRoom to manage pipeline, diligence, and integration from first look to Day 100.',
        overlay: 'Corporate development teams choose DealRoom because it works at every deal size and complexity. With $255B+ in transactions powered, DealRoom carries the institutional knowledge of thousands of deals into your workflows — from pipeline origination and CRM integration through due diligence rooms and post-merger integration tracking. This breadth of proven use means less configuration and more execution from day one.',
      },
      tags: ['pipeline', 'diligence', 'integration'],
      targetRoles: ['corp-dev', 'executive', 'private-equity'],
    },
    {
      id: 'o2',
      title: '40+ Hours Saved Per Deal',
      cardType: 'outcome',
      icon: 'clock',
      iconType: 'lucide',
      stat: '40+ hrs',
      description: {
        small: 'Save 40+ hours of manual work per deal.',
        medium: 'Cadence Education saves over 40 hours per deal by replacing manual tracking with DealRoom.',
        large: 'Cadence Education eliminated spreadsheets, email chains, and manual status updates by centralizing their M&A process on DealRoom. The result: 40+ hours saved per deal — time redirected to higher-value diligence and integration work.',
        overlay: 'Cadence Education\'s corp dev team was drowning in Excel trackers and email threads before DealRoom. After centralizing their pipeline, diligence, and integration workflows, they recovered 40+ hours per deal — equivalent to an extra week of focused work per transaction. DealRoom\'s automated workflows, centralized data rooms, and real-time dashboards eliminate the coordination overhead that kills M&A productivity.',
      },
      tags: ['pipeline', 'diligence', 'ai-automation'],
      targetRoles: ['corp-dev', 'integration-leader', 'private-equity'],
    },
    {
      id: 'o3',
      title: 'Deal Time Cut in Half',
      cardType: 'outcome',
      icon: 'zap',
      iconType: 'lucide',
      stat: '2x faster',
      description: {
        small: 'JAMF cut their deal cycle time in half.',
        medium: 'JAMF uses DealRoom to move twice as fast from LOI to close without sacrificing diligence quality.',
        large: 'JAMF\'s acquisition team leveraged DealRoom\'s structured workflows and centralized data rooms to compress their deal timelines by 50%. Faster diligence cycles mean better competitive positioning and lower deal fatigue for both sides of the table.',
        overlay: 'In competitive M&A markets, speed is a strategic advantage. JAMF\'s corp dev team cut their deal timeline in half by standardizing diligence workflows, automating document requests, and giving all stakeholders real-time visibility into deal status. With DealRoom, parallel workstreams run without the coordination bottlenecks that traditionally slow deals — diligence, legal, finance, and integration planning advance simultaneously rather than sequentially.',
      },
      tags: ['diligence', 'pipeline', 'team-collaboration'],
      targetRoles: ['corp-dev', 'executive', 'ma-advisor'],
    },
    {
      id: 'o4',
      title: '$200K Annual Cost Savings',
      cardType: 'outcome',
      icon: 'piggy-bank',
      iconType: 'lucide',
      stat: '$200K',
      description: {
        small: 'Liberty saves $200K per year with DealRoom.',
        medium: 'By consolidating M&A tools onto DealRoom, Liberty eliminated $200K in annual redundant software costs.',
        large: 'Liberty replaced a fragmented stack of data room providers, project management tools, and spreadsheets with DealRoom\'s unified platform. The consolidation eliminated $200,000 in annual software spend while improving team coordination across every deal.',
        overlay: 'Most corp dev teams are running 4-6 tools to manage a single deal: a virtual data room, a project tracker, a CRM, a document collaboration tool, and shared drives. Liberty realized they were paying for all of them separately — and still losing time to re-keying data between systems. By consolidating onto DealRoom\'s integrated platform, they captured $200K in annual savings while gaining a single source of truth for every active deal.',
      },
      tags: ['pipeline', 'reporting'],
      targetRoles: ['corp-dev', 'executive', 'finance-legal'],
    },
    {
      id: 'o5',
      title: '35 Hours Saved Per Deal',
      cardType: 'outcome',
      icon: 'timer',
      iconType: 'lucide',
      stat: '35 hrs',
      description: {
        small: 'Miro saves 35 hours per deal on diligence.',
        medium: 'Miro\'s M&A team eliminated 35 hours of administrative overhead per deal using DealRoom\'s automated workflows.',
        large: 'Miro\'s corp dev team used to spend 35+ hours per deal managing diligence logistics — document requests, follow-ups, version control, and status reporting. DealRoom automated these workflows, freeing the team to focus on analysis and negotiation.',
        overlay: 'Miro\'s acquisition team was spending more time managing process than evaluating targets. With DealRoom, automated diligence request lists, real-time document tracking, and stakeholder dashboards replaced manual coordination. The 35 hours recovered per deal go back into deal quality — deeper financial analysis, stronger integration planning, and faster decision-making at every stage.',
      },
      tags: ['diligence', 'ai-automation', 'team-collaboration'],
      targetRoles: ['corp-dev', 'integration-leader', 'ma-advisor'],
    },
    {
      id: 'o6',
      title: '350+ Companies Trust DealRoom',
      cardType: 'outcome',
      icon: 'users',
      iconType: 'lucide',
      stat: '350+',
      description: {
        small: 'The M&A platform of choice for 350+ teams.',
        medium: 'Over 350 companies — from growth-stage acquirers to Fortune 500 corp dev teams — rely on DealRoom.',
        large: 'DealRoom\'s customer base spans corp dev teams at public companies, high-growth acquirers, PE-backed roll-up platforms, and sell-side advisory firms. With 350+ customers, DealRoom brings proven workflows and best practices from thousands of deals into your team\'s process.',
        overlay: 'When 350+ M&A teams choose the same platform, they\'re voting for a system that actually works in the complexity of real deals. DealRoom\'s customer roster includes serial acquirers doing 10+ deals per year, single-deal teams managing their first acquisition, PE roll-up platforms standardizing across portfolio companies, and advisory firms supporting buy-side clients. Each of these teams brought their requirements to DealRoom — and DealRoom evolved to serve all of them.',
      },
      tags: ['pipeline', 'integration', 'reporting'],
      targetRoles: ['corp-dev', 'private-equity', 'executive', 'ma-advisor'],
    },
    {
      id: 'o7',
      title: '20+ Hours of Diligence Work Saved',
      cardType: 'outcome',
      icon: 'file-check',
      iconType: 'lucide',
      stat: '20+ hrs',
      description: {
        small: 'Wipfli recovers 20+ hours of diligence work per deal.',
        medium: 'Wipfli\'s advisory team saves 20+ hours per engagement by using DealRoom AI to automate document review.',
        large: 'Wipfli\'s M&A advisory team uses DealRoom AI to automatically analyze uploaded documents, flag missing items, and surface key findings. The result is 20+ hours saved per deal — allowing advisors to spend more time on insight and less on document management.',
        overlay: 'Wipfli\'s advisors were spending the first days of every engagement just organizing and cross-referencing documents in a data room. DealRoom AI changed that: documents are automatically categorized, analyzed for completeness against standard diligence checklists, and surfaced to reviewers with AI-generated summaries and flags. The 20+ hours saved per deal compound across Wipfli\'s full advisory practice — representing thousands of hours recovered annually.',
      },
      tags: ['diligence', 'ai-automation'],
      targetRoles: ['ma-advisor', 'corp-dev', 'finance-legal'],
    },

    // ── Learn (8) ─────────────────────────────────────────────────────────────
    {
      id: 'l1',
      title: 'You Can\'t Scale M&A with Duct Tape',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Why spreadsheets and email break at scale.',
        medium: 'DealRoom\'s flagship video on why legacy M&A tools fail growing corp dev teams.',
        large: 'As acquisition volume grows, the ad hoc tools that worked for two deals a year break down. This video explores why corporate development teams outgrow spreadsheets and shared drives — and what a modern M&A platform looks like in practice.',
        overlay: 'Every corp dev team starts with spreadsheets. But as deal volume increases, the coordination overhead of manual tracking — status updates, document chasing, version control, stakeholder alignment — consumes more bandwidth than the actual deal work. This video walks through the breaking points in legacy M&A workflows, with real examples from teams that made the transition to a purpose-built platform. If you\'ve felt the friction of scaling M&A on generic tools, this one is for you.',
      },
      tags: ['pipeline', 'diligence', 'ai-automation'],
      targetRoles: ['corp-dev', 'executive', 'private-equity'],
    },
    {
      id: 'l2',
      title: 'M&A Integration Playbook',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'book-open',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Best practices for post-merger integration.',
        medium: 'A comprehensive guide to building and executing integration plans that preserve deal value.',
        large: 'This playbook covers the end-to-end integration process — from pre-close planning through Day 100 milestones. Learn how leading integration teams structure workstreams, manage stakeholder communication, and track synergy capture using DealRoom.',
        overlay: 'Post-merger integration is where M&A value is won or lost. This playbook synthesizes best practices from 350+ DealRoom customers and covers: building your integration charter, standing up functional workstreams, managing cultural alignment, tracking synergy realization, and communicating progress to the board. Whether you\'re running your first integration or your twentieth, this guide offers frameworks you can apply immediately.',
      },
      tags: ['integration', 'team-collaboration', 'reporting'],
      targetRoles: ['integration-leader', 'corp-dev', 'executive'],
    },
    {
      id: 'l3',
      title: 'Building a Scalable Corp Dev Function',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'How high-performing corp dev teams are built.',
        medium: 'A webinar with corp dev leaders on the systems, processes, and tools behind scalable M&A functions.',
        large: 'Join corp dev leaders from high-growth acquirers for a discussion on what separates deal teams that scale from those that plateau. Topics include pipeline discipline, diligence standardization, integration readiness, and the technology stack that supports repeatable deal execution.',
        overlay: 'What does it take to go from completing 2 deals per year to 10? This webinar brings together corp dev leaders who\'ve made that transition — and dissects the operational changes required. From building a deal thesis and sourcing pipeline systematically, to running parallel diligence workstreams and integrating acquisitions without losing business continuity. If you\'re building or scaling a corp dev function, this conversation covers the decisions that define team performance.',
      },
      tags: ['pipeline', 'team-collaboration', 'reporting'],
      targetRoles: ['corp-dev', 'executive', 'private-equity'],
    },
    {
      id: 'l4',
      title: '5 Signs Your M&A Process Is Ready to Scale',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Is your deal process ready for higher volume?',
        medium: 'Five signals that your M&A workflow has outgrown its current tools and is ready for a platform upgrade.',
        large: 'If your team is tracking deals in spreadsheets, chasing documents over email, or manually updating stakeholders on deal status, you\'ve likely hit the ceiling of ad hoc tooling. This post outlines five clear signs that your M&A process needs a dedicated platform.',
        overlay: 'Ad hoc tools feel fine when deal volume is low. But as your acquisition ambitions grow, the friction compounds. This article breaks down the five leading indicators that your current process is becoming a bottleneck: status update meetings that exist only to share information, documents living in four different places, diligence timelines slipping due to coordination overhead, integration plans living in slide decks, and a team that spends more time managing process than evaluating deals. If you\'re nodding along, it\'s time for DealRoom.',
      },
      tags: ['pipeline', 'diligence', 'just-browsing'],
      targetRoles: ['corp-dev', 'executive', 'private-equity'],
    },
    {
      id: 'l5',
      title: 'DealRoom AI — Platform Demo',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'See DealRoom AI handle diligence in real time.',
        medium: 'A live demo of DealRoom AI automatically analyzing documents and surfacing key findings during diligence.',
        large: 'Watch DealRoom AI process a real data room: automatically categorizing documents, flagging missing items against a diligence checklist, extracting key financial and legal terms, and generating reviewer-ready summaries. See how AI compresses weeks of manual review into hours.',
        overlay: 'This demo walks through DealRoom AI\'s full diligence workflow — from uploading documents to generating deal memos. Watch as the AI automatically categorizes hundreds of documents, cross-references them against a standard diligence request list, extracts key data points (revenue figures, contract terms, IP ownership, employee headcount), and surfaces risks with supporting evidence. The same workflow applies to pipeline management: AI for Pipeline reads your email threads and auto-updates deal status without manual data entry.',
      },
      tags: ['ai-automation', 'diligence', 'pipeline'],
      targetRoles: ['corp-dev', 'integration-leader', 'ma-advisor', 'private-equity'],
    },
    {
      id: 'l6',
      title: 'M&A Science Podcast',
      cardType: 'learn',
      mediaType: 'podcast',
      icon: 'headphones',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Weekly M&A conversations with practitioners.',
        medium: 'Deep-dive interviews with corp dev leaders, integration specialists, and M&A advisors on deal execution.',
        large: 'The M&A Science Podcast features weekly conversations with practitioners across the deal lifecycle — from origination and sourcing through integration and value capture. Hosted by DealRoom, each episode surfaces tactical insights from experienced deal teams.',
        overlay: 'M&A Science is the practitioner\'s podcast for deal professionals. Each episode features candid conversations with corp dev leaders, integration specialists, bankers, and advisors sharing the tactics, mistakes, and frameworks they\'ve developed across hundreds of deals. Whether you\'re evaluating your first acquisition or running a serial acquirer\'s deal pipeline, you\'ll find immediately applicable insights in every episode.',
      },
      tags: ['pipeline', 'integration', 'just-browsing'],
      targetRoles: ['corp-dev', 'integration-leader', 'ma-advisor', 'executive'],
    },
    {
      id: 'l7',
      title: 'Customer Success Stories',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'star',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Real results from 350+ DealRoom customers.',
        medium: 'Case studies from corp dev teams at JAMF, Miro, 1-800 Flowers, Cadence Education, and more.',
        large: 'Browse detailed case studies from DealRoom customers across industries. See how specific teams — with specific deal volumes, team sizes, and objectives — implemented DealRoom and the measurable outcomes they achieved.',
        overlay: 'Every DealRoom customer case study is built around one question: what changed? From Cadence Education\'s 40+ hours saved per deal to Liberty\'s $200K in annual software savings to JAMF\'s 2x faster deal cycles — each story quantifies the before and after. Browse by industry, company size, or use case to find the stories most relevant to your situation, and reach out to DealRoom to connect with a customer reference in your space.',
      },
      tags: ['pipeline', 'diligence', 'integration', 'just-browsing'],
      targetRoles: ['corp-dev', 'executive', 'private-equity', 'ma-advisor'],
    },
    {
      id: 'l8',
      title: 'DealRoom Platform Overview',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'layout',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'One-page overview of the full DealRoom platform.',
        medium: 'A concise summary of DealRoom\'s Pipeline, Diligence, Integration, and AI capabilities.',
        large: 'This platform overview covers DealRoom\'s four core modules — Pipeline, Diligence, Integration, and AI — with feature highlights, use cases, and integration ecosystem. Ideal for sharing with stakeholders evaluating a platform decision.',
        overlay: 'The DealRoom Platform Overview is built for stakeholder conversations: it covers what each module does, who uses it, how it connects to your existing stack (Salesforce, HubSpot, Slack, and more), and what the implementation journey looks like. Share it with your CFO, general counsel, or IT team to answer the most common evaluation questions before your first demo call.',
      },
      tags: ['pipeline', 'diligence', 'integration', 'ai-automation', 'just-browsing'],
      targetRoles: ['corp-dev', 'executive', 'finance-legal', 'private-equity'],
    },

    // ── Solutions (6) ─────────────────────────────────────────────────────────
    {
      id: 's1',
      title: 'Pipeline',
      cardType: 'solution',
      icon: 'kanban',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Manage your full deal pipeline in one place.',
        medium: 'A purpose-built CRM for M&A — track targets, deal status, and team activity across your entire pipeline.',
        large: 'DealRoom Pipeline replaces spreadsheets and generic CRMs with an M&A-native deal tracker. Log targets, track relationship history, manage deal stages, assign ownership, and get AI-powered email integration that auto-updates deal status from your inbox.',
        overlay: 'DealRoom Pipeline is built for how corp dev teams actually work. Unlike generic CRMs, it understands M&A deal stages, tracks relationship history across your entire organization, and integrates with your email so AI for Pipeline can automatically extract deal updates from email conversations. Your pipeline stays current without manual data entry, and every team member sees the same real-time picture of where each deal stands.',
      },
      tags: ['pipeline', 'ai-automation', 'team-collaboration'],
      targetRoles: ['corp-dev', 'private-equity', 'executive'],
    },
    {
      id: 's2',
      title: 'Diligence',
      cardType: 'solution',
      icon: 'file-search',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Run structured, efficient due diligence.',
        medium: 'Manage document requests, data rooms, and workstreams in a single integrated diligence platform.',
        large: 'DealRoom Diligence centralizes the full due diligence process: structured request lists, secure data rooms, automated follow-ups, parallel workstreams for financial, legal, HR, and technical review, and AI-powered document analysis that surfaces key findings automatically.',
        overlay: 'Diligence is where most deal timelines slip. DealRoom Diligence eliminates the coordination overhead: send and track document requests through the platform (no more email follow-up), manage multiple workstreams in parallel with clear ownership and deadlines, control granular access permissions for internal and external reviewers, and let DealRoom AI analyze uploaded documents to flag missing items and extract key data points. The result is faster, more thorough diligence with less administrative burden on your team.',
      },
      tags: ['diligence', 'data-room', 'ai-automation'],
      targetRoles: ['corp-dev', 'ma-advisor', 'finance-legal', 'private-equity'],
    },
    {
      id: 's3',
      title: 'Integration',
      cardType: 'solution',
      icon: 'git-merge',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Manage post-merger integration end to end.',
        medium: 'Plan, execute, and track integration workstreams from Day 1 through synergy realization.',
        large: 'DealRoom Integration gives your team a dedicated workspace for post-merger execution: integration charters, functional workstream tracking, milestone management, synergy capture logging, and stakeholder reporting — all connected to the deal record it originated from.',
        overlay: 'Most PMI failures stem from the same root cause: integration planning starts too late and tracking is too loose. DealRoom Integration connects directly to the deal\'s diligence record so integration planning can begin during close, not after. Build your functional workstreams, assign ownership, set Day 30/60/100 milestones, log synergy capture as it occurs, and generate board-ready progress reports without manual compilation. The deal context carries forward so your integration team always knows why decisions were made.',
      },
      tags: ['integration', 'team-collaboration', 'reporting'],
      targetRoles: ['integration-leader', 'corp-dev', 'executive'],
    },
    {
      id: 's4',
      title: 'DealRoom AI',
      cardType: 'solution',
      icon: 'bot',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'AI that automates M&A workflows end to end.',
        medium: 'AI for Pipeline auto-updates deals from email. AI for Diligence analyzes documents and surfaces key findings.',
        large: 'DealRoom AI operates across the full deal lifecycle. AI for Pipeline reads your email and automatically logs deal activity, contact updates, and status changes. AI for Diligence processes uploaded documents to categorize, analyze, flag gaps, and generate summaries — turning days of manual review into hours.',
        overlay: 'DealRoom AI is purpose-built for M&A, not adapted from a generic LLM. AI for Pipeline understands deal conversation context — it knows the difference between a target introduction and a LOI discussion, and updates your pipeline record accordingly. AI for Diligence is trained on M&A document types: it categorizes financials, legal agreements, HR documents, and technical assessments automatically, cross-references them against standard diligence checklists, and extracts key data points with source citations. The result is an AI that does the work your team hates — so your team can focus on the analysis that drives deal decisions.',
      },
      tags: ['ai-automation', 'diligence', 'pipeline'],
      targetRoles: ['corp-dev', 'ma-advisor', 'private-equity', 'integration-leader'],
    },
    {
      id: 's5',
      title: 'Data Room',
      cardType: 'solution',
      icon: 'lock',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Secure, purpose-built virtual data room.',
        medium: 'A fully integrated data room with granular access controls, audit trails, and bulk document management.',
        large: 'DealRoom\'s virtual data room is built into the platform — no separate login, no per-document pricing, no vendor management. Control access at the folder, file, and user level. Track every view, download, and interaction with full audit logs. Manage bulk uploads and reorganize documents without losing version history.',
        overlay: 'Most teams manage their data room in a separate tool from their diligence workflow — creating a synchronization problem that slows deals and creates errors. DealRoom\'s integrated data room lives inside the same platform as your diligence request lists, workstreams, and deal records. Document uploads automatically connect to the relevant diligence items. Access permissions align with your workstream structure. Audit trails feed directly into your diligence reporting. And when the deal closes, everything lives in one searchable record for post-close reference.',
      },
      tags: ['data-room', 'diligence', 'team-collaboration'],
      targetRoles: ['corp-dev', 'ma-advisor', 'finance-legal', 'private-equity'],
    },
    {
      id: 's6',
      title: 'Reporting & Analytics',
      cardType: 'solution',
      icon: 'bar-chart-2',
      iconType: 'lucide',
      url: 'https://dealroom.net/',
      description: {
        small: 'Real-time dashboards for every deal stakeholder.',
        medium: 'Generate board-ready pipeline reports, diligence status updates, and integration progress dashboards automatically.',
        large: 'DealRoom Reporting gives every stakeholder the view they need: deal-level status for your team, pipeline health for leadership, diligence progress for functional leads, and integration milestone tracking for the board. All reports update in real time from the live deal record.',
        overlay: 'Manual reporting is one of the biggest time sinks in M&A. Teams spend hours each week pulling data from multiple tools, reconciling it, and formatting it for different audiences. DealRoom Reporting eliminates this: every dashboard pulls directly from the live deal record, so reports are always current without manual updates. Configure views for your CEO, your board, your integration team, and your external advisors — each sees the right level of detail for their role, and all of it is traceable back to the source data in DealRoom.',
      },
      tags: ['reporting', 'pipeline', 'integration'],
      targetRoles: ['corp-dev', 'executive', 'integration-leader', 'finance-legal'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: false,
    mediaCapture: false,
    calculator: false,
    captureInfo: true,
  },
};
