// Explorer Config — DFW Technology Prayer Breakfast (Pickleball & Prayer Social, May 13 2026)
// Faith + tech community kiosk experience for the DFWTPB Pickleball Event.

import type { ExplorerConfig, ThemeColors } from '../types';

const DFWPB_DARK: ThemeColors = {
  bg: '#180708',
  bgGradient: 'linear-gradient(135deg, #1A2347 0%, #070D1F 55%, #2A1014 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#BF353D',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(191,53,61,0.20)',
};

const DFWPB_LIGHT: ThemeColors = {
  bg: '#F4F5F9',
  bgGradient: 'linear-gradient(180deg, #F4F5F9 0%, #F2F3F8 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#BF353D',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(191,53,61,0.12)',
};

export const DFWPB_PICKLEBALL_CONFIG: ExplorerConfig = {
  id: 'dfwpb-pickleball-may132026',
  name: 'DFWTPB Explorer',
  version: 1,
  createdAt: '2026-05-04T00:00:00.000Z',
  updatedAt: '2026-05-04T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/dfwtpb.png',
      light: '/dfwtpb.png',
    },
    icon: '/dfwtpb.png',
    logoHeight: 48,
    colors: {
      primary: '#BF353D',
      secondary: '#255194',
      teal: '#D9534F',
      blue: '#255194',
      deepBlue: '#1A3A6F',
      navy: '#340E11',
      midnight: '#1C0809',
      plum: '#7A2329',
      bgDark: '#1C0809',
      dark: DFWPB_DARK,
      light: DFWPB_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(191,53,61,0.14)',
      orb2: 'rgba(37,81,148,0.14)',
      orb3: 'rgba(122,35,41,0.10)',
    },
    ctaGradient: 'linear-gradient(135deg, #BF353D, #255194)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #BF353D, #255194)',
    roleBackgrounds: {
      'table-host': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(191,53,61,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(37,81,148,0.12) 0%, transparent 55%)',
      'volunteer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(37,81,148,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(191,53,61,0.10) 0%, transparent 55%)',
      'partner': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(191,53,61,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(122,35,41,0.12) 0%, transparent 55%)',
      'curious-guest': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(191,53,61,0.10) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(37,81,148,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'form',
    formTitle: 'Welcome to DFWTPB',
    formSubtitle: "Let's get you checked in so we can personalize your experience.",
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to DFW Technology Prayer Breakfast processing your data to send relevant event communications and follow-ups.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Organization', type: 'text', placeholder: 'Company or organization', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Faith. Tech.',
      gradientWord: 'Community.',
      subtitle: 'DFW Tech Prayer Breakfast (DFWTPB) unites Dallas-Fort Worth tech professionals around faith, fellowship, and community at the annual breakfast, on the court, and year-round.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes you?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'table-host', label: 'Table Host', icon: 'utensils', iconType: 'lucide' },
        { value: 'volunteer', label: 'Volunteer', icon: 'heart', iconType: 'lucide' },
        { value: 'partner', label: 'Partner', icon: 'handshake', iconType: 'lucide' },
        { value: 'curious-guest', label: 'Curious Guest', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What brings you to DFWTPB?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'networking', label: 'Networking', icon: 'users', iconType: 'lucide' },
        { value: 'prayer-community', label: 'Prayer & Spiritual Community', icon: 'heart-handshake', iconType: 'lucide' },
        { value: 'speakers', label: 'Hearing Speakers', icon: 'mic', iconType: 'lucide' },
        { value: 'sponsorship', label: 'Sponsorship Info', icon: 'handshake', iconType: 'lucide' },
        { value: 'volunteering', label: 'Volunteering', icon: 'heart', iconType: 'lucide' },
        { value: 'pickleball-social', label: 'Pickleball Social', icon: 'circle-dot', iconType: 'lucide' },
        { value: 'tech-resources', label: 'Tech Industry Resources', icon: 'cpu', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and ways to get involved.',
      tabs: [
        { id: 'outcomes', label: 'At a Glance', icon: 'eye' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Website', value: 'website' },
        ]},
        { id: 'solutions', label: 'Get Involved', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'medium',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. We hope to see you at an upcoming DFWTPB gathering.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (6) ──────────────────────────────────
    {
      id: 'o1',
      title: '1,000+ DFW Tech Professionals Served',
      cardType: 'outcome',
      icon: 'users',
      iconType: 'lucide',
      stat: '1,000+',
      description: {
        small: 'Over 1,000 DFW tech professionals have joined the DFWTPB community.',
        medium: 'Over 1,000 DFW technology professionals have joined DFWTPB to bring faith into their everyday work.',
        large: 'Since launching, DFWTPB has gathered 1,000+ Dallas-Fort Worth technology professionals across CEOs, engineers, and students. Whatever your role in tech, this is a community that meets you where you are.',
        overlay: 'Since launching, DFW Technology Prayer Breakfast has welcomed more than 1,000 technology professionals from across the metroplex. CEOs share tables with engineers, founders sit beside students, ministry leaders pray alongside ICs. The room is intentionally cross-functional and cross-company. If you have spent years in tech feeling like you have to compartmentalize your faith from your work, this is the community that proves you do not have to. Show up once and you will see what we mean.',
      },
      tags: ['networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'o2',
      title: 'Annual Flagship Breakfast',
      cardType: 'outcome',
      icon: 'sunrise',
      iconType: 'lucide',
      stat: '1x / yr',
      description: {
        small: 'DFWTPB hosts one flagship breakfast each year for DFW tech.',
        medium: 'Each year DFWTPB hosts a flagship breakfast bringing keynote speakers, prayer, and community together.',
        large: 'The annual DFWTPB breakfast is the anchor event of the year. Expect a keynote speaker worth your morning, intentional prayer time, and meaningful peer connection over breakfast.',
        overlay: 'Once a year DFWTPB hosts the flagship breakfast that started it all. The morning runs roughly 90 minutes: a keynote speaker grounded in both faith and the realities of tech leadership, a panel discussion, intentional prayer, and time to connect with peers across the metroplex over breakfast. It is the one annual moment where the whole DFWTPB community gathers under one roof. Tables are available for individuals, teams, or sponsoring organizations, and the keynote alone is reason enough to clear your morning.',
      },
      tags: ['speakers', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },
    {
      id: 'o3',
      title: '50+ Partner Organizations',
      cardType: 'outcome',
      icon: 'building-2',
      iconType: 'lucide',
      stat: '50+',
      description: {
        small: 'More than 50 organizations across DFW back DFWTPB.',
        medium: 'More than 50 organizations across DFW tech and faith communities back DFWTPB.',
        large: 'DFWTPB is supported by a network of 50+ partner organizations spanning tech companies, churches, ministries, and startups across the metroplex. Together they make this work possible and extend the network for every attendee.',
        overlay: 'Behind every DFWTPB event is a network of 50+ partner organizations. Tech companies sponsor tables and provide visibility for their teams. Churches and ministries collaborate on programming and prayer initiatives. Startups bring fresh energy and offer their teams a place to plug in. This wide partner base means DFWTPB is not a single-source initiative; it is a coalition. When you attend, you are tapping into a community that spans the DFW tech ecosystem and the faith community at once.',
      },
      tags: ['sponsorship', 'networking'],
      targetRoles: ['partner', 'table-host'],
    },
    {
      id: 'o4',
      title: 'Inaugural Pickleball & Prayer Social',
      cardType: 'outcome',
      icon: 'circle-dot',
      iconType: 'lucide',
      stat: 'Today',
      description: {
        small: 'You are at the inaugural DFWTPB social.',
        medium: 'Today marks the launch of the Pickleball & Prayer Social, a new annual gathering for DFW tech.',
        large: 'Today is the inaugural Pickleball & Prayer Social. Combining friendly competition, intentional prayer, and time on the court, it is the newest annual event on the DFWTPB calendar.',
        overlay: 'You are at the inaugural Pickleball & Prayer Social. The format is intentional: pickleball matches woven through the day, food, and a prayer/program portion integrated with court time rather than interrupting it. From here on out, this becomes an annual event on the DFWTPB calendar. It is the most relaxed format we host and works especially well for inviting colleagues who would not otherwise come to a breakfast. Glad you are here.',
      },
      tags: ['pickleball-social', 'networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'o5',
      title: 'Year-Round Community',
      cardType: 'outcome',
      icon: 'calendar-heart',
      iconType: 'lucide',
      stat: '12 mo',
      description: {
        small: 'DFWTPB sustains community year-round, not just at the breakfast.',
        medium: 'DFWTPB sustains community year-round through socials, prayer groups, and partner events.',
        large: 'Beyond the flagship breakfast, DFWTPB connects DFW tech professionals year-round. Smaller socials, prayer groups, partnered church events, and ad-hoc gatherings keep the community active every month.',
        overlay: 'DFWTPB is more than a once-a-year event. Smaller socials happen quarterly. Prayer groups meet across the metroplex on different cadences and welcome new attendees throughout the year. Partner churches host ad-hoc gatherings tied to current events or season-of-life moments. New attendees often discover DFWTPB at a flagship breakfast and find a year-round home through these smaller groups. There is always a way to plug in regardless of when you first encountered DFWTPB.',
      },
      tags: ['prayer-community', 'networking'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'o6',
      title: 'Faith Connected to Work',
      cardType: 'outcome',
      icon: 'briefcase',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: 'Every gathering centers on faith and tech work, together.',
        medium: 'Every DFWTPB gathering centers on integrating personal faith with the realities of tech leadership.',
        large: 'Tech work can be isolating, fast-paced, and ethically complex. DFWTPB exists to help DFW technology professionals connect personal faith with the daily realities of working in technology.',
        overlay: 'Every DFWTPB gathering is built around one premise: tech work is one of the most consequential vocations of our time, and faith does not stop at the office door. Whether you build software, lead a team, or run a company, the questions you face daily about how to lead people, ship product, hire well, and navigate tradeoffs are the questions DFWTPB takes seriously alongside the spiritual life. Honest conversation, shared prayer, and a community of peers walking the same road.',
      },
      tags: ['prayer-community', 'speakers'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },
    // ── Learn (9) ─────────────────────────────────────
    {
      id: 'l2',
      title: 'Meet the Prayer Breakfast',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'info',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Start here to learn what DFWTPB is about.',
        medium: 'An overview of who we are, why we exist, and the community we have built across DFW tech.',
        large: 'New here? Start with the basics. The story of DFWTPB, the mission behind the breakfast, and the community of DFW tech professionals who make this work matter.',
        overlay: 'If you are brand new to DFWTPB, this is the place to start. The About page covers how the breakfast started, the mission behind it, and introduces the team and community of DFW tech professionals making it happen. It is a quick read that will help you understand what to expect at any DFWTPB gathering. After this, the Events page is the natural next click for picking a first gathering to attend.',
      },
      tags: ['prayer-community', 'networking'],
      targetRoles: ['curious-guest', 'volunteer'],
    },
    {
      id: 'l3',
      title: 'What We Do. And Why It Matters.',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Why DFWTPB exists and what makes it different.',
        medium: 'A grounded look at why DFWTPB exists and the impact this community has on DFW tech professionals.',
        large: 'Why bother with another tech meetup? This piece walks through what makes DFWTPB different, why the faith-tech intersection matters, and the personal stories behind the community.',
        overlay: 'This is the heart of DFWTPB explained simply. Why a faith-driven tech community matters in 2026. What we have seen happen in attendees\' lives and careers when they show up consistently. Why this community is worth your time even if you are skeptical of religious-flavored gatherings. If you are on the fence about whether DFWTPB is for you, start here. It is the most direct case for why we do what we do.',
      },
      tags: ['prayer-community', 'speakers'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },
    {
      id: 'l4',
      title: 'How Today Flows',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'clipboard-check',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'How the day flows between courts, food, and program.',
        medium: 'Today\'s schedule at a glance: pickleball matches, food, and the prayer/program portion woven throughout.',
        large: 'How today flows. Pickleball matches run throughout the day, food is provided, and the prayer/program portion is woven in rather than tacked on at the end. Paddles are on-site if you need one.',
        overlay: 'Today is intentionally relaxed. Pickleball matches happen throughout the day so you can rotate in and out at your own pace, food is provided, and the prayer/program portion is woven into the day rather than parked at the end. Paddles are available on-site if you did not bring one. All skill levels are welcome, beginners especially. The goal is honest community on the court and in the program time, not a competitive tournament.',
      },
      tags: ['pickleball-social'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'l5',
      title: 'Past Speakers & Highlights',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Watch highlight reels from past DFWTPB breakfasts.',
        medium: 'Highlight reels and clips from past DFWTPB breakfast keynotes and panel discussions.',
        large: 'Curious what a DFWTPB breakfast actually feels like? Watch highlight clips from past keynotes, panels, and prayer moments to get a real sense of the gathering.',
        overlay: 'Highlights from past DFWTPB breakfasts: keynote clips, panel discussions, prayer moments, and the texture of the room. These videos capture what is hardest to convey in writing: the tone, the audience reactions, the moments of unexpected vulnerability when a tech leader shares something honest from the stage. Spending five minutes here is the best way to understand the experience without attending in person. Worth a watch if you are deciding whether to invite colleagues to the next one.',
      },
      tags: ['speakers', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },
    {
      id: 'l6',
      title: 'Connect: Stay in the Loop',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'mail',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Subscribe to email updates and follow on social.',
        medium: 'Subscribe to email updates and follow DFWTPB on social to stay informed about future events.',
        large: 'Sign up for the email list, follow DFWTPB on social channels, and never miss a future breakfast, social, prayer group, or partner event.',
        overlay: 'Stay connected to DFWTPB without getting overwhelmed. The email list lands in your inbox a few times a month with event announcements and key prayer requests, never more than that. Social channels post day-to-day inspiration and ad-hoc gathering invites. Between flagship events, this is how new prayer groups and partner-led socials get announced first. Unsubscribe any time, no spam, no upsells. The lightest possible touch.',
      },
      tags: ['networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'l7',
      title: 'Upcoming DFWTPB Events',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'calendar',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com/our-events/',
      description: {
        small: 'See the full DFWTPB calendar of upcoming events.',
        medium: 'See the full DFWTPB calendar including the breakfast, the Pickleball Social, and year-round gatherings.',
        large: 'Browse every DFWTPB event in one place: the flagship breakfast, the Pickleball Social, and the smaller socials and prayer groups happening across DFW year-round.',
        overlay: 'The events page is the canonical calendar for DFWTPB. The flagship breakfast, the Pickleball & Prayer Social, the smaller quarterly socials, and the partner-led prayer groups happening across the metroplex are all listed in one place so you can plan ahead, invite colleagues, and find the events that fit your season. New events are added throughout the year as partnerships and prayer groups launch, so it is worth bookmarking.',
      },
      tags: ['networking', 'prayer-community', 'pickleball-social'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'l8',
      title: 'Partner with DFWTPB',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'handshake',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com/partner/',
      description: {
        small: 'How tech companies and ministries can partner with DFWTPB.',
        medium: 'How tech companies, churches, and ministries can partner with DFWTPB to amplify the mission.',
        large: 'Learn how organizations partner with DFWTPB. Sponsorship tiers, ministry partnerships, and the visibility partners gain across the DFW tech community.',
        overlay: 'The partner page covers every way an organization can support DFWTPB: tiered sponsorship for tech companies, ministry partnerships for churches and faith-based nonprofits, and table sponsorships for the flagship breakfast. Partners get listed on the site, gain access to community channels, and collaborate on programming. The page also includes the most up-to-date pricing and contact information to start a conversation about whether partnership is the right fit for your organization.',
      },
      tags: ['sponsorship', 'networking'],
      targetRoles: ['partner', 'table-host'],
    },
    {
      id: 'l9',
      title: 'Host a Table at the Breakfast',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'utensils',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com/table-host/',
      description: {
        small: 'Reserve a table at the breakfast for your team.',
        medium: 'Reserve a table at the flagship breakfast and bring colleagues, clients, or your team.',
        large: 'Hosting a table is the best way to introduce others to DFWTPB. Reserve a table at the flagship breakfast and fill it with colleagues, clients, or teammates.',
        overlay: 'Hosting a table at the flagship DFWTPB breakfast lets you introduce up to seven colleagues, clients, or teammates to the community in one shot. The table host page walks through pricing, what is included (the meal, branded recognition, reserved seating), and how to invite your guests. Table hosts often tell us their guests bring up the experience for months afterward. If you have ever wanted to share DFWTPB with people who would not otherwise come, this is the way to do it.',
      },
      tags: ['networking', 'speakers'],
      targetRoles: ['table-host', 'partner'],
    },
    {
      id: 'l10',
      title: 'Volunteer at DFWTPB',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'heart',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com/volunteer/',
      description: {
        small: 'Sign up to volunteer at upcoming DFWTPB events.',
        medium: 'Volunteer roles for the breakfast, the Pickleball Social, and year-round prayer groups.',
        large: 'Volunteers run the breakfast registration desk, hospitality at the Pickleball Social, and co-host smaller prayer groups across DFW. See open roles and sign up directly from the page.',
        overlay: 'Volunteers are the backbone of DFWTPB. The volunteer page lists every open role: registration and hospitality at the breakfast, court coordination at the Pickleball Social, and co-hosting smaller prayer groups across DFW year-round. There is no minimum commitment. Many of our most invested community members started as one-time volunteers and stayed because they found their people in that role. Sign up for a single event or a longer rhythm; both are welcome and useful.',
      },
      tags: ['volunteering'],
      targetRoles: ['volunteer', 'curious-guest'],
    },

    // ── Solutions / Get Involved (6) ──────────────────
    {
      id: 's2',
      title: 'Attend the Annual Breakfast',
      cardType: 'solution',
      icon: 'sunrise',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Reserve a seat or full table at the next breakfast.',
        medium: 'Save a seat for the next flagship DFWTPB breakfast featuring keynote speakers and prayer.',
        large: 'The flagship annual breakfast brings together DFW tech leaders for keynotes, panels, and intentional prayer time. Reserve your seat or a full table for your team.',
        overlay: 'Reserve your spot at the next flagship DFWTPB breakfast. Single seats and full tables (8 guests) are both available. The morning runs about 90 minutes: keynote speaker, panel discussion, intentional prayer, and time for community connection over breakfast. Tables are popular for teams who want to attend together; individual seats are best if you want to be seated with people you do not know yet. Both options work, and both fill up well before the event date.',
      },
      tags: ['speakers', 'networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },
    {
      id: 's3',
      title: 'Become a Sponsor',
      cardType: 'solution',
      icon: 'handshake',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Multiple sponsorship tiers for DFWTPB events.',
        medium: 'Sponsorship tiers for the breakfast, the Pickleball Social, and year-round programming.',
        large: 'Sponsorship makes DFWTPB possible. Tiered packages support the flagship breakfast, the Pickleball & Prayer Social, and year-round community programming with strong visibility.',
        overlay: 'DFWTPB sponsorship comes in tiers covering the flagship breakfast, the Pickleball & Prayer Social, and year-round programs. Each tier includes branded visibility on event materials, a dedicated table or court time, and the chance to support a community that matters to your team. Sponsors get specific commitments in writing covering visibility scope, audience reach, and what is included at each tier. Reach out to discuss what fits your goals and budget; the team responds within a few business days.',
      },
      tags: ['sponsorship'],
      targetRoles: ['partner', 'table-host'],
    },
    {
      id: 's4',
      title: 'Partner Organization Program',
      cardType: 'solution',
      icon: 'building-2',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Apply to partner with DFWTPB as an organization.',
        medium: 'Faith communities and tech organizations can partner with DFWTPB to amplify the shared mission.',
        large: 'The Partner Organization program connects DFWTPB with churches, ministries, and tech organizations who share the mission of integrating faith and work across DFW.',
        overlay: 'Churches, ministries, and tech-affiliated organizations are invited to partner with DFWTPB. Partners are listed on the site, gain access to our community channels, and collaborate on programming and events. It is the right fit if your organization cares about faith-work integration in DFW tech and is willing to lend resources, audience, or volunteer hours. Partnership is more substantive than sponsorship; it implies ongoing collaboration rather than a one-time check, and partners often co-host gatherings throughout the year.',
      },
      tags: ['sponsorship', 'networking'],
      targetRoles: ['partner'],
    },
    {
      id: 's5',
      title: 'Volunteer With Us',
      cardType: 'solution',
      icon: 'heart',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Volunteer at upcoming DFWTPB events or year-round.',
        medium: 'Volunteers help run the breakfast, the Pickleball Social, and year-round prayer groups.',
        large: 'Volunteer roles range from event-day logistics at the breakfast and Pickleball Social to leading or co-hosting smaller prayer groups across DFW throughout the year.',
        overlay: 'Volunteers are the backbone of DFWTPB. Roles range from event-day logistics like registration, hospitality, and court coordination at the Pickleball Social, to leading or co-hosting smaller prayer groups across DFW throughout the year. There is no minimum commitment required. Sign up for a single event, or for a recurring monthly rhythm. Many regular attendees started by volunteering and found that the volunteer side of the room is where the deepest community happens, because everyone is working on the same thing together.',
      },
      tags: ['volunteering'],
      targetRoles: ['volunteer', 'curious-guest'],
    },
    {
      id: 's6',
      title: 'Join the Community',
      cardType: 'solution',
      icon: 'users',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Sign up for the DFWTPB email list and prayer updates.',
        medium: 'Subscribe to event announcements, prayer requests, and updates on the DFWTPB community.',
        large: 'Joining the DFWTPB community starts with the email list. Event invites, prayer requests, and community updates land in your inbox a few times a month, never more.',
        overlay: 'The simplest way to be part of DFWTPB is to join the email list. A few times a month you will get event invitations, community prayer requests, and updates on what is happening across DFW tech. The list is intentionally low-volume, never daily, never marketing-heavy. Unsubscribe any time. No spam, no upsells, no third-party data sharing. It is the lightest-touch way to stay connected before deciding whether to attend a gathering, and the best way to discover ad-hoc prayer groups as they pop up.',
      },
      tags: ['networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 's7',
      title: 'Partner Brochure',
      cardType: 'solution',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: '/dfwtpb-partner-brochure.pdf',
      description: {
        small: 'Read the partner brochure with all the details.',
        medium: 'A printable overview of partner tiers, benefits, and how to get involved with DFWTPB.',
        large: 'The DFWTPB Partner Brochure walks through partnership tiers, benefits, visibility, and how partners support the breakfast, the Pickleball Social, and year-round community programming.',
        overlay: 'The Partner Brochure is the canonical document for organizations evaluating partnership with DFWTPB. It walks through every tier, what is included at each level, what visibility partners receive, audience reach, and the specific commitments made on both sides. The brochure also explains how partner dollars support the flagship breakfast, the Pickleball & Prayer Social, and year-round community programming. If your organization is weighing whether to partner, this document has every detail you need to make the case internally. Tap to read inline or open full-screen.',
      },
      tags: ['sponsorship', 'networking'],
      targetRoles: ['partner', 'table-host'],
    },
    {
      id: 's8',
      title: 'Table Host Brochure',
      cardType: 'solution',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: '/dfwtpb-table-host-brochure.pdf',
      description: {
        small: 'Read the table host brochure with all the details.',
        medium: 'A printable guide to hosting a table at the flagship DFWTPB breakfast.',
        large: 'The Table Host Brochure covers pricing, what is included, how to invite guests, and what to expect on the morning of the breakfast.',
        overlay: 'The Table Host Brochure is the canonical guide for anyone considering hosting a table at the flagship DFWTPB breakfast. It covers pricing per table, what is included (the meal, reserved seating, branded recognition), how to invite and seat your guests, and what to expect on the morning. The brochure also includes practical details like dress code, arrival timing, and how to get the most out of the conversations at your table. Tap to read inline or open full-screen.',
      },
      tags: ['networking', 'speakers'],
      targetRoles: ['table-host', 'partner'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
