// Explorer Config — DFW Technology Prayer Breakfast (Pickleball & Prayer Social, May 13 2026)
// Faith + tech community kiosk experience for the DFWTPB Pickleball Event.

import type { ExplorerConfig, ThemeColors } from '../types';

const DFWPB_DARK: ThemeColors = {
  bg: '#070D1F',
  bgGradient: 'linear-gradient(135deg, #1A2347 0%, #070D1F 55%, #2A1014 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#BF353D',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(191,53,61,0.20)',
};

const DFWPB_LIGHT: ThemeColors = {
  bg: '#F4F5F9',
  bgGradient: 'linear-gradient(180deg, #F4F5F9 0%, #F2F3F8 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#BF353D',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(191,53,61,0.12)',
};

export const DFWPB_PICKLEBALL_CONFIG: ExplorerConfig = {
  id: 'dfwpb-pickleball-may132026',
  name: 'DFWTPB Explorer',
  version: 1,
  createdAt: '2026-05-04T00:00:00.000Z',
  updatedAt: '2026-05-04T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/dfwtpb.png',
      light: '/dfwtpb.png',
    },
    icon: '/dfwtpb.png',
    colors: {
      primary: '#BF353D',
      secondary: '#255194',
      teal: '#D9534F',
      blue: '#255194',
      deepBlue: '#1A3A6F',
      navy: '#0F1E3D',
      midnight: '#070D1F',
      plum: '#7A2329',
      bgDark: '#070D1F',
      dark: DFWPB_DARK,
      light: DFWPB_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(191,53,61,0.14)',
      orb2: 'rgba(37,81,148,0.14)',
      orb3: 'rgba(122,35,41,0.10)',
    },
    ctaGradient: 'linear-gradient(135deg, #BF353D, #255194)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #BF353D, #255194)',
    roleBackgrounds: {
      'table-host': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(191,53,61,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(37,81,148,0.12) 0%, transparent 55%)',
      'volunteer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(37,81,148,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(191,53,61,0.10) 0%, transparent 55%)',
      'partner': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(191,53,61,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(122,35,41,0.12) 0%, transparent 55%)',
      'curious-guest': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(191,53,61,0.10) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(37,81,148,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'form',
    formTitle: 'Welcome to DFWTPB',
    formSubtitle: 'Tell us a bit about yourself so we can personalize your experience.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to DFW Technology Prayer Breakfast processing your data to send relevant event communications and follow-ups.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Organization', type: 'text', placeholder: 'Company or organization', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Faith. Tech.',
      gradientWord: 'Community.',
      subtitle: 'DFWTPB unites Dallas-Fort Worth tech professionals around faith, fellowship, and community at the annual breakfast, on the court, and year-round.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes you?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'table-host', label: 'Table Host', icon: 'utensils', iconType: 'lucide' },
        { value: 'volunteer', label: 'Volunteer', icon: 'heart', iconType: 'lucide' },
        { value: 'partner', label: 'Partner', icon: 'handshake', iconType: 'lucide' },
        { value: 'curious-guest', label: 'Curious Guest', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What brings you to DFWTPB?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'networking', label: 'Networking', icon: 'users', iconType: 'lucide' },
        { value: 'prayer-community', label: 'Prayer & Spiritual Community', icon: 'heart-handshake', iconType: 'lucide' },
        { value: 'speakers', label: 'Hearing Speakers', icon: 'mic', iconType: 'lucide' },
        { value: 'sponsorship', label: 'Sponsorship Info', icon: 'handshake', iconType: 'lucide' },
        { value: 'volunteering', label: 'Volunteering', icon: 'heart', iconType: 'lucide' },
        { value: 'pickleball-social', label: 'Pickleball Social', icon: 'circle-dot', iconType: 'lucide' },
        { value: 'tech-resources', label: 'Tech Industry Resources', icon: 'cpu', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and ways to get involved.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Website', value: 'website' },
        ]},
        { id: 'solutions', label: 'Get Involved', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'medium',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. We hope to see you at an upcoming DFWTPB gathering.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (6) ──────────────────────────────────
    {
      id: 'o1',
      title: '1,000+ DFW Tech Professionals Served',
      cardType: 'outcome',
      icon: 'users',
      iconType: 'lucide',
      stat: '1,000+',
      description: {
        small: 'Tech leaders united across DFW.',
        medium: 'More than 1,000 DFW technology professionals have gathered at DFWTPB events to connect faith and work.',
        large: 'DFWTPB has welcomed 1,000+ tech professionals from across the Dallas-Fort Worth metroplex, building a community where faith, leadership, and innovation intersect.',
        overlay: 'Since launching, DFW Technology Prayer Breakfast has welcomed 1,000+ technology professionals from companies across the metroplex. Whether you are a CEO, engineer, or student, this is a community that meets you where you are and connects faith to your everyday work.',
      },
      tags: ['networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'o2',
      title: 'Annual Flagship Breakfast',
      cardType: 'outcome',
      icon: 'sunrise',
      iconType: 'lucide',
      stat: '1x / yr',
      description: {
        small: 'A flagship annual gathering.',
        medium: 'Each year DFWTPB hosts a flagship prayer breakfast bringing together speakers, leaders, and community.',
        large: 'The flagship annual DFWTPB breakfast features keynote speakers, intentional prayer time, and meaningful connections among tech leaders across DFW.',
        overlay: 'Once a year, DFW tech professionals come together for a flagship breakfast featuring inspiring keynote speakers, intentional prayer, and fellowship. It is a singular opportunity to step back from day-to-day work and connect with peers around shared values.',
      },
      tags: ['speakers', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },
    {
      id: 'o3',
      title: '50+ Partner Organizations',
      cardType: 'outcome',
      icon: 'building-2',
      iconType: 'lucide',
      stat: '50+',
      description: {
        small: 'Partner organizations across DFW.',
        medium: '50+ partner organizations support DFWTPB, from startups to enterprise tech and faith communities.',
        large: 'A growing network of 50+ partner organizations across DFW — including tech companies, churches, and ministries — back DFWTPB and amplify its mission.',
        overlay: 'DFWTPB is supported by 50+ partner organizations spanning the DFW tech ecosystem and faith community. From early-stage startups to enterprise leaders to local ministries, our partners make this work possible and provide a wider network for attendees.',
      },
      tags: ['sponsorship', 'networking'],
      targetRoles: ['partner', 'table-host'],
    },
    {
      id: 'o4',
      title: 'New: Pickleball & Prayer Social',
      cardType: 'outcome',
      icon: 'circle-dot',
      iconType: 'lucide',
      stat: 'May 13',
      description: {
        small: 'New annual social on the court.',
        medium: 'A brand new social gathering combining pickleball, prayer, and DFW tech community on May 13, 2026.',
        large: 'The Pickleball & Prayer Social is DFWTPB\'s newest annual event — combining friendly competition, prayer, and community building on May 13, 2026.',
        overlay: 'On May 13, 2026, DFWTPB launches its newest annual event: the Pickleball & Prayer Social. It is a relaxed, fun setting where DFW tech professionals connect on the court, share a meal, and join in prayer together. All skill levels welcome.',
      },
      tags: ['pickleball-social', 'networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'o5',
      title: 'Year-Round Community',
      cardType: 'outcome',
      icon: 'calendar-heart',
      iconType: 'lucide',
      stat: '12 mo',
      description: {
        small: 'Connection beyond the breakfast.',
        medium: 'DFWTPB connects DFW tech professionals year-round through socials, prayer groups, and partner events.',
        large: 'Beyond the annual breakfast, DFWTPB sustains community through year-round socials, prayer groups, and partnered events with churches and tech organizations across the metroplex.',
        overlay: 'DFWTPB is more than a once-a-year event. The community connects year-round through smaller socials, prayer groups, partnered church events, and ad-hoc gatherings — so there is always a way to plug in regardless of when you discover us.',
      },
      tags: ['prayer-community', 'networking'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'o6',
      title: 'Faith Connected to Work',
      cardType: 'outcome',
      icon: 'briefcase',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: 'Bridging faith and tech work.',
        medium: 'Every DFWTPB gathering centers on integrating personal faith with the realities of tech leadership and work.',
        large: 'Whether you build software, lead a team, or run a company, DFWTPB exists to help you connect personal faith with the daily realities of working in technology.',
        overlay: 'Tech work can be isolating, fast-paced, and ethically complex. DFWTPB exists to help DFW technology professionals connect personal faith with their day-to-day work — through honest conversation, shared prayer, and a community of peers walking the same road.',
      },
      tags: ['prayer-community', 'speakers'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },

    // ── Learn (6) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Pickleball & Prayer Social Details',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'calendar',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Date, time, location and more.',
        medium: 'Full event details for the May 13, 2026 Pickleball & Prayer Social: schedule, location, and what to expect.',
        large: 'Get the full lowdown on the Pickleball & Prayer Social: when it starts, where to go, what gear you need (or do not), and how the day flows from court time to prayer time.',
        overlay: 'The Pickleball & Prayer Social happens May 13, 2026. Visit the DFWTPB site for the full event schedule, location and parking info, what to bring (or rent on-site), the prayer/program portion timing, and how to invite a colleague.',
      },
      tags: ['pickleball-social'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'l2',
      title: 'Meet the Prayer Breakfast',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'info',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'About DFWTPB and our mission.',
        medium: 'An overview of who we are, why we exist, and the community we have built across DFW tech.',
        large: 'New here? Start with the basics — the story of DFWTPB, the mission behind the breakfast, and the community of DFW tech professionals who make this work matter.',
        overlay: 'If you are new to DFWTPB, this is the place to start. Learn how the breakfast started, the mission behind it, and meet the team and community of DFW tech professionals making it happen. It is a quick read that will help you understand what to expect at any DFWTPB gathering.',
      },
      tags: ['prayer-community', 'networking'],
      targetRoles: ['curious-guest', 'volunteer'],
    },
    {
      id: 'l3',
      title: 'What We Do. And Why It Matters.',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Our mission, in plain words.',
        medium: 'A grounded look at why DFWTPB exists and the impact this community has on DFW tech professionals.',
        large: 'Why bother with another tech meetup? This piece walks through what makes DFWTPB different, why faith-tech intersection matters, and the personal stories behind the community.',
        overlay: 'This is the heart of DFWTPB explained simply: why a faith-driven tech community matters in 2026, what we have seen happen in attendees\' lives and careers, and why this is worth your time. If you are skeptical, start here.',
      },
      tags: ['prayer-community', 'speakers'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },
    {
      id: 'l4',
      title: 'Get Ready for the Big Day',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'clipboard-check',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'How to prepare for the event.',
        medium: 'Practical tips on what to wear, what to bring, and how to make the most of the Pickleball & Prayer Social.',
        large: 'A quick prep guide for first-timers and regulars alike: gear suggestions, the day-of schedule, suggested arrival time, and how the prayer portion fits with the social portion.',
        overlay: 'Wondering what to expect? This prep guide covers what to wear, what to bring (paddles available on-site if needed), arrival timing, the rough flow of the day, and how the prayer/program time integrates with the pickleball matches. Arrive ready, leave refreshed.',
      },
      tags: ['pickleball-social'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 'l5',
      title: 'Past Speakers & Highlights',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Highlights from past breakfasts.',
        medium: 'Watch highlight reels and clips from past DFWTPB breakfast keynotes and panel discussions.',
        large: 'Curious what a DFWTPB breakfast actually feels like? Watch highlight clips from past keynotes, panels, and prayer moments to get a real sense of the gathering.',
        overlay: 'Highlights from past DFWTPB breakfasts: keynote clips, panel discussions, prayer moments, and the texture of the room. The best way to understand the experience without attending in person is to spend a few minutes here.',
      },
      tags: ['speakers', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },
    {
      id: 'l6',
      title: 'Connect: Stay in the Loop',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'mail',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Subscribe and follow DFWTPB.',
        medium: 'Subscribe to email updates and follow DFWTPB on social to stay informed about future events.',
        large: 'Sign up for the email list, follow DFWTPB on social channels, and never miss a future breakfast, social, prayer group, or partner event happening across the metroplex.',
        overlay: 'Stay connected: subscribe to the DFWTPB email list for event announcements, follow on social channels for day-to-day inspiration and prayer requests, and watch for ad-hoc gatherings and prayer groups happening across DFW between flagship events.',
      },
      tags: ['networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },

    // ── Solutions / Get Involved (6) ──────────────────
    {
      id: 's1',
      title: 'Register for May 13 Pickleball Social',
      cardType: 'solution',
      icon: 'circle-dot',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Reserve your spot on the court.',
        medium: 'Reserve your spot for the May 13, 2026 Pickleball & Prayer Social — paddles and beginners welcome.',
        large: 'Register now for the Pickleball & Prayer Social on May 13, 2026. All skill levels welcome (beginners encouraged), paddles available on-site, and the prayer/program portion integrates with court time throughout the day.',
        overlay: 'The Pickleball & Prayer Social on May 13, 2026 is open to all DFW tech professionals — from never-played-before to competitive league players. Paddles available on-site, food provided, and the prayer/program portion is woven throughout the day. Bring a colleague who needs a break from the keyboard.',
      },
      tags: ['pickleball-social'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
    {
      id: 's2',
      title: 'Attend the Annual Breakfast',
      cardType: 'solution',
      icon: 'sunrise',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Reserve a seat at the breakfast.',
        medium: 'Save a seat for the next flagship DFWTPB breakfast featuring keynote speakers and prayer.',
        large: 'The flagship annual breakfast brings together DFW tech leaders for keynotes, panels, and intentional prayer time. Reserve your seat or a table for your team.',
        overlay: 'Reserve your spot at the next flagship DFWTPB breakfast. Single seats and full tables are both available. The morning includes a keynote speaker, panel discussion, intentional prayer, and time for community connection over breakfast.',
      },
      tags: ['speakers', 'networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'curious-guest'],
    },
    {
      id: 's3',
      title: 'Become a Sponsor',
      cardType: 'solution',
      icon: 'handshake',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Sponsor DFWTPB events.',
        medium: 'Multiple sponsorship tiers available for the breakfast, the Pickleball Social, and year-round programming.',
        large: 'Sponsorship makes DFWTPB possible. Tiered packages support the flagship breakfast, the Pickleball & Prayer Social, and year-round community programming with strong visibility for your brand.',
        overlay: 'DFWTPB sponsorship tiers cover the flagship breakfast, the Pickleball & Prayer Social, and year-round programs. Each tier includes branded visibility, dedicated tables or court time, and the chance to support a community that matters to your team. Reach out to discuss what fits.',
      },
      tags: ['sponsorship'],
      targetRoles: ['partner', 'table-host'],
    },
    {
      id: 's4',
      title: 'Partner Organization Program',
      cardType: 'solution',
      icon: 'building-2',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Partner with DFWTPB.',
        medium: 'Faith communities and tech organizations can partner with DFWTPB to amplify our shared mission.',
        large: 'The Partner Organization program connects DFWTPB with churches, ministries, and tech organizations who share our mission of integrating faith and work across DFW.',
        overlay: 'Churches, ministries, and tech-affiliated organizations are invited to partner with DFWTPB. Partners get listed on the site, gain access to our community channels, and collaborate on programming. It is the right fit if your org cares about faith-work integration in DFW tech.',
      },
      tags: ['sponsorship', 'networking'],
      targetRoles: ['partner'],
    },
    {
      id: 's5',
      title: 'Volunteer With Us',
      cardType: 'solution',
      icon: 'heart',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Volunteer at upcoming events.',
        medium: 'Volunteers help run the breakfast, the Pickleball Social, and year-round prayer groups.',
        large: 'Volunteer roles range from event-day logistics at the breakfast and Pickleball Social to leading or co-hosting smaller prayer groups across DFW throughout the year.',
        overlay: 'Volunteers are the backbone of DFWTPB. Roles range from event-day logistics (registration, hospitality, court coordination at the Pickleball Social) to leading or co-hosting smaller prayer groups across DFW throughout the year. Sign up — no minimum commitment required.',
      },
      tags: ['volunteering'],
      targetRoles: ['volunteer', 'curious-guest'],
    },
    {
      id: 's6',
      title: 'Join the Community',
      cardType: 'solution',
      icon: 'users',
      iconType: 'lucide',
      url: 'https://dfwtechpb.com',
      description: {
        small: 'Sign up for the DFWTPB list.',
        medium: 'Subscribe to event announcements, prayer requests, and updates on the DFWTPB community.',
        large: 'Joining the DFWTPB community starts with the email list — event invites, prayer requests, and community updates land in your inbox a few times a month, never more.',
        overlay: 'The simplest way to be part of DFWTPB is to join the email list: a few times a month you will get event invitations, community prayer requests, and updates on what is happening across DFW tech. Unsubscribe any time. No spam, no upsells.',
      },
      tags: ['networking', 'prayer-community'],
      targetRoles: ['table-host', 'partner', 'volunteer', 'curious-guest'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
