// Explorer Config — Dossani Paradise Management
// Multi-unit franchise operator headquartered in Grapevine, TX. Operates
// 25+ Burger Kings, 50+ Taco Bell / Pizza Hut / KFC / Long John Silver's
// (via North Texas Bells LLC), plus convenience stores, real estate, and
// Petrolink fuel distribution across Texas and Oklahoma. Founded by
// Al Dossani on Dec 21, 2011.

import type { ExplorerConfig, ThemeColors } from '../types';

const DOSSANI_DARK: ThemeColors = {
  // bg drives --exp-bg → used by Tools dropdown background.
  // Red-tinted to keep the menu visually on-brand instead of
  // generic dark navy. bgGradient stays as the blue depth wash
  // for the splash backdrop.
  bg: '#1F040B',
  bgGradient: 'linear-gradient(135deg, #003496 0%, #001F5C 55%, #1F040B 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#FF4D4D',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.78)',
  text3: 'rgba(255,255,255,0.52)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(255,4,4,0.22)',
};

const DOSSANI_LIGHT: ThemeColors = {
  bg: '#F4F5F9',
  bgGradient: 'linear-gradient(180deg, #F4F5F9 0%, #EEF1F8 100%)',
  surface: 'rgba(255,255,255,0.88)',
  surfaceHover: 'rgba(255,255,255,0.96)',
  border: 'rgba(0,21,61,0.10)',
  borderFocus: '#003496',
  text1: '#000A1F',
  text2: 'rgba(0,21,61,0.68)',
  text3: 'rgba(0,21,61,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#000A1F',
  inputPlaceholder: 'rgba(0,21,61,0.38)',
  logoText: '#000A1F',
  focusRing: 'rgba(0,52,150,0.14)',
};

export const DOSSANI_PARADISE_CONFIG: ExplorerConfig = {
  id: 'dossani-paradise',
  name: 'Dossani Paradise Explorer',
  version: 1,
  createdAt: '2026-06-03T00:00:00.000Z',
  updatedAt: '2026-06-03T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/dossani-paradise-logo-reverse.png',
      light: '/brand/assets/dossani-paradise-logo.png',
    },
    // Compact "DOSSANI [bar] PARADISE" wordmark, generated at 1387×200
    // for sharpness. 36px logoHeight matches the standard horizontal
    // wordmark treatment used by Formation, DealRoom, Maven FP.
    logoHeight: 36,
    icon: '/brand/assets/dossani-paradise-icon.png',
    colors: {
      primary: '#FF0404',   // Dossani red — bold accent
      secondary: '#003496', // Dossani blue — depth + endpoint
      teal: '#FF4D4D',      // softer red for hover/focus contrast
      blue: '#003496',
      deepBlue: '#001F5C',
      // midnight + navy are dark UI tones — theme.ts uses them for
      // .exp-dialog-bg (the Notes / Tools menu / dialog background)
      // and .exp-dialog-overlay-bg. Tinted toward the Dossani red so
      // dialogs feel distinctly branded instead of generic dark navy.
      navy: '#3D0815',      // deep maroon — drives dialog overlay backdrop
      midnight: '#1F040B',  // very dark wine — drives dialog/menu background
      plum: '#5C0202',      // deep red warm anchor
      bgDark: '#1F040B',
      dark: DOSSANI_DARK,
      light: DOSSANI_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(255,4,4,0.16)',     // red
      orb2: 'rgba(0,52,150,0.20)',    // Dossani blue
      orb3: 'rgba(92,2,2,0.12)',      // deep red anchor
    },
    ctaGradient: 'linear-gradient(135deg, #FF0404 0%, #003496 100%)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #FF4D4D 0%, #FF0404 100%)',
    // Per-role glows use red / blue / red-anchor triad for variety
    // while staying on the bold brand palette.
    roleBackgrounds: {
      'job-seeker': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,52,150,0.32) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(255,4,4,0.16) 0%, transparent 55%)',
      'franchisee': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,4,4,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(0,52,150,0.16) 0%, transparent 55%)',
      'vendor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,77,77,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(0,52,150,0.14) 0%, transparent 55%)',
      'real-estate': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,52,150,0.28) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(92,2,2,0.14) 0%, transparent 55%)',
      'customer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,4,4,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(255,77,77,0.12) 0%, transparent 55%)',
      'operator': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,31,92,0.30) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(255,4,4,0.14) 0%, transparent 55%)',
      'press': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(92,2,2,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(0,52,150,0.14) 0%, transparent 55%)',
      'visiting': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,52,150,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(255,4,4,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Welcome to Dossani Paradise',
    formSubtitle: 'Tell us a bit about yourself to get started.',
    scanLabel: 'Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Dossani Paradise Management processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@email.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Company name (if applicable)', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      // Two-line headline: solid white line, then gradient line.
      title: 'Building Texas,',
      gradientWord: 'One Store at a Time.',
      subtitle: 'A multi-unit franchise operator with 75+ restaurants, convenience stores, real estate, and fuel distribution across Texas and Oklahoma — founded by Al Dossani in 2011.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What brings you here today?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'job-seeker', label: 'Job Seeker / Crew', icon: 'users', iconType: 'lucide' },
        { value: 'franchisee', label: 'Franchisee / Investor', icon: 'trending-up', iconType: 'lucide' },
        { value: 'vendor', label: 'Vendor / Supplier', icon: 'truck', iconType: 'lucide' },
        { value: 'real-estate', label: 'Real Estate Partner', icon: 'landmark', iconType: 'lucide' },
        { value: 'customer', label: 'Customer / Community', icon: 'heart', iconType: 'lucide' },
        { value: 'operator', label: 'Operator / GM', icon: 'briefcase', iconType: 'lucide' },
        { value: 'press', label: 'Press / Media', icon: 'megaphone', iconType: 'lucide' },
        { value: 'visiting', label: 'Just Visiting', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you here to explore?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'careers', label: 'Careers & Hiring', icon: 'briefcase', iconType: 'lucide' },
        { value: 'franchise', label: 'Franchise Opportunity', icon: 'dollar-sign', iconType: 'lucide' },
        { value: 'real-estate', label: 'Real Estate', icon: 'landmark', iconType: 'lucide' },
        { value: 'supply', label: 'Vendor / Supply Chain', icon: 'truck', iconType: 'lucide' },
        { value: 'cstore', label: 'Convenience Stores', icon: 'store', iconType: 'lucide' },
        { value: 'restaurants', label: 'Restaurant Brands', icon: 'flame', iconType: 'lucide' },
        { value: 'fuel', label: 'Fuel & Petrolink', icon: 'zap', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Tour',
      subtitle: 'Brands, opportunities, and stories tailored to why you stopped by.',
      tabs: [
        // Tab labels kept to single short words so they never wrap to
        // two lines in the pill container (tab pill is fixed height).
        { id: 'outcomes', label: 'Numbers', icon: 'trending-up' },
        {
          id: 'learn',
          label: 'Discover',
          icon: 'book-open',
          filters: [
            { label: 'All', value: 'all' },
            { label: 'Website', value: 'website' },
            { label: 'PDF', value: 'pdf' },
            { label: 'Blog', value: 'blog' },
            { label: 'Video', value: 'video' },
          ],
        },
        { id: 'solutions', label: 'Brands', icon: 'layers' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review your picks and the Dossani Paradise team will follow up.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Explore Everything',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'The Dossani Paradise team will be in touch shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes / By the Numbers (7) ─────────────────
    {
      id: 'o1',
      title: '75+ Locations Across TX + OK',
      cardType: 'outcome',
      icon: 'map-pin',
      iconType: 'lucide',
      stat: '75+',
      description: {
        small: '75+ restaurants and stores across Texas and Oklahoma.',
        medium: '75+ restaurant and convenience-store locations spanning East Texas, West Texas, the DFW Metroplex, and Oklahoma.',
        large: 'Dossani Paradise Management operates 75+ restaurants and convenience stores across East Texas, West Texas, the DFW Metroplex, and Oklahoma — and is expanding rapidly.',
        overlay: '75+ active locations across East Texas, West Texas, the DFW Metroplex (Dallas, Fort Worth, Arlington, Plano, McKinney, Denton, Lewisville), and Oklahoma (Lawton, Duncan). The portfolio spans restaurants, convenience stores, fuel, and real estate — all under one operating team.',
      },
      tags: ['careers', 'restaurants', 'cstore'],
      targetRoles: ['job-seeker', 'franchisee', 'real-estate', 'visiting'],
    },
    {
      id: 'o2',
      title: '50+ Yum! Brand Restaurants',
      cardType: 'outcome',
      icon: 'flame',
      iconType: 'lucide',
      stat: '50+',
      description: {
        small: '50+ Taco Bell, Pizza Hut, KFC, and Long John Silver\'s.',
        medium: 'North Texas Bells LLC operates 50+ Taco Bell, Pizza Hut, KFC, and Long John Silver\'s locations.',
        large: 'Through North Texas Bells LLC — founded December 21, 2011 by Al Dossani and Troy Morrison — the company operates 50+ Taco Bell, Pizza Hut, KFC, and Long John Silver\'s locations across the region.',
        overlay: 'North Texas Bells LLC, founded December 21, 2011 by Al Dossani and Troy Morrison, operates 50+ Yum! Brands restaurants across the region: Taco Bell, Pizza Hut, KFC, and Long John Silver\'s. The same operations team handles development, training, supply chain, and brand standards across all four banners.',
      },
      tags: ['restaurants', 'careers'],
      targetRoles: ['job-seeker', 'franchisee', 'operator', 'customer'],
    },
    {
      id: 'o3',
      title: '25+ Burger King Units',
      cardType: 'outcome',
      icon: 'gift',
      iconType: 'lucide',
      stat: '25+',
      description: {
        small: '25+ Burger King restaurants across Texas.',
        medium: 'Dossani Paradise Management operates 25+ Burger King locations, expanding rapidly across East and West Texas.',
        large: 'Burger King operations launched October 2014 with the first store in Nash, TX. Dossani Paradise now operates 25+ Burger King restaurants across East and West Texas, expanding into Oklahoma.',
        overlay: 'Burger King is the company\'s newest growth engine. Operations launched October 2014 with the first store in Nash, TX. The portfolio now spans 25+ Burger King locations across East Texas (Marshall, Nash), West Texas (Wichita Falls), and Oklahoma (Lawton, Duncan) — with the playbook tuned for taking over and turning around underperforming stores.',
      },
      tags: ['restaurants', 'careers'],
      targetRoles: ['job-seeker', 'franchisee', 'operator'],
    },
    {
      id: 'o4',
      title: '4 Business Divisions',
      cardType: 'outcome',
      icon: 'layers',
      iconType: 'lucide',
      stat: '4',
      description: {
        small: 'Restaurants, C-stores, real estate, and fuel.',
        medium: 'Four integrated divisions: restaurants, convenience stores, real estate, and fuel distribution.',
        large: 'Dossani Paradise runs four integrated business divisions — restaurants, convenience stores, real estate holdings, and Petrolink fuel distribution — giving operators a fully vertical hospitality footprint.',
        overlay: 'Four integrated divisions: 75+ restaurants (Burger King, Taco Bell, Pizza Hut, KFC, Long John Silver\'s, Subway), convenience stores, commercial real estate holdings, and Petrolink fuel distribution. The verticals reinforce each other — fuel feeds the stores, real estate hosts the restaurants, and the operations team scales across all four.',
      },
      tags: ['cstore', 'restaurants', 'fuel', 'real-estate'],
      targetRoles: ['franchisee', 'vendor', 'real-estate', 'press'],
    },
    {
      id: 'o5',
      title: 'Texas-Born, Family-Operated',
      cardType: 'outcome',
      icon: 'star',
      iconType: 'lucide',
      stat: '2011',
      description: {
        small: 'Founded December 21, 2011 in Grapevine, TX.',
        medium: 'Founded by Al Dossani in December 2011 and headquartered in Grapevine, Texas.',
        large: 'Founded by Al Dossani on December 21, 2011 and headquartered in Grapevine, Texas — a family-operated business that has grown into one of the largest franchise operators in the region.',
        overlay: 'Founded by Al Dossani on December 21, 2011 and headquartered at 520 East Northwest Highway in Grapevine, Texas. A family-operated business that grew from a single store to one of the largest multi-brand franchise operators in the Texas/Oklahoma region — built on long-term relationships with brand partners, vendors, and team members.',
      },
      tags: ['careers', 'franchise'],
      targetRoles: ['customer', 'press', 'visiting', 'job-seeker'],
    },
    {
      id: 'o6',
      title: 'Turnaround Playbook',
      cardType: 'outcome',
      icon: 'trending-up',
      iconType: 'lucide',
      stat: 'Proven',
      description: {
        small: 'Specialty: turning around underperforming stores.',
        medium: 'A proven playbook for identifying underperforming stores and converting them into successful operations.',
        large: 'Dossani Paradise has built a reputation for identifying underperforming stores, applying a proven operations playbook, and converting them into top-performing locations across multiple brand banners.',
        overlay: 'The core operating thesis: take over underperforming stores, apply a proven turnaround playbook, and convert them into top-performing locations. The same operations discipline runs across every banner — Burger King, Taco Bell, Pizza Hut, KFC, Long John Silver\'s — and is the reason brand partners trust Dossani Paradise with new development territories.',
      },
      tags: ['franchise', 'restaurants'],
      targetRoles: ['franchisee', 'operator', 'press'],
    },
    {
      id: 'o7',
      title: 'Petrolink Fuel Network',
      cardType: 'outcome',
      icon: 'zap',
      iconType: 'lucide',
      stat: 'Vertical',
      description: {
        small: 'Petrolink fuel distribution feeds the network.',
        medium: 'Petrolink fuel distribution supplies the convenience-store network and external dealers across the region.',
        large: 'The Petrolink fuel distribution arm supplies the company\'s convenience stores and external dealers across Texas and Oklahoma — turning vertical integration into a competitive advantage.',
        overlay: 'Petrolink, the fuel distribution arm, supplies both the in-house convenience-store network and external dealers across Texas and Oklahoma. Vertical integration means tighter margins, more reliable supply, and a single relationship for dealers looking for a partner that understands the full c-store + fuel economics.',
      },
      tags: ['fuel', 'cstore', 'supply'],
      targetRoles: ['vendor', 'franchisee', 'operator'],
    },

    // ── Learn / Discover (8) ──────────────────────────
    {
      id: 'l1',
      title: 'About Dossani Paradise',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'info',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'The story behind Dossani Paradise Management.',
        medium: 'The full story: founding, four divisions, brand partners, and growth roadmap.',
        large: 'Dive into the founding story, the four divisions, the brand-partner roster, and where Dossani Paradise is headed next across Texas and Oklahoma.',
        overlay: 'The full story behind Dossani Paradise Management: how Al Dossani built the company from a single store in Grapevine into a 75+ location multi-brand operator, the partnerships with Yum! Brands and Burger King, and the growth roadmap across East Texas, West Texas, the DFW Metroplex, and Oklahoma.',
      },
      tags: ['careers', 'franchise', 'restaurants'],
      targetRoles: ['visiting', 'press', 'customer', 'franchisee'],
    },
    {
      id: 'l2',
      title: 'Restaurant Brand Portfolio',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'flame',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/restaurants/',
      description: {
        small: 'See all 75+ restaurants and the brands we run.',
        medium: 'Browse the full restaurant portfolio: Burger King, Taco Bell, Pizza Hut, KFC, Long John Silver\'s, and Subway.',
        large: 'A region-by-region map of the 75+ restaurants Dossani Paradise operates — Burger King, Taco Bell, Pizza Hut, KFC, Long John Silver\'s, and Subway — with the story of how each brand fits the portfolio.',
        overlay: 'A region-by-region map of every restaurant Dossani Paradise operates: 25+ Burger Kings (Dossani Paradise Management) plus 50+ Taco Bell, Pizza Hut, KFC, and Long John Silver\'s (North Texas Bells LLC), and Subway. Filter by brand, by city, and by what stage of development each location is in.',
      },
      tags: ['restaurants', 'careers'],
      targetRoles: ['customer', 'job-seeker', 'franchisee', 'press'],
    },
    {
      id: 'l3',
      title: 'Careers at Dossani Paradise',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'briefcase',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'Open roles across 75+ Texas + Oklahoma locations.',
        medium: 'Open crew, GM, multi-unit, and corporate roles across the 75+ restaurant and store footprint.',
        large: 'Apply through the Paycom employment portal for open roles spanning crew, shift leads, GMs, multi-unit leaders, and corporate positions across the 75+ location footprint.',
        overlay: 'Dossani Paradise hires through the Paycom employment portal across every level: crew at the BK / Taco Bell / Pizza Hut / KFC / Subway locations, shift leads, general managers, multi-unit leaders, fuel-supply roles at Petrolink, real estate / facilities, and corporate roles based out of Grapevine HQ. Filter by city, brand, and seniority to find a fit.',
      },
      tags: ['careers'],
      targetRoles: ['job-seeker', 'visiting', 'operator'],
    },
    {
      id: 'l4',
      title: 'Franchise & Partnership Inquiry',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'handshake',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'Talk to us about franchise and partnership deals.',
        medium: 'Connect with the development team about franchise, partnership, and JV opportunities.',
        large: 'Get in touch with the Dossani Paradise development team about franchise opportunities, partnership structures, and JV development across new and existing brand territories.',
        overlay: 'A direct line to the Dossani Paradise development team for franchise inquiries, partnership structures, JV development opportunities, and brand-territory conversations. Whether you\'re a brand looking for an operator in Texas or an investor looking for a partner with a proven turnaround playbook, this is the starting point.',
      },
      tags: ['franchise', 'real-estate'],
      targetRoles: ['franchisee', 'real-estate', 'press'],
    },
    {
      id: 'l5',
      title: 'Real Estate & Development',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'landmark',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'Land, sites, and development opportunities.',
        medium: 'Real estate holdings, available sites, and development partnerships across Texas and Oklahoma.',
        large: 'Dossani Paradise\'s real estate arm holds and develops commercial sites across Texas and Oklahoma — restaurant pads, c-store corners, fuel stations, and mixed-use parcels. Talk to the team about co-development.',
        overlay: 'The real estate division holds and develops commercial sites across Texas and Oklahoma — restaurant pads, convenience-store corners, fuel station footprints, and mixed-use parcels. Open to co-development deals, sale-leasebacks, and ground-lease structures with operators looking for a long-term landlord partner.',
      },
      tags: ['real-estate', 'franchise'],
      targetRoles: ['real-estate', 'franchisee', 'press'],
    },
    {
      id: 'l6',
      title: 'Vendor & Supply Partners',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'truck',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'Become a Dossani Paradise vendor.',
        medium: 'Supplier intake: food, paper, packaging, equipment, services, technology.',
        large: 'Vendor intake covers everything from food, paper, and packaging to equipment, services, and technology across all four divisions and 75+ locations.',
        overlay: 'Dossani Paradise\'s scale across 75+ restaurants, convenience stores, real estate, and Petrolink fuel makes for substantial supplier needs. Vendor intake covers food and paper, packaging, kitchen and store equipment, facilities and maintenance services, technology and POS, marketing and signage, and uniforms. Submit a brief intro and the procurement team will reach out.',
      },
      tags: ['supply'],
      targetRoles: ['vendor'],
    },
    {
      id: 'l7',
      title: 'Petrolink Fuel Distribution',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'zap',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'Petrolink fuel supply across TX and OK.',
        medium: 'Petrolink supplies fuel to the in-house c-store network and external dealers across Texas and Oklahoma.',
        large: 'Petrolink is the company\'s fuel distribution arm — supplying gasoline and diesel to the in-house convenience-store network and a growing list of independent dealer accounts across Texas and Oklahoma.',
        overlay: 'Petrolink supplies gasoline and diesel across Texas and Oklahoma — to the in-house convenience-store network and to a growing list of independent dealer accounts. Dealers get reliable supply, competitive pricing, and a partner that understands the c-store + fuel economics from the operator side.',
      },
      tags: ['fuel', 'cstore', 'supply'],
      targetRoles: ['vendor', 'franchisee', 'operator'],
    },
    {
      id: 'l8',
      title: 'Visit HQ in Grapevine',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'map-pin',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'HQ: 520 East Northwest Highway, Grapevine, TX.',
        medium: 'Dossani Paradise HQ — 520 East Northwest Highway, Grapevine, TX 76051.',
        large: 'Headquartered at 520 East Northwest Highway, Suite 100 in Grapevine, TX. Main line: 817-442-1159. The operations, real estate, and corporate teams all live under one roof.',
        overlay: 'Dossani Paradise Management headquarters: 520 East Northwest Highway, Suite 100, Grapevine, TX 76051. Main: 817-442-1159 · Fax: 817-442-1160. Operations, real estate, development, finance, and corporate teams all work out of the Grapevine HQ. Visitors welcome by appointment.',
      },
      tags: ['careers', 'franchise'],
      targetRoles: ['visiting', 'press', 'vendor'],
    },

    // ── Solutions / Our Brands (7) ────────────────────
    {
      id: 's1',
      title: 'Burger King',
      cardType: 'solution',
      icon: 'gift',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: '25+ Burger King restaurants and growing.',
        medium: '25+ Burger King restaurants across East Texas, West Texas, and Oklahoma.',
        large: 'Burger King operations launched October 2014 in Nash, TX. The portfolio has grown to 25+ restaurants across East Texas, West Texas, and Oklahoma — managed directly by Dossani Paradise Management.',
        overlay: '25+ Burger King restaurants across East Texas (Marshall, Nash), West Texas (Wichita Falls), and Oklahoma (Lawton, Duncan) — operations launched October 2014 with the first store in Nash, TX. The portfolio is growing rapidly through a combination of new builds and turnaround acquisitions.',
      },
      tags: ['restaurants', 'careers'],
      targetRoles: ['customer', 'job-seeker', 'operator', 'franchisee'],
    },
    {
      id: 's2',
      title: 'Taco Bell',
      cardType: 'solution',
      icon: 'flame',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/restaurants/',
      description: {
        small: 'Taco Bell — part of the 50+ Yum! portfolio.',
        medium: 'Taco Bell restaurants operated through North Texas Bells LLC across the region.',
        large: 'Taco Bell is one of four Yum! Brands operated through North Texas Bells LLC — 50+ combined Taco Bell, Pizza Hut, KFC, and Long John Silver\'s locations across the region.',
        overlay: 'Taco Bell is one of four Yum! Brands operated through North Texas Bells LLC — the JV founded December 21, 2011 by Al Dossani and Troy Morrison. The Taco Bell footprint is concentrated across DFW (Dallas, Fort Worth, Arlington, Plano, McKinney, Denton, Lewisville) with continued development across Texas and Oklahoma.',
      },
      tags: ['restaurants', 'careers'],
      targetRoles: ['customer', 'job-seeker', 'franchisee'],
    },
    {
      id: 's3',
      title: 'Pizza Hut',
      cardType: 'solution',
      icon: 'star',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/restaurants/',
      description: {
        small: 'Pizza Hut delivery + dine-in across the region.',
        medium: 'Pizza Hut restaurants operated through North Texas Bells LLC — delivery, dine-in, and Express formats.',
        large: 'Pizza Hut is part of the 50+ Yum! portfolio operated through North Texas Bells LLC — covering delivery, dine-in, and Express formats across the region.',
        overlay: 'Pizza Hut sits alongside Taco Bell, KFC, and Long John Silver\'s in the North Texas Bells LLC portfolio. The Pizza Hut footprint includes traditional dine-in, delivery, and Express formats — concentrated in DFW with continued development across smaller East Texas and West Texas markets.',
      },
      tags: ['restaurants', 'careers'],
      targetRoles: ['customer', 'job-seeker', 'franchisee'],
    },
    {
      id: 's4',
      title: 'KFC + Long John Silver\'s',
      cardType: 'solution',
      icon: 'gift',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/restaurants/',
      description: {
        small: 'KFC and KFC/LJS co-branded locations.',
        medium: 'KFC standalone and KFC / Long John Silver\'s co-branded locations across Texas.',
        large: 'KFC and Long John Silver\'s — operated standalone and as KFC/LJS co-branded locations — round out the Yum! Brands portfolio managed by North Texas Bells LLC.',
        overlay: 'KFC and Long John Silver\'s round out the Yum! portfolio. Operated both as standalone KFC locations and as KFC/LJS co-branded sites — a format that captures higher daypart coverage from chicken at lunch through seafood at dinner. Concentrated across DFW and East Texas with continued development.',
      },
      tags: ['restaurants', 'careers'],
      targetRoles: ['customer', 'job-seeker', 'franchisee'],
    },
    {
      id: 's5',
      title: 'Convenience Stores',
      cardType: 'solution',
      icon: 'store',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'C-store network supplied by Petrolink fuel.',
        medium: 'Convenience-store network supplied by the Petrolink fuel arm across Texas and Oklahoma.',
        large: 'The convenience-store division operates branded fuel and retail locations across Texas and Oklahoma — vertically integrated with Petrolink fuel distribution for tighter margins and reliable supply.',
        overlay: 'The c-store division operates branded fuel and retail locations across Texas and Oklahoma — vertically integrated with Petrolink fuel distribution. Tighter margins, reliable supply, and a single operations team handling fuel, retail, food service, and facilities across every site.',
      },
      tags: ['cstore', 'fuel'],
      targetRoles: ['customer', 'operator', 'vendor', 'franchisee'],
    },
    {
      id: 's6',
      title: 'Petrolink Fuel',
      cardType: 'solution',
      icon: 'zap',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'Fuel distribution to in-house and external dealers.',
        medium: 'Petrolink supplies gasoline and diesel to in-house c-stores and external dealer accounts.',
        large: 'Petrolink is the fuel distribution arm — supplying gasoline and diesel to the in-house c-store network and a growing list of independent dealers across Texas and Oklahoma.',
        overlay: 'Petrolink is the fuel distribution business — gasoline and diesel supplied to the in-house convenience-store network and to a growing list of independent dealer accounts. For dealers, the value prop is reliable supply, competitive pricing, and a partner that understands the c-store + fuel economics from the operator side, not just the supplier side.',
      },
      tags: ['fuel', 'cstore', 'supply'],
      targetRoles: ['vendor', 'franchisee', 'operator'],
    },
    {
      id: 's7',
      title: 'Real Estate Holdings',
      cardType: 'solution',
      icon: 'landmark',
      iconType: 'lucide',
      url: 'https://dossaniparadise.com/',
      description: {
        small: 'Commercial sites across Texas and Oklahoma.',
        medium: 'Commercial real estate holdings — restaurant pads, c-store corners, fuel sites, and mixed-use parcels.',
        large: 'The real estate arm holds and develops commercial sites across Texas and Oklahoma — restaurant pads, c-store corners, fuel station footprints, and mixed-use parcels. Open to co-development with the right operator partners.',
        overlay: 'Commercial real estate holdings across Texas and Oklahoma — restaurant pads, convenience-store corners, fuel station footprints, and mixed-use parcels. The real estate team is open to co-development deals, sale-leasebacks, and ground-lease structures with operators looking for a long-term landlord partner who understands hospitality real estate.',
      },
      tags: ['real-estate', 'franchise'],
      targetRoles: ['real-estate', 'franchisee', 'press'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
