// Explorer Config — Expedited Service Partners (ESP)
// 24/7 worksite solutions & equipment rental for emergency response, construction, and facilities

import type { ExplorerConfig, ThemeColors } from '../types';

const ESP_DARK: ThemeColors = {
  bg: '#0C1113',
  bgGradient: 'linear-gradient(135deg, #1C262B 0%, #10171A 55%, #211712 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#F7951D',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(247,149,29,0.18)',
};

const ESP_LIGHT: ThemeColors = {
  bg: '#F5F4F2',
  bgGradient: 'linear-gradient(180deg, #F5F4F2 0%, #F1F0EE 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#A85A0E',
  text1: '#1A1A1A',
  text2: 'rgba(26,26,26,0.65)',
  text3: 'rgba(26,26,26,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#1A1A1A',
  inputPlaceholder: 'rgba(26,26,26,0.35)',
  logoText: '#1A1A1A',
  focusRing: 'rgba(168,90,14,0.12)',
};

export const EXPEDITED_SERVICE_PARTNERS_CONFIG: ExplorerConfig = {
  id: 'expedited-service-partners',
  name: 'Expedited Service Partners Explorer',
  version: 1,
  createdAt: '2026-06-30T00:00:00.000Z',
  updatedAt: '2026-06-30T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/expedited-service-partners-logo-reverse.webp',
      light: '/brand/assets/expedited-service-partners-logo.webp',
    },
    // ESP logo is a circular badge with "EXPEDITED SERVICE PARTNERS" wrapped
    // around the ring — illegible at the locked 28px default, needs real size.
    logoHeight: 96,
    icon: '/brand/assets/expedited-service-partners-icon.webp',
    colors: {
      primary: '#F7951D',
      secondary: '#59595B',
      teal: '#FFAB4D',
      blue: '#3D4A52',
      deepBlue: '#26343C',
      navy: '#1C262B',
      midnight: '#10171A',
      plum: '#A85A0E',
      bgDark: '#0C1113',
      dark: ESP_DARK,
      light: ESP_LIGHT,
    },
    font: 'Inter',
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(247,149,29,0.16)',
      orb2: 'rgba(255,171,77,0.12)',
      orb3: 'rgba(89,89,91,0.14)',
    },
    ctaGradient: 'linear-gradient(135deg, #E07B14, #7A4510)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #FFB459, #F7951D)',
    roleBackgrounds: {
      'restoration': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(247,149,29,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(89,89,91,0.12) 0%, transparent 55%)',
      'construction': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,171,77,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(247,149,29,0.10) 0%, transparent 55%)',
      'property-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(89,89,91,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(247,149,29,0.12) 0%, transparent 55%)',
      'insurance': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(247,149,29,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(255,171,77,0.08) 0%, transparent 55%)',
      'government': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(61,74,82,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(247,149,29,0.15) 0%, transparent 55%)',
      'healthcare': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,171,77,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(89,89,91,0.12) 0%, transparent 55%)',
      'events': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(247,149,29,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(255,171,77,0.12) 0%, transparent 55%)',
      'industrial': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(89,89,91,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(61,74,82,0.12) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Please fill in the form to continue.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Expedited Service Partners processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Company name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Worksite',
      gradientWord: 'Solutions.',
      subtitle: 'Discover how Expedited Service Partners delivers 24/7 emergency response, equipment rental, and staffing solutions wherever your job site needs them.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes you?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'restoration', label: 'Restoration Company', icon: 'droplets', iconType: 'lucide' },
        { value: 'construction', label: 'Construction Contractor', icon: 'hard-hat', iconType: 'lucide' },
        { value: 'property-manager', label: 'Property Manager', icon: 'building-2', iconType: 'lucide' },
        { value: 'insurance', label: 'Insurance Adjuster / Broker', icon: 'shield-check', iconType: 'lucide' },
        { value: 'government', label: 'Municipality / Government', icon: 'landmark', iconType: 'lucide' },
        { value: 'healthcare', label: 'Healthcare Facility', icon: 'heart-pulse', iconType: 'lucide' },
        { value: 'events', label: 'Event Venue / Hospitality', icon: 'gift', iconType: 'lucide' },
        { value: 'industrial', label: 'Industrial / Manufacturing', icon: 'factory', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What do you need on-site?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'power', label: 'Power Generation', icon: 'zap', iconType: 'lucide' },
        { value: 'climate', label: 'Climate Control', icon: 'thermometer', iconType: 'lucide' },
        { value: 'equipment', label: 'Equipment Rental', icon: 'wrench', iconType: 'lucide' },
        { value: 'emergency', label: 'Emergency Response', icon: 'alert-triangle', iconType: 'lucide' },
        { value: 'staffing', label: 'Workforce & Staffing', icon: 'users', iconType: 'lucide' },
        { value: 'water', label: 'Water & Sanitation', icon: 'droplets', iconType: 'lucide' },
        { value: 'site-support', label: 'Lighting & Site Support', icon: 'lightbulb', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Podcast', value: 'podcast' },
          { label: 'PDF', value: 'pdf' },
        ]},
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (6) ──────────────────────────────────
    {
      id: 'o1',
      title: '2-Hour Emergency Response',
      cardType: 'outcome',
      icon: 'alert-triangle',
      iconType: 'lucide',
      stat: '2-Hr',
      description: {
        small: 'On-site emergency response in as little as 2 hours.',
        medium: 'ESP mobilizes equipment and crews to your site in as little as 2 hours after an emergency call.',
        large: 'When disaster strikes, every hour counts. ESP\'s 2-hour emergency response capability gets power, climate control, and technicians on-site fast, minimizing downtime and damage.',
        overlay: 'Restoration jobs, storm damage, and equipment failures don\'t wait for business hours. ESP\'s 2-hour emergency response network of generators, climate equipment, and licensed technicians is staged for rapid deployment, so your site is never left without power, cooling, or support when it matters most.',
      },
      tags: ['emergency', 'power'],
      targetRoles: ['restoration', 'insurance', 'government'],
    },
    {
      id: 'o2',
      title: '24/7/365 Availability',
      cardType: 'outcome',
      icon: 'clock',
      iconType: 'lucide',
      stat: '24/7/365',
      description: {
        small: 'Around-the-clock support, every day of the year.',
        medium: 'ESP\'s team is staffed and ready 24/7/365, including holidays and weekends.',
        large: 'Equipment failures and emergencies don\'t respect a schedule. ESP\'s dispatch and field teams are available 24 hours a day, 7 days a week, 365 days a year to keep your worksite running.',
        overlay: 'A worksite emergency at 2am on a holiday weekend is still an emergency. ESP staffs dispatch, technicians, and equipment logistics around the clock so a call placed any time of day or night gets the same rapid, professional response.',
      },
      tags: ['emergency', 'staffing'],
      targetRoles: ['restoration', 'construction', 'healthcare', 'government'],
    },
    {
      id: 'o3',
      title: 'One Call, Full Solution',
      cardType: 'outcome',
      icon: 'phone-call',
      iconType: 'lucide',
      stat: 'One Call',
      description: {
        small: 'Power, climate, equipment, and staffing from a single partner.',
        medium: 'Skip the vendor juggling. ESP coordinates power, climate control, equipment, and workforce from one call.',
        large: 'ESP consolidates power generation, climate control, heavy equipment, site support, and skilled labor under a single point of contact, so project managers stop chasing multiple vendors during critical timelines.',
        overlay: 'Coordinating separate vendors for generators, chillers, lighting, and labor wastes time you don\'t have during an emergency or tight build schedule. ESP\'s single-source model means one call sets the entire worksite solution in motion, from equipment delivery to licensed technicians on-site.',
      },
      tags: ['equipment', 'staffing'],
      targetRoles: ['construction', 'property-manager', 'industrial'],
    },
    {
      id: 'o4',
      title: 'Trusted Across 9+ Industries',
      cardType: 'outcome',
      icon: 'layout-grid',
      iconType: 'lucide',
      stat: '9+',
      description: {
        small: 'Serving restoration, construction, healthcare, and more.',
        medium: 'ESP supports restoration, construction, healthcare, government, retail, and event clients nationwide.',
        large: 'From hospitals to disaster restoration sites to large-scale events, ESP\'s equipment and crews flex to the demands of more than nine distinct industries without sacrificing response speed or quality.',
        overlay: 'No two worksites are alike. ESP\'s breadth across restoration, construction, healthcare, municipal, industrial, retail, and hospitality clients means the team understands the regulatory, safety, and logistical needs unique to each industry it serves.',
      },
      tags: ['emergency', 'equipment'],
      targetRoles: ['healthcare', 'government', 'events', 'industrial'],
    },
    {
      id: 'o5',
      title: 'Top-Rated Resource Partner',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: '#1',
      description: {
        small: '"ESP has proven to be our top resource partner."',
        medium: 'Clients consistently rank ESP as their most reliable equipment and staffing resource partner.',
        large: 'Restoration and construction partners cite ESP\'s outstanding customer service and dependability, with one client noting ESP "has proven to be CRC\'s top resource partner."',
        overlay: 'Reliability builds trust over time. ESP\'s long-standing partnerships with restoration companies, contractors, and facility teams are built on consistent, dependable execution job after job, earning ESP a reputation as the first call when a worksite needs support.',
      },
      tags: ['emergency', 'staffing'],
      targetRoles: ['restoration', 'construction', 'property-manager'],
    },
    {
      id: 'o6',
      title: 'Licensed, Field-Ready Crews',
      cardType: 'outcome',
      icon: 'hard-hat',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: 'Every job staffed with licensed technicians and operators.',
        medium: 'ESP fields project managers, licensed technicians, equipment operators, and health & safety officers on every deployment.',
        large: 'ESP doesn\'t just deliver equipment, it delivers the people to run it safely. Every deployment can include project managers, licensed technicians, equipment operators, and dedicated health & safety officers.',
        overlay: 'Equipment is only as effective as the people operating it. ESP pairs every rental and emergency deployment with the right mix of project managers, licensed technicians, certified equipment operators, and health & safety officers, ensuring the job gets done safely and correctly the first time.',
      },
      tags: ['staffing', 'equipment'],
      targetRoles: ['industrial', 'government', 'healthcare'],
    },

    // ── Learn (6) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Disaster Recovery Equipment Checklist',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'The equipment every restoration team should have on call.',
        medium: 'A practical checklist of power, climate, and extraction equipment for disaster recovery jobs.',
        large: 'This guide walks restoration and remediation teams through the generators, dehumidifiers, air movers, and extraction equipment needed to respond fast and protect a damaged site.',
        overlay: 'When water, fire, or storm damage hits, the right equipment mix determines how fast a site stabilizes. This checklist covers generators, chillers, dehumidification units, air scrubbers, and extraction equipment so restoration teams know exactly what to request on the first call.',
      },
      tags: ['emergency', 'climate'],
      targetRoles: ['restoration', 'insurance'],
    },
    {
      id: 'l2',
      title: 'Powering a Job Site: A Field Guide',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'zap',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'How to size and plan generator power for any site.',
        medium: 'Learn how ESP helps contractors size generators and plan fueling logistics for active job sites.',
        large: 'This field guide covers load calculations, generator sizing, and fueling logistics so construction teams avoid power gaps that stall a project timeline.',
        overlay: 'Undersized power is one of the most common causes of job site delays. This guide breaks down how ESP works with contractors to calculate load requirements, select the right generator capacity, and plan ongoing fueling service so power is never the bottleneck.',
      },
      tags: ['power'],
      targetRoles: ['construction', 'industrial'],
    },
    {
      id: 'l3',
      title: 'Inside a 2-Hour Emergency Deployment',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Watch how ESP mobilizes equipment after the call comes in.',
        medium: 'A behind-the-scenes look at how ESP dispatches equipment and crews within hours of an emergency call.',
        large: 'This video follows ESP\'s dispatch and field teams from the moment an emergency call comes in through equipment delivery and technician setup on-site.',
        overlay: 'Speed under pressure is ESP\'s core capability. This video shows the dispatch process, equipment staging, and technician deployment that makes a 2-hour emergency response possible, from the initial call to power restored on-site.',
      },
      tags: ['emergency', 'power'],
      targetRoles: ['restoration', 'government', 'healthcare'],
    },
    {
      id: 'l4',
      title: 'Climate Control for Sensitive Sites',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'thermometer',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Temperature and humidity control for healthcare and labs.',
        medium: 'Webinar on deploying temporary climate control for healthcare facilities and other sensitive environments.',
        large: 'This recorded webinar covers how ESP plans temporary AC, chiller, and dehumidification solutions for healthcare facilities, labs, and other environments with strict climate requirements.',
        overlay: 'Healthcare facilities and labs can\'t tolerate uncontrolled temperature or humidity swings during construction, renovation, or emergencies. This webinar covers ESP\'s approach to temporary climate control planning, equipment selection, and monitoring for sensitive environments.',
      },
      tags: ['climate'],
      targetRoles: ['healthcare', 'industrial'],
    },
    {
      id: 'l5',
      title: 'Planning Equipment for Large Events',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'globe',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Power, lighting, and climate planning for venues.',
        medium: 'A practical resource for event venues and hospitality teams planning power and climate needs.',
        large: 'This resource covers how event venues work with ESP to plan generators, lighting, and climate control well ahead of an event date, avoiding last-minute scrambles.',
        overlay: 'Large events have zero tolerance for power or climate failures mid-event. This resource walks event and hospitality teams through advance planning for generators, area lighting, and climate control, including backup contingencies for multi-day events.',
      },
      tags: ['power', 'site-support'],
      targetRoles: ['events'],
    },
    {
      id: 'l6',
      title: 'The ESP Values Behind Every Deployment',
      cardType: 'learn',
      mediaType: 'podcast',
      icon: 'headphones',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Loyalty, integrity, dedication, and teamwork in the field.',
        medium: 'ESP leadership discusses the core values that shape every emergency response and rental engagement.',
        large: 'In this conversation, ESP leadership talks through how loyalty, integrity, dedication, and teamwork show up in day-to-day field operations, from dispatch to technician conduct on-site.',
        overlay: 'Values mean little until they show up under pressure. This conversation with ESP leadership explores how loyalty, integrity, dedication, and teamwork translate into faster dispatch decisions, honest equipment recommendations, and field crews that show up and follow through.',
      },
      tags: ['staffing', 'emergency'],
      targetRoles: ['property-manager', 'government'],
    },

    // ── Solutions (6) ─────────────────────────────────
    {
      id: 's1',
      title: 'Power Generation & Fueling',
      cardType: 'solution',
      icon: 'zap',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Generators and fueling services for any size site.',
        medium: 'Generator rentals sized to your load, plus ongoing fueling service so power never runs out.',
        large: 'ESP supplies generators ranging from small portable units to large industrial capacity, paired with scheduled fueling service so job sites and emergency deployments never lose power.',
        overlay: 'Whether it\'s a single-day event or a months-long restoration project, ESP\'s power generation solution scales to match. The team handles load assessment, generator selection, delivery, and recurring fueling service, removing the guesswork from keeping a site powered.',
      },
      tags: ['power'],
      targetRoles: ['restoration', 'construction', 'events', 'industrial'],
    },
    {
      id: 's2',
      title: 'Climate Control Solutions',
      cardType: 'solution',
      icon: 'thermometer',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'AC, chillers, air movers, and dehumidification on demand.',
        medium: 'A full fleet of climate equipment including ACs, chillers, air movers, scrubbers, and temporary heating.',
        large: 'ESP\'s climate control fleet covers temporary AC, chillers, air movers, air scrubbers, dehumidification units, and temporary heating, deployed individually or as a complete site solution.',
        overlay: 'Temperature and humidity control can make or break a restoration timeline, a healthcare environment, or a construction schedule. ESP\'s climate equipment fleet, backed by licensed technicians, is sized and deployed to match the specific demands of your site.',
      },
      tags: ['climate'],
      targetRoles: ['restoration', 'healthcare', 'construction'],
    },
    {
      id: 's3',
      title: 'Equipment Rental Fleet',
      cardType: 'solution',
      icon: 'wrench',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Lighting, lifts, heavy equipment, and fencing.',
        medium: 'A broad rental fleet covering area lighting, lifts, heavy equipment, and site fencing.',
        large: 'From area lighting and aerial lifts to heavy equipment and perimeter fencing, ESP\'s rental fleet equips job sites with the tools needed to operate safely and efficiently.',
        overlay: 'Most worksites need more than one type of equipment to operate. ESP\'s rental fleet spans lighting towers, scissor and boom lifts, heavy equipment, and fencing, all available through the same logistics and delivery network as ESP\'s emergency response services.',
      },
      tags: ['equipment'],
      targetRoles: ['construction', 'events', 'industrial'],
    },
    {
      id: 's4',
      title: '24/7 Emergency Response',
      cardType: 'solution',
      icon: 'alert-triangle',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Rapid mobilization when disaster strikes.',
        medium: 'A standing emergency response capability that mobilizes equipment and crews within hours of a call.',
        large: 'ESP\'s emergency response service is built for restoration companies, insurers, and facility teams that need power, climate control, and skilled labor on-site fast, day or night.',
        overlay: 'Storm damage, fire, flooding, and equipment failures all demand the same thing: speed. ESP\'s emergency response solution combines pre-staged equipment, a 24/7 dispatch team, and licensed technicians to get a site stabilized and operational as quickly as possible.',
      },
      tags: ['emergency'],
      targetRoles: ['restoration', 'insurance', 'government'],
    },
    {
      id: 's5',
      title: 'Workforce & Staffing Solutions',
      cardType: 'solution',
      icon: 'users',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Project managers, technicians, and safety officers.',
        medium: 'On-demand staffing including project managers, licensed technicians, equipment operators, and safety officers.',
        large: 'ESP fields qualified project managers, licensed technicians, certified equipment operators, and dedicated health & safety officers to support deployments of any scale.',
        overlay: 'Equipment without the right people is just inventory. ESP\'s workforce solutions pair every deployment with the appropriate mix of project managers, licensed technicians, equipment operators, and health & safety officers, scaled to the size and complexity of the job.',
      },
      tags: ['staffing'],
      targetRoles: ['industrial', 'government', 'healthcare', 'property-manager'],
    },
    {
      id: 's6',
      title: 'Water, Sanitation & Site Support',
      cardType: 'solution',
      icon: 'droplets',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Potable water, extraction, sanitation, and containers.',
        medium: 'Full site support including potable water, water extraction, sanitation units, trailers, and containers.',
        large: 'ESP rounds out worksite logistics with potable water supply, extraction services, sanitation units, mobile trailers, and storage containers, all coordinated alongside power and climate equipment.',
        overlay: 'Beyond power and climate, a fully operational worksite needs water, sanitation, and storage logistics handled too. ESP coordinates potable water delivery, extraction services, sanitation units, trailers, and containers as part of a single, unified worksite solution.',
      },
      tags: ['water', 'site-support'],
      targetRoles: ['government', 'events', 'property-manager'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
