// Explorer Config — Expedited Service Partners (ESP)
// 24/7 worksite solutions & equipment rental for emergency response, construction, and facilities

import type { ExplorerConfig, ThemeColors } from '../types';

const ESP_DARK: ThemeColors = {
  bg: '#0C1113',
  bgGradient: 'linear-gradient(135deg, #1C262B 0%, #10171A 55%, #211712 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#F7951D',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(247,149,29,0.18)',
};

const ESP_LIGHT: ThemeColors = {
  bg: '#F5F4F2',
  bgGradient: 'linear-gradient(180deg, #F5F4F2 0%, #F1F0EE 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#A85A0E',
  text1: '#1A1A1A',
  text2: 'rgba(26,26,26,0.65)',
  text3: 'rgba(26,26,26,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#1A1A1A',
  inputPlaceholder: 'rgba(26,26,26,0.35)',
  logoText: '#1A1A1A',
  focusRing: 'rgba(168,90,14,0.12)',
};

export const EXPEDITED_SERVICE_PARTNERS_CONFIG: ExplorerConfig = {
  id: 'expedited-service-partners',
  name: 'Expedited Service Partners Explorer',
  version: 1,
  createdAt: '2026-06-30T00:00:00.000Z',
  updatedAt: '2026-06-30T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/expedited-service-partners-logo-reverse.png',
      light: '/brand/assets/expedited-service-partners-logo.png',
    },
    // ESP logo is a circular badge with "EXPEDITED SERVICE PARTNERS" wrapped
    // around the ring — illegible at the locked 28px default, needs real size.
    logoHeight: 96,
    icon: '/brand/assets/expedited-service-partners-icon.png',
    colors: {
      primary: '#F7951D',
      secondary: '#59595B',
      teal: '#FFAB4D',
      blue: '#3D4A52',
      deepBlue: '#26343C',
      navy: '#1C262B',
      midnight: '#10171A',
      plum: '#A85A0E',
      bgDark: '#0C1113',
      dark: ESP_DARK,
      light: ESP_LIGHT,
    },
    font: 'Inter',
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(247,149,29,0.16)',
      orb2: 'rgba(255,171,77,0.12)',
      orb3: 'rgba(89,89,91,0.14)',
    },
    ctaGradient: 'linear-gradient(135deg, #E07B14, #7A4510)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #FFB459, #F7951D)',
    roleBackgrounds: {
      'restoration': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(247,149,29,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(89,89,91,0.12) 0%, transparent 55%)',
      'construction': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,171,77,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(247,149,29,0.10) 0%, transparent 55%)',
      'property-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(89,89,91,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(247,149,29,0.12) 0%, transparent 55%)',
      'insurance': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(247,149,29,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(255,171,77,0.08) 0%, transparent 55%)',
      'government': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(61,74,82,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(247,149,29,0.15) 0%, transparent 55%)',
      'healthcare': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,171,77,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(89,89,91,0.12) 0%, transparent 55%)',
      'events': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(247,149,29,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(255,171,77,0.12) 0%, transparent 55%)',
      'industrial': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(89,89,91,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(61,74,82,0.12) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Please fill in the form to continue.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Expedited Service Partners processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Company name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Worksite',
      gradientWord: 'Solutions.',
      subtitle: 'Discover how Expedited Service Partners delivers 24/7 emergency response, equipment rental, and staffing solutions wherever your job site needs them.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes you?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'restoration', label: 'Restoration Company', icon: 'droplets', iconType: 'lucide' },
        { value: 'construction', label: 'Construction Contractor', icon: 'hard-hat', iconType: 'lucide' },
        { value: 'property-manager', label: 'Property Manager', icon: 'building-2', iconType: 'lucide' },
        { value: 'insurance', label: 'Insurance Adjuster / Broker', icon: 'shield-check', iconType: 'lucide' },
        { value: 'government', label: 'Municipality / Government', icon: 'landmark', iconType: 'lucide' },
        { value: 'healthcare', label: 'Healthcare Facility', icon: 'heart-pulse', iconType: 'lucide' },
        { value: 'events', label: 'Event Venue / Hospitality', icon: 'gift', iconType: 'lucide' },
        { value: 'industrial', label: 'Industrial / Manufacturing', icon: 'factory', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What do you need on-site?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'power', label: 'Power Generation', icon: 'zap', iconType: 'lucide' },
        { value: 'climate', label: 'Climate Control', icon: 'thermometer', iconType: 'lucide' },
        { value: 'equipment', label: 'Equipment Rental', icon: 'wrench', iconType: 'lucide' },
        { value: 'emergency', label: 'Emergency Response', icon: 'alert-triangle', iconType: 'lucide' },
        { value: 'staffing', label: 'Workforce & Staffing', icon: 'users', iconType: 'lucide' },
        { value: 'water', label: 'Water & Sanitation', icon: 'droplets', iconType: 'lucide' },
        { value: 'site-support', label: 'Lighting & Site Support', icon: 'lightbulb', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Podcast', value: 'podcast' },
          { label: 'PDF', value: 'pdf' },
        ]},
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (9) ──────────────────────────────────
    {
      id: 'o1',
      title: '2-Hour Emergency Response',
      cardType: 'outcome',
      icon: 'alert-triangle',
      iconType: 'lucide',
      stat: '2-Hr',
      description: {
        small: 'On-site emergency response in as little as 2 hours.',
        medium: 'ESP mobilizes equipment and crews to your site in as little as 2 hours after an emergency call.',
        large: 'When disaster strikes, every hour counts. ESP\'s 2-hour emergency response capability gets power, climate control, and technicians on-site fast, minimizing downtime and damage.',
        overlay: 'Restoration jobs, storm damage, and equipment failures don\'t wait for business hours. ESP\'s 2-hour emergency response network of generators, climate equipment, and licensed technicians is staged for rapid deployment, so your site is never left without power, cooling, or support when it matters most.',
      },
      tags: ['emergency', 'power'],
      targetRoles: ['restoration', 'insurance', 'government'],
    },
    {
      id: 'o2',
      title: '24/7/365 Availability',
      cardType: 'outcome',
      icon: 'clock',
      iconType: 'lucide',
      stat: '24/7/365',
      description: {
        small: 'Around-the-clock support, every day of the year.',
        medium: 'ESP\'s team is staffed and ready 24/7/365, including holidays and weekends.',
        large: 'Equipment failures and emergencies don\'t respect a schedule. ESP\'s dispatch and field teams are available 24 hours a day, 7 days a week, 365 days a year to keep your worksite running.',
        overlay: 'A worksite emergency at 2am on a holiday weekend is still an emergency. ESP staffs dispatch, technicians, and equipment logistics around the clock so a call placed any time of day or night gets the same rapid, professional response.',
      },
      tags: ['emergency', 'staffing'],
      targetRoles: ['restoration', 'construction', 'healthcare', 'government'],
    },
    {
      id: 'o3',
      title: 'One Call, Full Solution',
      cardType: 'outcome',
      icon: 'phone-call',
      iconType: 'lucide',
      stat: 'One Call',
      description: {
        small: 'Power, climate, equipment, and staffing from a single partner.',
        medium: 'Skip the vendor juggling. ESP coordinates power, climate control, equipment, and workforce from one call.',
        large: 'ESP consolidates power generation, climate control, heavy equipment, site support, and skilled labor under a single point of contact, so project managers stop chasing multiple vendors during critical timelines.',
        overlay: 'Coordinating separate vendors for generators, chillers, lighting, and labor wastes time you don\'t have during an emergency or tight build schedule. ESP\'s single-source model means one call sets the entire worksite solution in motion, from equipment delivery to licensed technicians on-site.',
      },
      tags: ['equipment', 'staffing'],
      targetRoles: ['construction', 'property-manager', 'industrial'],
    },
    {
      id: 'o4',
      title: 'Trusted Across 9+ Industries',
      cardType: 'outcome',
      icon: 'layout-grid',
      iconType: 'lucide',
      stat: '9+',
      description: {
        small: 'Serving restoration, construction, healthcare, and more.',
        medium: 'ESP supports restoration, construction, healthcare, government, retail, and event clients nationwide.',
        large: 'From hospitals to disaster restoration sites to large-scale events, ESP\'s equipment and crews flex to the demands of more than nine distinct industries without sacrificing response speed or quality.',
        overlay: 'No two worksites are alike. ESP\'s breadth across restoration, construction, healthcare, municipal, industrial, retail, and hospitality clients means the team understands the regulatory, safety, and logistical needs unique to each industry it serves.',
      },
      tags: ['emergency', 'equipment'],
      targetRoles: ['healthcare', 'government', 'events', 'industrial'],
    },
    {
      id: 'o5',
      title: 'Top-Rated Resource Partner',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: '#1',
      description: {
        small: '"ESP has proven to be our top resource partner."',
        medium: 'Clients consistently rank ESP as their most reliable equipment and staffing resource partner.',
        large: 'Restoration and construction partners cite ESP\'s outstanding customer service and dependability, with one client noting ESP "has proven to be CRC\'s top resource partner."',
        overlay: 'Reliability builds trust over time. ESP\'s long-standing partnerships with restoration companies, contractors, and facility teams are built on consistent, dependable execution job after job, earning ESP a reputation as the first call when a worksite needs support.',
      },
      tags: ['emergency', 'staffing'],
      targetRoles: ['restoration', 'construction', 'property-manager'],
    },
    {
      id: 'o6',
      title: 'Licensed, Field-Ready Crews',
      cardType: 'outcome',
      icon: 'hard-hat',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: 'Every job staffed with licensed technicians and operators.',
        medium: 'ESP fields project managers, licensed technicians, equipment operators, and health & safety officers on every deployment.',
        large: 'ESP doesn\'t just deliver equipment, it delivers the people to run it safely. Every deployment can include project managers, licensed technicians, equipment operators, and dedicated health & safety officers.',
        overlay: 'Equipment is only as effective as the people operating it. ESP pairs every rental and emergency deployment with the right mix of project managers, licensed technicians, certified equipment operators, and health & safety officers, ensuring the job gets done safely and correctly the first time.',
      },
      tags: ['staffing', 'equipment'],
      targetRoles: ['industrial', 'government', 'healthcare'],
    },
    {
      id: 'o7',
      title: '100% Independently Owned',
      cardType: 'outcome',
      icon: 'crown',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: 'No private equity. Decisions made in the field, not by a board.',
        medium: 'ESP is 100% independently owned, so dispatch and equipment decisions move at field speed.',
        large: 'Unlike PE-backed competitors, ESP is 100% independently owned. That means no layers of approval between a client\'s call and a truck rolling out, just a team empowered to say yes and move.',
        overlay: 'Private equity ownership often means slower decisions and margin-driven equipment allocation. ESP\'s independent ownership keeps the company agile: the same team that answers the emergency line can authorize the deployment, without waiting on corporate sign-off.',
      },
      tags: ['emergency', 'staffing'],
      targetRoles: ['restoration', 'construction', 'property-manager', 'government'],
    },
    {
      id: 'o8',
      title: 'Built for Category-5 Response',
      cardType: 'outcome',
      icon: 'cloud-rain',
      iconType: 'lucide',
      stat: '4x',
      description: {
        small: 'Operations quadrupled during Hurricanes Laura and Sally.',
        medium: 'ESP scaled 4x to respond to Hurricanes Laura and Sally, then again for the Texas winter freeze.',
        large: 'When Hurricanes Laura and Sally hit, ESP quadrupled its operations to meet demand. The team scaled again during the historic Texas freeze, proving it can surge capacity exactly when clients need it most.',
        overlay: 'Storm response separates real worksite partners from fair-weather vendors. ESP has a track record of scaling fast under real disaster conditions: quadrupling operations for back-to-back hurricanes and again during the Texas freeze, without losing responsiveness to non-disaster clients.',
      },
      tags: ['emergency', 'power'],
      targetRoles: ['restoration', 'insurance', 'government'],
    },
    {
      id: 'o9',
      title: 'Four Regional Hubs, Nationwide Reach',
      cardType: 'outcome',
      icon: 'map-pin',
      iconType: 'lucide',
      stat: '4',
      description: {
        small: 'Denver, Fort Worth, Moss Point, and Baytown.',
        medium: 'ESP operates from four regional hubs: Denver CO, Fort Worth TX, Moss Point MS, and Baytown TX.',
        large: 'With locations in Denver, Fort Worth, Moss Point, and Baytown, ESP positions equipment and crews close to the industries and disaster corridors that need them most.',
        overlay: 'Regional presence shortens response time. ESP\'s four hubs, Denver CO, Fort Worth TX, Moss Point MS, and Baytown TX, were built out as the company grew from a single-location operation, each one added to close a gap in coverage for restoration, industrial, and energy clients.',
      },
      tags: ['emergency', 'equipment'],
      targetRoles: ['industrial', 'government', 'construction'],
    },

    // ── Learn (9) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Disaster Recovery Equipment Checklist',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'The equipment every restoration team should have on call.',
        medium: 'A practical checklist of power, climate, and extraction equipment for disaster recovery jobs.',
        large: 'This guide walks restoration and remediation teams through the generators, dehumidifiers, air movers, and extraction equipment needed to respond fast and protect a damaged site.',
        overlay: 'When water, fire, or storm damage hits, the right equipment mix determines how fast a site stabilizes. This checklist covers generators, chillers, dehumidification units, air scrubbers, and extraction equipment so restoration teams know exactly what to request on the first call.',
      },
      tags: ['emergency', 'climate'],
      targetRoles: ['restoration', 'insurance'],
    },
    {
      id: 'l2',
      title: 'Powering a Job Site: A Field Guide',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'zap',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'How to size and plan generator power for any site.',
        medium: 'Learn how ESP helps contractors size generators and plan fueling logistics for active job sites.',
        large: 'This field guide covers load calculations, generator sizing, and fueling logistics so construction teams avoid power gaps that stall a project timeline.',
        overlay: 'Undersized power is one of the most common causes of job site delays. This guide breaks down how ESP works with contractors to calculate load requirements, select the right generator capacity, and plan ongoing fueling service so power is never the bottleneck.',
      },
      tags: ['power'],
      targetRoles: ['construction', 'industrial'],
    },
    {
      id: 'l3',
      title: 'Inside a 2-Hour Emergency Deployment',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Watch how ESP mobilizes equipment after the call comes in.',
        medium: 'A behind-the-scenes look at how ESP dispatches equipment and crews within hours of an emergency call.',
        large: 'This video follows ESP\'s dispatch and field teams from the moment an emergency call comes in through equipment delivery and technician setup on-site.',
        overlay: 'Speed under pressure is ESP\'s core capability. This video shows the dispatch process, equipment staging, and technician deployment that makes a 2-hour emergency response possible, from the initial call to power restored on-site.',
      },
      tags: ['emergency', 'power'],
      targetRoles: ['restoration', 'government', 'healthcare'],
    },
    {
      id: 'l4',
      title: 'Climate Control for Sensitive Sites',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'thermometer',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Temperature and humidity control for healthcare and labs.',
        medium: 'Webinar on deploying temporary climate control for healthcare facilities and other sensitive environments.',
        large: 'This recorded webinar covers how ESP plans temporary AC, chiller, and dehumidification solutions for healthcare facilities, labs, and other environments with strict climate requirements.',
        overlay: 'Healthcare facilities and labs can\'t tolerate uncontrolled temperature or humidity swings during construction, renovation, or emergencies. This webinar covers ESP\'s approach to temporary climate control planning, equipment selection, and monitoring for sensitive environments.',
      },
      tags: ['climate'],
      targetRoles: ['healthcare', 'industrial'],
    },
    {
      id: 'l5',
      title: 'Planning Equipment for Large Events',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'globe',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Power, lighting, and climate planning for venues.',
        medium: 'A practical resource for event venues and hospitality teams planning power and climate needs.',
        large: 'This resource covers how event venues work with ESP to plan generators, lighting, and climate control well ahead of an event date, avoiding last-minute scrambles.',
        overlay: 'Large events have zero tolerance for power or climate failures mid-event. This resource walks event and hospitality teams through advance planning for generators, area lighting, and climate control, including backup contingencies for multi-day events.',
      },
      tags: ['power', 'site-support'],
      targetRoles: ['events'],
    },
    {
      id: 'l6',
      title: 'The ESP Values Behind Every Deployment',
      cardType: 'learn',
      mediaType: 'podcast',
      icon: 'headphones',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Loyalty, integrity, dedication, and teamwork in the field.',
        medium: 'ESP leadership discusses the core values that shape every emergency response and rental engagement.',
        large: 'In this conversation, ESP leadership talks through how loyalty, integrity, dedication, and teamwork show up in day-to-day field operations, from dispatch to technician conduct on-site.',
        overlay: 'Values mean little until they show up under pressure. This conversation with ESP leadership explores how loyalty, integrity, dedication, and teamwork translate into faster dispatch decisions, honest equipment recommendations, and field crews that show up and follow through.',
      },
      tags: ['staffing', 'emergency'],
      targetRoles: ['property-manager', 'government'],
    },
    {
      id: 'l7',
      title: 'From One Truck to Four Regions: The ESP Story',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'history',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/about-us/',
      description: {
        small: 'How a one-man operation became a national worksite partner.',
        medium: 'ESP\'s growth from a single founder in 2019 to four regional hubs today.',
        large: 'Founded in 2019 as a one-man operation, ESP pivoted into PPE sourcing during the pandemic, quadrupled operations during Hurricanes Laura and Sally, and has since opened locations in Moss Point and Fort Worth.',
        overlay: 'ESP started in 2019 as a single founder with an agile business model. The company pivoted into PPE sourcing and sanitizing services in 2020, then quadrupled its operations responding to Hurricanes Laura and Sally and the Texas freeze. By 2022 it had opened a Moss Point, Mississippi location and built out back-office and sales functions; by 2024 it added a Dallas/Fort Worth location and brought on a CFO and COO. Today it remains 100% independently owned.',
      },
      tags: ['emergency', 'staffing'],
      targetRoles: ['restoration', 'construction', 'property-manager', 'government', 'industrial'],
    },
    {
      id: 'l8',
      title: 'Contingency Planning 101 for Facility Teams',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/worksite-solutions/',
      description: {
        small: 'Build an emergency preparedness plan before you need one.',
        medium: 'A whitepaper on building a customized contingency plan for power, staffing, and equipment failures.',
        large: 'This whitepaper walks facility and operations teams through building a contingency plan: backup power thresholds, pre-approved vendor lists, staffing escalation paths, and communication protocols for when something goes wrong.',
        overlay: 'The best emergency response is the one you planned before the emergency happened. This whitepaper covers ESP\'s approach to contingency planning: identifying single points of failure, setting backup power and climate thresholds, pre-clearing vendor and equipment approvals, and building a staffing escalation path so a facility team already knows who to call and what happens next.',
      },
      tags: ['staffing', 'emergency'],
      targetRoles: ['healthcare', 'government', 'property-manager', 'industrial'],
    },
    {
      id: 'l9',
      title: 'Choosing the Right Generator Size for Your Site',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'battery-charging',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/equipment-rental/power-generation/',
      description: {
        small: 'From 15kW portable units to 2-megawatt industrial power.',
        medium: 'ESP\'s generator fleet spans 15kW to 2 megawatts. Here\'s how to size the right unit for your site.',
        large: 'This guide breaks down ESP\'s generator range, from 15kW portable units suited for small job sites to 2-megawatt industrial generators for large facilities, and how to calculate which capacity a given site actually needs.',
        overlay: 'Oversizing a generator wastes fuel and rental spend; undersizing one risks a site going dark mid-project. ESP\'s fleet spans 15kW portable units to 2-megawatt industrial generators, and this guide walks through load calculation basics so contractors and facility managers can request the right capacity the first time.',
      },
      tags: ['power'],
      targetRoles: ['construction', 'industrial', 'healthcare'],
    },

    // ── Solutions (11) ─────────────────────────────────
    {
      id: 's1',
      title: 'Power Generation & Fueling',
      cardType: 'solution',
      icon: 'zap',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Generators from 15kW to 2 megawatts, plus fueling services.',
        medium: 'Generator rentals spanning 15kW portable units to 2-megawatt industrial capacity, plus ongoing fueling service.',
        large: 'ESP supplies generators ranging from 15kW portable units to 2-megawatt industrial capacity, paired with scheduled fueling service so job sites and emergency deployments never lose power.',
        overlay: 'Whether it\'s a single-day event or a months-long restoration project, ESP\'s power generation solution scales to match, spanning 15kW portable units to 2-megawatt industrial generators. The team handles load assessment, generator selection, delivery, and recurring fueling service, removing the guesswork from keeping a site powered.',
      },
      tags: ['power'],
      targetRoles: ['restoration', 'construction', 'events', 'industrial'],
    },
    {
      id: 's2',
      title: 'Climate Control Solutions',
      cardType: 'solution',
      icon: 'thermometer',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'AC, chillers, air movers, and dehumidification on demand.',
        medium: 'A full fleet of climate equipment including ACs, chillers, air movers, scrubbers, and temporary heating.',
        large: 'ESP\'s climate control fleet covers temporary AC, chillers, air movers, air scrubbers, dehumidification units, and temporary heating, deployed individually or as a complete site solution.',
        overlay: 'Temperature and humidity control can make or break a restoration timeline, a healthcare environment, or a construction schedule. ESP\'s climate equipment fleet, backed by licensed technicians, is sized and deployed to match the specific demands of your site.',
      },
      tags: ['climate'],
      targetRoles: ['restoration', 'healthcare', 'construction'],
    },
    {
      id: 's3',
      title: 'Lighting Solutions',
      cardType: 'solution',
      icon: 'lightbulb',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/equipment-rental/lighting/',
      description: {
        small: 'Compact mobile towers and high-capacity industrial lighting.',
        medium: 'Portable light towers for tight sites plus high-capacity industrial lighting for large jobs, with custom emergency lighting setups.',
        large: 'ESP\'s lighting fleet covers compact, portable light towers for smaller sites, high-capacity industrial units for large jobs, and custom emergency lighting setups deployed alongside power and staffing.',
        overlay: 'A worksite that goes dark stops working. ESP offers compact, portable light towers for tight or mobile sites, high-capacity industrial units for large-scale jobs, and custom emergency lighting configurations, all delivered and serviced through the same logistics network as ESP\'s power and equipment rentals.',
      },
      tags: ['equipment', 'site-support'],
      targetRoles: ['construction', 'events', 'industrial', 'government'],
    },
    {
      id: 's3b',
      title: 'Lifts & Heavy Equipment',
      cardType: 'solution',
      icon: 'truck',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/equipment-rental/lifts-heavy-equipment/',
      description: {
        small: 'Boom lifts, scissor lifts, excavators, and telehandlers.',
        medium: 'Aerial lifts, heavy machinery, and material handling equipment, delivered with licensed operators.',
        large: 'ESP\'s heavy equipment fleet includes boom lifts and scissor lifts for elevated work, excavators, bulldozers, loaders, and backhoes for site work, plus forklifts and telehandlers for material handling, all available with licensed operators.',
        overlay: 'Renting the machine is only half the job. ESP pairs boom lifts, scissor lifts, excavators, bulldozers, loaders, backhoes, forklifts, and telehandlers with licensed equipment operators, so contractors get working capacity, not just idle iron sitting on-site.',
      },
      tags: ['equipment'],
      targetRoles: ['construction', 'industrial'],
    },
    {
      id: 's3c',
      title: 'Temporary Fencing Solutions',
      cardType: 'solution',
      icon: 'shield',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/equipment-rental/fencing-solutions/',
      description: {
        small: 'Construction, event, security, and abatement fencing.',
        medium: 'Fast-setup fencing for construction sites, events, security perimeters, and hazardous-material abatement projects.',
        large: 'ESP installs and maintains construction fencing to secure job sites, event fencing for crowd management, high-strength security fencing, and specialized abatement fencing for asbestos or mold remediation, plus school and temporary-site fencing.',
        overlay: 'Fencing needs vary as much as the sites they protect. ESP offers construction fencing to prevent unauthorized site access, event fencing for crowd control at festivals and gatherings, high-strength security fencing, abatement fencing for hazardous remediation work, and customizable school and temporary-site fencing, all with delivery, installation, and removal included.',
      },
      tags: ['equipment', 'site-support'],
      targetRoles: ['construction', 'events', 'government'],
    },
    {
      id: 's4',
      title: '24/7 Emergency Response',
      cardType: 'solution',
      icon: 'alert-triangle',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Rapid mobilization when disaster strikes.',
        medium: 'A standing emergency response capability that mobilizes equipment and crews within hours of a call.',
        large: 'ESP\'s emergency response service is built for restoration companies, insurers, and facility teams that need power, climate control, and skilled labor on-site fast, day or night.',
        overlay: 'Storm damage, fire, flooding, and equipment failures all demand the same thing: speed. ESP\'s emergency response solution combines pre-staged equipment, a 24/7 dispatch team, and licensed technicians to get a site stabilized and operational as quickly as possible.',
      },
      tags: ['emergency'],
      targetRoles: ['restoration', 'insurance', 'government'],
    },
    {
      id: 's5',
      title: 'Workforce & Staffing Solutions',
      cardType: 'solution',
      icon: 'users',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/',
      description: {
        small: 'Project managers, technicians, and safety officers.',
        medium: 'On-demand staffing including project managers, licensed technicians, equipment operators, and safety officers.',
        large: 'ESP fields qualified project managers, licensed technicians, certified equipment operators, and dedicated health & safety officers to support deployments of any scale.',
        overlay: 'Equipment without the right people is just inventory. ESP\'s workforce solutions pair every deployment with the appropriate mix of project managers, licensed technicians, equipment operators, and health & safety officers, scaled to the size and complexity of the job.',
      },
      tags: ['staffing'],
      targetRoles: ['industrial', 'government', 'healthcare', 'property-manager'],
    },
    {
      id: 's6',
      title: 'Potable Water & Extraction',
      cardType: 'solution',
      icon: 'droplets',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/equipment-rental/water-supply-solutions/',
      description: {
        small: 'Potable water tanks, trailers, and extraction pumps.',
        medium: 'Potable water tanks, water trailers, and transfer systems, plus motorized pumps and extraction gear for water damage.',
        large: 'ESP supplies potable water tanks, water trailers, and transfer systems for sites without reliable water access, alongside motorized pumps and portable extraction equipment for flood and water-damage response.',
        overlay: 'Water logistics run in two directions on a worksite: getting clean water in, and getting damaging water out. ESP handles both, with potable water tanks, trailers, and transfer systems for sites and events, and motorized pumps and portable extraction gear for restoration and flood response.',
      },
      tags: ['water'],
      targetRoles: ['restoration', 'government', 'events'],
    },
    {
      id: 's7b',
      title: 'Sanitation Solutions',
      cardType: 'solution',
      icon: 'boxes',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/equipment-rental/sanitation/',
      description: {
        small: 'Portable restrooms, handwashing stations, and decon units.',
        medium: 'Portable restrooms, handwashing stations, restroom trailers, and decontamination equipment for job sites and events.',
        large: 'ESP\'s sanitation fleet includes portable restrooms, handwashing stations with soap and sanitizer, upgraded restroom trailers for larger projects, and specialized decontamination equipment for hazardous-material work.',
        overlay: 'Sanitation compliance is non-negotiable on any staffed job site. ESP provides portable restrooms and handwashing stations for construction sites and events, restroom trailers for larger or longer-duration projects, and decontamination equipment for hazardous materials and industrial cleaning, all maintained on-site for the project duration.',
      },
      tags: ['water', 'site-support'],
      targetRoles: ['construction', 'events', 'industrial', 'healthcare'],
    },
    {
      id: 's7c',
      title: 'Trailers, Containers & Vehicles',
      cardType: 'solution',
      icon: 'container',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/equipment-rental/trailers-containers-vehicles/',
      description: {
        small: 'Mobile offices, dump trailers, flatbeds, and transport vehicles.',
        medium: 'Mobile office trailers, dump and utility trailers, flatbeds for heavy equipment, and vehicles for crew and material transport.',
        large: 'ESP supplies mobile office trailers for on-site staff, dump trailers for construction debris, utility and flatbed trailers for hauling equipment and materials, and trucks and vans to move workers and supplies to and from the job site.',
        overlay: 'Every worksite needs somewhere to run operations and something to move equipment with. ESP provides mobile office trailers for meetings and staff accommodations, dump trailers for debris removal, versatile utility trailers, flatbeds for heavy equipment transport, and trucks and vans for crew and material logistics.',
      },
      tags: ['equipment', 'site-support'],
      targetRoles: ['construction', 'property-manager', 'industrial'],
    },
    {
      id: 's7d',
      title: 'Contingency Planning & Consulting',
      cardType: 'solution',
      icon: 'clipboard-list',
      iconType: 'lucide',
      url: 'https://expeditedpartners.com/worksite-solutions/',
      description: {
        small: 'Project management and emergency preparedness planning.',
        medium: 'Project management, technical response, and customized contingency planning to keep operations running before something breaks.',
        large: 'ESP\'s consulting services cover project management from start to finish, technical response using site-inspection technology and data collection, and customized contingency planning so clients have an emergency strategy in place before they need it.',
        overlay: 'Not every engagement starts with an emergency. ESP\'s project management and consulting team draws on industry experience to plan projects, oversee execution, and build customized contingency strategies, plus technical response services using inspection technology and data collection to track site progress in real time.',
      },
      tags: ['staffing', 'emergency'],
      targetRoles: ['government', 'healthcare', 'property-manager', 'industrial'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
