// Explorer Config — Formation at The Star
// Executive co-working & event space at The Star in Frisco, TX (Dallas
// Cowboys World Headquarters). Brand: warm platinum gray + Cowboys navy.
// Voice: aspirational, performance-oriented, "Work the Cowboys Way."

import type { ExplorerConfig, ThemeColors } from '../types';

const FORMATION_DARK: ThemeColors = {
  bg: '#081317',
  bgGradient: 'linear-gradient(135deg, #041E42 0%, #020F22 55%, #010816 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#B5C0C4',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.78)',
  text3: 'rgba(255,255,255,0.52)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(134,147,151,0.22)',
};

const FORMATION_LIGHT: ThemeColors = {
  bg: '#F4F5F7',
  bgGradient: 'linear-gradient(180deg, #F4F5F7 0%, #EDEFF2 100%)',
  surface: 'rgba(255,255,255,0.88)',
  surfaceHover: 'rgba(255,255,255,0.96)',
  border: 'rgba(4,30,66,0.10)',
  borderFocus: '#041E42',
  text1: '#041E42',
  text2: 'rgba(4,30,66,0.68)',
  text3: 'rgba(4,30,66,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#041E42',
  inputPlaceholder: 'rgba(4,30,66,0.38)',
  logoText: '#041E42',
  focusRing: 'rgba(4,30,66,0.14)',
};

export const FORMATION_CONFIG: ExplorerConfig = {
  id: 'formation',
  name: 'Formation Explorer',
  version: 1,
  createdAt: '2026-05-26T00:00:00.000Z',
  updatedAt: '2026-05-26T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/formation-logo-reverse.png',
      light: '/brand/assets/formation-logo.png',
    },
    // FORMATION wordmark — 502×130 aspect (~3.86:1). Bumped above the
    // 28px default so the letterforms read at a comfortable size.
    logoHeight: 36,
    icon: '/brand/assets/formation-icon.png',
    colors: {
      // Brand palette derived from Formation intake: warm platinum gray +
      // Dallas Cowboys navy. Supplemented with darker navy variants for
      // depth and a warm gray-brown for gradient variety.
      primary: '#869397',   // platinum gray — main accent
      secondary: '#041E42', // Cowboys navy — endpoint
      teal: '#B5C0C4',      // lighter platinum for highlights
      blue: '#041E42',
      deepBlue: '#031633',
      navy: '#112A32',
      midnight: '#09171B',
      plum: '#5C6166',      // warm gray-brown
      bgDark: '#09171B',
      dark: FORMATION_DARK,
      light: FORMATION_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(134,147,151,0.16)',  // platinum
      orb2: 'rgba(4,30,66,0.20)',      // Cowboys navy
      orb3: 'rgba(92,97,102,0.12)',    // warm anchor
    },
    ctaGradient: 'linear-gradient(135deg, #869397 0%, #041E42 100%)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #B5C0C4 0%, #869397 100%)',
    // Subtle per-role glows using the warm-gray / navy / warm-anchor triad.
    roleBackgrounds: {
      'executive': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(4,30,66,0.32) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(92,97,102,0.18) 0%, transparent 55%)',
      'founder': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(134,147,151,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(4,30,66,0.18) 0%, transparent 55%)',
      'sales': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(181,192,196,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(4,30,66,0.16) 0%, transparent 55%)',
      'remote': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(134,147,151,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(92,97,102,0.16) 0%, transparent 55%)',
      'event-planner': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(4,30,66,0.28) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(181,192,196,0.16) 0%, transparent 55%)',
      'team-lead': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(134,147,151,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(4,30,66,0.16) 0%, transparent 55%)',
      'consultant': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(181,192,196,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(92,97,102,0.14) 0%, transparent 55%)',
      'visiting': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(92,97,102,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(134,147,151,0.14) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Welcome to Formation',
    formSubtitle: 'Tell us a bit about yourself to get started.',
    scanLabel: 'Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Formation processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Work Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Company name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Work the',
      gradientWord: 'Cowboys Way.',
      subtitle: 'Executive workspace for the ambitious — steps from Dallas Cowboys World Headquarters at The Star in Frisco.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes you?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'executive', label: 'Executive / C-Suite', icon: 'briefcase', iconType: 'lucide' },
        { value: 'founder', label: 'Founder / Entrepreneur', icon: 'rocket', iconType: 'lucide' },
        { value: 'sales', label: 'Sales / Business Dev', icon: 'trending-up', iconType: 'lucide' },
        { value: 'remote', label: 'Remote Professional', icon: 'monitor', iconType: 'lucide' },
        { value: 'event-planner', label: 'Event Planner', icon: 'calendar-days', iconType: 'lucide' },
        { value: 'team-lead', label: 'Team Lead / Manager', icon: 'users', iconType: 'lucide' },
        { value: 'consultant', label: 'Consultant / Freelancer', icon: 'cog', iconType: 'lucide' },
        { value: 'visiting', label: 'Just Visiting', icon: 'map-pin', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you here to explore?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'private-office', label: 'Private Office', icon: 'lock', iconType: 'lucide' },
        { value: 'day-pass', label: 'Day Pass / Drop-In', icon: 'calendar', iconType: 'lucide' },
        { value: 'conference-rooms', label: 'Conference Rooms', icon: 'monitor', iconType: 'lucide' },
        { value: 'event-space', label: 'Event Hosting', icon: 'sparkles', iconType: 'lucide' },
        { value: 'networking', label: 'Networking & Events', icon: 'handshake', iconType: 'lucide' },
        { value: 'amenities', label: 'Member Amenities', icon: 'award', iconType: 'lucide' },
        { value: 'catering', label: 'Catering & Lunch', icon: 'gift', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Tour',
      subtitle: 'Memberships, spaces, and experiences tailored to how you work.',
      tabs: [
        { id: 'outcomes', label: 'Why Formation', icon: 'award' },
        {
          id: 'learn',
          label: 'Discover',
          icon: 'book-open',
          filters: [
            { label: 'All', value: 'all' },
            { label: 'Video', value: 'video' },
            { label: 'Blog', value: 'blog' },
            { label: 'PDF', value: 'pdf' },
            { label: 'Website', value: 'website' },
          ],
        },
        { id: 'solutions', label: 'Memberships', icon: 'building-2' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review your picks and a Formation membership advisor will follow up.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Explore Everything',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'A Formation membership advisor will be in touch shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes / Why Formation (7) ──────────────────
    {
      id: 'o1',
      title: 'Best in DFW Co-Working',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: 'Multi-Year',
      description: {
        small: 'Multi-year "Best in DFW Co-Working Space" winner.',
        medium: 'Recognized as Best in DFW Co-Working Space — a multi-year award winner serving the Dallas-Fort Worth executive community.',
        large: 'Formation has been recognized as the Best in DFW Co-Working Space for multiple consecutive years — the workspace executives and ambitious professionals choose when image, location, and execution all matter.',
        overlay: 'Multi-year "Best in DFW Co-Working Space" award winner. Formation is the workspace DFW executives, founders, and consultants choose when image, location, and execution all matter — voted top of category year after year.',
      },
      tags: ['private-office', 'amenities'],
      targetRoles: ['executive', 'founder', 'team-lead'],
    },
    {
      id: 'o2',
      title: 'Steps from Cowboys HQ',
      cardType: 'outcome',
      icon: 'map-pin',
      iconType: 'lucide',
      stat: 'The Star',
      description: {
        small: 'Located at The Star in Frisco, steps from Cowboys HQ.',
        medium: 'Located inside The Star in Frisco — steps from the Dallas Cowboys World Headquarters and entertainment complex.',
        large: 'Formation sits at the heart of The Star in Frisco — the 91-acre Dallas Cowboys World Headquarters and mixed-use entertainment complex. The address itself opens doors.',
        overlay: '5 Cowboys Way, Suite 300. Formation occupies the executive floor at The Star in Frisco — the 91-acre Dallas Cowboys World Headquarters and mixed-use complex. An address that opens doors before a meeting even starts.',
      },
      tags: ['private-office', 'event-space'],
      targetRoles: ['executive', 'founder', 'sales', 'visiting'],
    },
    {
      id: 'o3',
      title: '30+ Restaurants & Shops',
      cardType: 'outcome',
      icon: 'gift',
      iconType: 'lucide',
      stat: '30+',
      description: {
        small: '30+ on-site restaurants and shops at The Star.',
        medium: '30+ restaurants and shops at The Star — lunch, client dinners, and meetings happen without leaving the campus.',
        large: 'With 30+ restaurants, cafés, and shops on the same campus, members never need to leave The Star for a lunch, a coffee meeting, or a client dinner — everything happens within a 5-minute walk.',
        overlay: 'Lunch meetings, client coffees, after-work drinks, gifts to send back — The Star\'s 30+ on-site restaurants and shops mean members never need to leave the campus. Everything from quick takeout to white-tablecloth client dinners is a five-minute walk away.',
      },
      tags: ['catering', 'amenities', 'networking'],
      targetRoles: ['executive', 'sales', 'remote', 'consultant'],
    },
    {
      id: 'o4',
      title: 'Event Space for 40 Guests',
      cardType: 'outcome',
      icon: 'sparkles',
      iconType: 'lucide',
      stat: '40',
      description: {
        small: 'Branded event space hosting up to 40 guests.',
        medium: 'Branded event space and conference rooms host up to 40 guests — corporate gatherings, training, client briefings.',
        large: 'Formation\'s event space and configurable conference rooms host up to 40 guests — perfect for client briefings, training seminars, board meetings, launch events, and curated networking nights.',
        overlay: 'Need a space that elevates your brand for the day? Formation\'s event space and configurable conference rooms host up to 40 guests with full A/V, catering coordination, and an address your guests will remember. Available to members and as a standalone booking.',
      },
      tags: ['event-space', 'conference-rooms'],
      targetRoles: ['event-planner', 'executive', 'team-lead', 'sales'],
    },
    {
      id: 'o5',
      title: 'Member Events by Cowboys Staff',
      cardType: 'outcome',
      icon: 'star',
      iconType: 'lucide',
      stat: 'Curated',
      description: {
        small: 'Member-only events curated by Cowboys staff.',
        medium: 'Exclusive member events curated by Dallas Cowboys staff — networking, speakers, and on-campus experiences.',
        large: 'Members get access to a year-round calendar of events curated by Dallas Cowboys staff — speaker series, networking nights, on-campus experiences, and behind-the-scenes access you can\'t get anywhere else.',
        overlay: 'Members-only access to an ongoing calendar of events curated by Dallas Cowboys staff: executive speaker series, networking nights, on-campus experiences, and behind-the-scenes access at The Star. The kind of access that makes membership pay for itself.',
      },
      tags: ['networking', 'amenities'],
      targetRoles: ['executive', 'founder', 'team-lead', 'sales'],
    },
    {
      id: 'o6',
      title: 'Private Offices for 1–5',
      cardType: 'outcome',
      icon: 'lock',
      iconType: 'lucide',
      stat: '1–5',
      description: {
        small: 'Private offices configured for 1 to 5 occupants.',
        medium: 'Furnished private offices for 1 to 5 occupants — your team, your name on the door, on the executive floor.',
        large: 'Choose from furnished private offices configured for 1 to 5 occupants — full-time space for your team, with your name on the door and full executive-floor privileges across the building.',
        overlay: 'Bring your whole team. Formation\'s furnished private offices accommodate 1 to 5 occupants, each with your name on the door, secure 24/7 access, and full member privileges across conference rooms, event space, and curated events.',
      },
      tags: ['private-office'],
      targetRoles: ['executive', 'founder', 'team-lead'],
    },
    {
      id: 'o7',
      title: 'Daily Coffee & Lunch Service',
      cardType: 'outcome',
      icon: 'flame',
      iconType: 'lucide',
      stat: 'Daily',
      description: {
        small: 'Daily coffee, lunch delivery, and catering on hand.',
        medium: 'Daily coffee service, lunch delivery, and on-call catering — fuel for executives who don\'t have time to leave the desk.',
        large: 'Daily coffee bar, lunch delivery, and on-call catering keep the workday moving — fuel for executives who don\'t have time to leave the desk between meetings.',
        overlay: 'A daily coffee bar in the lounge, lunch delivery from The Star\'s 30+ restaurants, and on-call catering for client meetings and events. Formation keeps the workday moving so members can stay focused on what actually moves the needle.',
      },
      tags: ['amenities', 'catering'],
      targetRoles: ['executive', 'remote', 'consultant'],
    },

    // ── Learn / Discover (8) ──────────────────────────
    {
      id: 'l1',
      title: 'A Day at Formation',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'See a typical day inside Formation at The Star.',
        medium: 'A walkthrough video of a typical day inside Formation — morning coffee through after-work networking.',
        large: 'Take a video walkthrough of a typical day at Formation: morning coffee in the lounge, a breakaway call from a private booth, a 12-person briefing in the boardroom, lunch from The Star, and an evening member event.',
        overlay: 'A short video walkthrough of a typical day at Formation: morning coffee in the lounge, a breakaway call from a private booth, a 12-person client briefing in the boardroom, lunch from one of The Star\'s 30+ restaurants, and an evening member event. About 90 seconds.',
      },
      tags: ['amenities', 'private-office', 'networking'],
      targetRoles: ['executive', 'founder', 'remote', 'visiting'],
    },
    {
      id: 'l2',
      title: 'Membership Tiers at a Glance',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'Compare every Formation membership in one PDF.',
        medium: 'A one-page PDF comparing every Formation membership — private office, dedicated desk, open workspace, day pass.',
        large: 'A one-page reference PDF comparing every Formation membership tier — private office, dedicated desk, open workspace, day pass, summer pass — across price, included hours, and amenities.',
        overlay: 'A one-page reference comparing every Formation membership — private office, dedicated desk, open workspace, day pass, monthly membership, summer pass. Side-by-side pricing, included conference room hours, guest passes, storage lockers, mailing privileges, and member event access. Designed to be screenshot-shared with your operations team.',
      },
      tags: ['private-office', 'day-pass'],
      targetRoles: ['executive', 'founder', 'remote', 'consultant'],
    },
    {
      id: 'l3',
      title: 'The Star Dining Guide',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'gift',
      iconType: 'lucide',
      url: 'https://www.thestarinfrisco.com/',
      description: {
        small: 'Where members eat, drink, and meet across The Star.',
        medium: 'A members\' guide to The Star\'s 30+ restaurants and cafés — what to pick for client lunches, quick takeout, and after-work drinks.',
        large: 'A curated members\' guide to The Star\'s 30+ restaurants, cafés, and bars — what to pick for client lunches, quick takeout, after-work drinks, and proper dinners. Walking times from the Formation entrance included.',
        overlay: 'The Star is one of the largest dining destinations in Frisco. This members\' guide ranks the 30+ restaurants, cafés, and bars by occasion: best for first-meeting client lunches, fastest takeout for working lunches, best craft cocktails for after work, and best private dining for closing dinners. Walking times from Formation\'s entrance included.',
      },
      tags: ['catering', 'amenities', 'networking'],
      targetRoles: ['executive', 'sales', 'founder', 'consultant'],
    },
    {
      id: 'l4',
      title: 'Event Space Gallery',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'image',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'See the event space, boardroom, and conference rooms.',
        medium: 'A photo tour of Formation\'s event space, executive boardroom, and configurable conference rooms.',
        large: 'A photo tour of Formation\'s event space and meeting rooms — the executive boardroom, configurable conference rooms, breakaway booths, and the main event floor configured for receptions, training, and dinners.',
        overlay: 'A photo tour of every bookable space at Formation: the executive boardroom (12 seats), the configurable mid-size conference rooms (6–8 seats), the breakaway booths for private calls, and the main event floor configured for receptions, training, and seated dinners up to 40 guests.',
      },
      tags: ['event-space', 'conference-rooms'],
      targetRoles: ['event-planner', 'executive', 'team-lead'],
    },
    {
      id: 'l5',
      title: 'The Cowboys Way: Brand Story',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'star',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'How Formation embodies the Cowboys winning tradition.',
        medium: 'How Formation was built to embody the Dallas Cowboys winning tradition — design, hospitality, and standards.',
        large: 'The brand story behind Formation: how the workspace was designed from the ground up to embody the Dallas Cowboys winning tradition — design, hospitality, performance standards, and the executive eye for detail.',
        overlay: 'The brand story behind Formation. How a workspace gets built from the ground up to embody the Dallas Cowboys winning tradition — design choices, hospitality standards, performance expectations, and the executive eye for detail that runs through everything from the boardroom finishes to the coffee program.',
      },
      tags: ['amenities', 'private-office'],
      targetRoles: ['executive', 'founder', 'visiting'],
    },
    {
      id: 'l6',
      title: 'Inside the Member Event Calendar',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'calendar-days',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'See what\'s on the member events calendar.',
        medium: 'Browse upcoming member-only events curated by Dallas Cowboys staff — speakers, networking, on-campus access.',
        large: 'Browse the upcoming member-only events curated by Dallas Cowboys staff: executive speaker series, networking happy hours, on-campus experiences, training sessions, and behind-the-scenes access at The Star.',
        overlay: 'Browse what\'s coming up on the member calendar: executive speaker series with industry leaders, monthly networking happy hours, on-campus experiences curated by Cowboys staff, training sessions, and behind-the-scenes access at The Star you cannot get anywhere else.',
      },
      tags: ['networking', 'amenities'],
      targetRoles: ['executive', 'founder', 'sales', 'team-lead'],
    },
    {
      id: 'l7',
      title: 'Booking Your First Event',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'calendar',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'A planner\'s guide to booking event space.',
        medium: 'A planner\'s guide to booking Formation\'s event space — capacity, A/V, catering, and lead times.',
        large: 'A planner\'s guide to booking event space at Formation: capacity by configuration, A/V and tech included, catering coordination, recommended lead times, and member vs. non-member pricing.',
        overlay: 'Everything an event planner needs to confidently book Formation: capacity by room and configuration, A/V and tech included by default, catering coordination through The Star, recommended lead times by event type, member vs. non-member pricing, and the standard contract terms. PDF, one page, designed to be forwarded.',
      },
      tags: ['event-space', 'conference-rooms'],
      targetRoles: ['event-planner', 'executive', 'team-lead'],
    },
    {
      id: 'l8',
      title: 'Schedule a Tour',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'map-pin',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'Book a 30-minute walkthrough of Formation.',
        medium: 'Book a 30-minute on-site walkthrough — see the offices, lounges, event space, and meet the membership team.',
        large: 'Book a 30-minute on-site walkthrough at 5 Cowboys Way, Suite 300. See the private offices, executive lounges, conference rooms, event space, and meet the Formation membership team in person.',
        overlay: 'Book a 30-minute walkthrough of Formation at The Star in Frisco. The tour covers the private office floor, the dedicated desk area, executive lounges, conference rooms, the event space, and finishes with the membership team to talk through which tier fits your work style. Free, no pressure, complimentary parking validated.',
      },
      tags: ['private-office', 'event-space', 'amenities'],
      targetRoles: ['executive', 'founder', 'visiting', 'team-lead'],
    },

    // ── Solutions / Memberships (7) ───────────────────
    {
      id: 's1',
      title: 'Private Office',
      cardType: 'solution',
      icon: 'lock',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'Your team, your name on the door, executive floor.',
        medium: 'Furnished private offices for 1 to 5 occupants with full member privileges across the building.',
        large: 'Furnished private offices configured for 1 to 5 occupants. Your team, your name on the door, 24/7 secure access, and full member privileges across conference rooms, event space, and curated events.',
        overlay: 'Formation\'s flagship membership. Furnished private offices configured for 1 to 5 occupants on the executive floor at The Star. Your name on the door, 24/7 secure access, mailing address, included conference room hours, member event access, guest passes, and storage lockers. The right answer for established teams that need a real headquarters with the address to match.',
      },
      tags: ['private-office'],
      targetRoles: ['executive', 'founder', 'team-lead'],
    },
    {
      id: 's2',
      title: 'Dedicated Desk',
      cardType: 'solution',
      icon: 'monitor',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'A reserved desk in the executive open workspace.',
        medium: 'A reserved desk in the open workspace — your spot, your setup, ready every morning.',
        large: 'A reserved desk in the executive open workspace — your spot, your setup, ready every morning. Includes mailing address, storage locker, conference room hours, and full member privileges.',
        overlay: 'A reserved seat in the executive open workspace, ready every morning with your monitor, chair, and setup exactly how you left it. Comes with the Formation mailing address, a storage locker, included conference room hours, and full member privileges across event space and curated events. Right for consultants, advisors, and remote executives who need a real home base in DFW.',
      },
      tags: ['private-office', 'amenities'],
      targetRoles: ['consultant', 'remote', 'sales', 'founder'],
    },
    {
      id: 's3',
      title: 'Open Workspace',
      cardType: 'solution',
      icon: 'monitor',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'Drop in and work from the executive lounge.',
        medium: 'Unreserved seating in the executive lounge and shared workspace — month-to-month flexibility.',
        large: 'Unreserved seating across the executive lounge and shared workspace. Month-to-month membership with full Wi-Fi, coffee, conference room access, and member event privileges.',
        overlay: 'Month-to-month membership with unreserved seating across the executive lounge, café, and shared workspace. Full Wi-Fi, coffee bar, included conference room hours, member event access. The right answer for solo executives, consultants, and traveling professionals who want the Formation address and amenities without committing to a dedicated seat.',
      },
      tags: ['day-pass', 'amenities'],
      targetRoles: ['remote', 'consultant', 'visiting'],
    },
    {
      id: 's4',
      title: 'Day Pass',
      cardType: 'solution',
      icon: 'calendar',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'A single-day pass to work from Formation.',
        medium: 'A single-day pass to work from the executive lounge, café, and shared workspace.',
        large: 'A one-day pass to work from Formation — executive lounge, café, shared workspace, Wi-Fi, and coffee bar. Ideal for in-town meetings or trial-runs before joining.',
        overlay: 'A single-day pass to work from Formation: executive lounge, café, shared workspace, Wi-Fi, coffee bar, and visitor access to The Star. The right answer for visiting executives with an in-town day of meetings, or for prospective members who want to try before they commit.',
      },
      tags: ['day-pass', 'amenities'],
      targetRoles: ['visiting', 'sales', 'consultant'],
    },
    {
      id: 's5',
      title: 'Summer Pass',
      cardType: 'solution',
      icon: 'lightbulb',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'Three-month pass perfect for interns and summer teams.',
        medium: 'A three-month membership perfect for interns, summer teams, and seasonal projects at The Star.',
        large: 'A three-month membership designed for interns, summer teams, and seasonal projects. Open workspace access, Wi-Fi, coffee, conference rooms, and member events for the full summer.',
        overlay: 'A purpose-built three-month membership for interns, summer associates, and seasonal project teams. Full open-workspace access, Wi-Fi, coffee, included conference room hours, and member event invitations for the duration of the summer. Discounted pricing for groups.',
      },
      tags: ['day-pass', 'amenities'],
      targetRoles: ['team-lead', 'remote', 'founder'],
    },
    {
      id: 's6',
      title: 'Event & Conference Space',
      cardType: 'solution',
      icon: 'sparkles',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'Book event space for up to 40 guests.',
        medium: 'Book Formation\'s branded event space and conference rooms for up to 40 guests — A/V and catering included.',
        large: 'Book Formation\'s branded event space and configurable conference rooms for up to 40 guests. Full A/V, catering coordination, and an address at The Star your guests will remember.',
        overlay: 'Book Formation\'s event space, executive boardroom, or configurable conference rooms for client briefings, training, board meetings, launch events, or curated networking nights. Up to 40 guests, full A/V, catering coordinated through The Star\'s 30+ restaurants, and an address that elevates every invitation. Available to members at preferred rates and as a standalone booking.',
      },
      tags: ['event-space', 'conference-rooms'],
      targetRoles: ['event-planner', 'executive', 'team-lead', 'sales'],
    },
    {
      id: 's7',
      title: 'Catering & Hospitality',
      cardType: 'solution',
      icon: 'gift',
      iconType: 'lucide',
      url: 'https://formationatthestar.com/',
      description: {
        small: 'On-call catering from The Star\'s 30+ restaurants.',
        medium: 'On-call catering coordinated through The Star\'s 30+ restaurants — meetings, events, and daily lunch.',
        large: 'On-call catering, daily lunch delivery, and event hospitality coordinated through The Star\'s 30+ on-site restaurants. From two-person client lunches to 40-guest receptions.',
        overlay: 'On-call catering for meetings and events, daily lunch delivery for members, and full event hospitality coordinated through The Star\'s 30+ restaurants. Two-person client lunches, 40-guest receptions, white-tablecloth dinners — Formation handles the coordination so you handle the meeting.',
      },
      tags: ['catering', 'amenities', 'event-space'],
      targetRoles: ['executive', 'event-planner', 'sales'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
