// Explorer Config: Fortune Tire
// Tire-brand kiosk for Fortune Tire USA. Fortune blue palette + Tire Advisor calculator.
// Flow: Role → Interests → Results.

import type { ExplorerConfig, ThemeColors } from '../types';

const FORTUNE_DARK: ThemeColors = {
  bg: '#0A1428',
  bgGradient: 'linear-gradient(135deg, #0A1F3D 0%, #060F1F 55%, #0A1428 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#3FAAE0',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(63,170,224,0.20)',
};

const FORTUNE_LIGHT: ThemeColors = {
  bg: '#F4F5F9',
  bgGradient: 'linear-gradient(180deg, #F4F5F9 0%, #EAF2FA 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#0067C0',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(0,103,192,0.12)',
};

export const FORTUNE_TIRE_CONFIG: ExplorerConfig = {
  id: 'fortune-tire',
  name: 'Fortune Tire Explorer',
  version: 1,
  createdAt: '2026-05-05T00:00:00.000Z',
  updatedAt: '2026-05-05T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/fortune-tire-logo-reverse.png',
      light: '/brand/assets/fortune-tire-logo.png',
    },
    invertLogoOnLight: true,
    icon: '/brand/assets/fortune-tire-icon.png',
    colors: {
      primary: '#3FAAE0',
      secondary: '#0067C0',
      teal: '#3FAAE0',
      blue: '#0067C0',
      deepBlue: '#003F87',
      navy: '#0A1F3D',
      midnight: '#060F1F',
      plum: '#5C3D7A',
      bgDark: '#0A1428',
      dark: FORTUNE_DARK,
      light: FORTUNE_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(0,103,192,0.18)',
      orb2: 'rgba(63,170,224,0.16)',
      orb3: 'rgba(0,63,135,0.14)',
    },
    ctaGradient: 'linear-gradient(135deg, #0067C0, #3FAAE0)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #3FAAE0, #0067C0)',
    gradientWordLight: 'linear-gradient(135deg, #003F87, #0067C0)',
    roleBackgrounds: {
      consumer: 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(63,170,224,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(0,103,192,0.10) 0%, transparent 55%)',
      dealer: 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,103,192,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(63,170,224,0.10) 0%, transparent 55%)',
      distributor: 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,63,135,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(63,170,224,0.10) 0%, transparent 55%)',
      fleet: 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(63,170,224,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(0,103,192,0.10) 0%, transparent 55%)',
      installer: 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,103,192,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 35% 15%, rgba(0,63,135,0.10) 0%, transparent 55%)',
      oem: 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,63,135,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 65% 15%, rgba(63,170,224,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'form',
    formTitle: 'Welcome to Fortune Tire',
    formSubtitle: 'Tell us a bit about you so we can tailor your tire journey.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Fortune Tire contacting you about products, programs, and dealer events.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@email.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company / Shop', type: 'text', placeholder: 'Company or shop name', required: false, halfWidth: false },
      { id: 'zip', label: 'ZIP Code', type: 'text', placeholder: '12345', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Expect More from',
      gradientWord: 'Your Tires.',
      subtitle: 'Discover Fortune Tire, engineered for peak performance, highest rated safety, and the longest miles on the road.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'How are you exploring Fortune Tire today?',
      subtitle: 'Select the option that best describes you.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'consumer', label: 'Driver', icon: 'user', iconType: 'lucide' },
        { value: 'dealer', label: 'Dealer / Retailer', icon: 'store', iconType: 'lucide' },
        { value: 'distributor', label: 'Distributor', icon: 'truck', iconType: 'lucide' },
        { value: 'fleet', label: 'Fleet Manager', icon: 'bus', iconType: 'lucide' },
        { value: 'installer', label: 'Installer / Shop', icon: 'wrench', iconType: 'lucide' },
        { value: 'oem', label: 'OEM Partner', icon: 'factory', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What kind of tires are you interested in?',
      subtitle: "Select all that apply, we'll match you to the right Fortune lines.",
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'passenger', label: 'Passenger & SUV', icon: 'car', iconType: 'lucide' },
        { value: 'light-truck', label: 'Light Truck & Off-Road', icon: 'truck', iconType: 'lucide' },
        { value: 'commercial', label: 'Commercial (TBR)', icon: 'container', iconType: 'lucide' },
        { value: 'all-season', label: 'All-Season & Climate', icon: 'cloud-sun', iconType: 'lucide' },
        { value: 'performance', label: 'Performance & Touring', icon: 'gauge', iconType: 'lucide' },
        { value: 'browse', label: 'Just Exploring', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Fortune Tire Match',
      subtitle: 'Personalized products, education, and brand outcomes based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Why Fortune', icon: 'sparkles' },
        { id: 'solutions', label: 'Tire Lines', icon: 'circle-dot' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Whitepaper', value: 'whitepaper' },
          { label: 'Website', value: 'website' },
        ]},
      ],
      cardsPerPage: 6,
      defaultView: 'medium',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated Fortune Tire results.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Tire Library',
      subtitle: 'Browse the full Fortune Tire content library.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your interest in Fortune Tire. Your personalized tire packet will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (Why Fortune) - 6 cards ─────────────────────
    {
      id: 'wf1',
      title: '30+ Years of Tire Engineering',
      cardType: 'outcome',
      icon: 'history',
      iconType: 'lucide',
      stat: '30+',
      description: {
        small: '30+ years engineering high-performance tires.',
        medium: 'Three decades of tire engineering for passenger, light truck, and commercial markets.',
        large: 'Three decades of dedicated tire engineering across passenger, SUV, light truck, and commercial markets, with R&D centers focused on durability, wet braking, and treadwear.',
        overlay: 'Fortune Tire has spent more than 30 years engineering high-performance tires for passenger cars, SUVs, light trucks, and commercial vehicles. The company invests heavily in compound R&D, tread design, and durability testing, with a focus on wet braking, treadwear, and ride comfort that meets and exceeds industry benchmarks.',
      },
      tags: ['heritage', 'engineering'],
      targetRoles: ['consumer', 'dealer', 'distributor', 'fleet', 'installer', 'oem'],
    },
    {
      id: 'wf2',
      title: '100M Tires Produced Annually',
      cardType: 'outcome',
      icon: 'factory',
      iconType: 'lucide',
      stat: '100M',
      description: {
        small: '100M+ tires produced every year.',
        medium: 'High-volume manufacturing keeps Fortune Tire reliable, available, and competitively priced.',
        large: 'Fortune Tire produces over 100 million tires per year across modern manufacturing facilities, supporting reliable supply, predictable lead times, and competitive pricing for dealers and distributors worldwide.',
        overlay: 'Fortune Tire produces more than 100 million tires per year across modern, automated manufacturing facilities. That production scale translates into reliable supply for dealers, predictable lead times for distributors, competitive pricing for consumers, and the consistency that fleet operators need for total cost of ownership.',
      },
      tags: ['manufacturing', 'scale'],
      targetRoles: ['dealer', 'distributor', 'fleet', 'oem'],
    },
    {
      id: 'wf3',
      title: '85% Wet Braking Score',
      cardType: 'outcome',
      icon: 'droplets',
      iconType: 'lucide',
      stat: '85%',
      description: {
        small: 'Top-tier wet braking performance.',
        medium: 'Fortune compounds and tread designs deliver elite wet braking scores in independent testing.',
        large: 'Independent third-party testing places Fortune Tire among the top tier for wet braking performance, with advanced silica compounds and water-evacuation grooves that shorten stopping distances on wet pavement.',
        overlay: 'Independent third-party testing places Fortune Tire among the top tier for wet braking performance. Advanced silica compounds, optimized tread block stiffness, and high-volume water evacuation grooves combine to shorten stopping distances on wet pavement, a critical safety advantage in the rain that keeps drivers and passengers safer year round.',
      },
      tags: ['safety', 'performance'],
      targetRoles: ['consumer', 'dealer', 'fleet'],
      targetInterests: ['passenger', 'all-season', 'performance'],
    },
    {
      id: 'wf4',
      title: 'Top-3 Wet Performance Rating',
      cardType: 'outcome',
      icon: 'trophy',
      iconType: 'lucide',
      stat: 'Top 3',
      description: {
        small: 'Top-3 ranked for wet performance.',
        medium: 'Fortune all-season tires consistently rank top-3 in wet performance among value brands.',
        large: 'Fortune Tire all-season lines consistently rank in the top three for wet performance among value-priced premium tires, balancing dry grip, wet braking, hydroplaning resistance, and treadwear.',
        overlay: 'Fortune Tire all-season lines, including ClimaFlex 4S and Perfectus, consistently rank in the top three for wet performance among value-priced premium tires in independent testing. The product team balances dry grip, wet braking, hydroplaning resistance, treadwear, and ride comfort to deliver real-world results that match or exceed brands costing significantly more.',
      },
      tags: ['ratings', 'performance'],
      targetRoles: ['consumer', 'dealer'],
      targetInterests: ['passenger', 'all-season'],
    },
    {
      id: 'wf5',
      title: '5-Year Treadwear Warranty',
      cardType: 'outcome',
      icon: 'shield-check',
      iconType: 'lucide',
      stat: '5 yr',
      description: {
        small: 'Backed by a 5-year treadwear warranty.',
        medium: 'Most Fortune passenger lines come with a 5-year limited treadwear warranty.',
        large: "Most Fortune Tire passenger and light-truck lines are backed by a 5-year limited treadwear warranty plus a 30-day satisfaction guarantee, supported through Fortune's authorized dealer network.",
        overlay: "Most Fortune Tire passenger, SUV, and light-truck lines are backed by a 5-year limited treadwear warranty, plus a 30-day satisfaction guarantee, road hazard coverage from many participating dealers, and full nationwide support through Fortune's authorized dealer network. Buy with confidence, drive with confidence.",
      },
      tags: ['warranty', 'value'],
      targetRoles: ['consumer', 'dealer', 'fleet'],
    },
    {
      id: 'wf6',
      title: 'Distribution in 20+ Countries',
      cardType: 'outcome',
      icon: 'globe',
      iconType: 'lucide',
      stat: '20+',
      description: {
        small: 'Distributed in 20+ countries worldwide.',
        medium: 'Global distribution network spans 20+ countries with strong North American coverage.',
        large: 'Fortune Tire distributes through more than 20 countries with deep North American dealer coverage, ensuring product availability, technical support, and warranty service close to wherever you operate.',
        overlay: 'Fortune Tire distributes through more than 20 countries worldwide, with particularly deep dealer and distributor coverage across North America. That global footprint means reliable product availability, local technical support, predictable warranty service, and the kind of supply chain depth that fleet operators and large dealers depend on.',
      },
      tags: ['global', 'distribution'],
      targetRoles: ['dealer', 'distributor', 'fleet', 'oem'],
    },

    // ── Solutions (Tire Lines) - 6 cards ─────────────────────
    {
      id: 's1',
      title: 'ClimaFlex 4S',
      cardType: 'solution',
      icon: 'cloud-snow',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'Premium all-season for cold and wet climates.',
        medium: 'Premium all-season tire engineered for confident performance in cold, wet, and snowy conditions.',
        large: 'ClimaFlex 4S is Fortune Tire\'s premium all-weather line, engineered for confident performance from dry summer pavement to cold, wet, and lightly snowy roads, with 3PMSF severe-snow certification on most sizes.',
        overlay: 'ClimaFlex 4S is Fortune Tire\'s premium all-weather offering, engineered to perform with confidence from dry summer pavement through heavy rain, cold weather, and light to moderate snow. Most sizes carry the 3PMSF severe-snow certification. The compound stays flexible in cold temperatures, the directional tread evacuates water and slush, and the silica-rich compound delivers strong wet braking and treadwear.',
      },
      tags: ['all-season', 'premium', 'safety'],
      targetRoles: ['consumer', 'dealer', 'installer'],
      targetInterests: ['passenger', 'all-season'],
    },
    {
      id: 's2',
      title: 'Perfectus',
      cardType: 'solution',
      icon: 'disc-3',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'Touring comfort for everyday drivers.',
        medium: 'Quiet, comfortable touring tire built for daily commutes and family driving.',
        large: 'Perfectus is built for the everyday driver, quiet ride, comfortable handling, balanced wet and dry performance, and long, even treadwear for daily commutes, school runs, and weekend trips.',
        overlay: 'Perfectus is the touring all-season built for the everyday driver. The asymmetric tread pattern delivers a quiet ride and comfortable handling. The compound balances wet grip, dry grip, and long, even treadwear for daily commutes, school runs, errands, and weekend trips. It is a strong value proposition for drivers who want reliable performance at a fair price.',
      },
      tags: ['touring', 'comfort', 'all-season'],
      targetRoles: ['consumer', 'dealer', 'installer'],
      targetInterests: ['passenger', 'all-season'],
    },
    {
      id: 's3',
      title: 'Viento',
      cardType: 'solution',
      icon: 'gauge',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'High-performance touring for spirited drivers.',
        medium: 'Ultra-high performance touring tire for sport sedans, coupes, and performance crossovers.',
        large: 'Viento is the ultra-high performance touring tire for sport sedans, coupes, and performance crossovers, sharp steering response, strong dry grip, confident wet braking, and the long highway miles touring drivers expect.',
        overlay: 'Viento is the ultra-high performance touring tire engineered for sport sedans, coupes, and performance crossovers. It delivers sharp steering response, strong dry grip in spirited driving, confident wet braking, and the long highway mileage touring drivers expect. Available in a wide range of UHP sizes, including larger 18+ inch fitments and W and Y speed ratings.',
      },
      tags: ['performance', 'touring', 'UHP'],
      targetRoles: ['consumer', 'dealer'],
      targetInterests: ['passenger', 'performance'],
    },
    {
      id: 's4',
      title: 'Tormenta A/T2',
      cardType: 'solution',
      icon: 'mountain-snow',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'All-terrain for trucks and SUVs.',
        medium: 'Balanced all-terrain that handles light off-road work without sacrificing on-road comfort.',
        large: 'Tormenta A/T2 is the all-terrain that handles dirt, gravel, and light off-road work without sacrificing on-road manners, with strong tread block stability, sidewall protection, and a quiet highway ride.',
        overlay: 'Tormenta A/T2 is the all-terrain tire built for trucks and SUVs that split their time between highway miles and light off-road work. The aggressive yet refined tread blocks deliver confident grip on dirt, gravel, and packed snow while keeping the highway ride quiet and stable. Reinforced sidewalls add protection on rough trails, and the wear pattern is engineered for long, even highway miles.',
      },
      tags: ['all-terrain', 'truck', 'off-road'],
      targetRoles: ['consumer', 'dealer', 'installer'],
      targetInterests: ['light-truck', 'all-season'],
    },
    {
      id: 's5',
      title: 'Tormenta M/T',
      cardType: 'solution',
      icon: 'mountain',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'Aggressive mud-terrain for serious off-road.',
        medium: 'Aggressive mud-terrain built for the worst trails, mud, rocks, and demanding off-road work.',
        large: 'Tormenta M/T is the aggressive mud-terrain built for the worst trails, deep mud, sharp rocks, and demanding off-road work, with deep tread, reinforced sidewall lugs, and tough cut-and-chip resistance.',
        overlay: 'Tormenta M/T is built for off-road enthusiasts and work trucks that take on the worst conditions. Deep, widely spaced tread blocks bite through mud and self-clean as the tire rotates. Reinforced sidewall lugs deliver bite on rocks and ledges and protect against pinch flats. The compound resists cuts and chips on sharp surfaces, while staying drivable enough for the road back home.',
      },
      tags: ['mud-terrain', 'truck', 'off-road'],
      targetRoles: ['consumer', 'dealer', 'fleet'],
      targetInterests: ['light-truck'],
    },
    {
      id: 's6',
      title: 'TBR FFH130ET',
      cardType: 'solution',
      icon: 'truck',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'Long-haul steer tire for commercial trucks.',
        medium: 'Premium long-haul steer position tire engineered for fleet cost-per-mile.',
        large: "FFH130ET is Fortune's premium long-haul steer tire, engineered for low rolling resistance, even wear, and the kind of treadlife that improves fleet cost-per-mile across the steer axle.",
        overlay: "FFH130ET is Fortune Tire's premium long-haul steer position TBR, engineered specifically for fleet cost-per-mile. The compound and casing deliver low rolling resistance to support fuel economy targets, while the tread design promotes even wear across the contact patch and resists irregular wear from misalignment. SmartWay-friendly options available, with strong retread potential through the casing program.",
      },
      tags: ['TBR', 'steer', 'fleet'],
      targetRoles: ['dealer', 'distributor', 'fleet'],
      targetInterests: ['commercial'],
    },

    // ── Learn - 6 cards ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Tire Advisor: How It Works',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'compass',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'Find the right Fortune Tire in seconds.',
        medium: "The Fortune Tire Advisor matches your driving needs to the right Fortune product line.",
        large: "The Fortune Tire Advisor matches your tire size and driving needs, daily commute, long trips, wet weather, winter, off-road, to the right Fortune product line in seconds.",
        overlay: "The Fortune Tire Advisor is a quick fitment finder that matches your tire size, width, ratio, and diameter, plus your real-world driving needs (daily commute, long trips, sun and rain, cold and wintry, light or heavy off-road) to the right Fortune product line. Open the Tire Advisor from the top toolbar to try it for yourself, results come back in seconds with a clear explanation of why each tire matches.",
      },
      tags: ['tools', 'fitment'],
      targetRoles: ['consumer', 'dealer', 'installer'],
    },
    {
      id: 'l2',
      title: 'Why Wet Performance Matters',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'cloud-rain',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'How wet braking saves lives on rainy roads.',
        medium: 'A short read on why wet braking, hydroplaning resistance, and tread depth matter for safety.',
        large: 'A short read on why wet braking distance, hydroplaning resistance, and tread depth matter so much for safety, and how Fortune compounds and tread designs target each of those measures.',
        overlay: "Wet performance is the single biggest safety differentiator between tires. This article walks through why wet braking distance, hydroplaning resistance, and minimum tread depth matter so much, especially in rainy regions, and explains how Fortune Tire's silica compound chemistry, tread block design, and water evacuation grooves are tuned to perform when the road is wet. Worth reading before you choose your next set of tires.",
      },
      tags: ['safety', 'education'],
      targetRoles: ['consumer', 'dealer'],
      targetInterests: ['passenger', 'all-season'],
    },
    {
      id: 'l3',
      title: 'Tire Care 101',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'book-open',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'Get the most miles out of every tire.',
        medium: 'A practical owner guide to tire pressure, rotation, alignment, and tread inspection.',
        large: "A practical owner's guide to tire pressure, rotation, alignment, balance, and tread inspection, all the small habits that get the most miles and safest performance out of every Fortune tire.",
        overlay: "Tire Care 101 is a practical owner's guide covering the small habits that protect your investment and your safety, monthly tire pressure checks, recommended rotation intervals (every 5,000 to 8,000 miles), alignment and balance, the penny test for tread depth, sidewall inspection for cuts and bulges, and storage for seasonal tires. A few minutes of care per month gets the most miles and safest performance out of every Fortune tire.",
      },
      tags: ['education', 'maintenance'],
      targetRoles: ['consumer', 'dealer', 'fleet', 'installer'],
    },
    {
      id: 'l4',
      title: 'ClimaFlex 4S Launch',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'Watch the launch of ClimaFlex 4S.',
        medium: 'A short product launch film for the ClimaFlex 4S premium all-weather tire.',
        large: 'A short product launch film for the ClimaFlex 4S premium all-weather tire, walking through the compound, tread design, and 3PMSF severe-snow certification that make it Fortune\'s flagship all-weather product.',
        overlay: 'This product launch film walks through the engineering story behind ClimaFlex 4S: the silica-rich winter-capable compound, the directional tread that evacuates water and slush, the variable sipe geometry that bites in snow, and the 3PMSF severe-snow certification on most sizes. The film also covers test results from independent third-party labs and how the tire performs across the full year, from dry summer to wet fall to cold, light-snow winter.',
      },
      tags: ['product-launch', 'video'],
      targetRoles: ['consumer', 'dealer', 'installer'],
      targetInterests: ['passenger', 'all-season'],
    },
    {
      id: 'l5',
      title: 'Fortune Tire Brand Story',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'Meet the people behind Fortune Tire.',
        medium: 'A brand film introducing the people, factories, and engineering behind Fortune Tire.',
        large: 'A brand film introducing the people, factories, and engineering culture behind Fortune Tire, the heritage, the R&D investment, and the customer-first ethos behind every product.',
        overlay: 'Meet the people, factories, and engineering culture that built Fortune Tire. This brand film walks through the heritage, three decades of dedicated tire engineering, the R&D investment that drives the wet performance leadership, and the customer-first ethos that shows up in everything from product design to dealer support to warranty service. A short, honest look at why Fortune Tire is built differently, and built for the long haul.',
      },
      tags: ['brand', 'video'],
      targetRoles: ['consumer', 'dealer', 'distributor', 'fleet', 'installer', 'oem'],
    },
    {
      id: 'l6',
      title: 'TBR Fleet Cost-Per-Mile Guide',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://fortunetireusa.com/',
      description: {
        small: 'Lower fleet TCO with the right TBR strategy.',
        medium: 'A whitepaper for fleet managers on lowering total cost of ownership through tire strategy.',
        large: "A whitepaper for fleet managers on lowering total cost of ownership through TBR tire selection, axle position strategy, retread programs, and inflation discipline.",
        overlay: 'This whitepaper is for fleet managers and maintenance directors looking to lower total cost of ownership through smarter tire strategy. It covers Fortune Tire TBR product positioning across steer, drive, and trailer axles, the role of casing quality in retread economics, inflation discipline and TPMS, alignment and wear-pattern diagnosis, and the math of cost-per-mile. Includes case studies from real fleets that switched to Fortune TBR.',
      },
      tags: ['fleet', 'whitepaper', 'TBR'],
      targetRoles: ['dealer', 'distributor', 'fleet', 'oem'],
      targetInterests: ['commercial'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: true,
    captureInfo: true,
  },
};
