// Explorer Config — Friends of Medicine
// A curated professional network for those advancing human health across medicine, capital, and innovation.

import type { ExplorerConfig, ThemeColors } from '../types';

const FOM_DARK: ThemeColors = {
  bg: '#07141A',
  bgGradient: 'linear-gradient(135deg, #0F2428 0%, #07141A 55%, #091B1E 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#1D9DAA',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(29,157,170,0.20)',
};

const FOM_LIGHT: ThemeColors = {
  bg: '#F3F7F8',
  bgGradient: 'linear-gradient(180deg, #F3F7F8 0%, #EDF3F5 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#0F6E78',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(15,110,120,0.12)',
};

export const FRIENDS_OF_MEDICINE_CONFIG: ExplorerConfig = {
  id: 'friends-of-medicine',
  name: 'Friends of Medicine Explorer',
  version: 1,
  createdAt: '2026-06-22T00:00:00.000Z',
  updatedAt: '2026-06-22T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/friends-of-medicine-logo-dark.png',
      light: '/brand/assets/friends-of-medicine-logo-dark.png',
    },
    invertLogoOnLight: true,
    icon: '/brand/assets/friends-of-medicine-icon.png',
    colors: {
      primary: '#1D9DAA',
      secondary: '#0F6E78',
      teal: '#1D9DAA',
      blue: '#0F6E78',
      deepBlue: '#0A4F57',
      navy: '#091B1E',
      midnight: '#050D10',
      plum: '#5D8FA5',
      bgDark: '#07141A',
      dark: FOM_DARK,
      light: FOM_LIGHT,
    },
    font: "Inter, -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(29,157,170,0.15)',
      orb2: 'rgba(15,110,120,0.12)',
      orb3: 'rgba(93,143,165,0.10)',
    },
    ctaGradient: 'linear-gradient(135deg, #1D9DAA, #0F6E78)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #1D9DAA, #0F6E78)',
    roleBackgrounds: {
      'physician': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(29,157,170,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(15,110,120,0.10) 0%, transparent 55%)',
      'founder': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(15,110,120,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(29,157,170,0.10) 0%, transparent 55%)',
      'investor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(29,157,170,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(10,79,87,0.14) 0%, transparent 55%)',
      'digital-health': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(15,110,120,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(29,157,170,0.08) 0%, transparent 55%)',
      'innovator': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(93,143,165,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(29,157,170,0.14) 0%, transparent 55%)',
      'health-system': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(29,157,170,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(10,79,87,0.12) 0%, transparent 55%)',
      'advanced-practitioner': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(15,110,120,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(93,143,165,0.12) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(29,157,170,0.12) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(15,110,120,0.08) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Share your info so we can follow up with personalized resources about the network.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Friends of Medicine processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Organization', type: 'text', placeholder: 'Practice, company, or firm', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role or specialty', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Proximity Creates',
      gradientWord: 'Opportunity.',
      subtitle: 'A curated professional network for those advancing human health — across medicine, capital, and innovation.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes you?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'physician', label: 'Physician / Clinician', icon: 'heart-pulse', iconType: 'lucide' },
        { value: 'founder', label: 'Healthcare Founder / Entrepreneur', icon: 'rocket', iconType: 'lucide' },
        { value: 'investor', label: 'Venture Investor', icon: 'trending-up', iconType: 'lucide' },
        { value: 'digital-health', label: 'Digital Health Operator', icon: 'cpu', iconType: 'lucide' },
        { value: 'innovator', label: 'Clinical Innovator', icon: 'lightbulb', iconType: 'lucide' },
        { value: 'health-system', label: 'Health System Leader', icon: 'building-2', iconType: 'lucide' },
        { value: 'advanced-practitioner', label: 'NP / PA / Advanced Practitioner', icon: 'clipboard-list', iconType: 'lucide' },
        { value: 'other', label: 'Other Healthcare Professional', icon: 'users', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you most interested in?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'clinical-ai', label: 'Clinical AI & Digital Health', icon: 'cpu', iconType: 'lucide' },
        { value: 'longevity', label: 'Longevity & Integrative Medicine', icon: 'leaf', iconType: 'lucide' },
        { value: 'entrepreneurship', label: 'Healthcare Entrepreneurship', icon: 'rocket', iconType: 'lucide' },
        { value: 'networking', label: 'Physician & Investor Connections', icon: 'handshake', iconType: 'lucide' },
        { value: 'cme', label: 'CME & Continuing Education', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'wellness', label: 'Wellness & Peak Performance', icon: 'heart', iconType: 'lucide' },
        { value: 'capital', label: 'Capital & Investment Access', icon: 'dollar-sign', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Exploring', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and programs based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        {
          id: 'learn',
          label: 'Learn',
          icon: 'book-open',
          filters: [
            { label: 'All', value: 'all' },
            { label: 'Video', value: 'video' },
            { label: 'Podcast', value: 'podcast' },
            { label: 'Blog', value: 'blog' },
            { label: 'PDF', value: 'pdf' },
          ],
        },
        { id: 'solutions', label: 'Programs', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: "We're excited to connect. Our team will be in touch with more about Friends of Medicine.",
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: '4 Major Cities, One Network',
      cardType: 'outcome',
      icon: 'map-pin',
      iconType: 'lucide',
      stat: '4 Cities',
      description: {
        small: "Walk-in privileges across Miami, Dallas, New York, and Atlanta.",
        medium: "Inner Circle members enjoy walk-in access to events and programming in Miami, Dallas, New York, and Atlanta.",
        large: "Friends of Medicine spans four major healthcare markets: Miami, Dallas, New York, and Atlanta. Inner Circle members receive walk-in privileges across the entire network, making every city a home base for connection.",
        overlay: "Wherever your work takes you, the Friends of Medicine network travels with you. Inner Circle members enjoy walk-in privileges across all four metropolitan hubs: Miami, Dallas, New York, and Atlanta. Whether you're attending a conference, conducting due diligence, or relocating, you're always welcomed into the same caliber of curated room — physicians, founders, investors, and innovators gathered with purpose.",
      },
      tags: ['networking', 'capital'],
      targetRoles: ['physician', 'founder', 'investor', 'health-system'],
    },
    {
      id: 'o2',
      title: 'Four Monthly Event Series',
      cardType: 'outcome',
      icon: 'calendar',
      iconType: 'lucide',
      stat: '4/Month',
      description: {
        small: "Four curated event series every month across tech, wellness, founders, and community.",
        medium: "Tech Tuesday, Wellness Wednesday, Unwind Thursday, and Founders Friday — recurring monthly gatherings for every corner of healthcare.",
        large: "Every month, Friends of Medicine runs four distinct event series, each designed for a different facet of healthcare: Clinical AI and tech on Tuesdays, longevity and wellness on Wednesdays, community connection on Thursdays, and founders and investors on Fridays.",
        overlay: "The Friends of Medicine calendar isn't accidental — it's architected for depth. Tech Tuesday convenes clinicians, AI builders, and digital health operators. Wellness Wednesday draws longevity practitioners and biohacking innovators. Unwind Thursday creates space for authentic connection without agenda. Founders Friday brings physician-founders face-to-face with investors and operators by invitation only. Together, they create a rhythm of access that no single annual conference can replicate.",
      },
      tags: ['networking', 'clinical-ai', 'longevity', 'entrepreneurship'],
      targetRoles: ['physician', 'founder', 'investor', 'digital-health', 'innovator'],
    },
    {
      id: 'o3',
      title: 'Inner Circle: Curated by Conversation',
      cardType: 'outcome',
      icon: 'crown',
      iconType: 'lucide',
      stat: 'By Invite',
      description: {
        small: "A selective, application-based membership for those at the frontier of healthcare.",
        medium: "Inner Circle is curated, selective, and by conversation — an invitation-only tier for those actively advancing medicine, capital, or innovation.",
        large: "Inner Circle membership is not sold — it is extended. The selective application and conversation process ensures every member is actively advancing human health, creating rooms where every handshake holds real potential.",
        overlay: "Friends of Medicine's Inner Circle tier is deliberately small and intentionally curated. The application process — rooted in conversation rather than credentials — ensures the network stays vibrant and high-signal. Members are physicians building practices, founders raising rounds, investors deploying capital, and innovators reshaping care delivery. The result is a room where everyone belongs and every introduction has genuine potential.",
      },
      tags: ['networking', 'capital', 'entrepreneurship'],
      targetRoles: ['physician', 'founder', 'investor', 'health-system'],
    },
    {
      id: 'o4',
      title: 'The Reset Retreat — Annual',
      cardType: 'outcome',
      icon: 'mountain-snow',
      iconType: 'lucide',
      stat: 'Annual',
      description: {
        small: "One weekend each year for Inner Circle members — connection, reflection, and renewal.",
        medium: "The Reset Retreat is a single annual weekend for Inner Circle members and select high-performance guests, designed for deep connection and renewal.",
        large: "Once a year, Inner Circle members and select guests gather for The Reset Retreat — a weekend without agenda or programming, designed to create the unhurried space where the best relationships are built.",
        overlay: "The Reset Retreat is the anchor of the Friends of Medicine calendar. Unlike conferences or panels, it has no agenda: no keynotes, no name tags, no speed networking. It is a single weekend experience — exclusive to Inner Circle members and select high-performance guests — built on the premise that lasting professional relationships are born in unstructured time. Past retreats have produced co-founder introductions, investment commitments, and clinical partnerships that never would have emerged across a conference table.",
      },
      tags: ['networking', 'wellness'],
      targetRoles: ['physician', 'founder', 'investor', 'innovator'],
    },
    {
      id: 'o5',
      title: 'CME-Eligible Dinner Series',
      cardType: 'outcome',
      icon: 'graduation-cap',
      iconType: 'lucide',
      stat: 'CME Credit',
      description: {
        small: "Earn continuing medical education credits through curated dinner series.",
        medium: "Friends of Medicine offers CME-eligible dinner events, combining high-level clinical education with the network's signature curated atmosphere.",
        large: "Select Friends of Medicine events qualify for CME credit, blending continuing medical education with the curated connection the network is known for — so professional development and relationship building happen in the same room.",
        overlay: "For physicians navigating CME requirements alongside busy clinical schedules, Friends of Medicine offers a better path: CME-eligible dinner events that satisfy continuing education requirements while placing attendees in rooms with peers and innovators. The format is intimate by design — not a lecture hall, but a curated table where clinical education and genuine networking reinforce each other.",
      },
      tags: ['cme', 'networking'],
      targetRoles: ['physician', 'advanced-practitioner', 'health-system'],
    },
    {
      id: 'o6',
      title: 'Medicine, Capital, and Innovation — One Room',
      cardType: 'outcome',
      icon: 'handshake',
      iconType: 'lucide',
      stat: '3 Worlds',
      description: {
        small: "The only network convening physicians, founders, and investors under one roof.",
        medium: "Friends of Medicine is the rare network where clinicians, entrepreneurs, and capital meet by design — creating cross-sector relationships no vertical community can replicate.",
        large: "Most professional networks are siloed by sector. Friends of Medicine intentionally bridges medicine, capital, and innovation, creating rooms where a physician's clinical insight, a founder's execution, and an investor's capital can find each other.",
        overlay: "The most transformative healthcare relationships happen at the intersection of clinical expertise, entrepreneurial drive, and investment capital. Friends of Medicine is architected for exactly that intersection. Physicians bring domain knowledge and patient insight. Founders bring execution and vision. Investors bring capital and pattern recognition. Convened together in curated, intimate settings, these three worlds create opportunities that no single-sector network can generate.",
      },
      tags: ['networking', 'capital', 'entrepreneurship', 'clinical-ai'],
      targetRoles: ['physician', 'founder', 'investor', 'digital-health'],
    },
    {
      id: 'o7',
      title: 'Private Members Community Thread',
      cardType: 'outcome',
      icon: 'message-circle',
      iconType: 'lucide',
      stat: 'Always On',
      description: {
        small: "A private, always-on community thread exclusively for Inner Circle members.",
        medium: "Inner Circle members stay connected between events through a private, moderated community thread — ongoing access to the network's collective knowledge.",
        large: "Between events, Inner Circle members stay connected through a private digital community — where questions get answered by peers, opportunities get shared, and the network's collective intelligence is always accessible.",
        overlay: "The value of a professional network doesn't pause between events. Friends of Medicine Inner Circle members access a private, moderated community thread that extends the network's reach into daily professional life. Post a clinical question, share a deal opportunity, request an introduction, or get a second opinion from a peer across the country. The community is the connective tissue between the curated rooms that FOM creates — a signal-rich channel reserved exclusively for Inner Circle members.",
      },
      tags: ['networking', 'cme', 'entrepreneurship'],
      targetRoles: ['physician', 'founder', 'investor', 'health-system', 'innovator'],
    },

    // ── Learn (7) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Behind the Scrubs Podcast',
      cardType: 'learn',
      mediaType: 'podcast',
      icon: 'headphones',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/',
      description: {
        small: "Long-form conversations with physicians, founders, and innovators.",
        medium: "Behind the Scrubs features candid, long-form conversations with the people shaping the future of healthcare.",
        large: "Friends of Medicine's flagship podcast, Behind the Scrubs, goes beyond the résumé — exploring the personal journeys, clinical insights, and entrepreneurial stories of those advancing human health.",
        overlay: "Behind the Scrubs is the audio extension of the Friends of Medicine network. Each episode features a long-form conversation with a physician, founder, investor, or innovator — the kind of raw, unfiltered dialogue that happens at the best FOM dinners, now available anywhere. Topics range from building a health tech company inside a clinical career to navigating investor relationships as a physician-founder, to the personal cost of practicing at the frontier of medicine.",
      },
      tags: ['entrepreneurship', 'networking', 'clinical-ai', 'longevity'],
      targetRoles: ['physician', 'founder', 'investor', 'innovator'],
    },
    {
      id: 'l2',
      title: 'What Is Friends of Medicine?',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/',
      description: {
        small: "An introduction to the network, its mission, and its community.",
        medium: "A short video overview of Friends of Medicine — the mission, the community, and what happens when medicine, capital, and innovation share a room.",
        large: "This overview walks through what Friends of Medicine is, who it's for, and why proximity matters in healthcare advancement. Learn how the network brings together physicians, founders, and investors to create transformative professional relationships.",
        overlay: "This video answers the question everyone asks when they first encounter Friends of Medicine: what exactly is it? It covers the network's founding premise — that proximity creates opportunity — the community it has built across four cities, the programs and events that define the calendar, and the type of professional who finds the most value in membership. If you're considering applying or just want to understand the community before a conversation, start here.",
      },
      tags: ['networking', 'entrepreneurship'],
      targetRoles: ['physician', 'founder', 'investor', 'digital-health', 'health-system', 'advanced-practitioner'],
    },
    {
      id: 'l3',
      title: 'The Inner Circle: A Member Perspective',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/',
      description: {
        small: "What membership looks like from the inside.",
        medium: "A firsthand look at the Inner Circle experience — the events, the community, and the professional relationships that form over time.",
        large: "This guide shares the Inner Circle member experience: how the curated application process works, what to expect at your first event, how the city-to-city access functions, and the kinds of professional relationships that develop through consistent participation.",
        overlay: "Most professional networks are easy to join and hard to value. Friends of Medicine inverts that equation: the Inner Circle requires a genuine conversation and deliberate selection, then delivers consistent, high-caliber access. This member perspective guide covers what the application process actually involves, how walk-in city privileges work across Miami, Dallas, New York, and Atlanta, what each event series offers month-to-month, and the arc of professional relationships that form over the first 12 months of membership.",
      },
      tags: ['networking', 'cme'],
      targetRoles: ['physician', 'founder', 'investor', 'health-system'],
    },
    {
      id: 'l4',
      title: 'Tech Tuesday: Clinical AI Trends',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/',
      description: {
        small: "Insights from the front lines of clinical AI and digital health.",
        medium: "Recaps and insights from Tech Tuesday — FOM's monthly gathering for clinicians, AI builders, and digital health operators.",
        large: "Tech Tuesday brings together physicians and technologists exploring clinical AI, digital health tools, and the reshaping of care delivery. This post captures key themes, conversations, and opportunities emerging from the series.",
        overlay: "Tech Tuesday is the pulse of healthcare technology within the Friends of Medicine network. Each month, clinicians working inside AI-enabled health systems sit across from the engineers building those tools — creating a rare feedback loop between end-users and builders. This blog post captures the ideas and trends surfacing from recent gatherings: from ambient clinical documentation and AI diagnostics to regulatory strategy and clinical trial design for digital therapeutics.",
      },
      tags: ['clinical-ai', 'entrepreneurship'],
      targetRoles: ['physician', 'digital-health', 'innovator', 'founder'],
    },
    {
      id: 'l5',
      title: 'Founders Friday: Medicine Meets Business',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/',
      description: {
        small: "Physician-founders and investors share the realities of building at the intersection.",
        medium: "A recorded Founders Friday panel on the physician-founder journey — from clinical practice to startup board rooms.",
        large: "Founders Friday is FOM's most selective event: an invitation-only dinner connecting physician-founders with operators and investors. This recording captures the candid conversation about building healthcare companies while maintaining clinical identity.",
        overlay: "Founders Friday is closed to the press and open only by application — so this recording is a rare window into the conversation. Physician-founders share what prompted the transition from clinical practice to entrepreneurship, how they navigate dual identities, how they approach investor conversations, and what they wish they knew before raising their first round. The investors in the room share what makes physician-founders uniquely compelling — and uniquely challenging — as deal partners.",
      },
      tags: ['entrepreneurship', 'capital', 'networking'],
      targetRoles: ['founder', 'investor', 'physician'],
    },
    {
      id: 'l6',
      title: 'Longevity Medicine: The Wellness Wednesday Lens',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'leaf',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/',
      description: {
        small: "Inside the longevity and integrative medicine conversations at Wellness Wednesday.",
        medium: "An inside look at what practitioners, biohackers, and wellness builders are exploring at FOM's Wellness Wednesday series.",
        large: "Wellness Wednesday convenes the practitioners and innovators at the frontier of longevity medicine: hormone optimization, peptides, regenerative medicine, and medical aesthetics. This post captures the clinical and entrepreneurial conversations shaping integrative health.",
        overlay: "Longevity medicine sits at one of healthcare's most contested intersections: rigorous clinical science, patient-driven demand, and significant commercial opportunity. Wellness Wednesday brings practitioners, operators, and innovators together to navigate this terrain together. This piece covers the conversations emerging from recent gatherings: the evidence base for peptide protocols, the clinical economics of a longevity practice, the regulatory landscape for regenerative therapies, and how wellness operators are scaling without losing clinical credibility.",
      },
      tags: ['longevity', 'wellness', 'entrepreneurship'],
      targetRoles: ['physician', 'innovator', 'advanced-practitioner', 'founder'],
    },
    {
      id: 'l7',
      title: 'The Reset Retreat: Why Unstructured Time Works',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'globe',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/',
      description: {
        small: "The philosophy behind FOM's annual retreat and why it produces lasting connections.",
        medium: "Why Friends of Medicine's annual Reset Retreat — with no agenda and no programming — consistently creates the network's most meaningful relationships.",
        large: "The Reset Retreat has no agenda. No keynotes. No workshops. This piece explores why that is — and why unstructured time with the right people consistently produces the professional relationships that structured networking never achieves.",
        overlay: "The most important professional relationships in medicine rarely form at conferences. They form in the spaces between sessions, over late dinners, or on long drives between meetings. The Reset Retreat is designed around this insight: bring together the right people — Inner Circle members and select high-performance guests — remove the agenda, and let proximity and shared context do the rest. This piece explores the philosophy behind the format, the research supporting unstructured social time for professional relationship formation, and what past attendees say happened in the year after their first retreat.",
      },
      tags: ['networking', 'wellness'],
      targetRoles: ['physician', 'founder', 'investor', 'health-system'],
    },

    // ── Solutions (Programs) (7) ──────────────────────
    {
      id: 's1',
      title: 'Inner Circle Membership',
      cardType: 'solution',
      icon: 'crown',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/membership',
      description: {
        small: "Premium, invitation-only network access across four cities.",
        medium: "Inner Circle is FOM's premium tier — curated membership granting walk-in access to events citywide, private community, annual retreat priority, and CME dinners.",
        large: "Inner Circle membership provides comprehensive network access: walk-in event privileges in all four cities, access to all four monthly event series, private digital community thread, priority access to The Reset Retreat, CME-eligible dinners, and speaking and podcast visibility opportunities.",
        overlay: "Inner Circle is the full Friends of Medicine experience. Members receive walk-in privileges at events across Miami, Dallas, New York, and Atlanta; access to Tech Tuesday, Wellness Wednesday, Unwind Thursday, and Founders Friday; the private members-only community thread for ongoing connection; priority access and pricing for The Reset Retreat; CME-eligible dinner invitations; and opportunities for speaking visibility and podcast features. Membership is by application and conversation — not open enrollment.",
      },
      tags: ['networking', 'cme', 'capital', 'entrepreneurship'],
      targetRoles: ['physician', 'founder', 'investor', 'health-system', 'innovator'],
    },
    {
      id: 's2',
      title: 'The Portal (Standard Access)',
      cardType: 'solution',
      icon: 'globe',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/membership',
      description: {
        small: "Entry-level access to the Friends of Medicine network.",
        medium: "The Portal provides standard access to the Friends of Medicine community — a starting point for those new to the network.",
        large: "The Portal is the entry point to Friends of Medicine — providing access to the network's digital community and select events for those not yet in Inner Circle, or exploring whether full membership is the right fit.",
        overlay: "Not every professional relationship begins at Inner Circle. The Portal provides a starting point: access to the Friends of Medicine digital community and opportunities to attend select network events. It's the beginning of a relationship with the FOM community — and for many members, the first step toward applying for Inner Circle after experiencing firsthand what the network offers.",
      },
      tags: ['networking'],
      targetRoles: ['physician', 'founder', 'digital-health', 'advanced-practitioner', 'other'],
    },
    {
      id: 's3',
      title: 'Tech Tuesday',
      cardType: 'solution',
      icon: 'cpu',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/events',
      description: {
        small: "Monthly gathering for clinicians, AI builders, and digital health operators.",
        medium: "Tech Tuesday is FOM's monthly convening for those reshaping healthcare through technology — clinicians, technologists, and digital health builders.",
        large: "Tech Tuesday brings together the clinicians who use healthcare technology and the builders who create it. Held the first Tuesday of each month in Miami, it's the network's most tech-forward gathering, covering clinical AI, digital health tools, and the future of care delivery.",
        overlay: "Tech Tuesday is where clinical insight meets technological ambition. The monthly gathering convenes physicians working inside AI-enabled systems, digital health founders building the next generation of tools, and technologists navigating the complexity of healthcare regulation and adoption. The format is intentionally conversational — not a product showcase or a pitch night, but a curated room where clinical feedback reaches builders and technical possibility reaches clinicians. Currently hosted in Miami at Rosa Sky.",
      },
      tags: ['clinical-ai', 'entrepreneurship', 'networking'],
      targetRoles: ['physician', 'digital-health', 'founder', 'innovator'],
    },
    {
      id: 's4',
      title: 'Founders Friday',
      cardType: 'solution',
      icon: 'rocket',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/events',
      description: {
        small: "Invitation-only dinner connecting physician-founders with operators and investors.",
        medium: "Founders Friday is FOM's most selective event — a private dinner for physician-founders, healthcare operators, and aligned investors, by application only.",
        large: "Founders Friday is an invitation-only dinner series convening physician-founders alongside operators and investors aligned with healthcare. It's the most selective event in the FOM calendar — and consistently produces the network's most consequential introductions.",
        overlay: "Founders Friday is closed to the press and open only by application — a deliberate design choice to protect the candor that makes the conversation valuable. Physician-founders share the realities of building healthcare companies from inside clinical practice. Operators share what clinical founders often miss. Investors share what makes physician-founders uniquely positioned — and uniquely challenging — as partners. The format produces introductions, co-founder relationships, and term sheets. Hosted in Miami at a private venue.",
      },
      tags: ['entrepreneurship', 'capital', 'networking'],
      targetRoles: ['founder', 'investor', 'physician'],
    },
    {
      id: 's5',
      title: 'Wellness Wednesday',
      cardType: 'solution',
      icon: 'leaf',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/events',
      description: {
        small: "Monthly gathering for longevity medicine and integrative health practitioners.",
        medium: "Wellness Wednesday convenes practitioners, operators, and innovators in longevity, biohacking, hormone optimization, and regenerative medicine.",
        large: "Wellness Wednesday is the network's gathering for those at the frontier of integrative and longevity medicine — practitioners, biohacking operators, and wellness entrepreneurs exploring the clinical and commercial future of human optimization.",
        overlay: "Longevity medicine is one of healthcare's fastest-moving and most contested spaces. Wellness Wednesday creates a monthly professional room for the practitioners, operators, and innovators navigating it: physicians building longevity practices, biohacking entrepreneurs scaling direct-to-consumer wellness, and researchers pushing the boundaries of regenerative medicine and hormone optimization. The gathering is deliberately practitioner-forward — clinical credibility and commercial ambition coexist in the same room. Hosted monthly in Miami at Yaya.",
      },
      tags: ['longevity', 'wellness', 'entrepreneurship'],
      targetRoles: ['physician', 'innovator', 'advanced-practitioner', 'founder'],
    },
    {
      id: 's6',
      title: 'Unwind Thursday',
      cardType: 'solution',
      icon: 'users',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/events',
      description: {
        small: "An after-hours decompression space for healthcare professionals — no agenda, no speeches.",
        medium: "Unwind Thursday is FOM's monthly community gathering for physicians, nurses, advanced practitioners, and healthcare leaders — no agenda, no pitches, just connection.",
        large: "Unwind Thursday is intentionally agenda-free: a space for physicians, nurses, advanced practitioners, and healthcare leaders to decompress, connect authentically, and build the peer relationships that make medicine sustainable.",
        overlay: "Healthcare is relentless. Unwind Thursday exists as a counterpoint: the second Thursday of each month, a curated room of physicians, nurses, advanced practitioners, and healthcare leaders gathers at Giselle Miami with no agenda, no keynotes, and no pitches. Just intentional space for the people who carry the weight of clinical work to connect with peers who understand that weight. For many attendees, it becomes the most consistent professional gathering in their lives — not because of what's discussed, but because of who shows up.",
      },
      tags: ['networking', 'wellness', 'cme'],
      targetRoles: ['physician', 'advanced-practitioner', 'health-system', 'other'],
    },
    {
      id: 's7',
      title: 'The Reset Retreat',
      cardType: 'solution',
      icon: 'mountain-snow',
      iconType: 'lucide',
      url: 'https://friendsofmed.com/events',
      description: {
        small: "The annual Inner Circle retreat — one weekend, no agenda, transformative connections.",
        medium: "The Reset Retreat is a single annual weekend for Inner Circle members and select guests — designed for the deep connection that only unhurried time creates.",
        large: "Once a year, Inner Circle members and select high-performance guests gather for The Reset Retreat: a weekend without agenda or programming, built on the premise that the best professional relationships form in unstructured time with the right people.",
        overlay: "The Reset Retreat is the anchor of the Friends of Medicine year. Unlike every other professional gathering, it has no agenda: no keynotes, no workshops, no formal programming. It is a deliberate weekend experience — exclusive to Inner Circle members and select guests — built on the insight that lasting professional relationships are born in unhurried space. Past retreats have produced co-founder introductions, investment commitments, clinical partnerships, and friendships that define careers. Priority access and pricing are Inner Circle member benefits.",
      },
      tags: ['networking', 'wellness'],
      targetRoles: ['physician', 'founder', 'investor', 'health-system', 'innovator'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
