// Explorer Config — Maven Financial Partners
// Fractional CFO & financial advisory for healthcare practices

import type { ExplorerConfig, ThemeColors } from '../types';

const MAVEN_DARK: ThemeColors = {
  bg: '#081217',
  bgGradient: 'linear-gradient(135deg, #1A3040 0%, #0C161E 55%, #162A3A 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#8FB8C8',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(123,157,174,0.20)',
};

const MAVEN_LIGHT: ThemeColors = {
  bg: '#F3F5F7',
  bgGradient: 'linear-gradient(180deg, #F3F5F7 0%, #EEF1F4 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#5A8394',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(90,131,148,0.12)',
};

export const MAVEN_FP_CONFIG: ExplorerConfig = {
  id: 'maven-fp',
  name: 'Maven Financial Partners Explorer',
  version: 1,
  createdAt: '2026-04-07T00:00:00.000Z',
  updatedAt: '2026-04-07T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/maven-fp-logo-reverse.png',
      light: '/brand/assets/maven-fp-logo.png',
    },
    icon: '/brand/assets/maven-fp-icon.png',
    colors: {
      primary: '#7B9DAE',
      secondary: '#5A8394',
      teal: '#8FB8C8',
      blue: '#5A8394',
      deepBlue: '#3D6474',
      navy: '#112732',
      midnight: '#09151B',
      plum: '#6E7F8C',
      bgDark: '#09151B',
      dark: MAVEN_DARK,
      light: MAVEN_LIGHT,
    },
    font: "'Montserrat', Inter, -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(123,157,174,0.14)',
      orb2: 'rgba(143,184,200,0.12)',
      orb3: 'rgba(110,127,140,0.10)',
    },
    ctaGradient: 'linear-gradient(135deg, #7B9DAE, #3D6474)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #8FB8C8, #5A8394)',
    roleBackgrounds: {
      'practice-owner': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(123,157,174,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(110,127,140,0.12) 0%, transparent 55%)',
      'office-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(143,184,200,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(123,157,174,0.10) 0%, transparent 55%)',
      'cfo-controller': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(110,127,140,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(123,157,174,0.12) 0%, transparent 55%)',
      'clinical-director': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(123,157,174,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(143,184,200,0.08) 0%, transparent 55%)',
      'dso-mso': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(61,100,116,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(143,184,200,0.15) 0%, transparent 55%)',
      'new-practice': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(143,184,200,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(110,127,140,0.12) 0%, transparent 55%)',
      'investor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(110,127,140,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(61,100,116,0.12) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(110,127,140,0.12) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(143,184,200,0.08) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Please fill in the form to continue.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Maven Financial Partners processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@practice.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Practice Name', type: 'text', placeholder: 'Practice or company name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Financial',
      gradientWord: 'Clarity.',
      subtitle: 'Discover how Maven\'s fractional CFO services help practice owners gain awareness, clarity, and confidence in their financial decisions.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes your role?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'practice-owner', label: 'Practice Owner / Physician', icon: 'stethoscope', iconType: 'lucide' },
        { value: 'office-manager', label: 'Office / Practice Manager', icon: 'clipboard-list', iconType: 'lucide' },
        { value: 'cfo-controller', label: 'CFO / Controller', icon: 'calculator', iconType: 'lucide' },
        { value: 'clinical-director', label: 'Clinical Director', icon: 'heart-pulse', iconType: 'lucide' },
        { value: 'dso-mso', label: 'DSO / MSO Leadership', icon: 'building-2', iconType: 'lucide' },
        { value: 'new-practice', label: 'Starting a New Practice', icon: 'rocket', iconType: 'lucide' },
        { value: 'investor', label: 'Investor / PE', icon: 'trending-up', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'message-circle', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What financial challenges are you facing?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'profitability', label: 'Profitability & EBITDA', icon: 'trending-up', iconType: 'lucide' },
        { value: 'cash-flow', label: 'Cash Flow Management', icon: 'wallet', iconType: 'lucide' },
        { value: 'kpi-tracking', label: 'KPI Tracking & Benchmarks', icon: 'bar-chart-2', iconType: 'lucide' },
        { value: 'compensation', label: 'Compensation Modeling', icon: 'users', iconType: 'lucide' },
        { value: 'growth-strategy', label: 'Growth Strategy', icon: 'target', iconType: 'lucide' },
        { value: 'practice-valuation', label: 'Practice Valuation / Exit', icon: 'badge-dollar-sign', iconType: 'lucide' },
        { value: 'compliance', label: 'MSO / Compliance Setup', icon: 'shield-check', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Podcast', value: 'podcast' },
          { label: 'PDF', value: 'pdf' },
        ]},
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: '300+ Practices Served',
      cardType: 'outcome',
      icon: 'building-2',
      iconType: 'lucide',
      stat: '300+',
      description: {
        small: 'Trusted by over 300 healthcare practices.',
        medium: 'Over 300 dental, medspa, and aesthetic practices trust Maven for fractional CFO support.',
        large: 'Maven Financial Partners has served over 300 healthcare practices, delivering fractional CFO expertise to dental, medspa, plastic surgery, dermatology, and wellness clinics across the country.',
        overlay: 'With 300+ practices served, Maven brings deep pattern recognition across specialties. This means your practice benefits from benchmarks, compensation models, and growth strategies proven across hundreds of similar businesses, not generic advice from generalist accountants.',
      },
      tags: ['profitability', 'growth-strategy'],
      targetRoles: ['practice-owner', 'dso-mso', 'new-practice'],
    },
    {
      id: 'o2',
      title: '90% Client Retention Rate',
      cardType: 'outcome',
      icon: 'heart-handshake',
      iconType: 'lucide',
      stat: '90%',
      description: {
        small: '9 out of 10 clients stay with Maven long-term.',
        medium: '90% of Maven clients retain their partnership year over year, a testament to consistent results.',
        large: 'Maven achieves a 90% client retention rate because the financial clarity and strategic guidance they provide becomes indispensable to practice owners navigating growth, profitability, and exit planning.',
        overlay: 'A 90% retention rate is exceptional in consulting. Practice owners stay with Maven because the monthly financial deep dives, KPI scorecards, and strategic guidance deliver measurable improvements to profitability, cash flow, and practice value that compound over time.',
      },
      tags: ['profitability', 'kpi-tracking'],
      targetRoles: ['practice-owner', 'office-manager', 'cfo-controller'],
    },
    {
      id: 'o3',
      title: 'Measurable Revenue Growth',
      cardType: 'outcome',
      icon: 'trending-up',
      iconType: 'lucide',
      stat: '$3K+',
      description: {
        small: 'Clients see thousands in monthly revenue gains.',
        medium: 'Practices report $3,000+ in monthly net revenue improvements through Maven\'s data-driven guidance.',
        large: 'Maven\'s monthly financial analysis and strategic recommendations have helped practices achieve $3,000+ in net monthly revenue improvements by identifying inefficiencies, optimizing service mix, and improving collection rates.',
        overlay: 'Revenue growth comes from the details. Maven analyzes your P&L, PMS data, and revenue cycle to uncover specific opportunities: underpriced services, collection leakage, underperforming providers, and cost overruns. Clients consistently report $3,000+ monthly net revenue improvement within the first quarter of engagement.',
      },
      tags: ['profitability', 'cash-flow'],
      targetRoles: ['practice-owner', 'cfo-controller', 'office-manager'],
    },
    {
      id: 'o4',
      title: '75+ Years Combined Experience',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: '75+',
      description: {
        small: 'Backed by 75+ years of financial expertise.',
        medium: '75+ combined years of financial advisory experience across healthcare and dental verticals.',
        large: 'Maven\'s team of 17 financial experts brings over 75 combined years of advisory experience specifically in healthcare, dental, and aesthetic practice finance, not generic small business consulting.',
        overlay: 'With 17 specialists and 75+ years of combined experience concentrated in healthcare practice finance, Maven offers a depth of industry knowledge that general accountants and bookkeepers simply cannot match. This specialization means faster diagnoses, better benchmarks, and strategies that actually work in your specific vertical.',
      },
      tags: ['growth-strategy', 'compliance'],
      targetRoles: ['practice-owner', 'new-practice', 'investor'],
    },
    {
      id: 'o5',
      title: 'Full Financial Visibility in 30 Days',
      cardType: 'outcome',
      icon: 'eye',
      iconType: 'lucide',
      stat: '30 days',
      description: {
        small: 'Gain complete financial clarity within a month.',
        medium: 'Maven delivers a comprehensive financial scorecard and KPI dashboard within your first 30 days.',
        large: 'Within the first 30 days, Maven extracts your financial data, builds a custom scorecard, sets KPI benchmarks, and delivers a detailed analysis that gives you full visibility into your practice\'s financial health.',
        overlay: 'Most practice owners operate without a clear picture of their financial performance. Maven\'s onboarding process delivers full visibility within 30 days: data extraction from your PMS and accounting systems, custom scorecard creation, KPI benchmarking against industry peers, and a deep-dive analysis that reveals exactly where your practice stands and where the opportunities are.',
      },
      tags: ['kpi-tracking', 'cash-flow'],
      targetRoles: ['practice-owner', 'office-manager', 'new-practice'],
    },
    {
      id: 'o6',
      title: 'Optimized Provider Compensation',
      cardType: 'outcome',
      icon: 'calculator',
      iconType: 'lucide',
      stat: '15%+',
      description: {
        small: 'Improve margins through smarter compensation.',
        medium: 'Practices see 15%+ EBITDA improvement through optimized provider compensation models.',
        large: 'Maven builds custom compensation models that align provider incentives with practice profitability, helping owners achieve 15%+ improvement in EBITDA margins while retaining top clinical talent.',
        overlay: 'Provider compensation is typically the largest expense in a healthcare practice. Maven\'s data-driven compensation modeling aligns provider pay with production, collections, and profitability metrics. The result is a fair, transparent structure that motivates performance while improving EBITDA margins by 15% or more.',
      },
      tags: ['compensation', 'profitability'],
      targetRoles: ['practice-owner', 'cfo-controller', 'dso-mso'],
    },
    {
      id: 'o7',
      title: 'Maximized Practice Valuation',
      cardType: 'outcome',
      icon: 'gem',
      iconType: 'lucide',
      stat: '2-3x',
      description: {
        small: 'Increase your practice value for a future exit.',
        medium: 'Practices working with Maven position themselves for 2-3x higher valuations at exit.',
        large: 'Maven\'s strategic financial planning helps practice owners optimize EBITDA, clean up financials, and build systems that position the practice for a 2-3x higher valuation when it comes time to sell or take on investors.',
        overlay: 'Whether you plan to sell in 2 years or 10, practice valuation starts with financial discipline. Maven helps you optimize the metrics buyers care about most: EBITDA margin, revenue growth trajectory, provider retention, and operational scalability. Practices that work with Maven for 12+ months consistently achieve 2-3x higher multiples than industry averages.',
      },
      tags: ['practice-valuation', 'growth-strategy'],
      targetRoles: ['practice-owner', 'investor', 'dso-mso'],
    },

    // ── Learn (8) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Medspa Profitability: The Book',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'book-open',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Maven\'s guide to medspa financial success.',
        medium: 'The definitive guide to medspa profitability from Maven\'s team of financial experts.',
        large: 'Maven\'s book "Medspa Profitability" distills lessons from hundreds of engagements into a practical guide covering pricing, cost control, provider compensation, and growth strategies for medspa owners.',
        overlay: '"Medspa Profitability" is Maven\'s flagship publication, drawing on insights from 300+ practice engagements. It covers the full financial lifecycle of a medspa: pricing strategies, service mix optimization, provider compensation models, marketing ROI, cost control frameworks, and exit planning. Written specifically for medspa owners and operators.',
      },
      tags: ['profitability', 'growth-strategy'],
      targetRoles: ['practice-owner', 'new-practice'],
    },
    {
      id: 'l2',
      title: 'How to Read Your P&L Like a CFO',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Decode your profit and loss statement.',
        medium: 'Learn how to interpret your P&L statement and use it to make better business decisions.',
        large: 'Maven\'s "P&L storytelling" approach teaches practice owners to read their financial statements as a narrative, identifying trends, red flags, and growth opportunities that most owners miss.',
        overlay: 'Your P&L tells a story about your practice, but most owners only see the bottom line. This guide teaches Maven\'s signature P&L storytelling approach: how to read revenue trends by service line, spot cost creep before it erodes margins, benchmark your ratios against industry standards, and use financial data to drive strategic decisions with confidence.',
      },
      tags: ['kpi-tracking', 'profitability'],
      targetRoles: ['practice-owner', 'office-manager', 'new-practice'],
    },
    {
      id: 'l3',
      title: 'KPIs Every Practice Owner Should Track',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'The essential KPIs for healthcare practices.',
        medium: 'Maven\'s team breaks down the KPIs that matter most for dental, medspa, and aesthetic practices.',
        large: 'This video walkthrough covers the essential KPIs for healthcare practice performance: revenue per provider, collection rate, overhead ratio, patient acquisition cost, and lifetime value, with real benchmarks from Maven\'s data.',
        overlay: 'Not all KPIs are created equal. In this video, Maven\'s senior consultants walk through the metrics that actually drive practice profitability. Learn which KPIs to track weekly vs. monthly, how to benchmark against 300+ practices in Maven\'s dataset, and how to build a scorecard that keeps your entire team focused on the numbers that move the needle.',
      },
      tags: ['kpi-tracking', 'profitability'],
      targetRoles: ['practice-owner', 'office-manager', 'cfo-controller'],
    },
    {
      id: 'l4',
      title: 'Compensation Models That Work',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Design compensation that drives performance.',
        medium: 'Webinar on building compensation structures that align provider performance with practice goals.',
        large: 'This recorded webinar covers Maven\'s approach to provider compensation modeling: balancing base vs. production-based pay, setting fair collection targets, and creating structures that retain talent while protecting margins.',
        overlay: 'Provider compensation is the single largest expense in most practices, and getting it wrong leads to either margin erosion or provider turnover. This webinar features Maven\'s senior consultants walking through real-world compensation models that align incentives: base plus production splits, tiered collection bonuses, and equity-based retention strategies.',
      },
      tags: ['compensation', 'profitability'],
      targetRoles: ['practice-owner', 'cfo-controller', 'dso-mso'],
    },
    {
      id: 'l5',
      title: 'The Maven Podcast: Practice Finance',
      cardType: 'learn',
      mediaType: 'podcast',
      icon: 'headphones',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Weekly practice finance insights from Maven.',
        medium: 'Tune in for weekly conversations with practice owners and financial experts on growing profitably.',
        large: 'The Maven Podcast features weekly conversations with practice owners, industry experts, and Maven\'s own team on topics ranging from cash flow management and growth strategy to exit planning and compliance.',
        overlay: 'Each episode of the Maven Podcast features candid conversations about the financial realities of running a healthcare practice. Hear from owners who have scaled from single to multi-location, navigated acquisitions, optimized their compensation models, and achieved financial clarity with Maven\'s support. Real stories, real numbers, real advice.',
      },
      tags: ['growth-strategy', 'profitability'],
      targetRoles: ['practice-owner', 'new-practice', 'investor'],
    },
    {
      id: 'l6',
      title: 'MSO-PC Structures Explained',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Understanding MSO and PC entity structures.',
        medium: 'A guide to Management Services Organization structures for multi-location healthcare practices.',
        large: 'This guide breaks down MSO-PC entity structures, including how fund flows work, how to calculate fair management fees, and the compliance considerations every multi-location practice owner needs to understand.',
        overlay: 'As practices scale to multiple locations, entity structure becomes critical. This guide covers the MSO-PC (Management Services Organization - Professional Corporation) model: how it works, when it makes sense, fund flow mechanics, management fee calculations, tax implications, and the compliance guardrails you need to stay on the right side of corporate practice of medicine laws.',
      },
      tags: ['compliance', 'growth-strategy'],
      targetRoles: ['dso-mso', 'practice-owner', 'investor'],
    },
    {
      id: 'l7',
      title: 'Preparing Your Practice for Sale',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'A roadmap to maximize your exit value.',
        medium: 'Whitepaper on the 12-24 month financial preparation needed to maximize your practice sale price.',
        large: 'This whitepaper outlines Maven\'s proven approach to exit preparation: EBITDA optimization, financial cleanup, systems documentation, and strategic positioning that maximizes your practice valuation over a 12-24 month timeline.',
        overlay: 'Selling a practice is often the largest financial transaction of an owner\'s career. This whitepaper details the financial preparation that maximizes value: EBITDA normalization and optimization, cleaning up owner distributions and personal expenses, documenting systems and processes, building a management layer, and positioning the practice to attract premium buyers at 2-3x higher multiples.',
      },
      tags: ['practice-valuation', 'profitability'],
      targetRoles: ['practice-owner', 'investor', 'cfo-controller'],
    },
    {
      id: 'l8',
      title: 'Budgeting for Growth: A Practical Guide',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'globe',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Build a budget that supports your growth goals.',
        medium: 'Learn how to create a budget aligned with your long-term practice vision and growth targets.',
        large: 'This practical guide walks through Maven\'s budgeting framework: aligning spending with strategic goals, setting revenue targets by service line, planning for capital investments, and building cash reserves to fund growth.',
        overlay: 'Most practice budgets are either nonexistent or disconnected from strategy. Maven\'s budgeting framework ties every dollar to your growth plan: revenue targets by service line and provider, marketing spend tied to patient acquisition cost, staffing models aligned with capacity, and capital reserves for expansion. Learn how to build a budget that is a strategic tool, not just a spreadsheet.',
      },
      tags: ['cash-flow', 'growth-strategy'],
      targetRoles: ['practice-owner', 'office-manager', 'cfo-controller'],
    },

    // ── Solutions (7) ─────────────────────────────────
    {
      id: 's1',
      title: 'Fractional CFO Services',
      cardType: 'solution',
      icon: 'briefcase',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'All the benefits of a CFO at a fraction of the cost.',
        medium: 'Full-scope CFO expertise tailored to your practice, without the six-figure salary.',
        large: 'Maven\'s fractional CFO model gives practice owners access to senior financial strategy, monthly deep dives, KPI tracking, and executive guidance at a price that makes sense for healthcare businesses of all sizes.',
        overlay: 'A full-time CFO costs $200K+ per year, which is out of reach for most practices. Maven\'s fractional model delivers the same caliber of financial leadership through a dedicated consultant who knows your business, attends monthly strategy sessions, builds your scorecards and budgets, and provides on-call guidance for every financial decision.',
      },
      tags: ['profitability', 'kpi-tracking', 'cash-flow'],
      targetRoles: ['practice-owner', 'office-manager', 'new-practice'],
    },
    {
      id: 's2',
      title: 'KPI Scorecard & Benchmarking',
      cardType: 'solution',
      icon: 'bar-chart-2',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Custom scorecards with industry benchmarks.',
        medium: 'Track the metrics that matter with Maven\'s custom KPI scorecards benchmarked against 300+ practices.',
        large: 'Maven builds a custom financial scorecard for your practice, tracking revenue per provider, overhead ratios, collection rates, and patient metrics, all benchmarked against industry standards from 300+ similar practices.',
        overlay: 'Your KPI scorecard is your practice\'s vital signs monitor. Maven builds and maintains a custom dashboard tracking the metrics that drive profitability: revenue per provider, collection rate, overhead ratio, patient acquisition cost, lifetime value, and more. Every metric is benchmarked against Maven\'s proprietary dataset from 300+ practices in your specialty.',
      },
      tags: ['kpi-tracking', 'profitability'],
      targetRoles: ['practice-owner', 'office-manager', 'cfo-controller'],
    },
    {
      id: 's3',
      title: 'Compensation Modeling',
      cardType: 'solution',
      icon: 'users',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Data-driven provider compensation design.',
        medium: 'Build compensation structures that align provider performance with practice profitability.',
        large: 'Maven designs custom compensation models for providers and staff that balance retention, motivation, and profitability using data from hundreds of healthcare practice engagements.',
        overlay: 'Getting compensation wrong is costly: overpay erodes margins, underpay drives turnover. Maven\'s compensation modeling service uses production data, collection rates, and industry benchmarks to design structures that work. From base-plus-production splits to tiered bonus models and equity participation, every model is customized to your practice\'s economics and goals.',
      },
      tags: ['compensation', 'profitability'],
      targetRoles: ['practice-owner', 'cfo-controller', 'dso-mso'],
    },
    {
      id: 's4',
      title: 'Cash Flow Management',
      cardType: 'solution',
      icon: 'wallet',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Optimize your cash flow cycle.',
        medium: 'Gain control of your cash flow with forecasting, collections optimization, and spending accountability.',
        large: 'Maven\'s cash flow management service provides rolling forecasts, collections analysis, expense monitoring, and strategic planning to ensure your practice always has the liquidity to operate and invest in growth.',
        overlay: 'Cash flow problems sink profitable practices. Maven provides rolling 13-week cash flow forecasts, collections cycle analysis, expense categorization and accountability, and strategic reserve planning. You\'ll know exactly where your money goes, when it arrives, and how much runway you have for expansion, equipment purchases, and owner distributions.',
      },
      tags: ['cash-flow', 'profitability'],
      targetRoles: ['practice-owner', 'office-manager', 'cfo-controller'],
    },
    {
      id: 's5',
      title: 'Practice Valuation & Exit Planning',
      cardType: 'solution',
      icon: 'gem',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Know your practice value and grow it.',
        medium: 'Understand your current valuation and build a roadmap to maximize it for a future sale or partnership.',
        large: 'Maven\'s valuation and exit planning service assesses your current practice value, identifies the levers that drive higher multiples, and builds a 12-24 month plan to maximize your exit or partnership terms.',
        overlay: 'Whether you\'re exploring a sale, bringing in a partner, or raising capital, knowing your practice value is essential. Maven provides a comprehensive valuation analysis based on EBITDA multiples, revenue trajectory, and comparable transactions. Then we build a roadmap to maximize value: EBITDA optimization, financial cleanup, systems documentation, and buyer positioning.',
      },
      tags: ['practice-valuation', 'growth-strategy'],
      targetRoles: ['practice-owner', 'investor', 'dso-mso'],
    },
    {
      id: 's6',
      title: 'MSO & Compliance Advisory',
      cardType: 'solution',
      icon: 'shield-check',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Navigate MSO structures and compliance.',
        medium: 'Expert guidance on MSO-PC entity structures, management fees, and regulatory compliance.',
        large: 'Maven helps multi-location practices set up and manage MSO-PC structures, calculate compliant management fees, establish proper fund flows, and navigate the regulatory complexities of healthcare corporate structures.',
        overlay: 'Multi-location healthcare practices need proper entity structures to stay compliant with corporate practice of medicine laws. Maven provides end-to-end MSO advisory: entity formation guidance, management fee calculations that pass regulatory scrutiny, fund flow mapping, intercompany agreements, and ongoing compliance monitoring. We work alongside your legal counsel to ensure your structure is both tax-efficient and legally sound.',
      },
      tags: ['compliance', 'growth-strategy'],
      targetRoles: ['dso-mso', 'practice-owner', 'investor'],
    },
    {
      id: 's7',
      title: 'New Practice Financial Setup',
      cardType: 'solution',
      icon: 'rocket',
      iconType: 'lucide',
      url: 'https://www.mavenfp.com',
      description: {
        small: 'Launch your practice on solid financial footing.',
        medium: 'Complete financial infrastructure setup for new practices, from budgets to KPIs to accounting systems.',
        large: 'Maven\'s new practice package sets up your entire financial infrastructure: chart of accounts, budget, revenue projections, break-even analysis, KPI framework, and ongoing fractional CFO support to guide you through year one.',
        overlay: 'Starting a practice without financial infrastructure is flying blind. Maven\'s new practice setup includes: chart of accounts configuration, 12-month revenue and expense projections, break-even analysis, KPI framework with targets, compensation structure for your first hires, banking and accounting system recommendations, and ongoing fractional CFO support to course-correct as real data comes in.',
      },
      tags: ['cash-flow', 'kpi-tracking', 'growth-strategy'],
      targetRoles: ['new-practice', 'practice-owner'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
