// Explorer Config — Momentify (Trade Shows)
// Branded trade-show kiosk: capture, qualify, personalize, follow up.

import type { ExplorerConfig, ThemeColors } from '../types';

// Momentify brand palette — straight from design-tokens.json
//   cyan #0CF4DF · teal #00BBA5 · blue #254FE5 · deep-blue #1F3395
//   navy #1A2E73 · midnight #0B0B3C · plum #7C316D · bg-dark #07081F
//   Action gradient: cyan → blue · Brand gradient: teal → blue
//   Depth bg: plum 0% → midnight 45% → navy 100%

const MOMENTIFY_DARK: ThemeColors = {
  bg: '#07081F',
  bgGradient: 'linear-gradient(160deg, #1A2E73 0%, #0B0B3C 45%, #07081F 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#0CF4DF',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.78)',
  text3: 'rgba(255,255,255,0.52)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(12,244,223,0.22)',
};

const MOMENTIFY_LIGHT: ThemeColors = {
  bg: '#F4F5FA',
  bgGradient: 'linear-gradient(180deg, #F4F5FA 0%, #EEF3FD 100%)',
  surface: 'rgba(255,255,255,0.88)',
  surfaceHover: 'rgba(255,255,255,0.96)',
  border: 'rgba(11,11,60,0.10)',
  borderFocus: '#1F3395',
  text1: '#061341',
  text2: 'rgba(6,19,65,0.68)',
  text3: 'rgba(6,19,65,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#061341',
  inputPlaceholder: 'rgba(6,19,65,0.38)',
  logoText: '#061341',
  focusRing: 'rgba(31,51,149,0.16)',
};

export const MOMENTIFY_CONFIG: ExplorerConfig = {
  id: 'momentify',
  name: 'Momentify Explorer',
  version: 1,
  createdAt: '2026-05-25T00:00:00.000Z',
  updatedAt: '2026-05-25T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/Momentify-Logo_Reverse.svg',
      light: '/brand/assets/Momentify-Logo.svg',
    },
    icon: '/brand/assets/Momentify-Icon.svg',
    colors: {
      // Brand palette — design-tokens.json
      primary: '#0CF4DF',   // cyan — vibrant accent on dark surfaces
      secondary: '#254FE5', // blue — action gradient endpoint
      teal: '#00BBA5',      // eyebrow / interactive accent
      blue: '#254FE5',
      deepBlue: '#1F3395',  // accent on light surfaces
      navy: '#1A2E73',
      midnight: '#0B0B3C',
      plum: '#7C316D',      // warm gradient anchor
      bgDark: '#07081F',
      dark: MOMENTIFY_DARK,
      light: MOMENTIFY_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    // Vibrant aurora pulled from cyan + blue + plum — same triad as the marketing site
    auroraOrbs: {
      orb1: 'rgba(12,244,223,0.18)',  // cyan
      orb2: 'rgba(37,79,229,0.20)',   // blue
      orb3: 'rgba(124,49,109,0.16)',  // plum
    },
    // CTA = brand gradient (teal → blue, softer). Headline word = action gradient (cyan → blue, vivid).
    ctaGradient: 'linear-gradient(135deg, #00BBA5 0%, #254FE5 100%)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #0CF4DF 0%, #254FE5 100%)',
    // Per-role role backgrounds use the 5 solution-vertical hues so each role lands on a
    // different brand color: violet (Trade Shows), sol-teal (Tech Recruiting), amber (Field
    // Sales), indigo (Facilities), crimson (Venues & Events) — plus cyan / plum anchors.
    roleBackgrounds: {
      'marketing-leader': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(37,79,229,0.32) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(124,49,109,0.22) 0%, transparent 55%)',
      'field-sales': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(242,179,61,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(124,49,109,0.18) 0%, transparent 55%)',
      'demand-gen': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(12,244,223,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(37,79,229,0.20) 0%, transparent 55%)',
      'events-exhibits': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(107,33,212,0.28) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(0,187,165,0.16) 0%, transparent 55%)',
      'sales-ops': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(58,32,115,0.32) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(12,244,223,0.18) 0%, transparent 55%)',
      'product-marketing': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(95,217,194,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(37,79,229,0.18) 0%, transparent 55%)',
      'revops': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(242,94,61,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(37,79,229,0.18) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(124,49,109,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(0,187,165,0.14) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'scan',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Please fill in the form to continue.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Momentify processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: true,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Work Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Company name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Empower Every',
      gradientWord: 'Moment.',
      // Typewriter cycles through 1 main + 5 solution-vertical anchors. The gradient
      // cycles continuously across the 6 brand gradients (action, violet, sol-teal,
      // amber, indigo, crimson) via CSS animation in SplashScreen.
      typewriterWords: [
        'Moment.',         // action — brand
        'Trade Show.',     // violet — Trade Shows & Exhibits
        'Career Fair.',    // sol-teal — Technical Recruiting
        'Field Visit.',    // amber — Field Sales Enablement
        'Facility Tour.',  // indigo — Facilities
        'Experience.',     // crimson — Venues & Events
      ],
      subtitle: 'The operating system for in-person engagement. Momentify converts attention into outcomes your team can measure and prove.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes your role?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'marketing-leader', label: 'Marketing Leader / CMO', icon: 'megaphone', iconType: 'lucide' },
        { value: 'field-sales', label: 'Field Sales Leader', icon: 'briefcase', iconType: 'lucide' },
        { value: 'demand-gen', label: 'Demand Gen / Growth', icon: 'trending-up', iconType: 'lucide' },
        { value: 'events-exhibits', label: 'Events & Exhibits', icon: 'tent', iconType: 'lucide' },
        { value: 'sales-ops', label: 'Sales Ops', icon: 'settings', iconType: 'lucide' },
        { value: 'product-marketing', label: 'Product Marketing', icon: 'sparkles', iconType: 'lucide' },
        { value: 'revops', label: 'RevOps', icon: 'workflow', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'message-circle', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What do you want to solve at your next event?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'lead-capture', label: 'Lead Capture Efficiency', icon: 'scan-line', iconType: 'lucide' },
        { value: 'engagement-quality', label: 'Engagement Quality', icon: 'hand', iconType: 'lucide' },
        { value: 'follow-up', label: 'Follow-Up Speed', icon: 'send', iconType: 'lucide' },
        { value: 'conversion', label: 'Conversion Effectiveness', icon: 'target', iconType: 'lucide' },
        { value: 'rox-measurement', label: 'ROX Measurement', icon: 'gauge', iconType: 'lucide' },
        { value: 'personalization', label: 'Personalized Content', icon: 'user-check', iconType: 'lucide' },
        { value: 'integrations', label: 'CRM & MAP Integrations', icon: 'plug', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Outcomes, content, and solutions tailored to how you run events.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        {
          id: 'learn',
          label: 'Learn',
          icon: 'book-open',
          filters: [
            { label: 'All', value: 'all' },
            { label: 'Video', value: 'video' },
            { label: 'Blog', value: 'blog' },
            { label: 'Webinar', value: 'webinar' },
            { label: 'PDF', value: 'pdf' },
          ],
        },
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content is on its way.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: '92% More Leads, 3 Years Running',
      cardType: 'outcome',
      icon: 'trending-up',
      iconType: 'lucide',
      stat: '92%',
      description: {
        small: '92% more leads at the same event, 3 years in a row.',
        medium: 'Momentify customers have produced 92% more leads at the same event, three consecutive years.',
        large: 'Year over year over year, Momentify customers have delivered 92% more leads at the same event without expanding their booth footprint, headcount, or sponsorship tier.',
        overlay: 'The compounding case for Momentify: 92% more leads at the same event, three consecutive years. Same square footage, same staff, same show. The difference is replacing badge scans with engagement-aware capture that records role, interest, and intent — then routing that data to reps before the booth closes.',
      },
      tags: ['lead-capture', 'rox-measurement'],
      targetRoles: ['marketing-leader', 'field-sales', 'demand-gen'],
    },
    {
      id: 'o2',
      title: '65%+ Qualified Leads',
      cardType: 'outcome',
      icon: 'target',
      iconType: 'lucide',
      stat: '65%+',
      description: {
        small: 'Momentify customers see 65%+ qualified leads.',
        medium: 'Momentify lifts qualified-lead rates above 65%, versus an industry average below 20%.',
        large: 'Industry average qualified-lead rates from trade shows sit below 20%. Momentify customers consistently see 65%+ qualified leads by capturing role, interest, and intent alongside the badge scan.',
        overlay: 'Most trade show leads land in CRM as a name and a company. Momentify customers see 65%+ of captured leads come through fully qualified — role, interest, and intent attached — versus an industry average below 20%. That is the difference between an SDR queue worth working and a spreadsheet that never gets opened.',
      },
      tags: ['lead-capture', 'engagement-quality', 'conversion'],
      targetRoles: ['marketing-leader', 'demand-gen', 'field-sales'],
    },
    {
      id: 'o3',
      title: '10,000+ Leads Across 50 Events',
      cardType: 'outcome',
      icon: 'scan-line',
      iconType: 'lucide',
      stat: '10K+',
      description: {
        small: '10,000+ leads captured across 50 events in 18 months.',
        medium: 'Momentify customers have captured 10,000+ leads across 50 events in 18 months.',
        large: 'Across a single 18-month program, Momentify customers have captured 10,000+ leads across 50 events — with $411M in potential pipeline value attached.',
        overlay: 'A real customer program: 10,000+ leads captured across 50 events in 18 months, with $411M in potential pipeline value tied directly to event spend. Every lead carries role, interest, content engagement, and follow-up routing — making the program legible to finance, not just marketing.',
      },
      tags: ['lead-capture', 'rox-measurement', 'conversion'],
      targetRoles: ['marketing-leader', 'events-exhibits', 'demand-gen'],
    },
    {
      id: 'o4',
      title: 'Your Live ROX Score',
      cardType: 'outcome',
      icon: 'gauge',
      iconType: 'lucide',
      stat: 'Live',
      description: {
        small: 'One score across four categories that tells you whether your moments worked.',
        medium: 'ROX™ scores Lead Capture Efficiency, Engagement Quality, Follow-Up Speed, and Conversion Effectiveness in one live gauge.',
        large: 'Return on Experience (ROX)™ combines four categories — Lead Capture Efficiency, Engagement Quality, Follow-Up Speed, and Conversion Effectiveness — into a single live score with Critical Gap, Needs Optimization, High ROX, and Elite ROX tiers.',
        overlay: 'ROX™ is "one score across four categories that tells you whether your moments actually worked." Lead Capture Efficiency, Engagement Quality, Follow-Up Speed, and Conversion Effectiveness all feed a single live gauge with four tiers — Critical Gap, Needs Optimization, High ROX, and Elite ROX. Calculate yours with no login required.',
      },
      tags: ['rox-measurement', 'engagement-quality', 'conversion'],
      targetRoles: ['marketing-leader', 'demand-gen', 'events-exhibits'],
    },
    {
      id: 'o5',
      title: '85% More Content Visibility',
      cardType: 'outcome',
      icon: 'eye',
      iconType: 'lucide',
      stat: '85%',
      description: {
        small: 'Digital delivery lifts content visibility 85% over print.',
        medium: '85% more content gets seen at the booth versus traditional print collateral.',
        large: 'Replacing printed brochures with Momentify\'s personalized, role-aware content delivery lifts content visibility by 85% — and tells you which pieces actually got engaged with.',
        overlay: 'Printed brochures land in the bottom of a bag. Momentify delivers personalized content based on attendee role, interest, and pain point — lifting content visibility 85% over traditional print materials and giving product marketing real engagement signal on every asset.',
      },
      tags: ['personalization', 'engagement-quality'],
      targetRoles: ['product-marketing', 'marketing-leader', 'events-exhibits'],
    },
    {
      id: 'o6',
      title: '<20% Can Prove Event ROI',
      cardType: 'outcome',
      icon: 'alert-triangle',
      iconType: 'lucide',
      stat: '$50B',
      description: {
        small: '$50B is spent annually with under 20% proving ROI.',
        medium: 'Of $50B+ spent annually on in-person engagement, fewer than 1 in 5 organizations can tie spend to outcomes.',
        large: 'US organizations spend $50B+ a year on trade shows, recruiting events, and facility visits. Fewer than 1 in 5 can tie that spend to measurable outcomes. Momentify is built to close that gap.',
        overlay: '$50B+ is spent annually in the US on trade shows, recruiting events, and facility visits — yet fewer than 1 in 5 organizations can tie that spend to measurable outcomes. Momentify is the operating system that converts attention into outcomes your team can actually measure and prove.',
      },
      tags: ['rox-measurement', 'conversion'],
      targetRoles: ['marketing-leader', 'revops', 'demand-gen'],
    },
    {
      id: 'o7',
      title: '544 Follow-Ups Routed Automatically',
      cardType: 'outcome',
      icon: 'send',
      iconType: 'lucide',
      stat: '544',
      description: {
        small: '544 follow-ups routed to the right reps automatically.',
        medium: 'In one program: 1,952 companies represented and 544 follow-ups routed to the right reps automatically.',
        large: 'Industry-average post-show follow-up takes 7+ days. Momentify cut it to instant in a program with 1,952 companies represented and 544 follow-ups routed to the right reps automatically.',
        overlay: 'The industry average is 7+ days to first follow-up after a show. In a recent Momentify program, 1,952 companies were represented at the booth and 544 follow-ups were routed to the right reps automatically — by interest, intent, and territory — before anyone left the floor.',
      },
      tags: ['follow-up', 'integrations'],
      targetRoles: ['sales-ops', 'revops', 'demand-gen'],
    },

    // ── Learn (8) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Calculate Your Trade Show ROX',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'gauge',
      iconType: 'lucide',
      url: 'https://momentifyapp.com/solutions/trade-shows',
      description: {
        small: 'Score your last show across the four ROX™ categories.',
        medium: 'Score your last show on Lead Capture Efficiency, Engagement Quality, Follow-Up Speed, and Conversion Effectiveness.',
        large: 'The ROX calculator scores any program against the four categories of Return on Experience — and places you on the Critical Gap → Elite ROX scale. No login required.',
        overlay: 'Find out where your last show actually lands. The ROX calculator scores any program across Lead Capture Efficiency, Engagement Quality, Follow-Up Speed, and Conversion Effectiveness, then places you on the four-tier scale: Critical Gap, Needs Optimization, High ROX, or Elite ROX. No login required — just your numbers.',
      },
      tags: ['rox-measurement', 'lead-capture', 'engagement-quality'],
      targetRoles: ['marketing-leader', 'demand-gen', 'events-exhibits'],
    },
    {
      id: 'l2',
      title: 'Your Booth Deserves More Than Badge Scans',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://momentifyapp.com/solutions/trade-shows',
      description: {
        small: 'The engagement platform between "Hello" and CRM.',
        medium: 'The case for replacing badge scanners with engagement-aware capture that records role, interest, and intent.',
        large: 'Badge scanners record presence. Momentify records role, interest, and intent — the engagement layer between "Hello" at the booth and the lead landing in CRM.',
        overlay: 'A badge scan tells you who walked by. An engagement-aware booth tells you what they cared about, what they read, and what they want next. This piece makes the case for retiring badge scanners as the system of record at the booth and replacing them with an engagement platform that lives between "Hello" and CRM.',
      },
      tags: ['lead-capture', 'engagement-quality'],
      targetRoles: ['marketing-leader', 'events-exhibits', 'product-marketing'],
    },
    {
      id: 'l3',
      title: 'The Four Categories of ROX™',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'bar-chart-2',
      iconType: 'lucide',
      url: 'https://momentifyapp.com',
      description: {
        small: 'Lead Capture, Engagement, Follow-Up, Conversion.',
        medium: 'A breakdown of the four categories that make up the Return on Experience (ROX)™ score.',
        large: 'Inside the ROX™ framework: Lead Capture Efficiency (% of visitors becoming leads), Engagement Quality (depth of interaction with content), Follow-Up Speed (team response time), and Conversion Effectiveness (leads converting to meetings, hires, or deals).',
        overlay: 'A breakdown of the four categories that make up the Return on Experience (ROX)™ score: Lead Capture Efficiency measures the percentage of visitors becoming leads. Engagement Quality measures depth of interaction with content. Follow-Up Speed measures team response time post-event. Conversion Effectiveness measures leads converting to meetings, hires, or deals. Together they roll into the Critical Gap → Elite ROX gauge.',
      },
      tags: ['rox-measurement', 'engagement-quality', 'conversion'],
      targetRoles: ['marketing-leader', 'demand-gen', 'revops'],
    },
    {
      id: 'l4',
      title: 'From Booth Traffic to Pipeline',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://momentifyapp.com/solutions/trade-shows',
      description: {
        small: 'See a Momentify booth in action — Hello to CRM.',
        medium: 'A walkthrough of a Momentify-powered booth from first hello to CRM-routed lead.',
        large: 'A short product walkthrough showing the path from booth hello to CRM — badge enrichment, personalized content, real-time lead scoring, and automatic Salesforce/HubSpot routing.',
        overlay: 'A short product walkthrough showing the path from first hello at the booth to a fully-attributed CRM record: badge enrichment with role and interest, personalized content delivery by pain point, real-time lead scoring by engagement depth, and automatic routing into Salesforce or HubSpot before the visitor leaves the floor.',
      },
      tags: ['lead-capture', 'engagement-quality', 'follow-up'],
      targetRoles: ['events-exhibits', 'field-sales', 'marketing-leader'],
    },
    {
      id: 'l5',
      title: 'Mustang Cat Case Study',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'award',
      iconType: 'lucide',
      url: 'https://momentifyapp.com/case-studies/mustang-cat',
      description: {
        small: '7 hires traced to a digital recruiting program.',
        medium: 'How Mustang Cat traced 7 hires and matched 40 dealers with candidates through Momentify.',
        large: 'How Mustang Cat used Momentify\'s Technical Recruiting motion to trace 7 hires and match 40 dealers with candidates from a single program — replacing clipboards with real-time qualification.',
        overlay: 'Mustang Cat replaced clipboards and post-event lead spreadsheets with Momentify at recruiting events. The program traced 7 hires directly to the digital recruiting process and matched 40 dealers with candidates from a single program. Candidates self-qualified by role and shift preference; recruiters got real-time alerts on high-fit walk-ups.',
      },
      tags: ['lead-capture', 'follow-up', 'engagement-quality'],
      targetRoles: ['events-exhibits', 'marketing-leader', 'sales-ops'],
    },
    {
      id: 'l6',
      title: 'Integrations: Salesforce, HubSpot & More',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'plug',
      iconType: 'lucide',
      url: 'https://momentifyapp.com/solutions/trade-shows',
      description: {
        small: 'Sync leads to Salesforce and HubSpot automatically.',
        medium: 'Sync captured leads to Salesforce and HubSpot automatically, with full engagement context attached.',
        large: 'A reference for Momentify\'s integrations layer — automatic sync to Salesforce and HubSpot, lead scoring by engagement depth, and webhook patterns for the rest of your stack.',
        overlay: 'Captured leads are only useful when they reach the right rep, in the right system, with the right context. Momentify syncs leads to Salesforce and HubSpot automatically with role, interest, content viewed, dwell time, and a real-time engagement score attached — and webhook patterns extend the same flow to Marketo, Pardot, Outreach, Salesloft, and anything else.',
      },
      tags: ['integrations', 'follow-up'],
      targetRoles: ['sales-ops', 'revops', 'demand-gen'],
    },
    {
      id: 'l7',
      title: 'Recap Decks With One-Click Charts',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'presentation',
      iconType: 'lucide',
      url: 'https://momentifyapp.com/solutions/trade-shows',
      description: {
        small: 'Export insights into recap decks with one click.',
        medium: 'Export engagement insights into recap decks with one-click chart copy.',
        large: 'Every Momentify dashboard supports one-click chart copy directly into recap decks — so the exec readout writes itself instead of consuming an analyst for two weeks.',
        overlay: 'The week after a show usually disappears into manual deck-building. Momentify lets you export every engagement insight directly into your recap deck with one-click chart copy — booth performance, ROX score, top-engaged content, and follow-up status — so the exec readout writes itself instead of consuming an analyst for two weeks.',
      },
      tags: ['rox-measurement', 'engagement-quality'],
      targetRoles: ['marketing-leader', 'demand-gen', 'events-exhibits'],
    },
    {
      id: 'l8',
      title: 'Built for Event Teams in the Field',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'tablet-smartphone',
      iconType: 'lucide',
      url: 'https://momentifyapp.com/solutions/trade-shows',
      description: {
        small: 'iOS and Windows apps for booth and field teams.',
        medium: 'Native iOS and Windows apps plus QR-enabled mobile engagement for walk-ups.',
        large: 'Momentify runs natively on iOS and Windows for booth and field teams — plus QR-enabled mobile engagement so any walk-up can self-serve on their phone.',
        overlay: 'Built for the people actually running the booth: native iOS app for iPad kiosks and rep tablets, native Windows app for desktop scanning stations, and QR-enabled mobile engagement so walk-ups can self-serve on their own phone. Same experience, same data, same real-time ROX score across every surface.',
      },
      tags: ['lead-capture', 'engagement-quality'],
      targetRoles: ['events-exhibits', 'field-sales', 'sales-ops'],
    },

    // ── Solutions (7) ─────────────────────────────────
    {
      id: 's1',
      title: 'Trade Shows & Exhibits',
      cardType: 'solution',
      icon: 'tent',
      iconType: 'lucide',
      url: 'https://momentifyapp.com/solutions/trade-shows',
      description: {
        small: 'From branded space to outcome-driven experience.',
        medium: 'The engagement platform between "Hello" and CRM — capture, qualify, personalize, follow up.',
        large: 'Momentify for Trade Shows & Exhibits replaces badge scanners with the engagement platform between "Hello" and CRM — real-time lead capture, personalized content delivery, engagement analytics, and integrations that work.',
        overlay: 'Your booth deserves more than just badge scans. Momentify for Trade Shows & Exhibits is the engagement platform between "Hello" and CRM: real-time lead capture with role and interest, personalized content delivery by pain point, engagement analytics by depth, and CRM integrations that route the right lead to the right rep before the booth closes.',
      },
      tags: ['lead-capture', 'rox-measurement', 'engagement-quality'],
      targetRoles: ['marketing-leader', 'events-exhibits', 'field-sales', 'demand-gen'],
    },
    {
      id: 's2',
      title: 'Technical Recruiting',
      cardType: 'solution',
      icon: 'user-plus',
      iconType: 'lucide',
      url: 'https://momentifyapp.com',
      description: {
        small: 'Score recruiting events on candidate quality and speed.',
        medium: 'Score recruiting events on candidate quality and follow-up speed — with ROX™ for talent.',
        large: 'Momentify for Technical Recruiting scores recruiting events on candidate quality and follow-up speed, letting candidates self-qualify by role and shift preference while recruiters get real-time alerts on top matches.',
        overlay: 'Recruiting events run on clipboards and chaos. Momentify for Technical Recruiting scores each event on candidate quality and follow-up speed — candidates self-qualify by role, location, and shift preference; recruiters get real-time alerts on top matches; the ATS gets a fully-attributed candidate record before the candidate leaves the booth.',
      },
      tags: ['lead-capture', 'engagement-quality', 'follow-up'],
      targetRoles: ['marketing-leader', 'sales-ops', 'revops', 'events-exhibits'],
    },
    {
      id: 's3',
      title: 'Field Sales Enablement',
      cardType: 'solution',
      icon: 'briefcase',
      iconType: 'lucide',
      url: 'https://momentifyapp.com',
      description: {
        small: 'Track rep engagement across job sites and visits.',
        medium: 'Track rep engagement across job sites, customer visits, and on-site meetings.',
        large: 'Momentify for Field Sales Enablement tracks rep engagement across job sites and customer visits — the same personalized, ROX-scored experience that powers the booth, brought to every account visit.',
        overlay: 'Field reps walk into accounts armed with whatever PDFs they had time to download. Momentify for Field Sales Enablement tracks rep engagement across job sites and customer visits — a personalized, branded, tablet-ready experience built for the meeting in front of them, with every touch logged to CRM and scored on the same ROX scale as the booth.',
      },
      tags: ['personalization', 'engagement-quality', 'conversion'],
      targetRoles: ['field-sales', 'sales-ops', 'product-marketing'],
    },
    {
      id: 's4',
      title: 'Facilities',
      cardType: 'solution',
      icon: 'building-2',
      iconType: 'lucide',
      url: 'https://momentifyapp.com',
      description: {
        small: 'Measure interaction depth across showrooms & demos.',
        medium: 'Measure interaction depth across showrooms, demo centers, and training centers.',
        large: 'Momentify for Facilities measures interaction depth across showrooms, demo centers, and training centers — turning permanent spaces into always-on, ROX-scored engagement moments.',
        overlay: 'Showrooms, demo centers, and training centers see the highest-intent visitors of any channel — but capture almost nothing. Momentify for Facilities measures interaction depth across each space, turning permanent installations into always-on, branded experiences that capture, personalize, and follow up just like a show booth, 365 days a year.',
      },
      tags: ['engagement-quality', 'personalization'],
      targetRoles: ['events-exhibits', 'marketing-leader', 'product-marketing'],
    },
    {
      id: 's5',
      title: 'Venues & Events',
      cardType: 'solution',
      icon: 'calendar-days',
      iconType: 'lucide',
      url: 'https://momentifyapp.com',
      description: {
        small: 'Score event spaces on engagement and conversion.',
        medium: 'Score event spaces on visitor engagement and conversion across the full event lifecycle.',
        large: 'Momentify for Venues & Events scores event spaces on visitor engagement and conversion — covering check-in, session engagement, sponsor activations, and post-event nurture.',
        overlay: 'Conference organizers stitch together six tools to run an event. Momentify for Venues & Events scores the entire space on visitor engagement and conversion — check-in, session engagement, sponsor activations, and post-event nurture — giving organizers a single attendee record and sponsors real, attributable ROI.',
      },
      tags: ['engagement-quality', 'rox-measurement', 'follow-up'],
      targetRoles: ['events-exhibits', 'marketing-leader', 'demand-gen'],
    },
    {
      id: 's6',
      title: 'Return on Experience (ROX)™',
      cardType: 'solution',
      icon: 'gauge',
      iconType: 'lucide',
      url: 'https://momentifyapp.com',
      description: {
        small: 'One score that tells you if your moments worked.',
        medium: 'One score across four categories that tells you whether your moments actually worked.',
        large: 'ROX™ is the measurement layer that runs across every Momentify solution — Lead Capture Efficiency, Engagement Quality, Follow-Up Speed, and Conversion Effectiveness rolled into a single live score.',
        overlay: 'Return on Experience (ROX)™ is the measurement layer that runs across every Momentify solution. One score across four categories — Lead Capture Efficiency, Engagement Quality, Follow-Up Speed, Conversion Effectiveness — placed on the Critical Gap → Elite ROX scale. Comparable across events, programs, and verticals, with no login required to calculate your first score.',
      },
      tags: ['rox-measurement', 'engagement-quality', 'conversion'],
      targetRoles: ['marketing-leader', 'demand-gen', 'revops', 'events-exhibits'],
    },
    {
      id: 's7',
      title: 'CRM & MAP Integrations',
      cardType: 'solution',
      icon: 'workflow',
      iconType: 'lucide',
      url: 'https://momentifyapp.com',
      description: {
        small: 'Sync leads to Salesforce and HubSpot automatically.',
        medium: 'Auto-sync engagement-aware leads to Salesforce, HubSpot, and the rest of your stack.',
        large: 'Captured leads sync to Salesforce and HubSpot automatically — with role, interest, content viewed, dwell time, and live engagement score attached — plus webhook patterns for Marketo, Pardot, Outreach, Salesloft, and beyond.',
        overlay: 'A captured lead is only useful when it reaches the right rep, in the right system, with the right context. Momentify\'s integrations layer syncs engagement-aware leads to Salesforce and HubSpot automatically — role, interest, content viewed, dwell time, and a live engagement score attached — with webhook patterns extending the same flow to Marketo, Pardot, Outreach, Salesloft, and Zapier.',
      },
      tags: ['integrations', 'follow-up'],
      targetRoles: ['sales-ops', 'revops', 'demand-gen'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: true,
    captureInfo: true,
  },
};
