// Explorer Config — Mustang CAT Management Training Program
// On-campus recruiting kiosk for Mustang CAT's MTP funnel.
// Personalizes content by college, degree area, and opportunity interest.

import type { ExplorerConfig, ThemeColors } from '../types';

// ─── Theme ────────────────────────────────────────
// CAT yellow + black branding. Black-dominant dark theme with yellow accents.

const MUSTANG_DARK: ThemeColors = {
  bg: '#0A0A0A',
  bgGradient: 'linear-gradient(135deg, #1A1500 0%, #0A0A0A 55%, #1F1A00 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#FFCC00',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(255,204,0,0.25)',
};

const MUSTANG_LIGHT: ThemeColors = {
  bg: '#F6F6F2',
  bgGradient: 'linear-gradient(180deg, #F8F7F2 0%, #F3F2EC 100%)',
  surface: 'rgba(255,255,255,0.92)',
  surfaceHover: 'rgba(255,255,255,1.00)',
  border: 'rgba(20,20,20,0.10)',
  borderFocus: '#C9A200',
  text1: '#0A0A0A',
  text2: 'rgba(10,10,10,0.65)',
  text3: 'rgba(10,10,10,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0A0A0A',
  inputPlaceholder: 'rgba(10,10,10,0.35)',
  logoText: '#0A0A0A',
  focusRing: 'rgba(201,162,0,0.15)',
};

export const MUSTANG_CAT_MTP_CONFIG: ExplorerConfig = {
  id: 'mustang-cat-mtp',
  name: 'Mustang CAT — MTP Recruiting',
  kind: 'recruiter',
  version: 1,
  createdAt: '2026-06-16T00:00:00.000Z',
  updatedAt: '2026-06-16T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/mustang-cat-mtp-dark.png',
      light: '/brand/assets/mustang-cat-mtp-light.png',
    },
    icon: '/brand/assets/mustang-cat-mtp-light.png',
    colors: {
      primary: '#FFCC00',
      secondary: '#000000',
      teal: '#FFCC00',
      blue: '#3D3D3D',
      deepBlue: '#1F1F1F',
      navy: '#15140A',
      midnight: '#0A0A05',
      plum: '#7A6300',
      bgDark: '#0A0A0A',
      dark: MUSTANG_DARK,
      light: MUSTANG_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(255,204,0,0.14)',
      orb2: 'rgba(255,204,0,0.10)',
      orb3: 'rgba(122,99,0,0.12)',
    },
    ctaGradient: 'linear-gradient(135deg, #FFCC00, #C9A200)',
    ctaTextColor: '#0A0A0A',
    gradientWord: 'linear-gradient(135deg, #FFE066, #FFCC00)',
    roleBackgrounds: {
      'sfa': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(106,0,50,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(255,204,0,0.10) 0%, transparent 55%)',
      'tamu': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(80,0,0,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(255,204,0,0.10) 0%, transparent 55%)',
      'shsu': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(243,106,45,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(255,204,0,0.08) 0%, transparent 55%)',
      'baylor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,48,21,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(255,204,0,0.12) 0%, transparent 55%)',
      'texas-tech': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(204,0,0,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(255,204,0,0.08) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,204,0,0.14) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(122,99,0,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Welcome to the MTP Recruiting Booth',
    formSubtitle: 'Drop your info so we can stay in touch after the fair.',
    scanLabel: 'Scan Your Resume QR',
    scanHint: 'Hold your QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Mustang Cat processing your data to follow up about the Management Training Program.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@school.edu', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      {
        id: 'graduationDate',
        label: 'Expected Graduation',
        type: 'select',
        placeholder: 'Select semester',
        required: true,
        halfWidth: true,
        options: [
          'Spring 2026',
          'Summer 2026',
          'Fall 2026',
          'Spring 2027',
          'Summer 2027',
          'Fall 2027',
          'Spring 2028',
          'Summer 2028',
          'Fall 2028',
          'Spring 2029 or later',
        ],
      },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Build Your Career at',
      gradientWord: 'Mustang Cat.',
      subtitle: 'Discover the Management Training Program — your launchpad into a long-term career in heavy equipment.',
      buttonText: 'Tap to Begin',
      // Background image hook: drop a hero into /brand/assets/ and reference it here.
      // backgroundImage: '/brand/assets/mustangcat-interview-bg.jpg',
      // backgroundImageOverlay: 'rgba(10,10,10,0.55)',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'Which school are you with?',
      subtitle: 'Pick your college so we can tailor your experience.',
      showGreeting: true,
      showSelectAll: false,
      // TODO: swap `iconType: 'lucide'` → `iconType: 'image'` with `/brand/assets/college-*.svg`
      // once branded SVG marks are sourced for SFA, TAMU, SHSU, Baylor, Texas Tech.
      options: [
        { value: 'sfa', label: 'Stephen F. Austin', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'tamu', label: 'Texas A&M', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'shsu', label: 'Sam Houston State', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'baylor', label: 'Baylor', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'texas-tech', label: 'Texas Tech', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'school', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you studying?',
      subtitle: 'Pick the areas that match your degree — we will surface the best-fit tracks.',
      showGreeting: false,
      showSelectAll: false,
      layout: 'list',
      showMostSelected: true,
      mostSelectedLimit: 3,
      // Sorted A→Z by label so candidates can scan quickly.
      options: [
        { value: 'agribusiness', label: 'Agribusiness / Ag Science', icon: 'sprout', iconType: 'lucide' },
        { value: 'architecture-design', label: 'Architecture & Design', icon: 'pencil-ruler', iconType: 'lucide' },
        { value: 'arts', label: 'Arts & Performing Arts', icon: 'palette', iconType: 'lucide' },
        { value: 'business-econ', label: 'Business & Economics', icon: 'briefcase', iconType: 'lucide' },
        { value: 'comms-media', label: 'Communications & Media', icon: 'megaphone', iconType: 'lucide' },
        { value: 'cs-it', label: 'Computer Science / IT', icon: 'cpu', iconType: 'lucide' },
        { value: 'education', label: 'Education', icon: 'school', iconType: 'lucide' },
        { value: 'engineering', label: 'Engineering', icon: 'hard-hat', iconType: 'lucide' },
        { value: 'environmental', label: 'Environmental Studies', icon: 'tree-pine', iconType: 'lucide' },
        { value: 'health-sciences', label: 'Health Sciences', icon: 'heart-pulse', iconType: 'lucide' },
        { value: 'humanities', label: 'Humanities', icon: 'book-open', iconType: 'lucide' },
        { value: 'law-cj', label: 'Law & Criminal Justice', icon: 'gavel', iconType: 'lucide' },
        { value: 'math-stats', label: 'Math & Statistics', icon: 'calculator', iconType: 'lucide' },
        { value: 'mis', label: 'Management Info Systems', icon: 'database', iconType: 'lucide' },
        { value: 'natural-sciences', label: 'Natural Sciences', icon: 'flask-conical', iconType: 'lucide' },
        { value: 'social-sciences', label: 'Social Sciences', icon: 'users', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'opportunity',
      selectionMode: 'single',
      title: 'What kind of opportunity?',
      subtitle: 'Tell us how you want to start.',
      showGreeting: false,
      showSelectAll: false,
      options: [
        { value: 'internship', label: 'Internship', icon: 'briefcase', iconType: 'lucide' },
        { value: 'full-time', label: 'Full-Time Position', icon: 'rocket', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'location',
      selectionMode: 'single',
      title: 'Where would you like to work?',
      subtitle: 'Pick a Mustang Cat location — or pick Other / Multiple if you are flexible.',
      showGreeting: false,
      showSelectAll: false,
      options: [
        { value: 'houston', label: 'Mustang Cat — Houston', icon: 'building', iconType: 'lucide' },
        { value: 'beaumont', label: 'Mustang Cat — Beaumont', icon: 'building', iconType: 'lucide' },
        { value: 'bryan', label: 'Mustang Cat — Bryan', icon: 'building', iconType: 'lucide' },
        { value: 'el-campo', label: 'Mustang Cat — El Campo', icon: 'building', iconType: 'lucide' },
        { value: 'rental', label: 'Rental Stores / Multiple', icon: 'warehouse', iconType: 'lucide' },
        { value: 'other-location', label: 'Other / Open to Anywhere', icon: 'map-pin', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Before You Go',
      subtitle: 'Watch this short video about the Mustang Cat Management Training Program.',
      tabs: [
        { id: 'learn', label: 'Watch', icon: 'play-circle' },
      ],
      cardsPerPage: 1,
      defaultView: 'large',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share — we will email these to you after the fair.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Explore everything Mustang Cat has to offer new graduates.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'A recruiter will follow up shortly. Watch your inbox for next steps.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── The closing video — the only card on the results screen ──
    {
      id: 'mtp-overview',
      title: 'Learn More About Our MTP — Watch Before You Go',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: '/brand/assets/mustang-cat-mtp-overview.mp4',
      description: {
        small: 'The closing video on the Mustang Cat MTP.',
        medium: 'A short film about the Mustang Cat Developmental Management and Sales Training Program. Watch before you leave the booth.',
        large: 'A short film about the Mustang Cat Developmental Management and Sales Training Program — directly from our team. The MTP captures everything we offer to new graduates. Watch this before you leave the booth.',
        overlay: 'A short film about the Mustang Cat Developmental Management and Sales Training Program — directly from the team that runs it. Every Recruiting Fair candidate is encouraged to watch this video before leaving the booth. It captures the rotations, the mentorship, the locations, and what life after MTP looks like.',
      },
      tags: ['overview', 'program-structure', 'closing'],
      targetRoles: ['sfa', 'tamu', 'shsu', 'baylor', 'texas-tech', 'other'],
    },
  ],


  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
