// Explorer Config — Mustang CAT Recruiting
// Career fair / campus recruiting kiosk for ThinkBIG, T4W, and open positions.
// Same black/yellow CAT brand as mustang-cat-mtp; content focused on
// students, parents, and career-changers exploring technician paths.

import type { ExplorerConfig, ThemeColors } from '../types';

const MUSTANG_DARK: ThemeColors = {
  bg: '#0A0A0A',
  bgGradient: 'linear-gradient(135deg, #1A1500 0%, #0A0A0A 55%, #1F1A00 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#FFCC00',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(255,204,0,0.25)',
};

const MUSTANG_LIGHT: ThemeColors = {
  bg: '#F6F6F2',
  bgGradient: 'linear-gradient(180deg, #F8F7F2 0%, #F3F2EC 100%)',
  surface: 'rgba(255,255,255,0.92)',
  surfaceHover: 'rgba(255,255,255,1.00)',
  border: 'rgba(20,20,20,0.10)',
  borderFocus: '#C9A200',
  text1: '#0A0A0A',
  text2: 'rgba(10,10,10,0.65)',
  text3: 'rgba(10,10,10,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0A0A0A',
  inputPlaceholder: 'rgba(10,10,10,0.35)',
  logoText: '#0A0A0A',
  focusRing: 'rgba(201,162,0,0.15)',
};

export const MUSTANG_CAT_RECRUIT_CONFIG: ExplorerConfig = {
  id: 'mustang-cat-recruit',
  name: 'Mustang CAT — Recruiting Explorer',
  kind: 'recruiter',
  version: 1,
  createdAt: '2026-07-08T00:00:00.000Z',
  updatedAt: '2026-07-08T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/mustang-cat-mtp-dark.png',
      light: '/brand/assets/mustang-cat-mtp-light.png',
    },
    icon: '/brand/assets/mustang-cat-recruit-icon.png',
    colors: {
      primary: '#FFCC00',
      secondary: '#000000',
      teal: '#FFCC00',
      blue: '#3D3D3D',
      deepBlue: '#1F1F1F',
      navy: '#15140A',
      midnight: '#0A0A05',
      plum: '#7A6300',
      bgDark: '#0A0A0A',
      dark: MUSTANG_DARK,
      light: MUSTANG_LIGHT,
    },
    font: 'Inter',
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(255,204,0,0.14)',
      orb2: 'rgba(255,204,0,0.10)',
      orb3: 'rgba(122,99,0,0.12)',
    },
    ctaGradient: 'linear-gradient(135deg, #FFCC00, #C9A200)',
    ctaTextColor: '#0A0A0A',
    gradientWord: '#FFCC00',
    roleBackgrounds: {
      'student':   'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,204,0,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(122,99,0,0.10) 0%, transparent 55%)',
      'advisor':   'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,204,0,0.14) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(100,80,0,0.12) 0%, transparent 55%)',
      'parent':    'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(200,160,0,0.14) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(255,204,0,0.08) 0%, transparent 55%)',
      'exploring': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,204,0,0.12) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(122,99,0,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Stay Connected',
    formSubtitle: 'Share your info and we\'ll follow up with program details and next steps.',
    scanLabel: 'Scan Your Resume QR',
    scanHint: 'Hold your QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to Mustang Cat processing your data to fulfill your request and send relevant follow-up communications. Please refer to our Privacy Policy for details.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@example.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Build Your Future at',
      gradientWord: 'Mustang Cat.',
      subtitle: 'Discover ThinkBIG, free online certification, and open career opportunities — your path to a rewarding career in construction and energy.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What describes you best?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'student', label: 'Student / Job Seeker', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'advisor', label: 'Advisor / Instructor', icon: 'book-open', iconType: 'lucide' },
        { value: 'parent', label: 'Parent / Family', icon: 'users', iconType: 'lucide' },
        { value: 'exploring', label: 'Just Exploring', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you most interested in?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'thinkbig', label: 'ThinkBIG Program', icon: 'zap', iconType: 'lucide' },
        { value: 'technician-career', label: 'Technician Careers', icon: 'wrench', iconType: 'lucide' },
        { value: 'free-training', label: 'Free Online Training', icon: 'laptop', iconType: 'lucide' },
        { value: 'job-openings', label: 'Current Job Openings', icon: 'briefcase', iconType: 'lucide' },
        { value: 'benefits', label: 'Pay & Benefits', icon: 'award', iconType: 'lucide' },
        { value: 'veteran', label: 'Veteran Programs', icon: 'shield', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Matches',
      subtitle: 'Content personalized to your role and interests.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'trending-up' },
        { id: 'learn', label: 'Learn', icon: 'book-open' },
        { id: 'solutions', label: 'Programs', icon: 'layers' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Picks',
      subtitle: 'Here\'s what you saved. We\'ll send these to your email.',
    },
    {
      type: 'content-library',
      id: 'content-library',
      title: 'All Programs & Resources',
      subtitle: 'Browse everything Mustang Cat has to offer.',
    },
    {
      type: 'thank-you',
      id: 'thank-you',
      title: 'Thanks for Stopping By!',
      subtitle: 'We\'ll follow up with the resources you selected. Check your inbox soon.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ─── Outcomes ────────────────────────────────────────
    {
      id: 'outcome-earn-while-train',
      cardType: 'outcome',
      title: 'Earn While You Train',
      stat: 'Paid',
      icon: 'dollar-sign',
      iconType: 'lucide',
      description: {
        small: 'ThinkBIG pays you a competitive wage throughout the program.',
        medium: 'ThinkBIG pays you throughout the program. Unlike traditional internships, you earn competitive wages during every on-the-job phase of the two-year curriculum.',
        large: 'ThinkBIG pays you throughout the program. Unlike traditional internships, you earn competitive wages during every on-the-job phase of the two-year curriculum. Tool reimbursement and tuition support are included on top of your earnings.',
        overlay: 'ThinkBIG is structured so that financial barriers don\'t stand in the way of your career. You receive competitive wages during every dealership employment phase, plus scholarship funding to cover tuition costs. Mustang Cat also reimburses tool purchases, removing one of the biggest upfront expenses for new technicians. You graduate with credentials and money in your pocket.',
      },
      url: 'https://www.mustangcat.com/career/think-big-technician-internship-program/',
      targetRoles: ['student', 'parent'],
      tags: ['thinkbig', 'benefits'],
    },
    {
      id: 'outcome-degree-two-years',
      cardType: 'outcome',
      title: 'Degree in 2 Years',
      stat: '2 Yrs',
      icon: 'graduation-cap',
      iconType: 'lucide',
      description: {
        small: 'Earn an accredited associate\'s or bachelor\'s degree in two years.',
        medium: 'ThinkBIG\'s alternating study-and-work structure lets you earn an accredited degree in just two years — without sacrificing real-world experience.',
        large: 'ThinkBIG\'s alternating study-and-work structure lets you earn an accredited degree in just two years — without sacrificing real-world experience. Each semester balances 8 weeks in the classroom with 8 weeks of paid work at a Cat dealership.',
        overlay: 'ThinkBIG compresses what might otherwise take four years into a focused, efficient two-year program. You alternate between classroom instruction and paid dealership employment each semester, earning your associate\'s or bachelor\'s degree while building hands-on experience. The schedule is demanding but intentional — you graduate with both academic credentials and real-world competency that most new graduates simply don\'t have.',
      },
      url: 'https://www.mustangcat.com/career/think-big-technician-internship-program/',
      targetRoles: ['student', 'parent', 'exploring'],
      tags: ['thinkbig', 'technician-career'],
    },
    {
      id: 'outcome-2000-hours',
      cardType: 'outcome',
      title: '2,000+ Hours of Real Experience',
      stat: '2,000+',
      icon: 'clock',
      iconType: 'lucide',
      description: {
        small: 'ThinkBIG graduates enter the workforce with 2,000+ hours of hands-on CAT experience.',
        medium: 'By the time you complete ThinkBIG, you\'ve accumulated over 2,000 hours of practical dealership experience — far more than a standard college graduate.',
        large: 'By the time you complete ThinkBIG, you\'ve accumulated over 2,000 hours of practical dealership experience — far more than a standard college graduate. That experience is supervised by seasoned CAT technicians and directly applicable to day-one dealership work.',
        overlay: 'Most employers are reluctant to hire new graduates without experience. ThinkBIG solves that problem by integrating 2,000+ hours of paid, real-world dealership work into the curriculum itself. You train alongside experienced CAT technicians, learning in actual service environments on actual CAT equipment. When you graduate, you\'re not starting from zero — you\'re entering the workforce with a track record that commands respect and higher starting pay.',
      },
      url: 'https://www.mustangcat.com/career/think-big-technician-internship-program/',
      targetRoles: ['student', 'advisor'],
      tags: ['thinkbig', 'technician-career'],
    },
    {
      id: 'outcome-tuition-covered',
      cardType: 'outcome',
      title: 'Tuition Covered',
      stat: '100%',
      icon: 'banknote',
      iconType: 'lucide',
      description: {
        small: 'Mustang Cat scholarship and reimbursement cover your full tuition cost.',
        medium: 'Mustang Cat provides scholarship funding and tuition reimbursement so that cost is never the reason a qualified candidate walks away from ThinkBIG.',
        large: 'Mustang Cat provides scholarship funding and tuition reimbursement so that cost is never the reason a qualified candidate walks away from ThinkBIG. Add in tool reimbursement and a paid internship, and your out-of-pocket investment is minimal.',
        overlay: 'College costs are a real barrier for many students. ThinkBIG removes it. Mustang Cat funds scholarships for accepted students and provides tuition reimbursement throughout the program. Combined with the competitive wages you earn during your on-the-job phases and reimbursement for required tools, your net cost of earning a CAT-credentialed degree approaches zero — while you still get paid throughout.',
      },
      url: 'https://www.mustangcat.com/career/think-big-technician-internship-program/',
      targetRoles: ['student', 'parent'],
      tags: ['thinkbig', 'benefits'],
    },
    {
      id: 'outcome-22-free-courses',
      cardType: 'outcome',
      title: '22 Free Online Courses',
      stat: '22',
      icon: 'laptop',
      iconType: 'lucide',
      description: {
        small: 'Technicians for the World delivers 22 free CAT-curriculum courses online.',
        medium: 'T4W offers 22 CAT-developed online courses covering diesel engines, hydraulics, electrical systems, and more — completely free, anytime, anywhere.',
        large: 'T4W offers 22 CAT-developed online courses covering diesel engines, hydraulics, electrical systems, and more — completely free, anytime, anywhere. It\'s backed by Caterpillar\'s Global Service Technician training program and requires zero prior experience.',
        overlay: 'Technicians for the World (T4W) is Caterpillar\'s gift to anyone, anywhere who wants to learn how to service heavy equipment. The program delivers 22 structured online courses drawn directly from CAT\'s professional training curriculum. Topics span diesel fundamentals, hydraulics, power train, electrification, workplace safety, and more. There are no fees, no prerequisites, and no set schedule — you complete courses at your own pace. T4W is an ideal stepping stone for anyone considering a technician career.',
      },
      url: 'https://dealer.techniciansfortheworld.com/',
      targetRoles: ['student', 'exploring'],
      tags: ['free-training', 'technician-career'],
    },
    {
      id: 'outcome-191-countries',
      cardType: 'outcome',
      title: 'Career Mobility Worldwide',
      stat: '191',
      icon: 'globe',
      iconType: 'lucide',
      description: {
        small: 'The Cat dealer network covers 191 countries with 2,000+ locations.',
        medium: 'CAT-certified technicians can find opportunities at 2,000+ dealer locations across 191 countries — your credentials travel wherever you want to go.',
        large: 'CAT-certified technicians can find opportunities at 2,000+ dealer locations across 191 countries — your credentials travel wherever you want to go. A ThinkBIG or T4W certification is recognized throughout the global network.',
        overlay: 'Caterpillar operates the world\'s largest heavy equipment dealer network — over 160 independent dealers, more than 2,000 locations, and a presence in 191 countries. When you earn a ThinkBIG degree or T4W certification, you\'re credentialed within that entire ecosystem. Whether you want to build a career in Texas or take your skills abroad, the Cat network opens doors that most trades certifications simply can\'t match.',
      },
      url: 'https://www.mustangcat.com/careers/',
      targetRoles: ['student', 'exploring'],
      tags: ['job-openings', 'technician-career'],
    },
    {
      id: 'outcome-since-1952',
      cardType: 'outcome',
      title: 'Building Texas Since 1952',
      stat: '70+ Yrs',
      icon: 'building-2',
      iconType: 'lucide',
      description: {
        small: 'Mustang Cat has served Southeast Texas construction and energy since 1952.',
        medium: 'Over 70 years of local expertise means stability, mentorship, and deep community roots for every Mustang Cat employee.',
        large: 'Over 70 years of local expertise means stability, mentorship, and deep community roots for every Mustang Cat employee. When you join Mustang Cat, you\'re joining a company that\'s been powering Texas for generations.',
        overlay: 'Mustang Cat has been part of the Southeast Texas industrial landscape since 1952 — over 70 years of "Building Texas and Powering the World." That kind of longevity means something: established processes, experienced mentors, genuine community investment, and job security that newer companies can\'t offer. When you start a career here, you\'re not just joining a company — you\'re joining a legacy.',
      },
      url: 'https://www.mustangcat.com/careers/',
      targetRoles: ['student', 'parent', 'advisor'],
      tags: ['benefits', 'job-openings'],
    },

    // ─── Learn ───────────────────────────────────────────
    {
      id: 'learn-thinkbig-overview',
      cardType: 'learn',
      title: 'ThinkBIG Program Guide',
      mediaType: 'website',
      icon: 'external-link',
      iconType: 'lucide',
      description: {
        small: 'The official ThinkBIG program overview — eligibility, structure, and how to apply.',
        medium: 'Learn everything about ThinkBIG on Mustang Cat\'s site: program structure, eligibility requirements, degree options, and application steps.',
        large: 'Learn everything about ThinkBIG on Mustang Cat\'s site: program structure, eligibility requirements, degree options, and application steps. Includes contact info for careers@mustangcat.com and 1-800-256-1001.',
        overlay: 'The ThinkBIG CAT Dealer Prep Program is the fastest path from high school to a credentialed technician career. This page covers the full program details: the alternating 8-week classroom / 8-week employment structure, associate\'s and bachelor\'s degree options, eligibility requirements (high school diploma, test scores, two recommendation letters), financial support, and how to apply. Questions? Contact careers@mustangcat.com or call 1-800-256-1001.',
      },
      url: 'https://www.mustangcat.com/career/think-big-technician-internship-program/',
      targetRoles: ['student', 'parent', 'advisor'],
      tags: ['thinkbig', 'technician-career'],
    },
    {
      id: 'learn-thinkbig-flyer',
      cardType: 'learn',
      title: 'ThinkBIG Program Flyer',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      description: {
        small: 'A printable one-pager covering the ThinkBIG program essentials.',
        medium: 'Take the ThinkBIG flyer home — key program facts, degree options, pay and benefits, and next steps in a single downloadable sheet.',
        large: 'Take the ThinkBIG flyer home — key program facts, degree options, pay and benefits, and next steps in a single downloadable sheet. Share it with parents, advisors, or anyone else helping you make this decision.',
        overlay: 'The ThinkBIG one-pager summarizes everything a prospective student (or their family) needs to know: program structure, what you earn, what degree you get, eligibility checklist, and how to apply. It\'s designed to be shared — take one for anyone who wasn\'t here today.',
      },
      url: '#',
      targetRoles: ['student', 'parent'],
      tags: ['thinkbig'],
    },
    {
      id: 'learn-thinkbig-osuit',
      cardType: 'learn',
      title: 'ThinkBIG + OSUIT Partnership',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      description: {
        small: 'See how Mustang Cat and OSUIT partner to deliver the ThinkBIG curriculum.',
        medium: 'This video explores the Mustang Cat and Oklahoma State University Institute of Technology (OSUIT) partnership that powers ThinkBIG\'s academic credentials.',
        large: 'This video explores the Mustang Cat and Oklahoma State University Institute of Technology (OSUIT) partnership that powers ThinkBIG\'s academic credentials. See the facility, hear from students and instructors, and learn what makes this program unique.',
        overlay: 'Mustang Cat partners with Oklahoma State University Institute of Technology (OSUIT) to deliver the academic side of ThinkBIG. This partnership video gives a behind-the-scenes look at the program: facilities, faculty, current students, and what a typical semester looks like. If you\'re weighing ThinkBIG, this is the most direct way to understand what you\'re signing up for.',
      },
      url: '#',
      targetRoles: ['student', 'parent', 'advisor'],
      tags: ['thinkbig', 'technician-career'],
    },
    {
      id: 'learn-t4w-program',
      cardType: 'learn',
      title: 'Technicians for the World',
      mediaType: 'website',
      icon: 'globe',
      iconType: 'lucide',
      description: {
        small: '22 free CAT-curriculum online courses open to anyone, anywhere.',
        medium: 'T4W is Caterpillar\'s free online training program — 22 courses covering diesel engines, hydraulics, electrical systems, and more. No cost, no prerequisites.',
        large: 'T4W is Caterpillar\'s free online training program — 22 courses covering diesel engines, hydraulics, electrical systems, and more. No cost, no prerequisites, and accessible from any device. A great first step into the CAT ecosystem.',
        overlay: 'Technicians for the World (T4W) is sponsored by Caterpillar and open to anyone seeking a technician career. 22 structured online courses walk you through every major discipline: diesel engine basics, hydraulics, power train, electricity, electrification, and workplace safety. There are no fees, no deadlines, and no required experience. Complete courses at your own pace from any internet-connected device. Whether you\'re a student, career-changer, or just curious about the field, T4W is the easiest way to get started.',
      },
      url: 'https://dealer.techniciansfortheworld.com/',
      targetRoles: ['student', 'exploring', 'advisor'],
      tags: ['free-training', 'technician-career'],
    },
    {
      id: 'learn-t4w-flyer',
      cardType: 'learn',
      title: 'T4W Training Overview',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      description: {
        small: 'A printable overview of the 22-course T4W curriculum.',
        medium: 'The T4W flyer lists all 22 courses, program benefits, and how to get started — print or share it with students and advisors.',
        large: 'The T4W flyer lists all 22 courses, program benefits, and how to get started. It\'s designed for career advisors, instructors, and students who want a quick reference to take away from today.',
        overlay: 'The Technicians for the World overview covers all 22 course titles, the sponsoring Caterpillar program behind them, how to access the curriculum, and what skills you\'ll develop. It\'s useful for academic advisors integrating T4W into career counseling, and for students who want a clear picture of what they\'re committing to. Everything is free — take the PDF and share it widely.',
      },
      url: '#',
      targetRoles: ['advisor', 'student'],
      tags: ['free-training'],
    },
    {
      id: 'learn-careers-page',
      cardType: 'learn',
      title: 'Mustang Cat Careers',
      mediaType: 'website',
      icon: 'briefcase',
      iconType: 'lucide',
      description: {
        small: 'Browse open positions at Mustang Cat across Houston and Southeast Texas.',
        medium: 'The Mustang Cat careers page lists current openings in service, rental, parts, and business roles across all Southeast Texas locations.',
        large: 'The Mustang Cat careers page lists current openings in service, rental, parts, and business roles across all Southeast Texas locations. Filter by department or location, and apply directly.',
        overlay: 'Mustang Cat is hiring across multiple disciplines and locations throughout Southeast Texas — from Houston and Katy to Beaumont, Bryan, El Campo, and League City. The careers page lists real-time openings in Mustang Cat, Mustang Rental, and Marine Services departments. Roles range from diesel technician and engine mechanic to business development and operations. Browse open positions, apply directly, or set up a job alert.',
      },
      url: 'https://www.mustangcat.com/careers/',
      targetRoles: ['student', 'exploring'],
      tags: ['job-openings'],
    },
    {
      id: 'learn-diesel-technician',
      cardType: 'learn',
      title: 'Life as a CAT Diesel Technician',
      mediaType: 'blog',
      icon: 'wrench',
      iconType: 'lucide',
      description: {
        small: 'What does a day in the life look like for a Mustang Cat technician?',
        medium: 'Get an inside look at what diesel technicians at Mustang Cat do day-to-day — equipment, environments, career ladder, and culture.',
        large: 'Get an inside look at what diesel technicians at Mustang Cat do day-to-day — equipment, environments, career ladder, and culture. The role offers variety, skilled work, and a clear path to advancement.',
        overlay: 'Diesel technicians at Mustang Cat diagnose, service, and repair the most sophisticated heavy equipment on the planet — CAT machines powering construction, oil and gas, and power generation projects across Texas. No two days are the same. You\'ll work across engine systems, hydraulics, electrical diagnostics, and more. Experienced techs mentor newer hires, and the skills you build are in demand globally. This page helps prospective candidates understand the day-to-day reality of the role before they commit.',
      },
      url: 'https://www.mustangcat.com/careers/',
      targetRoles: ['student', 'exploring'],
      tags: ['technician-career', 'job-openings'],
    },

    // ─── Solutions / Programs ─────────────────────────────
    {
      id: 'solution-thinkbig',
      cardType: 'solution',
      title: 'ThinkBIG Program',
      icon: 'zap',
      iconType: 'lucide',
      description: {
        small: 'Paid internship + accredited degree + 2,000+ hours of CAT experience in 2 years.',
        medium: 'ThinkBIG is a two-year CAT Dealer Prep Program that combines classroom instruction with paid dealership employment — you earn a degree and real experience simultaneously.',
        large: 'ThinkBIG is a two-year CAT Dealer Prep Program that combines classroom instruction with paid dealership employment — you earn a degree and real experience simultaneously. Tuition, scholarship, and tool reimbursement are included.',
        overlay: 'The ThinkBIG CAT Dealer Prep Program is the gold standard for entering the heavy equipment technician field. Over two years, you alternate between academic coursework (8 weeks) and paid internship at a sponsoring Cat dealership (8 weeks). You graduate with an accredited associate\'s or bachelor\'s degree, 2,000+ hours of verified dealership experience, and zero student debt thanks to Mustang Cat\'s tuition scholarship and reimbursement support. Eligibility: high school diploma, passing test score (SAT, ACT, or COMPASS), two recommendations, and strong mechanical aptitude. Apply at careers@mustangcat.com.',
      },
      url: 'https://www.mustangcat.com/career/think-big-technician-internship-program/',
      targetRoles: ['student', 'parent'],
      tags: ['thinkbig', 'technician-career', 'benefits'],
    },
    {
      id: 'solution-t4w',
      cardType: 'solution',
      title: 'Technicians for the World',
      icon: 'laptop',
      iconType: 'lucide',
      description: {
        small: 'Free online CAT curriculum — 22 courses, open to anyone, anytime.',
        medium: 'T4W delivers Caterpillar\'s Global Service Technician curriculum online for free. 22 courses, no prerequisites, no deadlines. The ideal on-ramp to a technician career.',
        large: 'T4W delivers Caterpillar\'s Global Service Technician curriculum online for free. 22 courses, no prerequisites, no deadlines. The ideal on-ramp to a technician career — and a strong credential for ThinkBIG applicants.',
        overlay: 'Technicians for the World is Caterpillar\'s commitment to making quality technician education accessible to everyone on the planet. The program features 22 online courses developed from CAT\'s internal Global Service Technician training — covering diesel engines, hydraulics, power train, electrical systems, hand tools, fasteners, workplace safety, and emerging electrification technology. It\'s free, self-paced, and requires only an internet connection. T4W completion signals initiative and foundational knowledge that employers — including Mustang Cat — genuinely value.',
      },
      url: 'https://dealer.techniciansfortheworld.com/',
      targetRoles: ['student', 'exploring'],
      tags: ['free-training', 'technician-career'],
    },
    {
      id: 'solution-dealer-job-board',
      cardType: 'solution',
      title: 'Cat Dealer Job Board',
      icon: 'map-pin',
      iconType: 'lucide',
      description: {
        small: '2,000+ Cat dealer locations across 191 countries are hiring technicians.',
        medium: 'The global Cat dealer network spans 160+ dealers, 2,000+ locations, and 191 countries — all sharing a common need for skilled CAT-trained technicians.',
        large: 'The global Cat dealer network spans 160+ dealers, 2,000+ locations, and 191 countries — all sharing a common need for skilled CAT-trained technicians. ThinkBIG and T4W credentials open doors throughout this global network.',
        overlay: 'When you become a CAT-trained technician, your credentials are recognized at over 2,000 dealer locations in 191 countries. The Cat Dealer Job Board aggregates open positions across this entire network — from small regional dealers to major operators like Mustang Cat. Whether you want to stay in Texas or eventually take your skills global, the board gives you visibility into the full scope of opportunity available to a CAT-credentialed technician.',
      },
      url: 'https://www.mustangcat.com/careers/',
      targetRoles: ['student', 'exploring'],
      tags: ['job-openings', 'technician-career'],
    },
    {
      id: 'solution-direct-hire',
      cardType: 'solution',
      title: 'Direct Hire at Mustang Cat',
      icon: 'briefcase',
      iconType: 'lucide',
      description: {
        small: 'Browse and apply for open roles across all Mustang Cat departments.',
        medium: 'Mustang Cat is actively hiring diesel technicians, engine mechanics, and business professionals across multiple Southeast Texas locations.',
        large: 'Mustang Cat is actively hiring diesel technicians, engine mechanics, and business professionals across multiple Southeast Texas locations. Mustang Cat, Mustang Rental, and Marine Services are all staffing up.',
        overlay: 'Ready to work now? Mustang Cat has open positions across its three divisions: Mustang Cat, Mustang Rental, and Marine Services. Roles include Diesel Technician, Heavy Equipment Mechanic, Engine Rebuild Mechanic, and various business and operations positions. Locations span Houston, Katy, Beaumont, Bryan, El Campo, League City, and more. Apply online at mustangcat.com/careers or speak with a recruiter here today.',
      },
      url: 'https://www.mustangcat.com/careers/',
      targetRoles: ['student', 'exploring'],
      tags: ['job-openings'],
    },
    {
      id: 'solution-veteran',
      cardType: 'solution',
      title: 'Veteran Recruitment Program',
      icon: 'shield',
      iconType: 'lucide',
      description: {
        small: 'Mustang Cat actively recruits veterans for their discipline and technical aptitude.',
        medium: 'Veterans bring the precise qualities Mustang Cat values most — discipline, reliability, and the ability to operate in demanding environments. Dedicated veteran recruiting is available.',
        large: 'Veterans bring the precise qualities Mustang Cat values most — discipline, reliability, and the ability to operate in demanding environments. Mustang Cat\'s veteran recruitment program offers tailored support and a clear path to technician roles.',
        overlay: 'Military service builds exactly the skills and mindset that make a great Mustang Cat technician: systematic troubleshooting, teamwork under pressure, equipment familiarity, and the discipline to complete complex tasks correctly the first time. Mustang Cat actively recruits veterans and provides dedicated support to help veterans translate military experience into CAT dealership careers. If you\'re separating from service and looking for a meaningful next chapter, talk to a recruiter at this booth today.',
      },
      url: 'https://www.mustangcat.com/careers/',
      targetRoles: ['exploring'],
      tags: ['veteran', 'job-openings'],
    },
    {
      id: 'solution-open-interviews',
      cardType: 'solution',
      title: 'Technician Open Interviews',
      icon: 'users',
      iconType: 'lucide',
      description: {
        small: 'Mustang Cat hosts walk-in open interview events for technician candidates.',
        medium: 'Skip the application queue — Mustang Cat\'s open interview events let qualified candidates meet directly with hiring managers for technician and mechanic roles.',
        large: 'Skip the application queue — Mustang Cat\'s open interview events let qualified candidates meet directly with hiring managers for technician and mechanic roles. Check the careers page for upcoming dates and locations.',
        overlay: 'Mustang Cat regularly hosts Technician Open Interview events where qualified candidates can walk in and speak directly with hiring managers — no lengthy application process required. These events are designed for diesel technicians, heavy equipment mechanics, and engine specialists who are ready to make a move. Attending an open interview is one of the fastest paths to a job offer at Mustang Cat. Ask a recruiter here today about the next scheduled event near you.',
      },
      url: 'https://www.mustangcat.com/careers/',
      targetRoles: ['student', 'exploring'],
      tags: ['job-openings', 'technician-career'],
    },
    {
      id: 'solution-mustang-rental',
      cardType: 'solution',
      title: 'Mustang Rental Careers',
      icon: 'truck',
      iconType: 'lucide',
      description: {
        small: 'Mustang Rental is growing and hiring across Southeast Texas.',
        medium: 'Mustang Rental offers technician and operations roles focused on CAT rental equipment — a dynamic environment with a wide variety of machine types and service scenarios.',
        large: 'Mustang Rental offers technician and operations roles focused on CAT rental equipment — a dynamic environment with a wide variety of machine types and service scenarios. Great for technicians who want broad exposure across the CAT product line.',
        overlay: 'Mustang Rental is the equipment rental division of Mustang Cat, providing CAT machines to construction, oil and gas, and industrial customers across Southeast Texas. Technician roles in rental offer a different kind of variety compared to the dealer side — you\'ll service a wider range of machine types on tighter turnaround schedules. If you thrive on variety and fast-paced environments, Mustang Rental is worth exploring. Roles are available now across multiple Texas locations.',
      },
      url: 'https://www.mustangcat.com/careers/',
      targetRoles: ['exploring'],
      tags: ['job-openings', 'technician-career'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
