// Explorer Config — PoweringU Foundation
// 501(c)(3) non-profit empowering student athletes — NIL education,
// workforce readiness, mentorship, equity & access. Deployed at events,
// college fairs, and fundraisers to drive donations, mentor signups, and
// student athlete program enrollment.
//
// Brand palette: PUF blue → green gradient, education-clean light feel.

import type { ExplorerConfig, ThemeColors } from '../types';

const PUF_DARK: ThemeColors = {
  bg: '#03101C',
  bgGradient: 'linear-gradient(135deg, #0B2E47 0%, #052033 55%, #03101C 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#3A9CD8',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.78)',
  text3: 'rgba(255,255,255,0.52)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(20,102,154,0.22)',
};

const PUF_LIGHT: ThemeColors = {
  bg: '#F4F6FA',
  bgGradient: 'linear-gradient(180deg, #F4F6FA 0%, #EDF1F6 100%)',
  surface: 'rgba(255,255,255,0.88)',
  surfaceHover: 'rgba(255,255,255,0.96)',
  border: 'rgba(11,46,71,0.10)',
  borderFocus: '#0F4F77',
  text1: '#0B2E47',
  text2: 'rgba(11,46,71,0.68)',
  text3: 'rgba(11,46,71,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0B2E47',
  inputPlaceholder: 'rgba(11,46,71,0.38)',
  logoText: '#0B2E47',
  focusRing: 'rgba(15,79,119,0.14)',
};

export const POWERINGU_CONFIG: ExplorerConfig = {
  id: 'poweringu',
  name: 'PoweringU Foundation Explorer',
  version: 1,
  createdAt: '2026-06-02T00:00:00.000Z',
  updatedAt: '2026-06-02T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/poweringu-logo-reverse.png',
      light: '/brand/assets/poweringu-logo.png',
    },
    // PUF logo: monogram + wordmark combined, source PNG tightly
    // cropped to its 160×136 content bbox (was 300×300 with ~50%
    // transparent padding). 108px height pairs with the cropped
    // aspect to give the mark real presence — critical for the
    // scaled-down Fan Gallery preview where the whole 1366px shell
    // renders at ~50%.
    logoHeight: 108,
    icon: '/brand/assets/poweringu-icon.png',
    colors: {
      // From intake: PUF blue + PUF green. Supplemented with darker
      // navy + brighter accents derived from the brand.
      primary: '#14669A',      // PUF blue — main accent
      secondary: '#1A9458',    // PUF green — secondary accent
      teal: '#3A9CD8',         // lighter PUF blue for highlights
      blue: '#14669A',
      deepBlue: '#0F4F77',
      navy: '#0B2E47',
      midnight: '#03101C',
      plum: '#1A9458',         // PUF green stands in as warm anchor
      bgDark: '#03101C',
      dark: PUF_DARK,
      light: PUF_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(20,102,154,0.18)',   // PUF blue
      orb2: 'rgba(26,148,88,0.16)',    // PUF green
      orb3: 'rgba(58,156,216,0.12)',   // light blue accent
    },
    // Brand action: blue → green (matches the PUF logo gradient).
    ctaGradient: 'linear-gradient(135deg, #14669A 0%, #1A9458 100%)',
    ctaTextColor: '#FFFFFF',
    // Headline gradient mirrors the action gradient with brighter stops
    // so it pops on the dark splash.
    gradientWord: 'linear-gradient(135deg, #3A9CD8 0%, #4FD188 100%)',
    // Per-role glows mix PUF blue, green, and the light-blue accent so
    // each role lands on a distinct brand color.
    roleBackgrounds: {
      'student-athlete': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(20,102,154,0.30) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(26,148,88,0.18) 0%, transparent 55%)',
      'parent': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(26,148,88,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(20,102,154,0.18) 0%, transparent 55%)',
      'coach': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(58,156,216,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(20,102,154,0.18) 0%, transparent 55%)',
      'educator': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(20,102,154,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(58,156,216,0.16) 0%, transparent 55%)',
      'mentor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(26,148,88,0.26) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(20,102,154,0.16) 0%, transparent 55%)',
      'corporate-partner': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(15,79,119,0.28) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(26,148,88,0.18) 0%, transparent 55%)',
      'donor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(26,148,88,0.24) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(58,156,216,0.14) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(20,102,154,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(26,148,88,0.14) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Welcome to PoweringU',
    formSubtitle: 'Share a quick intro so we can tailor your experience.',
    scanLabel: 'Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to PoweringU Foundation processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@email.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'School / Organization', type: 'text', placeholder: 'School or organization', required: false, halfWidth: true },
      { id: 'title', label: 'Role', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Empowering Every',
      gradientWord: 'Student.',
      // Typewriter cycles the audiences PoweringU serves — students,
      // athletes, scholars, mentors, communities, future. The cycling
      // brand-color orb glow plays behind via ExplorerShell.
      typewriterWords: [
        'Student.',
        'Athlete.',
        'Scholar.',
        'Mentor.',
        'Community.',
        'Future.',
      ],
      subtitle: 'PoweringU Foundation breaks down barriers to education for student athletes — through NIL training, workforce readiness, mentorship, and equity in underserved communities.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes you?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'student-athlete', label: 'Student Athlete', icon: 'trophy', iconType: 'lucide' },
        { value: 'parent', label: 'Parent / Guardian', icon: 'users', iconType: 'lucide' },
        { value: 'coach', label: 'Coach / Athletic Director', icon: 'megaphone', iconType: 'lucide' },
        { value: 'educator', label: 'Educator / School Leader', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'mentor', label: 'Mentor / Volunteer', icon: 'handshake', iconType: 'lucide' },
        { value: 'corporate-partner', label: 'Corporate Partner', icon: 'briefcase', iconType: 'lucide' },
        { value: 'donor', label: 'Donor / Supporter', icon: 'heart', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'message-circle', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What brings you here today?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'nil-education', label: 'NIL Education', icon: 'star', iconType: 'lucide' },
        { value: 'workforce-readiness', label: 'Workforce Readiness', icon: 'trending-up', iconType: 'lucide' },
        { value: 'scholarships', label: 'Scholarships', icon: 'award', iconType: 'lucide' },
        { value: 'mentorship', label: 'Mentorship', icon: 'users', iconType: 'lucide' },
        { value: 'dare-to-be-great', label: 'Dare to Be Great', icon: 'rocket', iconType: 'lucide' },
        { value: 'partner-with-us', label: 'Partner With Us', icon: 'handshake', iconType: 'lucide' },
        { value: 'donate', label: 'Donate / Sponsor', icon: 'heart', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Path',
      subtitle: 'Programs, stories, and ways to engage tailored to you.',
      tabs: [
        { id: 'outcomes', label: 'Why It Matters', icon: 'target' },
        {
          id: 'learn',
          label: 'Discover',
          icon: 'book-open',
          filters: [
            { label: 'All', value: 'all' },
            { label: 'Video', value: 'video' },
            { label: 'Blog', value: 'blog' },
            { label: 'PDF', value: 'pdf' },
            { label: 'Website', value: 'website' },
          ],
        },
        { id: 'solutions', label: 'Programs', icon: 'graduation-cap' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review your picks — a PoweringU team member will follow up.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Explore Everything',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'Welcome to the movement. We\'ll be in touch shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Why It Matters / Outcomes (7) ─────────────────
    {
      id: 'o1',
      title: '67% Lack Access to Programming',
      cardType: 'outcome',
      icon: 'alert-triangle',
      iconType: 'lucide',
      stat: '67%',
      description: {
        small: '67% of Black & Brown youth lack quality college/career programs.',
        medium: '67% of Black & Brown youth lack access to quality college and career programming — PoweringU exists to close that gap.',
        large: 'Two-thirds of Black & Brown youth in the US do not have access to quality college and career programming. PoweringU Foundation delivers programs directly to these communities so opportunity becomes the rule, not the exception.',
        overlay: '67% of Black & Brown youth in the US lack access to quality college and career programming. That gap shapes what their lives can look like before they ever step on a court or in a classroom. PoweringU Foundation closes it by bringing programs directly to underserved schools, HBCUs, and community organizations.',
      },
      tags: ['workforce-readiness', 'scholarships', 'partner-with-us'],
      targetRoles: ['donor', 'corporate-partner', 'educator', 'mentor'],
    },
    {
      id: 'o2',
      title: '$1.2B+ NIL Market',
      cardType: 'outcome',
      icon: 'dollar-sign',
      iconType: 'lucide',
      stat: '$1.2B+',
      description: {
        small: '$1.2B+ NIL market — only 12% of athletes feel confident.',
        medium: 'The NIL market is now $1.2B+ — but only 12% of student athletes feel confident navigating deals.',
        large: 'Name, Image, and Likeness has grown into a $1.2 billion-plus market in just a few years. Yet only 12% of student athletes feel confident negotiating deals, building their brand, or managing the financial side. PoweringU trains the other 88%.',
        overlay: 'NIL is now a $1.2 billion-plus market — but only 12% of student athletes feel confident navigating deals, building their brand, or managing the financial side. PoweringU\'s NIL curriculum gives athletes the contracts knowledge, brand strategy, and financial literacy to actually capture that opportunity instead of watching it pass.',
      },
      tags: ['nil-education'],
      targetRoles: ['student-athlete', 'parent', 'coach'],
    },
    {
      id: 'o3',
      title: '11.6M Jobs Need Skills',
      cardType: 'outcome',
      icon: 'briefcase',
      iconType: 'lucide',
      stat: '11.6M',
      description: {
        small: '11.6M jobs require postsecondary skills.',
        medium: '11.6M US jobs require postsecondary skills — only 42% of grads feel prepared.',
        large: '11.6 million US jobs require postsecondary skills, yet only 42% of recent graduates feel prepared for them. PoweringU\'s workforce readiness program closes the gap between graduation day and a meaningful first job.',
        overlay: '11.6 million US jobs today require postsecondary skills. Only 42% of recent graduates feel prepared for them. PoweringU\'s workforce readiness program closes that gap with resume building, interview prep, public speaking, entrepreneurship training, and mentor relationships — practical skills you can use the week you graduate.',
      },
      tags: ['workforce-readiness'],
      targetRoles: ['student-athlete', 'educator', 'corporate-partner'],
    },
    {
      id: 'o4',
      title: 'Dare to Be Great',
      cardType: 'outcome',
      icon: 'rocket',
      iconType: 'lucide',
      stat: 'Flagship',
      description: {
        small: 'Flagship program for athlete-led leadership.',
        medium: 'Dare to Be Great — PoweringU\'s flagship program for athlete-led leadership development.',
        large: 'Dare to Be Great is PoweringU\'s flagship program — a leadership and personal development curriculum built for student athletes, taught by people who have walked the path.',
        overlay: 'Dare to Be Great is PoweringU\'s flagship leadership and personal development program. Built specifically for student athletes and taught by mentors who have walked the path themselves — from underserved community to college campus to career — it covers identity, decision-making, financial confidence, brand-building, and the kind of grit a syllabus rarely teaches.',
      },
      tags: ['mentorship', 'dare-to-be-great'],
      targetRoles: ['student-athlete', 'parent', 'coach', 'mentor'],
    },
    {
      id: 'o5',
      title: '501(c)(3) Non-Profit',
      cardType: 'outcome',
      icon: 'shield-check',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: 'Registered 501(c)(3) — every donation is tax-deductible.',
        medium: 'PoweringU is a registered 501(c)(3) — every donation is tax-deductible (EIN 86-2840497).',
        large: 'PoweringU Foundation is a registered 501(c)(3) non-profit organization (EIN 86-2840497). Every donation goes directly toward programs, scholarships, and operations — and is tax-deductible.',
        overlay: 'PoweringU Foundation is a registered 501(c)(3) non-profit (EIN 86-2840497). Every donation is fully tax-deductible and goes directly toward programs that serve student athletes — NIL education, workforce readiness, scholarships, and mentorship in underserved communities.',
      },
      tags: ['donate', 'partner-with-us'],
      targetRoles: ['donor', 'corporate-partner'],
    },
    {
      id: 'o6',
      title: 'Direct to HBCUs',
      cardType: 'outcome',
      icon: 'graduation-cap',
      iconType: 'lucide',
      stat: 'HBCUs',
      description: {
        small: 'Programs delivered directly to HBCUs and underserved schools.',
        medium: 'PoweringU delivers programs directly to HBCUs and underserved schools — meeting students where they are.',
        large: 'Rather than waiting for students to come to us, PoweringU brings its NIL, workforce, and mentorship programming directly to Historically Black Colleges & Universities and underserved schools across the country.',
        overlay: 'Equity means meeting students where they already are. PoweringU brings its NIL curriculum, workforce readiness program, and Dare to Be Great leadership track directly to Historically Black Colleges & Universities, public high schools, and community organizations — eliminating the access gap that keeps quality programming out of underserved communities.',
      },
      tags: ['workforce-readiness', 'mentorship'],
      targetRoles: ['educator', 'donor', 'corporate-partner', 'mentor'],
    },
    {
      id: 'o7',
      title: 'Join the Movement',
      cardType: 'outcome',
      icon: 'heart',
      iconType: 'lucide',
      stat: 'Join',
      description: {
        small: 'Donate, mentor, volunteer, or partner.',
        medium: 'Four ways to plug in: donate, mentor, volunteer, or partner your organization.',
        large: 'There are four ways to plug in: tax-deductible donations, one-on-one mentorship, volunteering at programs and events, or partnering your organization with PoweringU.',
        overlay: 'Four ways to join the movement: make a tax-deductible donation that funds direct programming, become a one-on-one mentor for a student athlete, volunteer at programs and events, or partner your organization with PoweringU as a corporate sponsor. Every one of them moves the mission forward.',
      },
      tags: ['donate', 'mentorship', 'partner-with-us'],
      targetRoles: ['donor', 'mentor', 'corporate-partner', 'parent'],
    },

    // ── Discover / Learn (8) ──────────────────────────
    {
      id: 'l1',
      title: 'The PoweringU Story',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'How PoweringU started and who it serves.',
        medium: 'A short video on how PoweringU started and the student athletes it serves today.',
        large: 'A short video introduction to PoweringU Foundation — how it started, the student athletes it serves, and the impact a year of programming has on a young person\'s trajectory.',
        overlay: 'A short video introduction to PoweringU Foundation. How it started, the student athletes it serves today, the partner schools and HBCUs that host programming, and the specific change a year of NIL training, workforce prep, and mentorship makes in a young person\'s trajectory. ~3 minutes.',
      },
      tags: ['nil-education', 'workforce-readiness', 'mentorship'],
      targetRoles: ['student-athlete', 'parent', 'donor', 'mentor'],
    },
    {
      id: 'l2',
      title: 'NIL 101: A Student\'s Guide',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'The NIL fundamentals every student athlete needs.',
        medium: 'A PDF covering the NIL fundamentals: contracts, brand, taxes, and red flags.',
        large: 'A plain-language PDF covering NIL fundamentals every student athlete needs: how contracts work, how to build a personal brand, how taxes apply to NIL income, and the red flags that hint at a bad deal.',
        overlay: 'The fundamentals every student athlete should know before signing anything NIL-related. Contract basics (what to look for, what to never sign), personal brand strategy that translates to deal flow, the tax implications of NIL income (it\'s self-employment, not W-2), agent vs. attorney vs. parent, and the red flags that mean walk away. Plain English, designed for athletes — not lawyers.',
      },
      tags: ['nil-education'],
      targetRoles: ['student-athlete', 'parent', 'coach'],
    },
    {
      id: 'l3',
      title: 'Building a Career After Sports',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'trending-up',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'Workforce readiness for the day after sports.',
        medium: 'A blog series on workforce skills — resumes, interviews, public speaking, entrepreneurship.',
        large: 'A blog series on the workforce skills every student athlete needs for the day after sports: writing a resume that captures athletic discipline, interviewing under pressure, public speaking, and how to think about entrepreneurship.',
        overlay: 'A blog series for the day after sports. How to write a resume that translates athletic discipline into transferable workforce skills, how to interview confidently under pressure (you have an advantage — use it), how public speaking opens doors most people never see, and how to think about entrepreneurship if a traditional 9-to-5 isn\'t the goal. Written by mentors who built their own careers post-sports.',
      },
      tags: ['workforce-readiness'],
      targetRoles: ['student-athlete', 'mentor', 'educator'],
    },
    {
      id: 'l4',
      title: 'Dare to Be Great Curriculum',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'rocket',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'The full Dare to Be Great curriculum overview.',
        medium: 'A PDF overview of the Dare to Be Great curriculum — modules, outcomes, and delivery.',
        large: 'A PDF overview of the Dare to Be Great curriculum — every module, the outcomes each one is designed to produce, how PoweringU delivers it on campus or in community, and what partner schools need to host it.',
        overlay: 'A full curriculum overview of Dare to Be Great — the modules (identity, leadership, financial confidence, brand-building, decision-making), the outcomes each module produces, the delivery model (on campus, in community, hybrid), the time commitment for students and partner schools, and what it takes to bring it to your campus. Designed for educators and athletic directors evaluating program fit.',
      },
      tags: ['dare-to-be-great', 'mentorship', 'partner-with-us'],
      targetRoles: ['educator', 'coach', 'corporate-partner'],
    },
    {
      id: 'l5',
      title: 'Mentor Spotlight Series',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'Stories from PoweringU mentors.',
        medium: 'Short video stories from PoweringU mentors — why they show up.',
        large: 'A short video series featuring PoweringU mentors — former athletes, corporate leaders, educators — on why they show up for the next generation of student athletes.',
        overlay: 'Short video stories from PoweringU mentors. Former pro and college athletes, corporate leaders, educators, and community advocates talking about why they choose to show up for the next generation of student athletes, what they wish someone had told them at 18, and the kind of relationships that change a kid\'s trajectory in one conversation.',
      },
      tags: ['mentorship'],
      targetRoles: ['mentor', 'student-athlete', 'parent'],
    },
    {
      id: 'l6',
      title: 'Corporate Partnership Deck',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'briefcase',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'Partnership opportunities for corporate sponsors.',
        medium: 'A PDF deck outlining corporate partnership tiers and impact reporting.',
        large: 'A PDF deck outlining corporate partnership tiers, the programs your sponsorship funds, the schools served, brand activation opportunities at events, and how PoweringU reports impact back to partners.',
        overlay: 'For corporate sponsors evaluating partnership. Partnership tiers and what each unlocks, the specific programs your sponsorship funds, the schools and communities served, brand activation opportunities at PoweringU events and on-campus programming, and the impact reporting cadence PoweringU delivers back to partners (quarterly + annual). Includes case studies of existing partners.',
      },
      tags: ['partner-with-us', 'donate'],
      targetRoles: ['corporate-partner', 'donor'],
    },
    {
      id: 'l7',
      title: 'Donor Impact Report',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-bar-chart',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'How donor dollars translated into student impact.',
        medium: 'The annual impact report — every donor dollar mapped to student outcomes.',
        large: 'The annual impact report — every donor dollar mapped to the programs it funded, the students served, the schools and HBCUs partnered, and the outcomes those programs produced.',
        overlay: 'The annual impact report. Every donor dollar mapped to the programs it funded, the student athletes served, the schools and HBCUs partnered with, the mentor relationships established, and the measurable outcomes — workforce placements, scholarship awards, NIL deals navigated. Transparent, audited, and designed to show donors exactly where their generosity goes.',
      },
      tags: ['donate', 'partner-with-us'],
      targetRoles: ['donor', 'corporate-partner'],
    },
    {
      id: 'l8',
      title: 'Join Our Movement Newsletter',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'mail',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'Sign up for the PoweringU newsletter.',
        medium: 'Sign up for the PoweringU newsletter — monthly updates on programs, events, and impact stories.',
        large: 'Sign up for the PoweringU monthly newsletter — program updates, upcoming events, student athlete spotlights, mentor opportunities, and ways to support the mission.',
        overlay: 'Monthly updates from PoweringU Foundation: new programs launching, upcoming events and fundraisers, student athlete spotlights, mentor and volunteer opportunities, partnership announcements, and the ways the movement is growing. Sign up takes 10 seconds; unsubscribe is one click.',
      },
      tags: ['donate', 'mentorship', 'partner-with-us'],
      targetRoles: ['donor', 'mentor', 'parent', 'corporate-partner'],
    },

    // ── Programs / Solutions (7) ──────────────────────
    {
      id: 's1',
      title: 'NIL Education & Athlete Empowerment',
      cardType: 'solution',
      icon: 'star',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'NIL training: contracts, brand, financial literacy.',
        medium: 'A full NIL curriculum covering contracts, brand strategy, and financial literacy.',
        large: 'A full NIL curriculum covering contracts, brand strategy, financial literacy, and the business side of being a student athlete — taught by people who have actually navigated NIL deals.',
        overlay: 'PoweringU\'s flagship NIL curriculum gives student athletes the knowledge to actually capture the $1.2B+ NIL opportunity instead of watching it pass. Contract literacy, personal brand building, financial literacy and tax basics, and a clear framework for evaluating deals. Taught by people who have negotiated real NIL agreements — not theory from a textbook.',
      },
      tags: ['nil-education'],
      targetRoles: ['student-athlete', 'parent', 'coach', 'educator'],
    },
    {
      id: 's2',
      title: 'Workforce Readiness & Career Development',
      cardType: 'solution',
      icon: 'trending-up',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'Resumes, interviews, public speaking, entrepreneurship.',
        medium: 'Practical workforce skills for student athletes — resumes, interviews, public speaking, entrepreneurship.',
        large: 'A workforce readiness program built around the skills that actually translate after sports — resume building, interviewing, public speaking, entrepreneurship training, and ongoing mentorship.',
        overlay: 'A workforce readiness program built around what student athletes actually need for the day after sports. Resume writing that captures athletic discipline as transferable skills, interviewing under pressure (athletes already have the edge — they just need the framework), public speaking, entrepreneurship basics, and ongoing mentor relationships that open doors a resume alone never could.',
      },
      tags: ['workforce-readiness', 'mentorship'],
      targetRoles: ['student-athlete', 'educator', 'mentor', 'corporate-partner'],
    },
    {
      id: 's3',
      title: 'Dare to Be Great',
      cardType: 'solution',
      icon: 'rocket',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'Flagship leadership program for student athletes.',
        medium: 'Dare to Be Great — PoweringU\'s flagship leadership and personal development program.',
        large: 'Dare to Be Great is PoweringU\'s flagship leadership and personal development curriculum — identity, decision-making, financial confidence, brand-building, and the grit a syllabus rarely teaches.',
        overlay: 'Dare to Be Great is PoweringU\'s flagship leadership and personal development program — built specifically for student athletes and taught by mentors who walked the path themselves. Modules cover identity, decision-making under pressure, financial confidence, personal brand-building, and the kind of grit that doesn\'t show up on a syllabus. Delivered on campus, in community, or hybrid.',
      },
      tags: ['dare-to-be-great', 'mentorship'],
      targetRoles: ['student-athlete', 'parent', 'coach', 'educator'],
    },
    {
      id: 's4',
      title: 'Equity & Access in Underserved Communities',
      cardType: 'solution',
      icon: 'shield-check',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'Direct programming for underserved schools & HBCUs.',
        medium: 'Programming delivered directly to underserved schools and HBCUs — closing the access gap.',
        large: 'PoweringU delivers programming directly to underserved schools and HBCUs — meeting students where they are, eliminating the access barriers that keep quality college and career programming out of these communities.',
        overlay: 'Equity is meeting students where they are. PoweringU\'s Equity & Access program brings NIL training, workforce readiness, Dare to Be Great, and mentorship programs directly to underserved public high schools, HBCUs, and community organizations — at no cost to the student or the school. Funded by donors and corporate partners.',
      },
      tags: ['workforce-readiness', 'partner-with-us', 'mentorship'],
      targetRoles: ['educator', 'donor', 'corporate-partner', 'mentor'],
    },
    {
      id: 's5',
      title: 'Mentorship Network',
      cardType: 'solution',
      icon: 'handshake',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'One-on-one mentor matching for student athletes.',
        medium: 'A network of former athletes and industry leaders matched one-on-one with student athletes.',
        large: 'A network of former athletes, corporate leaders, and educators matched one-on-one with student athletes for ongoing mentorship — across NIL, career, and personal development.',
        overlay: 'PoweringU\'s mentorship network pairs student athletes one-on-one with mentors who have walked the path — former pro and college athletes, corporate executives, entrepreneurs, educators. Mentor relationships cover NIL strategy, career development, financial confidence, and the questions that don\'t fit anywhere else. Become a mentor or request one.',
      },
      tags: ['mentorship'],
      targetRoles: ['student-athlete', 'mentor', 'parent'],
    },
    {
      id: 's6',
      title: 'Corporate Partnership',
      cardType: 'solution',
      icon: 'briefcase',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'Partner your organization with PoweringU.',
        medium: 'Corporate partnership tiers that fund programs, brand activation, and impact reporting.',
        large: 'Corporate partnership tiers that fund programs at underserved schools and HBCUs — with brand activation at PoweringU events, on-campus programming, and quarterly impact reporting back to partners.',
        overlay: 'Corporate partnership is how PoweringU scales. Partnership tiers fund specific programs at underserved schools and HBCUs (NIL, workforce, Dare to Be Great, mentorship), give partners brand activation at events and on-campus programming, and include transparent quarterly + annual impact reporting so leadership and finance teams can see the actual outcomes their dollars produce.',
      },
      tags: ['partner-with-us', 'donate'],
      targetRoles: ['corporate-partner', 'donor'],
    },
    {
      id: 's7',
      title: 'Donate to the Foundation',
      cardType: 'solution',
      icon: 'heart',
      iconType: 'lucide',
      url: 'https://poweringufoundation.org/',
      description: {
        small: 'Make a tax-deductible donation — 501(c)(3).',
        medium: 'Tax-deductible donations fund programming for student athletes in underserved communities.',
        large: 'Tax-deductible donations fund every PoweringU program — NIL training, workforce readiness, Dare to Be Great, mentorship, and direct delivery to underserved schools and HBCUs.',
        overlay: 'PoweringU Foundation is a registered 501(c)(3) (EIN 86-2840497). Every donation is fully tax-deductible and goes directly toward programs serving student athletes — NIL education, workforce readiness, Dare to Be Great leadership, mentor matching, and equity programming for HBCUs and underserved schools. Monthly recurring options available.',
      },
      tags: ['donate'],
      targetRoles: ['donor', 'parent', 'mentor', 'corporate-partner'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
