// Explorer Config — PROVEN (Proven Sports)
// Verified athletic infrastructure connecting student-athletes, coaches,
// schools, and college recruiters. "Every Athlete Deserves a Fair Shot."

import type { ExplorerConfig, ThemeColors } from '../types';

const PROVEN_DARK: ThemeColors = {
  bg: '#03161C',
  bgGradient: 'linear-gradient(135deg, #19224D 0%, #0A0E24 55%, #112B52 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#50C8EC',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(80,200,236,0.15)',
};

const PROVEN_LIGHT: ThemeColors = {
  bg: '#F4F5F9',
  bgGradient: 'linear-gradient(180deg, #F4F5F9 0%, #F1F3F8 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#1FA8D8',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#19224D',
  focusRing: 'rgba(80,200,236,0.12)',
};

export const PROVEN_CONFIG: ExplorerConfig = {
  id: 'proven',
  name: 'PROVEN Explorer',
  version: 1,
  createdAt: '2026-05-29T00:00:00.000Z',
  updatedAt: '2026-05-29T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/proven-logo-reverse.png',
      light: '/brand/assets/proven-logo.png',
    },
    icon: '/brand/assets/proven-icon.png',
    colors: {
      primary: '#50C8EC',   // brand cyan (the PROVEN checkmark) — main accent
      secondary: '#F68A32', // brand orange — CTA / highlight
      teal: '#50C8EC',      // cyan drives selected-state tints
      blue: '#3B9FE0',
      deepBlue: '#1E5AA8',
      navy: '#06303C',      // brand navy — drives overlay backdrop
      midnight: '#031A20',  // near-black navy — drives dialog background
      plum: '#F68A32',      // warm accent used in gradients
      bgDark: '#031A20',
      dark: PROVEN_DARK,
      light: PROVEN_LIGHT,
    },
    font: "'Helvetica Neue'",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(80,200,236,0.14)',
      orb2: 'rgba(246,138,50,0.12)',
      orb3: 'rgba(30,90,168,0.10)',
    },
    ctaGradient: 'linear-gradient(135deg, #FBA94C, #F68A32)',
    ctaTextColor: '#19224D',
    gradientWord: 'linear-gradient(135deg, #50C8EC, #F68A32)',
    gradientWordLight: 'linear-gradient(135deg, #1FA8D8, #E8731A)',
    roleBackgrounds: {
      'student-athlete': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(80,200,236,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(246,138,50,0.12) 0%, transparent 55%)',
      'parent': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(246,138,50,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(80,200,236,0.12) 0%, transparent 55%)',
      'coach': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(59,159,224,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(80,200,236,0.14) 0%, transparent 55%)',
      'athletic-director': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(30,90,168,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(80,200,236,0.12) 0%, transparent 55%)',
      'college-recruiter': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(80,200,236,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(246,138,50,0.12) 0%, transparent 55%)',
      'school-leader': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(59,159,224,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(246,138,50,0.10) 0%, transparent 55%)',
      'association': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(246,138,50,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(80,200,236,0.14) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(30,90,168,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(80,200,236,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'form',
    formTitle: 'Tell us about you',
    formSubtitle: 'A few quick details so we can tailor what you see.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to PROVEN contacting you about verified athlete profiles, recruiting tools, and program resources relevant to your request.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@school.edu', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'organization', label: 'School / Organization', type: 'text', placeholder: 'School, district, or program', required: false, halfWidth: true },
      { id: 'sport', label: 'Sport', type: 'text', placeholder: 'Primary sport', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Every Athlete Deserves',
      gradientWord: 'a Fair Shot.',
      subtitle: 'The verified athletic infrastructure connecting student-athletes, coaches, schools, and college recruiters.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes you?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'student-athlete', label: 'Student-Athlete', icon: 'trophy', iconType: 'lucide' },
        { value: 'parent', label: 'Parent / Family', icon: 'users', iconType: 'lucide' },
        { value: 'coach', label: 'Coach', icon: 'megaphone', iconType: 'lucide' },
        { value: 'athletic-director', label: 'Athletic Director', icon: 'shield', iconType: 'lucide' },
        { value: 'college-recruiter', label: 'College Recruiter', icon: 'search', iconType: 'lucide' },
        { value: 'school-leader', label: 'School / District Leader', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'association', label: 'Association / Governing Body', icon: 'landmark', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'message-circle', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you here to explore?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'verified-data', label: 'Verified Performance Data', icon: 'shield-check', iconType: 'lucide' },
        { value: 'recruiting', label: 'Recruiting & College Pathways', icon: 'network', iconType: 'lucide' },
        { value: 'development', label: 'Athlete Development', icon: 'trending-up', iconType: 'lucide' },
        { value: 'nil-compliance', label: 'NIL & Compliance', icon: 'dollar-sign', iconType: 'lucide' },
        { value: 'program-building', label: 'Program Building', icon: 'layout-dashboard', iconType: 'lucide' },
        { value: 'elite-evaluation', label: 'Elite Evaluation', icon: 'award', iconType: 'lucide' },
        { value: 'equity-access', label: 'Equity & Access', icon: 'handshake', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Exploring', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and platform tools based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Guides', value: 'whitepaper' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Podcast', value: 'podcast' },
        ]},
        { id: 'solutions', label: 'Platform', icon: 'layers' },
      ],
      cardsPerPage: 6,
      defaultView: 'medium',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse everything PROVEN has to offer.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: 'Verified Data Recruiters Trust',
      cardType: 'outcome',
      icon: 'shield-check',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: 'Every metric laser-timed and video-verified.',
        medium: '100% of PROVEN performance data is laser-timed and video-verified, so recruiters can trust every number.',
        large: 'In a recruiting market flooded with inflated, unverified numbers, PROVEN captures laser-timed, video-backed performance data that flows directly into the athlete profile, giving college coaches data they can act on with confidence.',
        overlay: 'College staffs are smaller and rely on data and video before ever visiting an athlete. PROVEN replaces self-reported, inflated measurables with 100% laser-timed, video-verified performance data. Every stat is captured at controlled events and written straight to the athlete profile, building immediate credibility with recruiters and leveling the playing field for every athlete.',
      },
      tags: ['verified-data', 'recruiting'],
      targetRoles: ['student-athlete', 'coach', 'college-recruiter', 'parent'],
      targetInterests: ['verified-data', 'recruiting'],
    },
    {
      id: 'o2',
      title: 'One Platform for Every Sport',
      cardType: 'outcome',
      icon: 'layout-dashboard',
      iconType: 'lucide',
      stat: '1',
      description: {
        small: 'Replace spreadsheets with one athletics OS.',
        medium: 'A single platform unifies athlete data, recruiting, academics, and compliance across every team.',
        large: 'Most schools juggle spreadsheets, group texts, and disconnected tools. PROVEN consolidates verified data, development tracking, recruiting visibility, and administrative oversight into one athletics operating system.',
        overlay: 'Athletic departments are run on fragmented systems: spreadsheets for stats, group chats for comms, separate tools for compliance. PROVEN functions as the school\'s athletics operating system, unifying verified performance data, longitudinal development, recruiting activity, academics, and NIL oversight across every sport and season in a single platform.',
      },
      tags: ['program-building', 'verified-data'],
      targetRoles: ['athletic-director', 'school-leader', 'coach'],
      targetInterests: ['program-building'],
    },
    {
      id: 'o3',
      title: 'First Practice to Signing Day',
      cardType: 'outcome',
      icon: 'calendar-days',
      iconType: 'lucide',
      stat: '4 yrs',
      description: {
        small: 'A living profile that grows with the athlete.',
        medium: 'Track verified development across all four years, from freshman testing to signing day and beyond.',
        large: 'Recruiters value improvement. PROVEN maintains a living athlete profile with longitudinal, year-over-year verified data, so growth and trajectory become part of the story, not just a single combine number.',
        overlay: 'Recruiting now starts as early as freshman year. PROVEN builds a living athlete profile that evolves across all four years of high school, capturing verified testing, position-specific measurements, video, and academics over time. Coaches and recruiters can see progress and trajectory, turning consistent development into a powerful recruiting advantage.',
      },
      tags: ['development', 'recruiting'],
      targetRoles: ['student-athlete', 'parent', 'coach'],
      targetInterests: ['development', 'recruiting'],
    },
    {
      id: 'o4',
      title: 'NFL-Level Evaluation Experience',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: '300+',
      description: {
        small: '300+ combined years of pro scouting expertise.',
        medium: 'Proven Elite evaluators bring 300+ combined years of NFL, college, and high school scouting experience.',
        large: 'Elite Source Evaluators (ESE) is staffed by former NFL coaches, scouts, and executives with 300+ combined years of evaluation experience, applying a professional stratification model to project elite high school talent.',
        overlay: 'Film shows what a player has done; evaluation reveals who they will become. Proven Elite\'s Elite Source Evaluators are former NFL and college coaches, scouts, and executives with 300+ combined years of player evaluation experience. They apply the same professional stratification model used by NFL organizations, delivering a 360-degree view of talent that no highlight reel or star ranking can match.',
      },
      tags: ['elite-evaluation', 'recruiting'],
      targetRoles: ['college-recruiter', 'athletic-director', 'student-athlete'],
      targetInterests: ['elite-evaluation', 'recruiting'],
    },
    {
      id: 'o5',
      title: '10% Reinvested in Schools',
      cardType: 'outcome',
      icon: 'handshake',
      iconType: 'lucide',
      stat: '10%',
      description: {
        small: 'Revenue reinvested to fund under-resourced schools.',
        medium: 'PROVEN allocates 10% of Texas revenue to subsidize under-funded and rural school programs.',
        large: 'Equity is built into the model. PROVEN commits 10% of its Texas revenue to subsidize under-resourced and rural schools, helping preserve education-based athletics and level the playing field statewide.',
        overlay: 'PROVEN exists to protect education-based athletics against sport-centric academies and to give rural and under-resourced schools a fair shot. As part of its partnership model with state coaching associations, PROVEN allocates 10% of Texas revenue back to subsidize under-funded schools, ensuring access is not limited to the most visible or well-resourced programs.',
      },
      tags: ['equity-access'],
      targetRoles: ['association', 'school-leader', 'athletic-director'],
      targetInterests: ['equity-access'],
    },
    {
      id: 'o6',
      title: '5,000+ Texas Schools in Reach',
      cardType: 'outcome',
      icon: 'school',
      iconType: 'lucide',
      stat: '5,000+',
      description: {
        small: 'Built to scale across every Texas school.',
        medium: 'Designed to reach 1,000+ districts and 5,000+ schools across Texas, with nationwide scale ahead.',
        large: 'PROVEN is built for statewide rollout, targeting every student-athlete across 1,000+ Texas ISDs and 5,000+ schools, in partnership with coaching associations, with a long-term national footprint in the millions.',
        overlay: 'PROVEN\'s go-to-market is statewide and education-based, partnering with associations like THSCA and THSADA to reach 1,000+ Texas ISDs and 5,000+ schools. The platform is designed to serve every Texas student-athlete across every sport, with a long-term vision to scale nationally into the millions of athletes.',
      },
      tags: ['program-building', 'equity-access'],
      targetRoles: ['association', 'athletic-director', 'school-leader'],
      targetInterests: ['program-building', 'equity-access'],
    },
    {
      id: 'o7',
      title: 'A Free Profile for Every Athlete',
      cardType: 'outcome',
      icon: 'dollar-sign',
      iconType: 'lucide',
      stat: 'Free',
      description: {
        small: 'No paywalls, no pay-to-play.',
        medium: 'Every student-athlete gets a free, verified profile, regardless of background or budget.',
        large: 'PROVEN removes the pay-to-play barrier that dominates recruiting. The core verified athlete profile is free for every student-athlete, with optional premium enhancements available.',
        overlay: 'The recruiting market is crowded with pay-to-play services where unverified data and connections decide who gets seen. PROVEN flips that model: every student-athlete, regardless of background, receives a free verified profile housing combine data, video, academics, and coach verification. Optional premium enhancements exist, but visibility and credibility never sit behind a paywall.',
      },
      tags: ['verified-data', 'equity-access', 'recruiting'],
      targetRoles: ['student-athlete', 'parent'],
      targetInterests: ['equity-access', 'verified-data'],
    },

    // ── Learn (7) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'The Road to Recruitment',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'file-text',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'A student-athlete guide to standing out.',
        medium: 'How to get seen, get verified, and get recruited in the modern college sports landscape.',
        large: 'This student-athlete guide breaks down the modern recruiting process: what recruiters actually want to see, the five essentials of a standout profile, and how verified data turns potential into opportunity.',
        overlay: 'Thousands of athletes compete for limited roster spots, and recruiters receive more profiles than they can review. This guide walks student-athletes through the new recruiting reality: smaller college staffs that rely on data and video, the five essentials of a recruiting-ready profile, best practices for getting recruited, and why verified data is the ultimate credibility builder. Talent gets noticed; verified talent gets recruited.',
      },
      tags: ['recruiting', 'verified-data'],
      targetRoles: ['student-athlete', 'parent'],
      targetInterests: ['recruiting', 'verified-data'],
    },
    {
      id: 'l2',
      title: 'Beyond Coaching',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'book-open',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'Building championship programs, not just teams.',
        medium: 'How comprehensive program development drives success on and off the field.',
        large: 'This paper explores the difference between coaching a team and building a program, outlining the twelve pillars of a modern high school sports program and how coaches evolve from strategists into program architects.',
        overlay: 'Modern high school coaches are program architects, managing athlete data, recruiting visibility, parental expectations, staff, and NIL. This paper contrasts season-to-season team coaching with multi-year program building and details the twelve pillars of a sustainable program: athlete development, recruiting pathways, culture and leadership, parent and community engagement, staff development, academic integration, and more. A well-built program can outlast any single coach.',
      },
      tags: ['program-building', 'development'],
      targetRoles: ['coach', 'athletic-director'],
      targetInterests: ['program-building', 'development'],
    },
    {
      id: 'l3',
      title: 'Becoming a Proven School',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'graduation-cap',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'A blueprint for athletic directors.',
        medium: 'How modern athletic programs use verified data and unified infrastructure to elevate outcomes.',
        large: 'Written for athletic directors and school leaders, this narrative defines what it means to be a Proven School and quantifies the value of verified data, professional evaluation, and unified infrastructure across every program.',
        overlay: 'Today\'s athletic director balances compliance, competitive performance, multi-sport coordination, and college-placement expectations, usually with spreadsheets and ad hoc tools. This narrative defines the Proven School: verified performance as the standard, infrastructure that professionalizes coaching, and unified administrative visibility across all sports. It details four strategic value categories for ADs, from academic and compliance oversight to program performance analytics and brand protection.',
      },
      tags: ['program-building', 'nil-compliance'],
      targetRoles: ['athletic-director', 'school-leader'],
      targetInterests: ['program-building', 'nil-compliance'],
    },
    {
      id: 'l4',
      title: 'Precision Recruiting: Proven Elite',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'star',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'NFL-grade evaluation for elite talent.',
        medium: 'How Elite Source Evaluators redefine talent assessment for the modern college game.',
        large: 'This paper details how Proven Elite delivers NFL-level player evaluation: verified combine data, position-specific analysis, film breakdown, and behavioral interviews that reveal football IQ, leadership, and coachability.',
        overlay: 'In the NIL and transfer-portal era, recruiting is both a football and a financial decision, and even highly publicized prospects are hard to project. Proven Elite\'s Elite Source Evaluators bring NFL-grade evaluation to elite high school talent through invitation-only showcases: verified combine data, position-specific rankings, comprehensive write-ups, film assessment, and behavioral interviews. The result is confidential, professional player dossiers that give college coaches the accuracy and credibility a highlight reel never could.',
      },
      tags: ['elite-evaluation', 'recruiting'],
      targetRoles: ['college-recruiter', 'athletic-director', 'student-athlete'],
      targetInterests: ['elite-evaluation', 'recruiting'],
    },
    {
      id: 'l5',
      title: 'Understanding NIL & Representation',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'dollar-sign',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'What families need to know about NIL.',
        medium: 'A plain-language primer on NIL, advisors, and protecting your athlete.',
        large: 'NIL and representation are reshaping high school sports. This primer covers NIL awareness, how to vet agents and advisors, and how to protect your athlete from misinformation and unverified advisors.',
        overlay: 'The modern athlete must understand more than the game. NIL rules vary by state, and athletes are increasingly approached by agents and advisors. This resource helps families and coaches navigate NIL basics, brand management, and compliance, and explains how to identify who to trust at the high school level. PROVEN provides educational resources, transparent athlete-coach communication, and verified information management for safe, professional exposure.',
      },
      tags: ['nil-compliance'],
      targetRoles: ['parent', 'student-athlete', 'coach', 'athletic-director'],
      targetInterests: ['nil-compliance'],
    },
    {
      id: 'l6',
      title: 'What Recruiters Want to See',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'Inside the recruiter evaluation mindset.',
        medium: 'College recruiters break down exactly what separates a recruitable profile.',
        large: 'Recruiters explain what earns a second look: verified performance data, game and skill video, academic consistency, character and leadership, and professional communication and follow-through.',
        overlay: 'Coaches recruit people, not just players, and every interaction counts. In this segment, college recruiters detail the five things they look for first: verified, measurable performance data; game and skill video that shows game IQ; academic eligibility and consistency; character, discipline, and coachability; and responsive, professional communication. It is a practical look at how to make it easy for a coach to find you, evaluate you, and believe in you.',
      },
      tags: ['recruiting', 'verified-data'],
      targetRoles: ['student-athlete', 'parent', 'coach'],
      targetInterests: ['recruiting', 'verified-data'],
    },
    {
      id: 'l7',
      title: 'The Modern Recruiting Landscape',
      cardType: 'learn',
      mediaType: 'podcast',
      icon: 'mic',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'NIL, the portal, and the new rules of recruiting.',
        medium: 'A conversation on how NIL and the transfer portal reshaped recruiting decisions.',
        large: 'This conversation explores how the NIL era and transfer portal turned recruiting into a multi-million-dollar talent investment, and why verified, standardized evaluation has become a competitive advantage.',
        overlay: 'The rise of NIL and the transfer portal has made every scholarship a high-stakes financial decision, with roster turnover and brand reputation on the line. This discussion unpacks the volume of talent, the unreliability of unverified data, and why coaches increasingly demand consistent, verified evaluation. In the NIL era, accurate evaluation is not a luxury, it is a competitive advantage, and standardized verified data makes the process more efficient and equitable for everyone.',
      },
      tags: ['recruiting', 'elite-evaluation', 'nil-compliance'],
      targetRoles: ['college-recruiter', 'coach', 'athletic-director'],
      targetInterests: ['recruiting', 'elite-evaluation', 'nil-compliance'],
    },

    // ── Solutions / Platform (7) ──────────────────────
    {
      id: 's1',
      title: 'Proven Athlete Profile',
      cardType: 'solution',
      icon: 'user',
      iconType: 'lucide',
      url: 'https://proven-indol.vercel.app/',
      description: {
        small: 'One free, verified profile for every athlete.',
        medium: 'Verified stats, video, academics, and coach verification, all in one shareable profile.',
        large: 'The Proven Athlete Profile brings the five essentials together in one place: verified combine and performance data, embedded video, academic and athletic info formatted for recruiters, and trusted coach verification.',
        overlay: 'Your PROVEN profile is your 24/7 recruiter connection, always visible and always verified. It unifies the five essentials of a standout profile: accurate personal and academic information, verified athletic data, video highlights and skill footage, character and personality, and coach references. Built-in update tools and shareable links keep it current and maximize exposure in verified recruiter networks, with no paywalls or exaggerations.',
      },
      tags: ['verified-data', 'recruiting'],
      targetRoles: ['student-athlete', 'parent'],
      targetInterests: ['verified-data', 'recruiting'],
    },
    {
      id: 's2',
      title: 'Proven School',
      cardType: 'solution',
      icon: 'school',
      iconType: 'lucide',
      url: 'https://proven-indol.vercel.app/',
      description: {
        small: 'The athletics operating system for your school.',
        medium: 'School-wide infrastructure for verified data, program management, and recruiting visibility.',
        large: 'Proven School operates every team, athlete, and development process through one platform, delivering verified performance data, structured program management, and trusted college-recruiting visibility across the whole athletic department.',
        overlay: 'A Proven School runs its entire athletic department on professional-grade infrastructure. Coaches get centralized athlete data, analytics, recruiting tools, and academic oversight. Athletic directors get real-time dashboards across every sport: development trends, academic alerts, recruiting activity, and compliance support for NIL and representation. It protects school reputation, elevates athlete opportunity, and gives leadership visibility across the entire athletic ecosystem.',
      },
      tags: ['program-building', 'nil-compliance'],
      targetRoles: ['athletic-director', 'school-leader', 'coach'],
      targetInterests: ['program-building', 'nil-compliance'],
    },
    {
      id: 's3',
      title: 'Proven Elite (ESE)',
      cardType: 'solution',
      icon: 'crown',
      iconType: 'lucide',
      url: 'https://proven-indol.vercel.app/',
      description: {
        small: 'NFL-grade evaluation for elite talent.',
        medium: 'Invitation-only showcases led by former NFL scouts and executives.',
        large: 'Proven Elite\'s Elite Source Evaluators deliver professional-grade talent assessment through invitation-only showcase events: verified combine data, position-specific rankings, film breakdown, and behavioral interviews.',
        overlay: 'Proven Elite is more than a combine. Elite Source Evaluators, former NFL and college coaches, scouts, and executives, evaluate top high school talent using the professional stratification model NFL organizations rely on. Each evaluation includes verified combine data, position-specific analysis, comprehensive player write-ups, film assessment, and behavioral interviews to gauge intangibles, producing confidential dossiers that give recruiters genuine confidence.',
      },
      tags: ['elite-evaluation', 'recruiting'],
      targetRoles: ['college-recruiter', 'student-athlete', 'athletic-director'],
      targetInterests: ['elite-evaluation', 'recruiting'],
    },
    {
      id: 's4',
      title: 'Proven Portal',
      cardType: 'solution',
      icon: 'search',
      iconType: 'lucide',
      url: 'https://proven-indol.vercel.app/',
      description: {
        small: 'Search and evaluate verified prospects.',
        medium: 'A recruiter workspace to search, evaluate, and contact verified prospects.',
        large: 'The Proven Portal gives college recruiters a single place to search verified prospects, compare standardized performance data across athletes and positions, and connect with athletes and their coaches.',
        overlay: 'Recruiters face volume, geographic dispersion, unverified data, and the financial weight of every scholarship decision. The Proven Portal solves this with searchable, verified prospect profiles, objective cross-athlete comparison on standardized combine data, and direct, trusted access to athletes and coaches. It makes high-stakes recruiting decisions faster, more confident, and more equitable.',
      },
      tags: ['recruiting', 'elite-evaluation'],
      targetRoles: ['college-recruiter'],
      targetInterests: ['recruiting', 'elite-evaluation'],
    },
    {
      id: 's5',
      title: 'Verified Combine & Testing',
      cardType: 'solution',
      icon: 'gauge',
      iconType: 'lucide',
      url: 'https://proven-indol.vercel.app/',
      description: {
        small: 'Laser-timed, video-backed data capture.',
        medium: 'Capture performance with laser timing and video to generate trusted, verified metrics.',
        large: 'PROVEN\'s testing tools capture athletic performance with laser timing and video verification, generating standardized metrics, maxes, and measurables that flow directly into the athlete profile.',
        overlay: 'Measurables that lack consistency or credibility undermine recruiting. PROVEN\'s verified combine and testing tools use laser timing and video capture to produce standardized, trustworthy performance data, maxes, measurables, and position-specific metrics. Results write directly to the athlete\'s living profile, creating an objective record that recruiters trust and that ensures fairness and consistency across schools and regions.',
      },
      tags: ['verified-data', 'development'],
      targetRoles: ['student-athlete', 'coach', 'athletic-director'],
      targetInterests: ['verified-data', 'development'],
    },
    {
      id: 's6',
      title: 'Coach & Program Dashboards',
      cardType: 'solution',
      icon: 'layout-dashboard',
      iconType: 'lucide',
      url: 'https://proven-indol.vercel.app/',
      description: {
        small: 'Centralized data for the whole staff.',
        medium: 'Shared athlete data, analytics, and communication for coaches and staff.',
        large: 'Coach and program dashboards give every staff member access to the same athlete data, performance analytics, schedules, and recruiting tools, ensuring consistency across all teams and seasons.',
        overlay: 'Great programs do not rely on one person. PROVEN\'s shared database gives head coaches, assistants, and staff a single source of truth: centralized athlete data, performance analytics, development benchmarks, recruiting communication channels, and academic and eligibility oversight. It scales a coach\'s ability to advocate for every athlete on the roster while keeping the entire staff aligned year-round.',
      },
      tags: ['program-building', 'development'],
      targetRoles: ['coach', 'athletic-director'],
      targetInterests: ['program-building', 'development'],
    },
    {
      id: 's7',
      title: 'NIL & Compliance Center',
      cardType: 'solution',
      icon: 'dollar-sign',
      iconType: 'lucide',
      url: 'https://proven-indol.vercel.app/',
      description: {
        small: 'Education and safe, compliant communication.',
        medium: 'NIL education plus policy-aligned communication workflows that reduce risk.',
        large: 'The NIL & Compliance Center provides structured NIL education, policy-aligned communication workflows, and verified information management to protect athletes, families, and the school\'s brand.',
        overlay: 'NIL and representation introduce real risk for schools, families, and athletes. PROVEN\'s NIL & Compliance Center delivers structured education on NIL and representation, policy-aligned communication workflows, safe channels between college coaches, athletes, and families, and verified data that prevents misinformation and unethical recruiting behavior. It reduces compliance risk for the athletic director while protecting reputation and integrity.',
      },
      tags: ['nil-compliance'],
      targetRoles: ['athletic-director', 'parent', 'coach', 'school-leader'],
      targetInterests: ['nil-compliance'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
