// Explorer Config — Salas O'Brien
// Multidisciplinary engineering and design firm

import type { ExplorerConfig, ThemeColors } from '../types';

const SALAS_OBRIEN_DARK: ThemeColors = {
  bg: '#071D2F',
  bgGradient: 'linear-gradient(135deg, #0A2540 0%, #071D2F 55%, #082035 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#009DE0',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(0,157,224,0.20)',
};

const SALAS_OBRIEN_LIGHT: ThemeColors = {
  bg: '#F4F5F9',
  bgGradient: 'linear-gradient(180deg, #F4F5F9 0%, #F0F4F8 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#0077B6',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(0,157,224,0.12)',
};

export const SALAS_OBRIEN_CONFIG: ExplorerConfig = {
  id: 'salas-o-brien',
  name: "Salas O'Brien Explorer",
  version: 1,
  createdAt: '2026-04-28T00:00:00.000Z',
  updatedAt: '2026-04-28T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/salas-obrien-logo-reverse.svg',
      light: '/brand/assets/salas-obrien-logo.svg',
    },
    icon: '/brand/assets/salas-obrien-icon.png',
    colors: {
      primary: '#009DE0',
      secondary: '#0077B6',
      teal: '#009DE0',
      blue: '#0077B6',
      deepBlue: '#005A8E',
      navy: '#003A5C',
      midnight: '#00253D',
      plum: '#004870',
      bgDark: '#071D2F',
      dark: SALAS_OBRIEN_DARK,
      light: SALAS_OBRIEN_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(0,157,224,0.15)',
      orb2: 'rgba(0,90,142,0.12)',
      orb3: 'rgba(0,58,92,0.10)',
    },
    ctaGradient: 'linear-gradient(135deg, #009DE0, #005A8E)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #009DE0, #0077B6)',
    roleBackgrounds: {
      'facility-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,157,224,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(0,90,142,0.10) 0%, transparent 55%)',
      'energy-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,157,224,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(0,119,182,0.14) 0%, transparent 55%)',
      'c-suite': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,90,142,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(0,58,92,0.12) 0%, transparent 55%)',
      'project-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,58,92,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(0,119,182,0.10) 0%, transparent 55%)',
      'manufacturing-engineer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,37,61,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(0,90,142,0.12) 0%, transparent 55%)',
      'it-ot-director': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,157,224,0.14) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(0,72,112,0.12) 0%, transparent 55%)',
      'government-client': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,58,92,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(0,37,61,0.14) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(0,119,182,0.10) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(0,157,224,0.08) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'scan',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Please fill in the form to continue.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: "By sharing your information you consent to Salas O'Brien processing your data to fulfill your request and send relevant follow-up communications.",
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Company or organization', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Engineered for',
      gradientWord: 'Impact.',
      subtitle: "Discover how Salas O'Brien delivers multidisciplinary engineering excellence across energy, MEP, digital automation, and sustainability.",
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes your role?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'facility-manager', label: "Facility Manager / Owner's Rep", icon: 'building-2', iconType: 'lucide' },
        { value: 'energy-manager', label: 'Energy Manager / Sustainability Director', icon: 'zap', iconType: 'lucide' },
        { value: 'c-suite', label: 'C-Suite / Executive Leader', icon: 'briefcase', iconType: 'lucide' },
        { value: 'project-manager', label: 'Project Manager / Capital Planning', icon: 'clipboard-list', iconType: 'lucide' },
        { value: 'manufacturing-engineer', label: 'Manufacturing / Process Engineer', icon: 'factory', iconType: 'lucide' },
        { value: 'it-ot-director', label: 'IT / OT Director', icon: 'server', iconType: 'lucide' },
        { value: 'government-client', label: 'Government / Federal Client', icon: 'landmark', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'message-circle', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you most interested in?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'energy-decarbonization', label: 'Energy & Decarbonization', icon: 'flame', iconType: 'lucide' },
        { value: 'mep-building-systems', label: 'MEP & Building Systems', icon: 'wrench', iconType: 'lucide' },
        { value: 'digital-automation', label: 'Digital & Automation', icon: 'cpu', iconType: 'lucide' },
        { value: 'sustainability-net-zero', label: 'Sustainability & Net Zero', icon: 'leaf', iconType: 'lucide' },
        { value: 'process-industrial', label: 'Process & Industrial Engineering', icon: 'cog', iconType: 'lucide' },
        { value: 'resilience-security', label: 'Resilience & Energy Security', icon: 'shield', iconType: 'lucide' },
        { value: 'forensic-assessment', label: 'Forensic & Assessment Services', icon: 'search', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'PDF', value: 'pdf' },
          { label: 'Blog', value: 'blog' },
          { label: 'Webinar', value: 'webinar' },
          { label: 'Podcast', value: 'podcast' },
        ]},
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'medium',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: '#31 Top Design Firm',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: '#31',
      description: {
        small: 'ENR-ranked among the top design firms in the U.S.',
        medium: 'Salas O\'Brien is ENR-ranked #31 among the Top 500 Design Firms in 2026, a testament to consistent engineering excellence.',
        large: 'Recognized by Engineering News-Record as the #31 Top 500 Design Firm for 2026, Salas O\'Brien has built its reputation through disciplined technical delivery, a people-first culture, and an unwavering commitment to client outcomes across every market sector.',
        overlay: 'Engineering News-Record\'s Top 500 Design Firms ranking is the industry\'s most respected benchmark of scale, capability, and sustained performance. Salas O\'Brien\'s #31 ranking in 2026 reflects decades of growth through strategic acquisitions, organic expansion, and a culture that puts engineering excellence at the center of every engagement. Clients choose Salas O\'Brien knowing they\'re working with one of the most trusted firms in North America.',
      },
      tags: ['rankings', 'credibility'],
      targetRoles: ['facility-manager', 'energy-manager', 'c-suite', 'project-manager', 'manufacturing-engineer', 'it-ot-director', 'government-client', 'other'],
      targetInterests: ['energy-decarbonization', 'mep-building-systems', 'digital-automation', 'sustainability-net-zero', 'process-industrial', 'resilience-security', 'forensic-assessment', 'browsing'],
    },
    {
      id: 'o2',
      title: '4,850+ Expert Engineers',
      cardType: 'outcome',
      icon: 'users',
      iconType: 'lucide',
      stat: '4,850+',
      description: {
        small: 'A team of over 4,850 engineers and specialists.',
        medium: 'With 4,850+ team members across disciplines, Salas O\'Brien brings deep bench strength to every client engagement.',
        large: 'Salas O\'Brien\'s team of 4,850+ engineers, designers, and specialists spans mechanical, electrical, structural, civil, process, sustainability, and digital disciplines. This depth means clients get specialized expertise at every project phase without sacrificing coordination or quality.',
        overlay: 'Building a team of 4,850+ highly specialized professionals is no small feat. Salas O\'Brien has grown deliberately, attracting top engineering talent through a culture of ownership, continuous learning, and meaningful work. The result is a bench of multidisciplinary experts who bring both depth and breadth to every project, whether it\'s a single-discipline assignment or a complex, integrated delivery requiring coordination across MEP, sustainability, digital, and process teams simultaneously.',
      },
      tags: ['team', 'scale'],
      targetRoles: ['facility-manager', 'energy-manager', 'c-suite', 'project-manager', 'manufacturing-engineer', 'it-ot-director', 'government-client', 'other'],
      targetInterests: ['energy-decarbonization', 'mep-building-systems', 'digital-automation', 'sustainability-net-zero', 'process-industrial', 'resilience-security', 'forensic-assessment', 'browsing'],
    },
    {
      id: 'o3',
      title: '105+ Offices Across North America',
      cardType: 'outcome',
      icon: 'map-pin',
      iconType: 'lucide',
      stat: '105+',
      description: {
        small: 'Local presence in over 105 offices throughout North America.',
        medium: 'With 105+ offices across North America, Salas O\'Brien delivers local expertise backed by national resources.',
        large: '105+ offices positioned across North America means Salas O\'Brien engineers are never far from your project site. Clients benefit from responsive local teams who understand regional codes, market conditions, and construction environments, supported by the full capabilities of a nationally scaled firm.',
        overlay: 'National reach with local accountability is a competitive differentiator that sets Salas O\'Brien apart. Their 105+ offices aren\'t satellites of a distant headquarters; they are fully staffed, locally led teams embedded in the communities they serve. Whether your project is in a major metropolitan market or a secondary city, Salas O\'Brien can put boots on the ground with engineers who know the local landscape, the local utilities, and the local contractors. That combination of proximity and national scale is rare, and clients consistently cite it as a key reason they choose Salas O\'Brien.',
      },
      tags: ['geographic-reach', 'scale'],
      targetRoles: ['facility-manager', 'energy-manager', 'c-suite', 'project-manager', 'manufacturing-engineer', 'it-ot-director', 'government-client', 'other'],
      targetInterests: ['energy-decarbonization', 'mep-building-systems', 'digital-automation', 'sustainability-net-zero', 'process-industrial', 'resilience-security', 'forensic-assessment', 'browsing'],
    },
    {
      id: 'o4',
      title: '17,300+ Projects Delivered Annually',
      cardType: 'outcome',
      icon: 'trending-up',
      iconType: 'lucide',
      stat: '17,300+',
      description: {
        small: 'Over 17,300 projects completed every year.',
        medium: 'Salas O\'Brien delivers 17,300+ projects annually, applying proven processes and lessons learned across an extraordinary volume of work.',
        large: 'Executing 17,300+ projects per year means Salas O\'Brien has unmatched experience with project delivery at every scale. The institutional knowledge accumulated across this volume continuously sharpens technical quality, improves schedules, and informs better client outcomes on every new engagement.',
        overlay: '17,300+ projects annually is not just a volume metric; it is a learning engine. Every project Salas O\'Brien completes adds to an institutional knowledge base that informs better design decisions, smarter specifications, and more accurate budgets on the next project. Clients benefit directly from this experience curve: a firm that has solved your specific engineering challenge hundreds of times is simply better equipped to solve it for you efficiently, cost-effectively, and with fewer surprises than a competitor that encounters it for the first time.',
      },
      tags: ['project-volume', 'scale'],
      targetRoles: ['facility-manager', 'energy-manager', 'c-suite', 'project-manager', 'manufacturing-engineer', 'it-ot-director', 'government-client', 'other'],
      targetInterests: ['energy-decarbonization', 'mep-building-systems', 'digital-automation', 'sustainability-net-zero', 'process-industrial', 'resilience-security', 'forensic-assessment', 'browsing'],
    },
    {
      id: 'o5',
      title: '$20B Annual Construction Value',
      cardType: 'outcome',
      icon: 'building',
      iconType: 'lucide',
      stat: '$20B',
      description: {
        small: 'Managing $20B in construction value annually.',
        medium: 'Salas O\'Brien manages $20B in annual construction value, demonstrating the trust clients place in their project oversight.',
        large: '$20B in annual construction value under management reflects the confidence owners, developers, and institutions place in Salas O\'Brien\'s design and engineering leadership. This scale brings deep familiarity with cost drivers, constructability challenges, and contractor performance across all market sectors.',
        overlay: 'Managing $20B in construction value annually requires a systematic approach to quality, schedule, and budget that most firms simply cannot match. Salas O\'Brien\'s experience across this volume of capital deployment gives their engineers deep insight into what drives construction costs up or down, which specifications are buildable in today\'s market, and how to design for efficient construction. For clients making major capital investments, that practical construction intelligence translates directly into better project economics and fewer change orders.',
      },
      tags: ['scale', 'impact'],
      targetRoles: ['c-suite', 'project-manager', 'government-client'],
      targetInterests: ['mep-building-systems', 'energy-decarbonization', 'process-industrial'],
    },
    {
      id: 'o6',
      title: '#5 MEP Firm in North America',
      cardType: 'outcome',
      icon: 'trophy',
      iconType: 'lucide',
      stat: '#5',
      description: {
        small: 'Ranked #5 MEP Giants in North America by ENR.',
        medium: 'Salas O\'Brien is ranked #5 among MEP Giants in North America for 2025, reflecting their dominant position in building systems engineering.',
        large: 'ENR\'s MEP Giants ranking places Salas O\'Brien at #5 in North America, validating their leadership in mechanical, electrical, plumbing, fire protection, and technology systems. This ranking reflects both technical depth and the breadth of sectors and building types they serve across the continent.',
        overlay: 'The ENR MEP Giants ranking is the definitive measure of who leads in building systems engineering. Salas O\'Brien\'s #5 position in North America for 2025 is the result of building one of the most capable MEP practices on the continent, with specialists in HVAC, electrical distribution, plumbing, fire protection, technology infrastructure, acoustics, and commissioning. For owners and developers with demanding MEP requirements, working with a top-5 MEP firm means access to the deepest bench of building systems expertise available anywhere in the market.',
      },
      tags: ['mep', 'rankings'],
      targetRoles: ['facility-manager', 'project-manager', 'c-suite'],
      targetInterests: ['mep-building-systems', 'energy-decarbonization'],
    },
    {
      id: 'o7',
      title: 'Inc. 5000: 13-Time Honoree',
      cardType: 'outcome',
      icon: 'star',
      iconType: 'lucide',
      stat: '13x',
      description: {
        small: 'Recognized 13 times on the Inc. 5000 fastest-growing companies list.',
        medium: 'Salas O\'Brien has earned Inc. 5000 recognition 13 times, reflecting sustained growth and a business model that consistently wins client trust.',
        large: '13 Inc. 5000 appearances is a remarkable signal of sustained performance. It reflects an organization that has consistently grown revenue, expanded capability, and earned new business across multiple economic cycles, market downturns, and competitive shifts in the engineering industry.',
        overlay: 'Most companies appear on the Inc. 5000 list once or twice. Salas O\'Brien has earned that recognition 13 times, which speaks to the durability of their growth model. Behind that consistency is a clear value proposition that resonates in the market: multidisciplinary engineering delivered by a people-first culture with local presence and national scale. Clients who experience that model tend to come back, and they refer their peers. For new clients evaluating partners, 13 Inc. 5000 appearances is a powerful signal that Salas O\'Brien is doing something right, year after year.',
      },
      tags: ['growth', 'recognition'],
      targetRoles: ['facility-manager', 'energy-manager', 'c-suite', 'project-manager', 'manufacturing-engineer', 'it-ot-director', 'government-client', 'other'],
      targetInterests: ['energy-decarbonization', 'mep-building-systems', 'digital-automation', 'sustainability-net-zero', 'process-industrial', 'resilience-security', 'forensic-assessment', 'browsing'],
    },

    // ── Learn (7) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Energy Systems Innovation Overview',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://salasobrien.com/services/energy-resiliency/',
      description: {
        small: 'An overview of advanced energy systems and innovation.',
        medium: 'Explore Salas O\'Brien\'s approach to advanced energy systems, renewables, microgrids, and district energy infrastructure.',
        large: 'This video walkthrough covers Salas O\'Brien\'s full energy and resiliency practice, including renewable energy integration, distributed energy resources, microgrid design, district energy systems, and battery storage. See how their energy engineers help clients modernize infrastructure and reduce carbon footprints.',
        overlay: 'Salas O\'Brien\'s Energy & Resiliency practice is one of the most comprehensive in North America, spanning advanced energy systems, utility privatization, renewable energy integration, microgrid design, battery storage, solar development, district energy, and full-scale decarbonization planning. This video provides an overview of their capabilities, the types of clients they serve across sectors from federal facilities to commercial real estate, and the engineering approach that has made them a trusted partner for complex energy infrastructure challenges.',
      },
      tags: ['energy', 'innovation'],
      targetRoles: ['energy-manager', 'facility-manager', 'c-suite', 'government-client'],
      targetInterests: ['energy-decarbonization', 'resilience-security'],
    },
    {
      id: 'l2',
      title: 'Decarbonization Strategy Guide',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'A practical guide to transitioning from carbon to low-carbon energy.',
        medium: 'This guide outlines proven decarbonization pathways for transitioning facilities from carbon-intensive operations to low-carbon or net-zero energy profiles.',
        large: 'Salas O\'Brien\'s Decarbonization Strategy Guide provides a step-by-step framework for assessing current energy baselines, identifying decarbonization opportunities, prioritizing capital investments, and building a phased implementation roadmap. Practical guidance is grounded in hundreds of real client engagements across commercial, federal, industrial, and institutional sectors.',
        overlay: 'Decarbonization is one of the most complex strategic challenges facing facility owners and operators today. This guide distills Salas O\'Brien\'s experience across hundreds of decarbonization projects into a practical, actionable framework. It covers how to establish a credible energy baseline, evaluate electrification pathways for thermal loads, assess renewable energy options, model financial returns for capital investments, and build a phased roadmap that balances operational continuity with ambitious long-term goals. Whether you\'re pursuing regulatory compliance, ESG commitments, or operational savings, this guide provides the technical and strategic foundation to move forward confidently.',
      },
      tags: ['decarbonization', 'strategy'],
      targetRoles: ['energy-manager', 'c-suite', 'facility-manager', 'government-client'],
      targetInterests: ['energy-decarbonization', 'sustainability-net-zero'],
    },
    {
      id: 'l3',
      title: 'Net Zero: Where to Start',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://salasobrien.com/services/sustainability-consulting/',
      description: {
        small: 'A practical starting point for net zero sustainability programs.',
        medium: 'Salas O\'Brien\'s sustainability experts outline the first steps for organizations beginning their net zero journey, from LEED and WELL to ESG and energy modeling.',
        large: 'Getting started with a net zero program can feel overwhelming. This blog post breaks it down into manageable first steps: establishing an ESG baseline, conducting energy modeling, identifying quick wins through efficiency measures, and building the business case for deeper investments in renewables and electrification. Drawing on Salas O\'Brien\'s sustainability consulting practice, the guidance is grounded in real project experience.',
        overlay: 'Many organizations have made net zero commitments but aren\'t sure where to begin. This piece from Salas O\'Brien\'s sustainability consulting team provides clear, practical guidance for taking that first step. It covers how to conduct an energy and carbon baseline assessment, how to prioritize low-cost efficiency opportunities, how to engage stakeholders around LEED, WELL, and ESG reporting frameworks, and how to build a phased roadmap toward net zero that is financially defensible and operationally achievable. For organizations just starting the sustainability journey, this is the right place to begin.',
      },
      tags: ['sustainability', 'net-zero'],
      targetRoles: ['energy-manager', 'c-suite', 'facility-manager'],
      targetInterests: ['sustainability-net-zero', 'energy-decarbonization'],
    },
    {
      id: 'l4',
      title: 'Digital Transformation in Facilities',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'monitor',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'A webinar on digital transformation strategies for modern facilities.',
        medium: 'Salas O\'Brien experts discuss how industrial automation, digital twins, IIoT, and AI are reshaping facilities management and engineering operations.',
        large: 'In this webinar, Salas O\'Brien\'s Digital, Automation & Robotics practice leaders explore how organizations are using digital transformation to drive operational efficiency, predictive maintenance, safety improvements, and competitive differentiation. Topics include digital twin development, IIoT sensor integration, AI-driven analytics, AR/VR applications, and cybersecurity considerations for connected facilities.',
        overlay: 'Digital transformation in facilities is no longer optional; it\'s a competitive necessity. In this webinar, Salas O\'Brien\'s digital engineering experts walk through real-world examples of how industrial automation, digital twins, IIoT networks, AI analytics, and augmented reality are transforming how facilities operate and how engineering services are delivered. Attendees gain practical insight into how to assess their organization\'s digital readiness, prioritize investment areas, address cybersecurity risks in OT environments, and build a digital transformation roadmap that delivers measurable ROI at each stage.',
      },
      tags: ['digital-transformation', 'automation'],
      targetRoles: ['it-ot-director', 'manufacturing-engineer', 'c-suite', 'facility-manager'],
      targetInterests: ['digital-automation', 'mep-building-systems'],
    },
    {
      id: 'l5',
      title: 'Building Resilience into Critical Infrastructure',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'book-open',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'A whitepaper on engineering resilience for critical infrastructure.',
        medium: 'This whitepaper examines engineering strategies for building resilience into critical infrastructure, covering backup power, utility privatization, and energy security.',
        large: 'Salas O\'Brien\'s Critical Infrastructure Resilience whitepaper provides a comprehensive engineering framework for assessing vulnerabilities, designing redundancy, and implementing resilience measures across power, water, communications, and building systems. Case studies from federal, healthcare, and industrial clients illustrate how these strategies perform under real-world stress events.',
        overlay: 'Critical infrastructure resilience has never been more important. Climate-driven weather events, aging utility infrastructure, and geopolitical risks are creating new vulnerabilities for organizations that depend on reliable power, water, and communications. This whitepaper from Salas O\'Brien\'s engineering resilience team provides a thorough examination of how to assess infrastructure vulnerabilities, engineer appropriate redundancy and backup systems, evaluate utility privatization models for federal and institutional facilities, design microgrid systems for islanding capability, and measure resilience ROI. Backed by case studies from healthcare campuses, military installations, and industrial facilities, the guidance is practical and immediately applicable.',
      },
      tags: ['resilience', 'critical-infrastructure'],
      targetRoles: ['facility-manager', 'government-client', 'c-suite', 'energy-manager'],
      targetInterests: ['resilience-security', 'energy-decarbonization'],
    },
    {
      id: 'l6',
      title: 'MEP Engineering Best Practices for Modern Facilities',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://salasobrien.com/services/built-environment/',
      description: {
        small: 'Best practices in MEP engineering for contemporary buildings.',
        medium: 'Salas O\'Brien\'s MEP experts share best practices across mechanical, electrical, plumbing, fire protection, acoustics, and commissioning for modern facility projects.',
        large: 'Modern facilities demand increasingly sophisticated MEP systems that balance performance, energy efficiency, occupant comfort, and operational flexibility. This blog post from Salas O\'Brien\'s Built Environment practice distills lessons from thousands of projects into actionable best practices across HVAC design, electrical distribution, plumbing systems, fire protection, technology infrastructure, acoustic performance, and commissioning.',
        overlay: 'MEP systems are the circulatory system of any building, and getting them right at the design stage determines whether a facility performs as intended for its full useful life. Drawing on their position as the #5 MEP firm in North America, Salas O\'Brien\'s engineers share hard-won best practices from across thousands of projects in commercial, healthcare, education, data center, government, and industrial sectors. This post covers right-sizing mechanical systems for actual occupancy patterns, coordination strategies that prevent costly field conflicts, commissioning approaches that catch problems before occupancy, and technology integration considerations for future-ready buildings.',
      },
      tags: ['mep', 'best-practices'],
      targetRoles: ['facility-manager', 'project-manager', 'c-suite'],
      targetInterests: ['mep-building-systems', 'sustainability-net-zero'],
    },
    {
      id: 'l7',
      title: 'The Engineering Impact Podcast',
      cardType: 'learn',
      mediaType: 'podcast',
      icon: 'mic',
      iconType: 'lucide',
      url: '#',
      description: {
        small: 'Conversations on engineering excellence and client impact.',
        medium: 'The Engineering Impact Podcast features Salas O\'Brien leaders and clients discussing engineering innovation, project outcomes, and industry trends.',
        large: 'The Engineering Impact Podcast brings together Salas O\'Brien experts and industry leaders for candid conversations about what it takes to deliver engineering excellence. Episodes cover topics from decarbonization strategy and digital transformation to MEP innovation, forensic engineering, and the future of multidisciplinary project delivery.',
        overlay: 'The Engineering Impact Podcast is Salas O\'Brien\'s platform for sharing deep expertise and authentic perspectives on the topics that matter most to engineering professionals and facility owners. Episodes feature conversations with Salas O\'Brien practice leaders, clients, and industry thought leaders on subjects ranging from the latest trends in energy decarbonization and industrial automation to leadership lessons from complex project delivery and the evolving demands of the built environment. Whether you\'re an engineer looking to sharpen your technical knowledge or a facility owner trying to understand what\'s possible, this podcast offers valuable insight from the front lines of engineering practice.',
      },
      tags: ['podcast', 'thought-leadership'],
      targetRoles: ['facility-manager', 'energy-manager', 'c-suite', 'project-manager', 'manufacturing-engineer', 'it-ot-director', 'government-client', 'other'],
      targetInterests: ['energy-decarbonization', 'mep-building-systems', 'digital-automation', 'sustainability-net-zero', 'process-industrial', 'resilience-security', 'forensic-assessment', 'browsing'],
    },

    // ── Solutions (7) ─────────────────────────────────
    {
      id: 's1',
      title: 'Energy & Resiliency Services',
      cardType: 'solution',
      icon: 'zap',
      iconType: 'lucide',
      description: {
        small: 'Advanced energy systems, renewables, and resilient infrastructure.',
        medium: 'Salas O\'Brien\'s Energy & Resiliency practice delivers decarbonization, microgrid, solar, battery storage, and utility privatization solutions.',
        large: 'The Energy & Resiliency practice covers the full spectrum of modern energy engineering: decarbonization strategy and implementation, renewable energy integration, microgrid design and controls, battery storage, district energy systems, utility privatization, backup power, and advanced metering. Salas O\'Brien engineers work across federal, commercial, industrial, and institutional sectors to help clients achieve energy security, cost savings, and sustainability goals.',
        overlay: 'Energy and resilience have become inseparable strategic priorities for facility owners. Salas O\'Brien\'s Energy & Resiliency practice addresses both simultaneously. Their energy engineers help clients reduce carbon emissions and energy costs through decarbonization pathways, renewable integration, and efficiency improvements, while simultaneously hardening critical infrastructure against outages and disruptions through microgrids, backup power systems, battery storage, and utility privatization. The result is a more sustainable, more secure, and more cost-efficient energy infrastructure that meets today\'s operational demands and tomorrow\'s regulatory requirements.',
      },
      tags: ['energy', 'resiliency', 'decarbonization'],
      targetRoles: ['energy-manager', 'facility-manager', 'c-suite', 'government-client'],
      targetInterests: ['energy-decarbonization', 'resilience-security'],
    },
    {
      id: 's2',
      title: 'MEP & Built Environment',
      cardType: 'solution',
      icon: 'wrench',
      iconType: 'lucide',
      description: {
        small: 'Comprehensive MEP, structural, and technology systems engineering.',
        medium: 'Salas O\'Brien provides full-service MEP/FP, structural, civil, technology, acoustics, and commissioning for buildings of every type and scale.',
        large: 'As the #5 MEP firm in North America, Salas O\'Brien\'s Built Environment practice covers mechanical, electrical, plumbing, fire protection, structural, civil, technology, acoustics, building envelope, and commissioning. Their integrated delivery approach ensures all building systems are coordinated from the first design sketch through owner occupancy, minimizing conflicts, reducing costs, and maximizing operational performance.',
        overlay: 'The Built Environment practice is the foundation of Salas O\'Brien\'s business and the reason they hold the #5 MEP Giants ranking in North America. Their building systems engineers bring deep expertise in HVAC design, electrical distribution, plumbing, fire protection, structural engineering, civil site design, technology infrastructure, acoustic performance, and commissioning. What distinguishes Salas O\'Brien in this space is their integrated delivery model: because they can provide all of these disciplines under one roof, coordination is tighter, design conflicts are caught earlier, and the final product performs better for the owner. They work across commercial, healthcare, education, data center, government, hospitality, science and technology, and industrial market sectors.',
      },
      tags: ['mep', 'built-environment', 'commissioning'],
      targetRoles: ['facility-manager', 'project-manager', 'c-suite'],
      targetInterests: ['mep-building-systems', 'sustainability-net-zero'],
    },
    {
      id: 's3',
      title: 'Digital, Automation & Robotics',
      cardType: 'solution',
      icon: 'cpu',
      iconType: 'lucide',
      description: {
        small: 'Industrial automation, digital twins, IIoT, and robotics integration.',
        medium: 'Salas O\'Brien\'s digital practice delivers turnkey industrial automation, robotic systems, digital twins, IIoT, AI analytics, and OT cybersecurity.',
        large: 'The Digital, Automation & Robotics practice provides end-to-end engineering for the digitally connected facility and factory. Services include industrial automation system design and integration, turnkey robotic cell engineering, digital twin development, IIoT sensor and network architecture, AI and machine learning analytics, augmented and virtual reality applications, and cybersecurity for operational technology environments.',
        overlay: 'Digital transformation is reshaping every industry, and Salas O\'Brien\'s Digital, Automation & Robotics practice exists to help clients navigate that transformation with confidence. Their engineers bring together disciplines that are rarely found under one roof: industrial automation specialists who design and integrate complex control systems, robotics engineers who build turnkey automated work cells, digital twin architects who create virtual replicas of physical assets for simulation and optimization, IIoT experts who design sensor networks and data pipelines, and cybersecurity engineers who secure OT environments against evolving threats. For manufacturers, facility operators, and industrial organizations, Salas O\'Brien offers a single partner capable of delivering the full digital transformation stack.',
      },
      tags: ['digital', 'automation', 'robotics', 'iiot'],
      targetRoles: ['manufacturing-engineer', 'it-ot-director', 'c-suite'],
      targetInterests: ['digital-automation', 'process-industrial'],
    },
    {
      id: 's4',
      title: 'Sustainability Consulting & Design',
      cardType: 'solution',
      icon: 'leaf',
      iconType: 'lucide',
      description: {
        small: 'LEED, WELL, ESG, energy modeling, and net zero strategy.',
        medium: 'Salas O\'Brien\'s sustainability practice provides LEED and WELL consulting, ESG strategy, energy modeling, indoor air quality, and net zero roadmaps.',
        large: 'Sustainability Consulting & Design at Salas O\'Brien encompasses the full range of green building and ESG services: LEED and WELL certification consulting, ESG strategy development and reporting, energy modeling and simulation, indoor air quality assessment, net zero carbon roadmaps, life cycle assessment, and climate risk analysis. Their sustainability consultants work alongside the firm\'s MEP and energy engineers to ensure sustainability is embedded in design, not added as an afterthought.',
        overlay: 'Sustainability is no longer a nice-to-have; it is a business imperative driven by regulatory pressure, investor demands, tenant expectations, and a genuine commitment to reducing environmental impact. Salas O\'Brien\'s Sustainability Consulting & Design practice helps clients navigate this landscape with a clear-eyed, engineering-grounded approach. Whether the goal is achieving LEED Platinum, building an ESG reporting framework that satisfies investors, modeling energy performance to optimize capital investments, or developing a credible net zero roadmap, Salas O\'Brien brings the technical depth and strategic clarity to make it happen. Their sustainability consultants are embedded with MEP and energy engineering teams, ensuring that sustainability goals are translated into real, buildable, financially sound engineering solutions.',
      },
      tags: ['sustainability', 'leed', 'well', 'esg', 'net-zero'],
      targetRoles: ['energy-manager', 'c-suite', 'facility-manager'],
      targetInterests: ['sustainability-net-zero', 'energy-decarbonization'],
    },
    {
      id: 's5',
      title: 'Process Design & Integration',
      cardType: 'solution',
      icon: 'cog',
      iconType: 'lucide',
      description: {
        small: 'Process engineering, facility operations, and industrial construction management.',
        medium: 'Salas O\'Brien\'s Process Design & Integration practice delivers process engineering, facility optimization, and industrial construction management for complex manufacturing environments.',
        large: 'Process Design & Integration covers the engineering lifecycle from initial process concept through detailed design, commissioning, and operational support. Services include process flow development, P&ID design, facility layout optimization, utility system design for industrial processes, industrial construction management, startup and commissioning support, and ongoing operational improvement programs for pharmaceutical, food & beverage, biotech, chemical, and advanced manufacturing clients.',
        overlay: 'Industrial process facilities are among the most technically demanding projects in engineering, with requirements spanning process chemistry, mechanical systems, electrical and instrumentation, HVAC, utilities, environmental compliance, and quality systems. Salas O\'Brien\'s Process Design & Integration practice is built to handle that full complexity. Their process engineers work closely with clients from the earliest concept stages through detailed design, construction oversight, startup, and commissioning, providing continuity of technical knowledge across the entire project lifecycle. They serve pharmaceutical, biotech, food and beverage, chemical, and advanced manufacturing clients who demand rigorous compliance, exacting performance standards, and deep understanding of their processes.',
      },
      tags: ['process-engineering', 'industrial', 'manufacturing'],
      targetRoles: ['manufacturing-engineer', 'project-manager', 'c-suite'],
      targetInterests: ['process-industrial', 'digital-automation'],
    },
    {
      id: 's6',
      title: 'Forensic Consulting',
      cardType: 'solution',
      icon: 'search',
      iconType: 'lucide',
      description: {
        small: 'Forensic engineering, materials testing, and litigation support.',
        medium: 'Salas O\'Brien\'s forensic engineers provide failure analysis, materials testing, fire origin and cause determination, and expert litigation support.',
        large: 'Forensic Consulting at Salas O\'Brien combines deep engineering expertise with rigorous investigative methodology to serve clients facing construction defect claims, insurance investigations, regulatory inquiries, and litigation. Services include structural and systems failure analysis, materials testing and evaluation, fire origin and cause determination, code compliance assessment, and expert witness testimony.',
        overlay: 'When something goes wrong with a building, structure, or engineered system, the forensic investigation process requires both technical rigor and clear communication. Salas O\'Brien\'s Forensic Consulting practice brings experienced engineers who can analyze failures across structural, MEP, building envelope, and materials domains, gather and preserve evidence to legal standards, interpret test results and engineering data, and communicate findings clearly to legal teams, insurers, and courts. Whether the matter involves a construction defect claim, a catastrophic failure investigation, a fire origin and cause determination, or a dispute over code compliance, Salas O\'Brien provides objective, credible forensic engineering analysis and expert witness support.',
      },
      tags: ['forensic', 'litigation', 'failure-analysis'],
      targetRoles: ['c-suite', 'project-manager', 'other'],
      targetInterests: ['forensic-assessment'],
    },
    {
      id: 's7',
      title: 'Multi-Discipline Project Delivery',
      cardType: 'solution',
      icon: 'layers',
      iconType: 'lucide',
      description: {
        small: 'Integrated multidisciplinary delivery across all service lines.',
        medium: 'Salas O\'Brien integrates engineering disciplines across energy, MEP, digital, sustainability, and process for seamless complex project delivery.',
        large: 'One of Salas O\'Brien\'s greatest competitive strengths is the ability to deliver complex projects that span multiple engineering disciplines under a single, coordinated team. By integrating energy, MEP, digital, sustainability, process, and forensic expertise, they eliminate the coordination gaps that arise when clients must manage multiple specialty firms simultaneously, delivering better designs, faster schedules, and fewer surprises.',
        overlay: 'Complex facilities and infrastructure projects increasingly require expertise across multiple engineering disciplines simultaneously. Managing separate firms for MEP, energy, sustainability, process, and digital systems creates coordination risk, version control problems, and accountability gaps that drive up costs and delay schedules. Salas O\'Brien\'s multi-discipline delivery model solves this problem by bringing all required engineering disciplines under one coordinated team, with shared design tools, unified communication, and a single point of accountability to the owner. Clients consistently report that integrated delivery produces better designs, surfaces conflicts earlier, reduces RFIs during construction, and results in facilities that perform better from day one.',
      },
      tags: ['multidisciplinary', 'integration', 'project-delivery'],
      targetRoles: ['facility-manager', 'energy-manager', 'c-suite', 'project-manager', 'manufacturing-engineer', 'it-ot-director', 'government-client', 'other'],
      targetInterests: ['energy-decarbonization', 'mep-building-systems', 'digital-automation', 'sustainability-net-zero', 'process-industrial', 'resilience-security', 'forensic-assessment', 'browsing'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
