// Explorer Config — SalesFlowIQ
// AI-powered sales coaching and conversation intelligence platform

import type { ExplorerConfig, ThemeColors } from '../types';

const SALESFLOWIQ_DARK: ThemeColors = {
  bg: '#060D18',
  bgGradient: 'linear-gradient(135deg, #CC5A3D 0%, #081E30 55%, #0E3D5C 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#31B0E5',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(49,176,229,0.18)',
};

const SALESFLOWIQ_LIGHT: ThemeColors = {
  bg: '#F2F6FA',
  bgGradient: 'linear-gradient(160deg, #EDF2F7 0%, #F2F6FA 40%, #EBF0F6 100%)',
  surface: 'rgba(255,255,255,0.80)',
  surfaceHover: 'rgba(255,255,255,0.92)',
  border: 'rgba(8,30,48,0.08)',
  borderFocus: '#2899CC',
  text1: '#081E30',
  text2: 'rgba(8,30,48,0.62)',
  text3: 'rgba(8,30,48,0.42)',
  inputBg: '#FFFFFF',
  inputText: '#081E30',
  inputPlaceholder: 'rgba(8,30,48,0.35)',
  logoText: '#081E30',
  focusRing: 'rgba(40,153,204,0.12)',
};

export const SALESFLOWIQ_CONFIG: ExplorerConfig = {
  id: 'salesflowiq',
  name: 'SalesFlowIQ Explorer',
  version: 1,
  createdAt: '2026-04-14T00:00:00.000Z',
  updatedAt: '2026-04-14T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/salesflowiq-dark.png',
      light: '/brand/assets/salesflowiq-light.png',
    },
    icon: '/brand/assets/salesflowiq-icon.png',
    colors: {
      primary: '#31B0E5',
      secondary: '#FF7A59',
      teal: '#2899CC',
      blue: '#FF7A59',
      deepBlue: '#1B6B99',
      navy: '#0E3D5C',
      midnight: '#081E30',
      plum: '#CC5A3D',
      bgDark: '#060D18',
      dark: SALESFLOWIQ_DARK,
      light: SALESFLOWIQ_LIGHT,
    },
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(49,176,229,0.12)',
      orb2: 'rgba(255,122,89,0.13)',
      orb3: 'rgba(204,90,61,0.09)',
    },
    ctaGradient: 'linear-gradient(135deg, #2899CC, #FF7A59)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #31B0E5, #FF7A59)',
    gradientWordLight: 'linear-gradient(135deg, #1B6B99, #CC5A3D)',
    roleBackgrounds: {
      'vp-sales': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(204,90,61,0.25) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(27,107,153,0.18) 0%, transparent 55%)',
      'sales-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(49,176,229,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(255,122,89,0.14) 0%, transparent 55%)',
      'enablement': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(40,153,204,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(204,90,61,0.12) 0%, transparent 55%)',
      'rev-ops': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(27,107,153,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(49,176,229,0.15) 0%, transparent 55%)',
      'account-exec': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,122,89,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(40,153,204,0.15) 0%, transparent 55%)',
      'sdr-leader': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(49,176,229,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(27,107,153,0.20) 0%, transparent 55%)',
      'hr-talent': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(204,90,61,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(255,122,89,0.14) 0%, transparent 55%)',
      'other': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(40,153,204,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(204,90,61,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['scan', 'form', 'search'],
    defaultMode: 'scan',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Please fill in the form to continue.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to SalesFlowIQ processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Company name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Accelerate Every',
      gradientWord: 'Conversation.',
      subtitle: 'Discover AI-powered coaching, conversation intelligence, and analytics tailored to your sales organization.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes your role?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'vp-sales', label: 'VP of Sales / Sales Leader', icon: 'crown', iconType: 'lucide' },
        { value: 'sales-manager', label: 'Sales Manager', icon: 'users', iconType: 'lucide' },
        { value: 'enablement', label: 'Sales Enablement Leader', icon: 'rocket', iconType: 'lucide' },
        { value: 'rev-ops', label: 'Revenue Operations', icon: 'settings', iconType: 'lucide' },
        { value: 'account-exec', label: 'Sales Rep / Account Executive', icon: 'phone-call', iconType: 'lucide' },
        { value: 'sdr-leader', label: 'SDR / BDR Leader', icon: 'target', iconType: 'lucide' },
        { value: 'hr-talent', label: 'HR / Talent Acquisition', icon: 'user-plus', iconType: 'lucide' },
        { value: 'other', label: 'Other', icon: 'message-circle', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you most interested in?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'conversation-intel', label: 'Conversation Intelligence', icon: 'mic', iconType: 'lucide' },
        { value: 'coaching', label: 'Sales Coaching & Training', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'hiring', label: 'Hiring & Recruitment', icon: 'user-plus', iconType: 'lucide' },
        { value: 'analytics', label: 'Performance Analytics', icon: 'bar-chart-2', iconType: 'lucide' },
        { value: 'deal-accel', label: 'Deal Acceleration', icon: 'zap', iconType: 'lucide' },
        { value: 'onboarding', label: 'Team Onboarding', icon: 'clipboard-list', iconType: 'lucide' },
        { value: 'ai-automation', label: 'AI & Automation', icon: 'bot', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Exploring', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        { id: 'learn', label: 'Learn', icon: 'book-open', filters: [
          { label: 'All', value: 'all' },
          { label: 'Video', value: 'video' },
          { label: 'Blog', value: 'blog' },
          { label: 'Webinar', value: 'webinar' },
          { label: 'Whitepaper', value: 'whitepaper' },
          { label: 'PDF', value: 'pdf' },
        ]},
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'medium',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. Your personalized content will be sent to you shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: '35% Faster Ramp Time',
      cardType: 'outcome',
      icon: 'zap',
      iconType: 'lucide',
      stat: '35%',
      description: {
        small: 'New hires reach quota 35% faster with AI coaching.',
        medium: 'AI-driven skill assessments and adaptive practice scenarios help new reps reach quota 35% faster.',
        large: 'New hires reach quota 35% faster through AI-driven skill assessments, adaptive practice scenarios, and personalized coaching pathways that identify and close skill gaps in real time.',
        overlay: 'Ramping new sales reps is one of the most expensive and time-consuming challenges for growing teams. SalesFlowIQ combines AI-driven skill assessments with adaptive practice scenarios and personalized coaching pathways that identify gaps in real time, enabling new hires to reach full quota attainment 35% faster than traditional onboarding programs.',
      },
      tags: ['onboarding', 'coaching'],
      targetRoles: ['vp-sales', 'sales-manager', 'enablement'],
    },
    {
      id: 'o2',
      title: '2x Pipeline Conversion',
      cardType: 'outcome',
      icon: 'trending-up',
      iconType: 'lucide',
      stat: '2x',
      description: {
        small: 'Double pipeline conversion with conversation insights.',
        medium: 'Conversation intelligence surfaces winning patterns and deal-risk signals to double pipeline conversion rates.',
        large: 'Conversation intelligence surfaces winning patterns and deal-risk signals across every customer interaction, enabling reps to double their pipeline conversion by applying proven behaviors at each deal stage.',
        overlay: 'Most sales teams convert less than 20% of their pipeline. SalesFlowIQ analyzes every conversation to identify the specific behaviors, talk patterns, and competitive responses that correlate with closed deals. By surfacing these winning patterns and flagging at-risk deals in real time, teams consistently achieve 2x pipeline conversion improvement.',
      },
      tags: ['deal-accel', 'analytics'],
      targetRoles: ['vp-sales', 'rev-ops', 'account-exec'],
    },
    {
      id: 'o3',
      title: '28% Increase in Win Rates',
      cardType: 'outcome',
      icon: 'trophy',
      iconType: 'lucide',
      stat: '28%',
      description: {
        small: 'Boost win rates 28% with real-time AI guidance.',
        medium: 'AI coaching analyzes every interaction, providing real-time guidance that improves close rates by 28%.',
        large: 'AI coaching analyzes every customer interaction, providing reps with real-time guidance and post-call insights that improve messaging, objection handling, and close rates by 28%.',
        overlay: 'Win rates stall when reps rely on instinct instead of data. SalesFlowIQ\'s AI coaching engine analyzes every customer interaction across phone, video, and in-person meetings. It provides real-time guidance during live calls and detailed post-call insights on messaging effectiveness, objection handling, and competitive positioning, driving a 28% improvement in win rates.',
      },
      tags: ['coaching', 'conversation-intel'],
      targetRoles: ['sales-manager', 'enablement', 'account-exec'],
    },
    {
      id: 'o4',
      title: '60% Less Coaching Time',
      cardType: 'outcome',
      icon: 'clock',
      iconType: 'lucide',
      stat: '60%',
      description: {
        small: 'Cut manager coaching time by 60% with AI.',
        medium: 'Automated call analysis and AI-generated summaries reduce coaching time by 60% while improving quality.',
        large: 'Automated call analysis and AI-generated coaching summaries reduce the time managers spend reviewing calls by 60%, while increasing coaching quality and consistency across the team.',
        overlay: 'Sales managers spend an average of 8 hours per week reviewing calls and preparing coaching feedback. SalesFlowIQ automates call analysis and generates AI-powered coaching summaries with specific, actionable recommendations for each rep. This reduces coaching preparation time by 60% while actually improving coaching quality, consistency, and rep development outcomes.',
      },
      tags: ['coaching', 'ai-automation'],
      targetRoles: ['sales-manager', 'enablement'],
    },
    {
      id: 'o5',
      title: '3x More Qualified Pipeline',
      cardType: 'outcome',
      icon: 'filter',
      iconType: 'lucide',
      stat: '3x',
      description: {
        small: 'Generate 3x more qualified pipeline with AI.',
        medium: 'AI-powered prospecting intelligence and conversation scoring help SDR teams generate 3x more qualified pipeline.',
        large: 'AI-powered prospecting intelligence and conversation scoring help SDR teams generate 3x more qualified pipeline by identifying the highest-intent prospects and optimal outreach timing.',
        overlay: 'Outbound prospecting is a numbers game, but smart numbers win. SalesFlowIQ\'s AI analyzes conversation patterns, engagement signals, and historical win data to help SDR teams identify the highest-intent prospects and optimize outreach timing. Teams using these insights consistently generate 3x more qualified pipeline compared to traditional prospecting methods.',
      },
      tags: ['deal-accel', 'hiring'],
      targetRoles: ['sdr-leader', 'rev-ops', 'vp-sales'],
    },
    {
      id: 'o6',
      title: '45% Better Rep Retention',
      cardType: 'outcome',
      icon: 'heart',
      iconType: 'lucide',
      stat: '45%',
      description: {
        small: 'Improve rep retention by 45% with data-driven hiring.',
        medium: 'Data-driven hiring assessments and structured onboarding reduce early turnover and improve retention by 45%.',
        large: 'Data-driven hiring assessments combined with structured onboarding and continuous skill development reduce early turnover and improve rep retention by 45% across sales organizations.',
        overlay: 'Sales rep turnover costs organizations an average of $115,000 per departure when factoring in recruiting, training, and lost productivity. SalesFlowIQ\'s HireIQ platform uses AI-powered assessments to predict candidate success, while TrainerIQ provides structured skill development that keeps reps engaged and growing. Together, they reduce early turnover and improve overall rep retention by 45%.',
      },
      tags: ['hiring', 'onboarding'],
      targetRoles: ['hr-talent', 'vp-sales', 'sales-manager'],
    },
    {
      id: 'o7',
      title: 'Real-Time Performance Visibility',
      cardType: 'outcome',
      icon: 'activity',
      iconType: 'lucide',
      stat: '100%',
      description: {
        small: 'Complete visibility into team performance metrics.',
        medium: 'Unified dashboards provide instant visibility into calls, pipeline health, skill progression, and coaching effectiveness.',
        large: 'Unified dashboards give leaders instant visibility into team performance across calls, pipeline health, skill progression, and coaching effectiveness with AI-powered anomaly detection.',
        overlay: 'Sales leaders often make decisions based on lagging indicators and incomplete data. SalesFlowIQ\'s AnalyticsIQ provides unified dashboards that combine conversation analytics, pipeline health metrics, individual skill progression, and coaching effectiveness into a single real-time view. AI-powered anomaly detection surfaces emerging trends and at-risk deals before they become problems.',
      },
      tags: ['analytics', 'ai-automation'],
      targetRoles: ['vp-sales', 'rev-ops', 'sales-manager'],
    },

    // ── Learn (8) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'The Science of Sales Conversations',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai',
      description: {
        small: 'How AI transforms sales conversation analysis.',
        medium: 'Explore how conversation intelligence is transforming the way sales teams understand buyer signals and talk patterns.',
        large: 'This video explores how conversation intelligence is transforming the way sales teams understand buyer signals, talk patterns, and competitive dynamics to close more deals faster.',
        overlay: 'In this deep dive, learn how AI-powered conversation intelligence captures and analyzes every sales interaction to reveal winning patterns, competitor mentions, pricing discussions, and buying signals. See real examples of how top-performing teams use these insights to refine their messaging, handle objections more effectively, and accelerate deal velocity.',
      },
      tags: ['conversation-intel'],
      targetRoles: ['vp-sales', 'enablement', 'sales-manager'],
    },
    {
      id: 'l2',
      title: 'Building a Data-Driven Coaching Culture',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai',
      description: {
        small: 'Replace gut-feel coaching with data-driven frameworks.',
        medium: 'How leading sales organizations are replacing gut-feel coaching with data-driven frameworks powered by call analytics.',
        large: 'Learn how leading sales organizations are replacing gut-feel coaching with data-driven frameworks powered by call analytics, resulting in more consistent rep development and measurable performance gains.',
        overlay: 'The best sales managers don\'t just coach more, they coach smarter. This guide details how forward-thinking organizations are using conversation analytics to build systematic coaching cultures. Learn the frameworks for identifying coachable moments, measuring coaching impact, and scaling personalized development across large teams.',
      },
      tags: ['coaching', 'analytics'],
      targetRoles: ['sales-manager', 'enablement'],
    },
    {
      id: 'l3',
      title: 'AI-Powered Hiring: The Future of Sales Recruitment',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai',
      description: {
        small: 'AI assessments that predict sales candidate success.',
        medium: 'Recorded webinar covering how AI assessments predict sales success and reduce costly mis-hires.',
        large: 'This recorded webinar covers how AI assessments predict on-the-job sales success, reduce mis-hires by screening candidates with simulated scenarios, and accelerate time-to-productivity.',
        overlay: 'Hiring the wrong salesperson costs organizations up to 6x their annual salary. This webinar walks through how AI-driven assessments simulate real sales scenarios to evaluate candidates on the skills that actually predict success. Learn how to reduce mis-hires, accelerate ramp time, and build a more predictable hiring pipeline for your sales organization.',
      },
      tags: ['hiring', 'ai-automation'],
      targetRoles: ['hr-talent', 'vp-sales', 'sdr-leader'],
    },
    {
      id: 'l4',
      title: 'The Revenue Operations Playbook',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai',
      description: {
        small: 'Build a RevOps function for predictable revenue.',
        medium: 'Research-backed guide to building a RevOps function that unifies sales, marketing, and CS data.',
        large: 'This research-backed guide details how to build a RevOps function that unifies sales, marketing, and customer success data for predictable revenue growth and operational efficiency.',
        overlay: 'Revenue Operations is the connective tissue that aligns sales, marketing, and customer success around shared goals and unified data. This comprehensive playbook covers org design, tech stack architecture, KPI frameworks, and change management strategies for building a world-class RevOps function that drives predictable, scalable revenue growth.',
      },
      tags: ['analytics', 'deal-accel'],
      targetRoles: ['rev-ops', 'vp-sales'],
    },
    {
      id: 'l5',
      title: 'Conversation Intelligence ROI Calculator Guide',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai',
      description: {
        small: 'Calculate the ROI of conversation intelligence.',
        medium: 'Step-by-step guide to calculating the ROI of conversation intelligence across pipeline velocity and win rates.',
        large: 'A step-by-step guide to calculating the ROI of conversation intelligence across pipeline velocity, win rate improvement, ramp time reduction, and coaching efficiency gains.',
        overlay: 'Making the business case for conversation intelligence requires connecting technology investment to measurable revenue outcomes. This guide provides a detailed framework for calculating ROI across four dimensions: pipeline velocity improvement, win rate gains, new hire ramp time reduction, and coaching efficiency. Includes benchmarks from real deployments and a downloadable calculation worksheet.',
      },
      tags: ['conversation-intel', 'analytics'],
      targetRoles: ['vp-sales', 'rev-ops', 'enablement'],
    },
    {
      id: 'l6',
      title: 'From SDR to AE: Accelerating the Transition',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai',
      description: {
        small: 'Best practices for promoting SDRs to closing roles.',
        medium: 'Best practices for transitioning SDRs to closing roles with coaching frameworks and skill progression models.',
        large: 'Learn the best practices for transitioning SDRs to closing roles, including coaching frameworks, skill progression models, and how AI practice environments accelerate readiness.',
        overlay: 'The SDR-to-AE transition is a critical career moment that most organizations leave to chance. This guide details proven frameworks for identifying promotion-ready SDRs, building structured transition programs, and using AI-powered practice environments to accelerate closing skill development. Includes metrics for measuring transition success and reducing early-stage AE attrition.',
      },
      tags: ['onboarding', 'coaching'],
      targetRoles: ['sdr-leader', 'sales-manager', 'account-exec'],
    },
    {
      id: 'l7',
      title: 'Mastering Virtual Selling with AI',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai',
      description: {
        small: 'Leverage AI insights during video sales calls.',
        medium: 'How top-performing reps leverage AI insights during video calls to control deal momentum.',
        large: 'See how top-performing reps leverage AI insights during video calls to read the room, handle objections in real time, and maintain control of deal momentum throughout the sales cycle.',
        overlay: 'Virtual selling is now the default for most B2B sales interactions, but most reps aren\'t fully leveraging the technology. This video shows how top performers use AI-powered conversation intelligence during live video calls to monitor engagement, detect sentiment shifts, surface relevant battle cards, and receive real-time coaching prompts that dramatically improve meeting outcomes.',
      },
      tags: ['conversation-intel', 'ai-automation'],
      targetRoles: ['account-exec', 'sales-manager'],
    },
    {
      id: 'l8',
      title: 'State of Sales Enablement 2026',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai',
      description: {
        small: 'Industry report on sales enablement trends and ROI.',
        medium: 'Comprehensive industry report on sales enablement technology adoption trends and ROI benchmarks for 2026.',
        large: 'This comprehensive industry report covers the state of sales enablement technology, AI adoption trends, ROI benchmarks, and predictions for how the landscape will evolve through 2026 and beyond.',
        overlay: 'The sales enablement landscape is undergoing rapid transformation driven by AI, conversation intelligence, and predictive analytics. This annual report synthesizes data from 500+ sales organizations to benchmark technology adoption, measure ROI across different tool categories, identify emerging best practices, and forecast the capabilities that will define the next generation of sales enablement platforms.',
      },
      tags: ['coaching', 'analytics', 'ai-automation'],
      targetRoles: ['enablement', 'vp-sales', 'rev-ops'],
    },

    // ── Solutions (7) ─────────────────────────────────
    {
      id: 's1',
      title: 'ConversationIQ',
      cardType: 'solution',
      icon: 'mic',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai/products',
      description: {
        small: 'AI-powered conversation recording and analysis.',
        medium: 'Record, transcribe, and analyze every sales conversation to surface key moments and winning patterns.',
        large: 'ConversationIQ records, transcribes, and analyzes every sales conversation across phone, video, and in-person meetings. AI surfaces key moments, competitor mentions, pricing discussions, and buying signals.',
        overlay: 'ConversationIQ is the foundation of the SalesFlowIQ platform. It automatically records and transcribes every sales conversation across phone calls, video meetings, and in-person interactions. Advanced AI analyzes each conversation to identify key moments, competitor mentions, pricing discussions, objection patterns, and buying signals, giving managers complete visibility into team performance and deal health.',
      },
      tags: ['conversation-intel', 'coaching'],
      targetRoles: ['vp-sales', 'sales-manager', 'enablement', 'account-exec'],
    },
    {
      id: 's2',
      title: 'HireIQ',
      cardType: 'solution',
      icon: 'user-plus',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai/products',
      description: {
        small: 'AI-driven sales recruitment and assessment.',
        medium: 'AI-driven recruitment platform that assesses candidates with simulated sales scenarios to predict success.',
        large: 'HireIQ is an AI-driven recruitment platform that assesses candidates with simulated sales scenarios, predicts on-the-job performance, and reduces mis-hires across your sales organization.',
        overlay: 'Hiring the wrong salesperson is one of the most expensive mistakes an organization can make. HireIQ uses AI to simulate realistic sales scenarios that evaluate candidates on the skills and behaviors that actually predict success. The platform automates candidate screening, provides objective performance predictions, and dramatically reduces the time and cost of building a high-performing sales team.',
      },
      tags: ['hiring', 'onboarding'],
      targetRoles: ['hr-talent', 'vp-sales', 'sdr-leader'],
    },
    {
      id: 's3',
      title: 'TrainerIQ',
      cardType: 'solution',
      icon: 'graduation-cap',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai/products',
      description: {
        small: 'Adaptive AI practice and skill development platform.',
        medium: 'Practice platform where reps rehearse pitches, handle objections, and receive real-time AI feedback.',
        large: 'TrainerIQ is an adaptive practice platform where reps rehearse pitches, handle objections, and receive real-time AI feedback tuned to their skill level and deal context for continuous improvement.',
        overlay: 'Sales skills atrophy without practice, but traditional role-playing is inconsistent and hard to scale. TrainerIQ provides an AI-powered practice environment where reps can rehearse pitches, practice objection handling, and refine their messaging with instant, adaptive feedback. The platform adjusts difficulty based on skill level and provides personalized development plans that accelerate growth.',
      },
      tags: ['coaching', 'onboarding'],
      targetRoles: ['enablement', 'sales-manager', 'account-exec', 'sdr-leader'],
    },
    {
      id: 's4',
      title: 'AnalyticsIQ',
      cardType: 'solution',
      icon: 'bar-chart-2',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai/products',
      description: {
        small: 'Unified performance dashboards with AI insights.',
        medium: 'Unified performance dashboard covering pipeline health, rep activity, and coaching effectiveness with AI.',
        large: 'AnalyticsIQ is a unified performance dashboard covering pipeline health, rep activity, coaching effectiveness, and revenue forecasting with AI-powered anomaly detection and trend analysis.',
        overlay: 'Making data-driven decisions requires having the right data in the right format at the right time. AnalyticsIQ unifies conversation analytics, pipeline metrics, individual performance tracking, and coaching effectiveness into a single dashboard. AI-powered anomaly detection surfaces emerging trends, at-risk deals, and coaching opportunities before they become problems, giving leaders the insights they need to act proactively.',
      },
      tags: ['analytics', 'ai-automation'],
      targetRoles: ['vp-sales', 'rev-ops', 'sales-manager'],
    },
    {
      id: 's5',
      title: 'Teams, Zoom & Meet Integration',
      cardType: 'solution',
      icon: 'plug',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai/products',
      description: {
        small: 'Native integration with major meeting platforms.',
        medium: 'Native integration with Microsoft Teams, Zoom, Google Meet, and phone systems for automatic analysis.',
        large: 'Native integration with Microsoft Teams, Zoom, Google Meet, and phone systems provides automatic recording, transcription, and analysis with zero workflow change for your sales team.',
        overlay: 'SalesFlowIQ integrates natively with the tools your team already uses. Whether your reps are on Microsoft Teams, Zoom, Google Meet, or phone, every conversation is automatically captured, transcribed, and analyzed without any workflow changes. The integration is seamless and invisible to reps, ensuring 100% conversation capture without adoption friction.',
      },
      tags: ['conversation-intel', 'ai-automation'],
      targetRoles: ['rev-ops', 'sales-manager', 'account-exec'],
    },
    {
      id: 's6',
      title: 'Deal Intelligence Engine',
      cardType: 'solution',
      icon: 'search',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai/products',
      description: {
        small: 'AI-powered deal health scoring and predictions.',
        medium: 'AI analyzes conversation patterns across the deal cycle to score health and predict outcomes.',
        large: 'The Deal Intelligence Engine uses AI to analyze conversation patterns across the deal cycle, scoring deal health, predicting outcomes, and recommending next-best actions for reps and managers.',
        overlay: 'Every deal tells a story through the conversations that surround it. The Deal Intelligence Engine analyzes conversation patterns, engagement frequency, stakeholder sentiment, and competitive dynamics across the entire deal cycle. It generates real-time health scores, predicts close probability, identifies stalled deals, and recommends specific next-best actions that reps and managers can take to move deals forward.',
      },
      tags: ['deal-accel', 'analytics'],
      targetRoles: ['account-exec', 'sales-manager', 'vp-sales', 'rev-ops'],
    },
    {
      id: 's7',
      title: 'SalesFlowIQ Platform',
      cardType: 'solution',
      icon: 'layout-dashboard',
      iconType: 'lucide',
      url: 'https://salesflowiq.ai',
      description: {
        small: 'The unified AI sales coaching and intelligence platform.',
        medium: 'The complete AI platform combining conversation intelligence, hiring, training, and analytics in one ecosystem.',
        large: 'SalesFlowIQ is the unified AI sales coaching and intelligence platform that combines ConversationIQ, HireIQ, TrainerIQ, and AnalyticsIQ into a single ecosystem for end-to-end sales optimization.',
        overlay: 'SalesFlowIQ brings together every dimension of sales performance optimization into a single, unified platform. ConversationIQ captures and analyzes every interaction. HireIQ predicts candidate success. TrainerIQ accelerates skill development. AnalyticsIQ provides real-time visibility. Together, they create a closed-loop system where insights from conversations drive coaching, coaching drives performance, and performance data drives continuous improvement.',
      },
      tags: ['conversation-intel', 'analytics', 'coaching', 'ai-automation'],
      targetRoles: ['vp-sales', 'rev-ops', 'enablement'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
