// Explorer Config — Texas Legends (Event Services)
// Fan-facing / concourse kiosk for the Dallas Mavericks' NBA G League
// affiliate (Comerica Center, Frisco TX). Routes fans, businesses,
// group organizers, and families to season memberships, Owners Club,
// premium hospitality, group nights, performance experiences, Jr
// Legends youth programs, and community/business programs.
// Brand: navy #022C5D + royal blue #0254BC + silver (intake). Accent is
// a lifted royal blue for legibility on the navy dark theme.
// Content sourced from texas.gleague.nba.com (season tickets, owners
// club, premium experience, group nights, group experiences, Jr
// Legends, youth camps, Business Launchpad, community).

import type { ExplorerConfig, ThemeColors } from '../types';

const LEGENDS_DARK: ThemeColors = {
  bg: '#04101F',
  bgGradient: 'linear-gradient(135deg, #022C5D 0%, #061B3A 55%, #04101F 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#3D8BFF',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.78)',
  text3: 'rgba(255,255,255,0.52)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(61,139,255,0.25)',
};

const LEGENDS_LIGHT: ThemeColors = {
  bg: '#F4F6FA',
  bgGradient: 'linear-gradient(180deg, #F5F7FB 0%, #EEF2F8 100%)',
  surface: 'rgba(255,255,255,0.90)',
  surfaceHover: 'rgba(255,255,255,1.00)',
  border: 'rgba(2,44,93,0.10)',
  borderFocus: '#0254BC',
  text1: '#04101F',
  text2: 'rgba(4,16,31,0.66)',
  text3: 'rgba(4,16,31,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#04101F',
  inputPlaceholder: 'rgba(4,16,31,0.36)',
  logoText: '#04101F',
  focusRing: 'rgba(2,84,188,0.15)',
};

export const TEXAS_LEGENDS_CONFIG: ExplorerConfig = {
  id: 'texas-legends',
  name: 'Texas Legends Explorer',
  version: 1,
  createdAt: '2026-09-14T00:00:00.000Z',
  updatedAt: '2026-09-14T00:00:00.000Z',

  branding: {
    logo: {
      // Full-color circular badge is self-contained (navy ring, silver
      // keyline, white type) and reads on both dark and light.
      dark: '/brand/assets/texas-legends-dark.webp',
      light: '/brand/assets/texas-legends-light.webp',
    },
    // Square badge; 44px keeps the ring legible in the top bar.
    logoHeight: 44,
    icon: '/brand/assets/texas-legends-icon.webp',
    colors: {
      primary: '#3D8BFF',   // lifted royal blue, legible accent on navy
      secondary: '#0254BC', // brand royal blue
      teal: '#3D8BFF',      // accent doubles as hover/focus tint
      blue: '#0254BC',
      deepBlue: '#022C5D',  // brand navy
      navy: '#061B3A',
      midnight: '#04101F',
      plum: '#A7A9AC',      // brand silver, gradient support
      bgDark: '#04101F',
      dark: LEGENDS_DARK,
      light: LEGENDS_LIGHT,
    },
    // No loadable Google family detected on the site; Inter default.
    font: 'Inter',
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(2,84,188,0.18)',
      orb2: 'rgba(61,139,255,0.12)',
      orb3: 'rgba(167,169,172,0.10)',
    },
    // CTA = royal blue → navy; white text
    ctaGradient: 'linear-gradient(135deg, #0254BC, #022C5D)',
    ctaTextColor: '#FFFFFF',
    // Headline gradient: bright royal → silver highlight
    gradientWord: 'linear-gradient(135deg, #5FA1FF 0%, #3D8BFF 50%, #C9CBCE 100%)',
    roleBackgrounds: {
      'fan': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(2,84,188,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(61,139,255,0.10) 0%, transparent 55%)',
      'business': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(2,44,93,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(167,169,172,0.10) 0%, transparent 55%)',
      'group-organizer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(61,139,255,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(2,84,188,0.10) 0%, transparent 55%)',
      'parent': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(2,84,188,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(61,139,255,0.10) 0%, transparent 55%)',
      'community': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(2,44,93,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(2,84,188,0.10) 0%, transparent 55%)',
      'exploring': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(61,139,255,0.14) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(167,169,172,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Join the Legends Family',
    formSubtitle: 'Share your info and the Legends team will follow up with the tickets, experiences, and programs you pick.',
    scanLabel: 'Scan Your Ticket QR',
    scanHint: 'Hold your QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to the Texas Legends processing your data to fulfill your request and send relevant follow-up communications about tickets, events, and programs.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@example.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company / Organization', type: 'text', placeholder: 'Company, school, or group (optional)', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role (optional)', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Where North Texas',
      gradientWord: 'Becomes Legendary.',
      subtitle: 'The Dallas Mavericks\' G League affiliate, live at Comerica Center in Frisco. Season memberships, courtside hospitality, group nights, youth programs, and a business network that meets year-round. Tap to find your seat.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What brings you to the Legends?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'fan', label: 'Fan / Season Ticket Shopper', icon: 'star', iconType: 'lucide' },
        { value: 'business', label: 'Business Owner / Executive', icon: 'briefcase', iconType: 'lucide' },
        { value: 'group-organizer', label: 'Group / Event Organizer', icon: 'users', iconType: 'lucide' },
        { value: 'parent', label: 'Parent / Youth Coach', icon: 'graduation-cap', iconType: 'lucide' },
        { value: 'community', label: 'Community / Nonprofit Leader', icon: 'heart', iconType: 'lucide' },
        { value: 'exploring', label: 'Just Exploring', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you most interested in?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'season-tickets', label: 'Season Memberships', icon: 'calendar', iconType: 'lucide',
          relevantRoles: ['fan', 'business', 'parent', 'exploring'] },
        { value: 'premium', label: 'Premium & Courtside', icon: 'crown', iconType: 'lucide',
          relevantRoles: ['fan', 'business', 'group-organizer', 'exploring'] },
        { value: 'groups', label: 'Group Nights & Parties', icon: 'users', iconType: 'lucide',
          relevantRoles: ['group-organizer', 'business', 'parent', 'community', 'exploring'] },
        { value: 'performances', label: 'Perform at a Game', icon: 'mic', iconType: 'lucide',
          relevantRoles: ['group-organizer', 'parent', 'community', 'exploring'] },
        { value: 'networking', label: 'Business Networking', icon: 'handshake', iconType: 'lucide',
          relevantRoles: ['business', 'community', 'exploring'] },
        { value: 'partnerships', label: 'Partnerships & Promotion', icon: 'megaphone', iconType: 'lucide',
          relevantRoles: ['business', 'community', 'exploring'] },
        { value: 'youth', label: 'Youth Camps & Jr Legends', icon: 'school', iconType: 'lucide',
          relevantRoles: ['parent', 'community', 'fan', 'exploring'] },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide',
          relevantRoles: ['fan', 'business', 'group-organizer', 'parent', 'community', 'exploring'] },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Legends Lineup',
      subtitle: 'Tickets, experiences, and programs matched to you.',
      tabs: [
        { id: 'outcomes', label: 'Why Legends', icon: 'trending-up' },
        {
          id: 'learn',
          label: 'Discover',
          icon: 'book-open',
          filters: [
            { label: 'All', value: 'all' },
            { label: 'Website', value: 'website' },
            { label: 'Blog', value: 'blog' },
          ],
        },
        { id: 'solutions', label: 'Experiences', icon: 'layers' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Picks',
      subtitle: 'Review your saved items and the Legends team will follow up.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'All Experiences & Programs',
      subtitle: 'Browse everything the Texas Legends have to offer.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'See You at Comerica Center!',
      subtitle: 'We\'ll follow up with the experiences you selected. Check your inbox soon.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ─────────────────────────────────────────────────────────────────
    // Trait-mapping graph (mirrored on each interest's relevantRoles)
    //   fan             : season-tickets, premium, youth, browsing
    //   business        : season-tickets, premium, groups, networking,
    //                     partnerships, browsing
    //   group-organizer : premium, groups, performances, browsing
    //   parent          : season-tickets, groups, performances, youth,
    //                     browsing
    //   community       : groups, performances, networking,
    //                     partnerships, youth, browsing
    //   exploring       : all
    // ─────────────────────────────────────────────────────────────────

    // ── Outcomes / Why Legends (7) ───────────────────────────────────
    {
      id: 'o1',
      title: '24 Home Games in Frisco',
      cardType: 'outcome',
      icon: 'calendar',
      iconType: 'lucide',
      stat: '24',
      url: 'https://texas.gleague.nba.com/season-tickets',
      description: {
        small: 'A full season of pro basketball at Comerica Center.',
        medium: 'Two dozen home games a season at Comerica Center in Frisco, all covered by one season membership.',
        large: 'Season members get every one of the 24 home games at Comerica Center, plus priority seating, player meet and greets, and a no ticket left behind policy for the nights you can\'t make.',
        overlay: 'A Texas Legends season membership covers all 24 home games at Comerica Center in Frisco, the closest thing to NBA basketball in the north Dallas suburbs. Members get priority seating, exclusive meet and greets with Legends players, special offers, season ticket holder events, and a no ticket left behind policy so unused games don\'t go to waste. Reserve and Reserve Prime members are also backed by a guaranteed refund policy on remaining games if the experience doesn\'t deliver.',
      },
      tags: ['season-tickets'],
      targetRoles: ['fan', 'business', 'parent', 'exploring'],
      targetInterests: ['season-tickets', 'browsing'],
    },
    {
      id: 'o2',
      title: 'Season Seats From $22 a Game',
      cardType: 'outcome',
      icon: 'dollar-sign',
      iconType: 'lucide',
      stat: '$22',
      url: 'https://texas.gleague.nba.com/season-tickets',
      description: {
        small: 'Reserve season memberships start at $384 for the full season.',
        medium: 'Reserve seats run $384 for the full season, or $232 for a half season, about $22 a game.',
        large: 'Pro basketball for less than a movie night: Reserve memberships are $384 full season or $232 half season, and Reserve Prime is $648 full or $390 half. Both come with the guaranteed refund policy.',
        overlay: 'Legends season memberships are priced for families and regulars. Reserve seats are $384 for the full season ($232 half season, about $22 per game) and Reserve Prime seats are $648 full ($390 half, about $35 per game). Both tiers include the full member benefit package and a guaranteed refund policy: if you\'re not satisfied during the season, remaining games are refunded. Owners Club, Courtside, Courtside Suites, and Suites are custom-priced through the ticket office at 214-469-0822.',
      },
      tags: ['season-tickets'],
      targetRoles: ['fan', 'parent', 'exploring'],
      targetInterests: ['season-tickets', 'browsing'],
    },
    {
      id: 'o3',
      title: '3+ Networking Events Every Month',
      cardType: 'outcome',
      icon: 'handshake',
      iconType: 'lucide',
      stat: '3+',
      url: 'https://texas.gleague.nba.com/owners-club',
      description: {
        small: 'Owners Club members network year-round, not just on game nights.',
        medium: 'A monthly executive breakfast, a professional development luncheon, and a happy hour, every month, all season long.',
        large: 'The Owners Club is a business network with a basketball team attached: the Legends Pursuing Excellence Breakfast, the Legendary Luncheon, and a rotating-venue Happy Hour, three or more events every month.',
        overlay: 'Owners Club membership runs well beyond the 24 home games. Every month members gather for the Legends Pursuing Excellence Breakfast (3rd Tuesday, Rudy\'s BBQ and coffee, C-level speakers from sports and business, under 90 minutes with Q&A), the Legendary Luncheon (2nd Wednesday, professional development and open networking), and a Monthly Happy Hour (1st Thursday, rotating venues). It\'s the most consistent executive networking calendar in North Texas, built around the team.',
      },
      tags: ['networking', 'premium'],
      targetRoles: ['business', 'community', 'exploring'],
      targetInterests: ['networking', 'premium'],
    },
    {
      id: 'o4',
      title: 'Reach 155,000 Legends Fans',
      cardType: 'outcome',
      icon: 'megaphone',
      iconType: 'lucide',
      stat: '155K',
      url: 'https://texas.gleague.nba.com/legends-business-launchpad',
      description: {
        small: 'The Legends email list reaches roughly 155,000 subscribers.',
        medium: 'Business Launchpad winners get promoted to about 155,000 email subscribers plus courtside digital signage.',
        large: 'The Legends audience is a marketing channel: the Business Launchpad puts North Texas small businesses in front of roughly 155,000 email subscribers and on rotating courtside and stanchion signage at select games, free.',
        overlay: 'The Texas Legends reach about 155,000 email subscribers across North Texas, and the Legends Business Launchpad, presented by InTouch Credit Union, opens that audience to local small businesses at no cost. Winners are featured in email outreach to the full subscriber base and on rotating digital signage courtside and at the basket stanchions during designated games. For corporate partners, the same channels scale into full-season sponsorship packages.',
      },
      tags: ['partnerships'],
      targetRoles: ['business', 'community', 'exploring'],
      targetInterests: ['partnerships', 'networking'],
    },
    {
      id: 'o5',
      title: 'Courtside Suites for 6 Guests',
      cardType: 'outcome',
      icon: 'crown',
      iconType: 'lucide',
      stat: '6',
      url: 'https://texas.gleague.nba.com/premium-experience',
      description: {
        small: 'Sit on the hardwood with six guests at a branded tabletop.',
        medium: 'A Courtside Suite seats six at a branded tabletop on the floor, with Owners Club dining and private bar included.',
        large: 'Client entertainment at floor level: Courtside Suites put you and six guests at a branded tabletop on the hardwood, with Owners Club access, dinner buffet, and private bar from doors open to halftime.',
        overlay: 'Courtside Suites are the Legends\' signature hospitality product: a branded tabletop on the hardwood seating up to six guests, close enough to hear the coaches. Every premium package includes Owners Club access on the concourse behind section 121, with an inclusive dinner buffet and non-alcoholic beverages from doors open through halftime and a private bar. Individual Courtside seats with personalized chair backs, the Platinum Lounge, and Premium Suites round out the tiers. Contact sales@texlegends.com or 214-469-0822.',
      },
      tags: ['premium'],
      targetRoles: ['business', 'fan', 'group-organizer', 'exploring'],
      targetInterests: ['premium', 'season-tickets'],
    },
    {
      id: 'o6',
      title: 'Ages 6 to 14, Coached by the Pros',
      cardType: 'outcome',
      icon: 'school',
      iconType: 'lucide',
      stat: '6-14',
      url: 'https://texas.gleague.nba.com/jr-legends',
      description: {
        small: 'Jr Legends programs serve boys and girls ages 6 to 14.',
        medium: 'Jr Legends camps and free community clinics put kids ages 6 to 14 on the court with Legends coaching staff.',
        large: 'The official youth program of the Texas Legends: camps at every school break, free year-round community clinics, and Jr. NBA membership, all for boys and girls ages 6 to 14, taught by the Legends coaching staff.',
        overlay: 'Jr Legends is the official youth basketball participation program of the Texas Legends, built for boys and girls ages 6 to 14 and centered on education, sportsmanship, and hard work. Camps run at every school break at the Frisco Athletic Center with instruction from the Legends coaching staff, celebrity guest appearances, and camp gifts. Free community clinics run year-round, and the Science of Basketball and Tech Sideline displays at home games turn game night into a math and science lesson.',
      },
      tags: ['youth'],
      targetRoles: ['parent', 'community', 'fan', 'exploring'],
      targetInterests: ['youth', 'browsing'],
    },
    {
      id: 'o7',
      title: 'Mavericks-Owned Since 2010',
      cardType: 'outcome',
      icon: 'trophy',
      iconType: 'lucide',
      stat: '2010',
      url: 'https://texas.gleague.nba.com/roster',
      description: {
        small: 'The Dallas Mavericks\' own G League affiliate, in Frisco since 2010.',
        medium: 'Owned and operated by the Dallas Mavericks, the Legends have developed NBA talent in Frisco since 2010.',
        large: 'The Legends are the Mavericks\' pipeline: owned and operated by Dallas, playing in Frisco since 2010, and home to the first woman to coach a men\'s pro basketball team, Nancy Lieberman.',
        overlay: 'The Texas Legends have been the Dallas Mavericks\' NBA G League affiliate since moving to Frisco in 2010, and today the team is owned and operated by the Mavericks themselves. That means tomorrow\'s NBA call-ups are on the floor at Comerica Center tonight. The franchise also carries a piece of basketball history: in 2009 Hall of Famer Nancy Lieberman became the first woman to serve as head coach of a men\'s professional basketball team when she took over the Legends.',
      },
      tags: ['browsing'],
      targetRoles: ['fan', 'business', 'group-organizer', 'parent', 'community', 'exploring'],
      targetInterests: ['browsing', 'season-tickets'],
    },

    // ── Learn / Discover (7) ─────────────────────────────────────────
    {
      id: 'l1',
      title: 'Season Membership Guide',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/season-tickets',
      description: {
        small: 'Every membership tier, price, and benefit in one place.',
        medium: 'Compare Reserve, Reserve Prime, Owners Club, Courtside, Courtside Suites, and Suites side by side.',
        large: 'The full season membership guide: Reserve and Reserve Prime pricing, the custom-priced Owners Club, Courtside, Courtside Suite, and Suite tiers, member benefits, and the guaranteed refund policy.',
        overlay: 'The season membership guide lays out all six tiers: Reserve ($384 full, $232 half), Reserve Prime ($648 full, $390 half), and the custom-priced Owners Club, Courtside, Courtside Suites, and Suites ($1,500 single game). It covers member benefits (priority seating, player meet and greets, member events, no ticket left behind) and the guaranteed refund policy. Request info through the ticket form or call 214-469-0822. Save this card and the link lands in your follow-up email.',
      },
      tags: ['season-tickets'],
      targetRoles: ['fan', 'business', 'parent', 'exploring'],
      targetInterests: ['season-tickets', 'premium'],
    },
    {
      id: 'l2',
      title: 'Comerica Center Arena Map',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'map-pin',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/arena-map',
      description: {
        small: 'Find your section, the Owners Club, and the Choctaw Club.',
        medium: 'The Comerica Center seating map, from courtside and suites to the lower bowl and Party Plaza.',
        large: 'Know the building before you buy: the arena map shows courtside, suites, the Platinum Lounge, the Owners Club behind section 121, the Choctaw Club, Party Plaza, and lower bowl group seating.',
        overlay: 'The Comerica Center arena map is the fastest way to picture a Legends game night: courtside seats and Courtside Suites on the floor, Premium Suites and the Platinum Lounge above, the Owners Club on the concourse behind section 121, the Choctaw Club for groups, Party Plaza overlooking the court, and lower bowl reserved sections. Pair it with the parking and directions page for the Frisco commute. Save the card and the map link arrives in your follow-up email.',
      },
      tags: ['season-tickets', 'groups', 'premium'],
      targetRoles: ['fan', 'group-organizer', 'business', 'parent', 'exploring'],
      targetInterests: ['season-tickets', 'groups', 'premium', 'browsing'],
    },
    {
      id: 'l3',
      title: 'Performance Experiences Guide',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'mic',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/group-experiences-2',
      description: {
        small: 'Six ways your group can be part of the show.',
        medium: 'Anthem, Primetime and halftime performances, Kia Anthem Buddies, the High Five Tunnel, and Color Guard.',
        large: 'The performance guide covers every on-court opportunity: singing the anthem, Primetime and halftime performances for dance and entertainment groups, Kia Anthem Buddies for kids, the High Five Tunnel, and Color Guard for ROTC and scouts.',
        overlay: 'Groups don\'t just watch Legends games, they\'re in them. The performance experiences guide explains each opportunity: Anthem Performances (church groups, school choirs, soloists), Primetime Performances at center court moments before tipoff, Halftime Performances for youth dance and entertainment squads, Kia Anthem Buddies (kids stand courtside beside the players during the anthem), the High Five Tunnel, and Color Guard for ROTC and scout programs. Submit a group performance request to get on the calendar.',
      },
      tags: ['performances', 'groups'],
      targetRoles: ['group-organizer', 'parent', 'community', 'exploring'],
      targetInterests: ['performances', 'groups'],
    },
    {
      id: 'l4',
      title: 'Youth Camp Schedule',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'calendar',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/youth-basketball-camps',
      description: {
        small: 'Camp dates for every school break at the Frisco Athletic Center.',
        medium: 'Fall Break, Thanksgiving, Winter Break, MLK Day, Stars and Stripes, and Spring Break camps for ages 6 to 14.',
        large: 'The full youth camp calendar: Fall Break, Thanksgiving Break, Winter Break, a January 4th camp, MLK Day, Stars and Stripes, and Spring Break, all at the Frisco Athletic Center with registration through ActiveKids.',
        overlay: 'Legends youth camps line up with the school calendar so parents can plan: Fall Break (Oct 12-13), Thanksgiving Break (Nov 23-25), Winter Break (Dec 28-30), a January 4th camp, MLK Day (Jan 18), Stars and Stripes (Feb 12), and Spring Break (Mar 15-18). Every session runs at the Frisco Athletic Center (5828 Nancy Jane Ln) with instruction from Legends coaching staff, celebrity guests, and camp gifts. Register at activekids.com/orgs/texas-legends. Save the card and the schedule link arrives in your follow-up email.',
      },
      tags: ['youth'],
      targetRoles: ['parent', 'community', 'exploring'],
      targetInterests: ['youth'],
    },
    {
      id: 'l5',
      title: 'Legends News & Media',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'book-open',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/news',
      description: {
        small: 'Roster moves, call-ups, and game recaps from the Legends.',
        medium: 'The Legends newsroom: signings, Mavericks call-ups, game recaps, and community stories all season long.',
        large: 'Follow the pipeline in real time: the Legends news hub covers roster moves, two-way and call-up announcements to the Mavericks, game recaps, and the community programs happening around North Texas.',
        overlay: 'The Legends news and media hub is where the season unfolds off the court: player signings, two-way contracts and call-ups to the Dallas Mavericks, game recaps and highlights, and stories from the community programs, camps, and Owners Club events. Pair it with the schedule and roster pages to keep up with the team. Save the card and the link comes to your inbox with the rest of your picks.',
      },
      tags: ['browsing'],
      targetRoles: ['fan', 'business', 'group-organizer', 'parent', 'community', 'exploring'],
      targetInterests: ['browsing', 'season-tickets'],
    },
    {
      id: 'l6',
      title: 'Legends Mission of the Month',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'heart',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/legends-mission-of-the-month-presented-by-coserv',
      description: {
        small: 'A featured North Texas nonprofit every month, presented by Coserv.',
        medium: 'Each month the Legends and Coserv spotlight a local nonprofit with in-arena and digital promotion.',
        large: 'Mission of the Month, presented by Coserv, turns the Legends platform over to a different North Texas nonprofit each month, with promotion across game nights, email, and social to drive awareness and support.',
        overlay: 'The Legends Mission of the Month, presented by Coserv, gives one North Texas nonprofit the team\'s full platform for a month: in-arena recognition on game nights, digital and email promotion to the Legends fan base, and social amplification. It\'s the front door for community organizations that want to partner with the team, alongside the community appearance and donation request programs. Contact info@texlegends.com to nominate an organization.',
      },
      tags: ['partnerships'],
      targetRoles: ['community', 'business', 'exploring'],
      targetInterests: ['partnerships', 'networking', 'browsing'],
    },
    {
      id: 'l7',
      title: 'Legends Team Shop',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'shopping-cart',
      iconType: 'lucide',
      url: 'https://texlegendsshop.com',
      description: {
        small: 'Official Legends gear, including game-worn jerseys.',
        medium: 'The official team shop: jerseys, hats, and apparel, plus authenticated game-worn jerseys.',
        large: 'Rep the Legends year-round: the official team shop carries jerseys, hats, and apparel in navy, royal, and silver, plus authenticated game-worn jerseys from Legends players headed to the NBA.',
        overlay: 'The official Texas Legends team shop at texlegendsshop.com carries the full line of jerseys, hats, and apparel in the team\'s navy, royal blue, and silver, along with authenticated game-worn jerseys, a chance to own gear from a player before the Mavericks call them up. Group and corporate orders make easy giveaways for suite nights and employee events. Save the card and the shop link arrives in your follow-up email.',
      },
      tags: ['browsing'],
      targetRoles: ['fan', 'parent', 'group-organizer', 'exploring'],
      targetInterests: ['browsing', 'season-tickets', 'groups'],
    },

    // ── Solutions / Experiences (9) ──────────────────────────────────
    {
      id: 's1',
      title: 'Season Memberships',
      cardType: 'solution',
      icon: 'calendar',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/season-tickets',
      description: {
        small: 'All 24 home games, from Reserve to Suites.',
        medium: 'Six membership tiers covering all 24 home games, with priority seating, member events, and player meet and greets.',
        large: 'Season memberships cover every home game at Comerica Center across six tiers: Reserve, Reserve Prime, Owners Club, Courtside, Courtside Suites, and Suites, with full and half-season options and a guaranteed refund policy.',
        overlay: 'A Legends season membership is the best value in North Texas pro sports: all 24 home games at Comerica Center, priority seating, exclusive player meet and greets, member-only events, special offers, and a no ticket left behind policy. Choose from Reserve ($384 full / $232 half), Reserve Prime ($648 / $390), or the custom-priced Owners Club, Courtside, Courtside Suite, and Suite tiers. Reserve and Reserve Prime carry a guaranteed refund on remaining games. Request info at 214-469-0822 or info@texlegends.com.',
      },
      tags: ['season-tickets'],
      targetRoles: ['fan', 'business', 'parent', 'exploring'],
      targetInterests: ['season-tickets', 'browsing'],
    },
    {
      id: 's2',
      title: 'Owners Club Membership',
      cardType: 'solution',
      icon: 'crown',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/owners-club',
      description: {
        small: 'The best seats plus a private lounge and monthly networking.',
        medium: 'Premium seats, the private Owners Club Lounge at all 24 games, and a monthly calendar of executive networking events.',
        large: 'The Owners Club pairs the best seats in Comerica Center with the private Owners Club Lounge (complimentary buffet, private bar) and three or more networking events every month: breakfast, luncheon, and happy hour.',
        overlay: 'Owners Club membership is where the Legends stop being a ticket and become a network. Members get the best seats in Comerica Center and the private Owners Club Lounge at all 24 home games, with a complimentary all-you-can-eat buffet, non-alcoholic beverages, and private bar. Off the court, members meet at the Legends Pursuing Excellence Breakfast, the Legendary Luncheon, and a Monthly Happy Hour, three or more events every month with C-level speakers and open networking. Contact info@texlegends.com or 214-469-0822.',
      },
      tags: ['premium', 'networking'],
      targetRoles: ['business', 'community', 'fan', 'exploring'],
      targetInterests: ['premium', 'networking', 'season-tickets'],
    },
    {
      id: 's3',
      title: 'Courtside & Premium Suites',
      cardType: 'solution',
      icon: 'sparkles',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/premium-experience',
      description: {
        small: 'Courtside seats, Courtside Suites, Platinum Lounge, and Premium Suites.',
        medium: 'Four premium tiers, from personalized courtside chair backs to private suites, all with Owners Club dining and bar.',
        large: 'The premium lineup: individual Courtside seats with branded chair backs, six-guest Courtside Suites on the hardwood, the Platinum Lounge with high-tops and leather sofas, and Premium Suites for intimate entertaining.',
        overlay: 'Legends premium experiences are built for client entertainment and big nights out. Courtside seats put your name on a chair back on the hardwood. Courtside Suites seat up to six guests at a branded tabletop on the floor. The Platinum Lounge on the concourse offers high-top tables and leather sofas, and Premium Suites deliver first-class amenities and personal service in a private setting. Every option includes Owners Club access with an inclusive dinner buffet and non-alcoholic beverages from doors open to halftime, plus a private bar. Contact sales@texlegends.com or 214-469-0822.',
      },
      tags: ['premium'],
      targetRoles: ['business', 'fan', 'group-organizer', 'exploring'],
      targetInterests: ['premium', 'groups'],
    },
    {
      id: 's4',
      title: 'Group Night Out',
      cardType: 'solution',
      icon: 'users',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/group-nights',
      description: {
        small: 'Discounted group tickets, Skybox Suites, and Party Plaza.',
        medium: 'Bring the team, the office, or the whole league: discounted group seats, 14 to 16 person Skybox Suites, and Party Plaza for big groups.',
        large: 'Group Night Out packages fit any size: reserved lower bowl seating with a discount for every member, private Skybox Suites for 14 to 16 guests, and Party Plaza, a semi-secluded space overlooking the court for large groups, all with Choctaw Club access.',
        overlay: 'Group Night Out is the Legends\' answer to company outings, youth team celebrations, church groups, and client appreciation nights. Every member of your party gets an exclusive discounted ticket and reserved seating together. Choose lower bowl group seating, a private Skybox Suite for 14 to 16 guests with dedicated seating and court views, or Party Plaza, a semi-secluded area overlooking the court for large groups. Groups get access to the Choctaw Club for food and beverage, professional staff handle the logistics, and extra perks are reserved just for groups. Submit a request through the group night, suite night, or Party Plaza forms.',
      },
      tags: ['groups'],
      targetRoles: ['group-organizer', 'business', 'parent', 'community', 'exploring'],
      targetInterests: ['groups', 'premium'],
    },
    {
      id: 's5',
      title: 'Legendary Birthdays & Team Parties',
      cardType: 'solution',
      icon: 'gift',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/legendary-birthdays',
      description: {
        small: 'Game tickets, food, cupcakes, and a dedicated party zone.',
        medium: 'Birthday and youth team party packages with tickets, catering, cupcakes, and a private party zone at the game.',
        large: 'Legendary Birthdays and Legendary Team Parties bundle game tickets, food, cupcakes, and a dedicated party zone with staff handling the details, so parents and coaches get to enjoy the game too.',
        overlay: 'Hand the party planning to the Legends. Legendary Birthday packages include game tickets, food, cupcakes, and a dedicated party zone inside Comerica Center, with professional staff running the logistics. Legendary Team Party packages do the same for youth sports teams celebrating a season, with the option to add a High Five Tunnel or Anthem Buddies experience so the kids get on the court. Submit a birthday or team party request form to check dates and pricing.',
      },
      tags: ['groups', 'youth'],
      targetRoles: ['parent', 'group-organizer', 'exploring'],
      targetInterests: ['groups', 'youth', 'performances'],
    },
    {
      id: 's6',
      title: 'Perform at a Legends Game',
      cardType: 'solution',
      icon: 'mic',
      iconType: 'lucide',
      url: 'https://texlegends.formstack.com/forms/group_performance_information_request',
      description: {
        small: 'Anthem, halftime, Primetime, Anthem Buddies, High Five Tunnel, Color Guard.',
        medium: 'Put your choir, dance team, scouts, or ROTC on the court in front of thousands at Comerica Center.',
        large: 'Performance experiences give groups a moment on the floor: sing the anthem, perform at center court before tipoff or at halftime, stand courtside as Kia Anthem Buddies, line the High Five Tunnel, or present colors with your ROTC or scout program.',
        overlay: 'The Legends build group performances into every home game. Choirs, church groups, and soloists sing the National Anthem or God Bless America. Youth dance squads and entertainment groups take center court for Primetime Performances just before tipoff or at halftime. Kids stand courtside beside the players as Kia Anthem Buddies, groups line the tunnel to high-five the team as it takes the floor, and ROTC and scout programs present the colors. Submit a group performance information request to reserve a game date.',
      },
      tags: ['performances', 'groups'],
      targetRoles: ['group-organizer', 'parent', 'community', 'exploring'],
      targetInterests: ['performances', 'groups', 'youth'],
    },
    {
      id: 's7',
      title: 'Jr Legends Youth Programs',
      cardType: 'solution',
      icon: 'school',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/jr-legends',
      description: {
        small: 'Camps, free clinics, and Jr. NBA membership for ages 6 to 14.',
        medium: 'The official Legends youth program: school-break camps, free community clinics, Jr. NBA membership, and in-game STEM displays.',
        large: 'Jr Legends serves boys and girls ages 6 to 14 with basketball camps at every school break, free year-round community clinics on wellness and leadership, free Jr. NBA membership for youth leagues, and Science of Basketball displays at home games.',
        overlay: 'Jr Legends is the official youth basketball participation program of the Texas Legends, promoting education, sportsmanship, and hard work through the game. Camps run at every school break at the Frisco Athletic Center with Legends coaching staff, celebrity guests, and camp gifts. Free community clinics run year-round with a focus on wellness, sportsmanship, and leadership. Youth leagues and organizations can join the free Jr. NBA membership program, and the Science of Basketball and Tech Sideline displays at home games connect the sport to math and science. Register for camps at activekids.com/orgs/texas-legends.',
      },
      tags: ['youth'],
      targetRoles: ['parent', 'community', 'fan', 'exploring'],
      targetInterests: ['youth', 'browsing'],
    },
    {
      id: 's8',
      title: 'Legends Business Launchpad',
      cardType: 'solution',
      icon: 'rocket',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/legends-business-launchpad',
      description: {
        small: 'Free promotion for North Texas small businesses, presented by InTouch Credit Union.',
        medium: 'Enter to have your small business promoted to 155,000 subscribers and on courtside signage at select games, free.',
        large: 'The Business Launchpad, presented by InTouch Credit Union, spotlights North Texas small businesses at no cost: email exposure to roughly 155,000 subscribers plus rotating courtside and basket stanchion signage during designated games.',
        overlay: 'The Legends Business Launchpad, presented by InTouch Credit Union, is a free promotional program for small businesses in the North Texas community. Enter for a chance to be featured, and winners receive inclusion in email outreach to about 155,000 Legends subscribers, rotating digital signage courtside during designated games, and rotating signage at the basket stanchions during select matchups. It\'s a zero-cost way to test the Legends audience before exploring a full corporate partnership. Apply through the entry form on the Legends site.',
      },
      tags: ['partnerships'],
      targetRoles: ['business', 'community', 'exploring'],
      targetInterests: ['partnerships', 'networking'],
    },
    {
      id: 's9',
      title: 'Corporate Partnerships',
      cardType: 'solution',
      icon: 'briefcase',
      iconType: 'lucide',
      url: 'https://texas.gleague.nba.com/community',
      description: {
        small: 'Presenting sponsorships, in-arena signage, and activations.',
        medium: 'Join Kia, Coserv, InTouch Credit Union, and Choctaw as a Legends partner with presenting programs, signage, and activations.',
        large: 'Legends corporate partnerships range from presenting sponsorships (Mission of the Month, Business Launchpad, Together We Are More Networking, Kia Anthem Buddies) to in-arena signage, hospitality, digital reach, and custom activations like the Legends Kia Test Drive.',
        overlay: 'The Legends partner roster shows what a sponsorship can look like: Coserv presents Mission of the Month, InTouch Credit Union presents the Business Launchpad, Choctaw presents Together We Are More Networking and the Choctaw Club, and Kia presents Anthem Buddies and the Legends Kia Test Drive. Packages combine in-arena signage and courtside branding, hospitality in suites and the Owners Club, email and social reach to a 155,000-subscriber base, and custom activations tied to the Mavericks pipeline. Contact sales@texlegends.com or 214-469-0822 to build a package.',
      },
      tags: ['partnerships', 'networking'],
      targetRoles: ['business', 'community', 'exploring'],
      targetInterests: ['partnerships', 'networking', 'premium'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
