// Explorer Config — The Expo Group
// Premium trade show management, custom exhibit design, and community intelligence
// "Architects Connecting Communities™" — Founded 1991

import type { ExplorerConfig, ThemeColors } from '../types';

const EXPO_DARK: ThemeColors = {
  bg: '#0C0B0A',
  bgGradient: 'linear-gradient(135deg, #1A0A04 0%, #0C0B0A 55%, #160A06 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#E86028',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.75)',
  text3: 'rgba(255,255,255,0.50)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(232,96,40,0.20)',
};

const EXPO_LIGHT: ThemeColors = {
  bg: '#F5F4F2',
  bgGradient: 'linear-gradient(180deg, #F5F4F2 0%, #F0EEE9 100%)',
  surface: 'rgba(255,255,255,0.85)',
  surfaceHover: 'rgba(255,255,255,0.95)',
  border: 'rgba(15,23,42,0.10)',
  borderFocus: '#C4501E',
  text1: '#0F172A',
  text2: 'rgba(15,23,42,0.65)',
  text3: 'rgba(15,23,42,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#0F172A',
  inputPlaceholder: 'rgba(15,23,42,0.35)',
  logoText: '#0F172A',
  focusRing: 'rgba(196,80,30,0.12)',
};

export const THE_EXPO_GROUP_CONFIG: ExplorerConfig = {
  id: 'the-expo-group',
  name: 'The Expo Group Explorer',
  version: 1,
  createdAt: '2026-06-25T00:00:00.000Z',
  updatedAt: '2026-06-25T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/the-expo-group-logo-light.png',
      light: '/brand/assets/the-expo-group-logo-dark.png',
    },
    icon: '/brand/assets/the-expo-group-icon.png',
    colors: {
      primary: '#E86028',
      secondary: '#C4501E',
      teal: '#E86028',
      blue: '#B04018',
      deepBlue: '#8A3010',
      navy: '#1A0A04',
      midnight: '#120804',
      plum: '#C05020',
      bgDark: '#0C0B0A',
      dark: EXPO_DARK,
      light: EXPO_LIGHT,
    },
    font: 'Inter, -apple-system, sans-serif',
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(232,96,40,0.15)',
      orb2: 'rgba(180,60,20,0.12)',
      orb3: 'rgba(255,120,60,0.08)',
    },
    ctaGradient: 'linear-gradient(135deg, #E86028, #FF8040)',
    ctaTextColor: '#FFFFFF',
    gradientWord: 'linear-gradient(135deg, #E86028, #FF8040)',
    roleBackgrounds: {
      'show-organizer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(232,96,40,0.18) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(180,60,20,0.10) 0%, transparent 55%)',
      'association-exec': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(180,60,20,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(232,96,40,0.10) 0%, transparent 55%)',
      'exhibitor': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(232,96,40,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(196,80,30,0.12) 0%, transparent 55%)',
      'corporate-events': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(180,60,20,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(232,96,40,0.08) 0%, transparent 55%)',
      'executive': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(232,96,40,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(180,60,20,0.12) 0%, transparent 55%)',
      'event-designer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(255,120,60,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(232,96,40,0.12) 0%, transparent 55%)',
      'marketing-director': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(232,96,40,0.15) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(138,48,16,0.10) 0%, transparent 55%)',
      'newcomer': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(180,60,20,0.14) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(232,96,40,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Tell us about yourself',
    formSubtitle: 'Share your contact info so we can follow up with personalized resources.',
    scanLabel: 'Please Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to The Expo Group processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Email', type: 'email', placeholder: 'name@company.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Company', type: 'text', placeholder: 'Company name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role or title', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Architects Connecting',
      gradientWord: 'Communities.',
      subtitle: "Discover how The Expo Group's 35 years of expertise, CROWDPulse intelligence, and Single Source Solution® transform trade shows into community-defining moments.",
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What best describes your role?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'show-organizer', label: 'Show Organizer', icon: 'layout-dashboard', iconType: 'lucide' },
        { value: 'association-exec', label: 'Association Executive', icon: 'building-2', iconType: 'lucide' },
        { value: 'exhibitor', label: 'Exhibitor / Brand Team', icon: 'megaphone', iconType: 'lucide' },
        { value: 'corporate-events', label: 'Corporate Events Director', icon: 'briefcase', iconType: 'lucide' },
        { value: 'executive', label: 'Executive / Decision Maker', icon: 'crown', iconType: 'lucide' },
        { value: 'event-designer', label: 'Event Designer / Creative', icon: 'palette', iconType: 'lucide' },
        { value: 'marketing-director', label: 'Marketing Director', icon: 'target', iconType: 'lucide' },
        { value: 'newcomer', label: 'Exploring Trade Shows', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you most focused on?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      options: [
        { value: 'attendee-growth', label: 'Growing Attendance', icon: 'trending-up', iconType: 'lucide' },
        { value: 'exhibitor-roi', label: 'Exhibitor ROI & Value', icon: 'bar-chart-2', iconType: 'lucide' },
        { value: 'show-design', label: 'Show Design & Production', icon: 'sparkles', iconType: 'lucide' },
        { value: 'community-intel', label: 'Community Intelligence', icon: 'activity', iconType: 'lucide' },
        { value: 'sponsor-engagement', label: 'Sponsor Engagement', icon: 'handshake', iconType: 'lucide' },
        { value: 'logistics', label: 'Logistics & Operations', icon: 'layers', iconType: 'lucide' },
        { value: 'brand-experience', label: 'Brand & Immersive Experience', icon: 'zap', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Results',
      subtitle: 'Curated outcomes, content, and solutions based on your profile.',
      tabs: [
        { id: 'outcomes', label: 'Outcomes', icon: 'target' },
        {
          id: 'learn',
          label: 'Learn',
          icon: 'book-open',
          filters: [
            { label: 'All', value: 'all' },
            { label: 'Video', value: 'video' },
            { label: 'PDF', value: 'pdf' },
            { label: 'Blog', value: 'blog' },
            { label: 'Webinar', value: 'webinar' },
          ],
        },
        { id: 'solutions', label: 'Solutions', icon: 'puzzle' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review and share your curated content.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Content Library',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'We appreciate your time. The Expo Group team will be in touch with personalized resources and next steps.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ── Outcomes (7) ──────────────────────────────────
    {
      id: 'o1',
      title: '35 Years of Trade Show Excellence',
      cardType: 'outcome',
      icon: 'award',
      iconType: 'lucide',
      stat: '35 Yrs',
      description: {
        small: '35 years of expertise designing communities through events.',
        medium: 'Founded in 1991, The Expo Group brings 35 years of trade show management, design-build, and community intelligence expertise.',
        large: 'Since 1991, The Expo Group has been architecting communities through trade shows and events. Three and a half decades of experience means deep industry knowledge, long-standing client relationships, and tested processes that deliver results at every scale.',
        overlay: "Founded in 1991, The Expo Group has spent 35 years doing one thing: helping organizations connect with their communities through extraordinary trade show and event experiences. From small association conferences to industry flagship events like PRINTING United Expo, the team brings battle-tested processes, deep industry relationships, and a genuine commitment to helping clients grow. That longevity isn't just tenure — it's a compounding advantage built event by event.",
      },
      tags: ['show-design', 'logistics'],
      targetRoles: ['show-organizer', 'association-exec', 'executive', 'newcomer'],
    },
    {
      id: 'o2',
      title: 'Single Source Solution® (Patented)',
      cardType: 'outcome',
      icon: 'shield-check',
      iconType: 'lucide',
      stat: '1 Partner',
      description: {
        small: 'One partner for every aspect of your show.',
        medium: "The Expo Group's patented Single Source Solution® unifies every vendor, workflow, and deliverable under one accountable partner.",
        large: 'The patented Single Source Solution® means one point of contact, one contract, and one team accountable for every aspect of your event — from design and construction to show management, logistics, and on-site execution.',
        overlay: "Managing a trade show means coordinating dozens of vendors, each with their own contract, timeline, and point of contact. The Expo Group's patented Single Source Solution®, powered by the Automated Convention Processing System (ACPS), eliminates that complexity. One partner owns the entire process — design-build, logistics, show services, on-site management — so your team focuses on your event, not vendor coordination. When something needs to be solved, there is one call to make.",
      },
      tags: ['logistics', 'attendee-growth'],
      targetRoles: ['show-organizer', 'association-exec', 'corporate-events', 'executive'],
    },
    {
      id: 'o3',
      title: '20+ Year Average Team Experience',
      cardType: 'outcome',
      icon: 'users',
      iconType: 'lucide',
      stat: '20+ Yrs',
      description: {
        small: 'A team that averages 20+ years of industry expertise.',
        medium: "The Expo Group's leadership team averages 20+ years of trade show, events, and corporate sector experience.",
        large: "Experience matters in event production. The Expo Group's leadership team averages more than 20 years of deep trade show, event management, and corporate sector expertise — knowledge that pays off in faster problem-solving and better client outcomes.",
        overlay: "When you work with The Expo Group, you're not working with someone figuring it out. The leadership team averages 20+ years of hands-on experience across trade shows, events, and corporate sectors — experience that enables faster problem-solving, better vendor relationships, and anticipation of challenges before they become issues. This depth of expertise is built into every level of the team, not just the top. The result is an organization that handles complexity with confidence.",
      },
      tags: ['attendee-growth', 'logistics', 'show-design'],
      targetRoles: ['show-organizer', 'association-exec', 'executive', 'corporate-events'],
    },
    {
      id: 'o4',
      title: 'CROWDPulse: Billions of Market Signals',
      cardType: 'outcome',
      icon: 'activity',
      iconType: 'lucide',
      stat: 'Billions',
      description: {
        small: 'AI-powered market intelligence across billions of data points.',
        medium: 'CROWDPulse monitors billions of real-time market signals — search behavior, social conversations, and competitive dynamics — to guide event strategy.',
        large: "CROWDPulse is The Expo Group's AI-powered global intelligence platform that monitors billions of market signals in real time — delivering actionable intelligence on audience trends, exhibitor opportunities, and competitive dynamics before, during, and after your event.",
        overlay: 'Trade show organizers traditionally operate on intuition and lagging data. CROWDPulse changes that. This AI-powered platform monitors billions of real-time signals — search trends, social conversations, competitive dynamics, industry disruption patterns — and translates them into actionable intelligence for your event strategy. Know which topics are gaining momentum, which exhibitor categories are attracting attention, and which audience segments are underserved before you finalize your program.',
      },
      tags: ['community-intel', 'attendee-growth', 'exhibitor-roi'],
      targetRoles: ['show-organizer', 'association-exec', 'marketing-director', 'executive'],
    },
    {
      id: 'o5',
      title: 'Award-Winning Exhibit Design',
      cardType: 'outcome',
      icon: 'trophy',
      iconType: 'lucide',
      stat: 'Award-Winning',
      description: {
        small: 'Design-build solutions that earn Best Booth recognition.',
        medium: "The Expo Group's custom exhibit design and construction has earned Best Booth awards for immersive attendee experiences.",
        large: "The Expo Group's custom design-build approach delivers environments that don't just look good — they perform. Award-winning booth designs translate into more attendee engagement, stronger brand recall, and measurable exhibitor ROI.",
        overlay: "Exhibiting at a trade show is a significant investment. The Expo Group's award-winning design-build approach ensures that investment delivers results. From conceptual strategy through custom construction and on-site execution, each exhibit is designed to attract attendees, facilitate meaningful conversations, and generate measurable business outcomes — not just a good-looking booth. The Best Booth recognition their clients receive is a byproduct of that discipline.",
      },
      tags: ['show-design', 'brand-experience', 'exhibitor-roi'],
      targetRoles: ['exhibitor', 'event-designer', 'marketing-director', 'corporate-events'],
    },
    {
      id: 'o6',
      title: 'Unified Attendee & Exhibitor Intelligence',
      cardType: 'outcome',
      icon: 'bar-chart-2',
      iconType: 'lucide',
      stat: '3 Tiers',
      description: {
        small: 'Unified data intelligence across all your event platforms.',
        medium: "The Expo Group's Micro Lens consolidates AMS, CRM, registration, and lead capture data into a single attendee and exhibitor intelligence view.",
        large: 'The Community Intelligence Micro Lens pulls together all your fragmented event data — AMS, CRM, registration platforms, lead capture tools — into unified attendee and exhibitor intelligence that reveals high-potential segments and validates ROI.',
        overlay: "Fragmented data is the number one obstacle to smart event strategy. The Expo Group's Community Intelligence Micro Lens solves this by consolidating every data source — association management system, CRM, registration platforms, lead retrieval, mobile app — into a single intelligence view. Three engagement tiers (Foundational, Growth, Transformational) let organizations start where they are and scale their data capability as strategy matures.",
      },
      tags: ['community-intel', 'exhibitor-roi', 'attendee-growth'],
      targetRoles: ['show-organizer', 'association-exec', 'marketing-director'],
    },
    {
      id: 'o7',
      title: 'Shared Risk Innovation Model',
      cardType: 'outcome',
      icon: 'handshake',
      iconType: 'lucide',
      stat: 'Shared Risk',
      description: {
        small: 'Innovation with shared risk — aligned incentives from day one.',
        medium: "The Expo Group's shared risk model makes innovation accessible by investing alongside clients in new solutions and approaches.",
        large: "The Expo Group's shared risk innovation model means they invest alongside their clients in new approaches, making cutting-edge event technology and strategy affordable without requiring clients to absorb all the upfront risk.",
        overlay: "Adopting new event technology or strategy can feel risky when the investment is entirely on your side. The Expo Group's shared risk model changes that dynamic — they invest alongside their clients in innovative approaches, aligning incentives and making cutting-edge solutions accessible to organizations that want to evolve without betting the entire event budget on an unproven solution. It's a partner model, not a vendor model.",
      },
      tags: ['attendee-growth', 'community-intel', 'show-design'],
      targetRoles: ['show-organizer', 'association-exec', 'executive'],
    },

    // ── Learn (7) ─────────────────────────────────────
    {
      id: 'l1',
      title: 'Architects Connecting Communities',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://theexpogroup.com',
      description: {
        small: 'The Expo Group brand story and approach.',
        medium: "An overview of The Expo Group's approach to trade show management and what 'Architects Connecting Communities' means in practice.",
        large: "This brand overview explains what sets The Expo Group apart: the Single Source Solution® model, the CROWDPulse intelligence platform, and the 35-year commitment to helping organizations connect with their communities.",
        overlay: "This video walks through The Expo Group's origin story, core philosophy, and what 'Architects Connecting Communities' means in practice. From the founding vision of helping people perform at a higher level, through the development of patented event processing technology, to the launch of CROWDPulse — see how 35 years of focus on community-driven events translates into a fundamentally different partner model.",
      },
      tags: ['show-design', 'attendee-growth'],
      targetRoles: ['show-organizer', 'association-exec', 'executive', 'newcomer'],
    },
    {
      id: 'l2',
      title: 'CROWDPulse Community Intelligence Overview',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://theexpogroup.com/community-intelligence/',
      description: {
        small: 'How CROWDPulse turns market signals into event strategy.',
        medium: 'An overview of the CROWDPulse platform: how it works, what data it monitors, and how it translates signals into event strategy.',
        large: 'This overview covers how CROWDPulse monitors billions of market signals — search, social, competitive — and how the Micro Lens consolidates event data into unified attendee and exhibitor intelligence.',
        overlay: "CROWDPulse isn't just an analytics dashboard — it's a strategic advantage for event organizers. This overview explains how the platform works: macro-level market intelligence from CROWDPulse (global signals, industry trends, competitive dynamics) combined with micro-level event data from the Micro Lens (AMS, CRM, registration, lead capture) to give organizers a complete picture of their market and community.",
      },
      tags: ['community-intel', 'attendee-growth'],
      targetRoles: ['show-organizer', 'association-exec', 'marketing-director'],
    },
    {
      id: 'l3',
      title: 'PRINTING United Expo: Community at Scale',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://theexpogroup.com',
      description: {
        small: "How The Expo Group powers the printing industry's flagship event.",
        medium: "Case study: The Expo Group's role as Official Services Contractor for PRINTING United Expo, the printing industry's largest North American event.",
        large: "The Expo Group's partnership with PRINTING United Expo demonstrates what's possible when premium service and deep industry expertise combine at scale — managing the printing industry's most comprehensive North American event.",
        overlay: "PRINTING United Expo is the printing industry's largest North American event — and The Expo Group is the Official Services Contractor. This case study examines what that partnership looks like in practice: how the Single Source Solution® model applies at large-scale events, how the team manages the complexity of thousands of exhibitors and attendees, and what measurable outcomes are delivered for the show organizer, exhibitors, and attendees.",
      },
      tags: ['logistics', 'show-design', 'attendee-growth'],
      targetRoles: ['show-organizer', 'association-exec', 'corporate-events'],
    },
    {
      id: 'l4',
      title: 'Designing Immersive Trade Show Experiences',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://theexpogroup.com',
      description: {
        small: 'The design principles behind award-winning exhibits.',
        medium: "How The Expo Group approaches trade show design: the principles, process, and elements that create immersive environments attendees remember.",
        large: "This article explores the design philosophy behind The Expo Group's award-winning exhibit builds: how traffic flow, sensory engagement, and storytelling combine to create environments that drive meaningful exhibitor-attendee connections.",
        overlay: "Trade show design is part architecture, part theater, and part business strategy. This article breaks down The Expo Group's approach to creating immersive exhibit environments: starting with the attendee journey, designing for natural traffic flow and curiosity, layering sensory engagement, and engineering spaces where meaningful business conversations happen naturally. Includes examples from recent award-winning installations.",
      },
      tags: ['show-design', 'brand-experience', 'exhibitor-roi'],
      targetRoles: ['event-designer', 'exhibitor', 'marketing-director', 'corporate-events'],
    },
    {
      id: 'l5',
      title: 'Maximizing Exhibitor ROI: A Data-Driven Approach',
      cardType: 'learn',
      mediaType: 'webinar',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://theexpogroup.com',
      description: {
        small: 'Using data intelligence to prove and improve exhibitor value.',
        medium: 'Webinar: how community intelligence and post-show analytics help exhibitors demonstrate and improve their trade show ROI.',
        large: "This webinar covers how event organizers can use CROWDPulse and attendee intelligence data to help exhibitors measure the value of their participation and continuously improve ROI from event to event.",
        overlay: "Exhibitor ROI has always been the hardest question to answer after a trade show. This webinar shows how The Expo Group's Community Intelligence platform changes that — providing exhibitors with lead quality data, attendee engagement analytics, and comparative benchmarks that quantify the value of participation. Learn how to build an exhibitor ROI program that turns data into retention and upsell opportunities.",
      },
      tags: ['exhibitor-roi', 'community-intel', 'sponsor-engagement'],
      targetRoles: ['show-organizer', 'association-exec', 'marketing-director'],
    },
    {
      id: 'l6',
      title: 'The Attendee Intelligence Playbook',
      cardType: 'learn',
      mediaType: 'whitepaper',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://theexpogroup.com',
      description: {
        small: 'Turn attendee data into a growth strategy.',
        medium: 'Whitepaper: how to use unified attendee intelligence to identify high-potential segments, reduce churn, and grow event attendance.',
        large: 'This whitepaper covers how unified attendee intelligence — combining registration data, behavioral signals, and market trends — enables event organizers to identify high-potential audience segments and build targeted growth strategies.',
        overlay: "Most events know who attended last year. Fewer know why they came, what they wanted, and what would bring them back. This whitepaper walks through The Expo Group's attendee intelligence methodology: how to unify data sources, how to identify high-intent segments, how to predict churn before it happens, and how to develop audience growth strategies grounded in actual behavioral data rather than assumptions.",
      },
      tags: ['attendee-growth', 'community-intel'],
      targetRoles: ['show-organizer', 'association-exec', 'marketing-director', 'executive'],
    },
    {
      id: 'l7',
      title: 'Single Source Solution: The Advantage Explained',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://theexpogroup.com',
      description: {
        small: 'Why one partner for everything simplifies event production.',
        medium: "How The Expo Group's Single Source Solution® reduces vendor complexity, shortens timelines, and improves show outcomes.",
        large: "This article breaks down the real-world advantages of The Expo Group's patented Single Source Solution®: fewer handoffs, clearer accountability, faster problem resolution, and better alignment between design intent and execution quality.",
        overlay: "Managing five vendors means five contracts, five timelines, and five different answers when something goes wrong. The Expo Group's Single Source Solution® eliminates that complexity. This article explains how the model works in practice: one team owns design, construction, logistics, show services, and on-site management. When a problem occurs — and they always do — there's no finger-pointing, just solutions. The result is smoother shows, better attendee experiences, and a significantly reduced management burden for show organizers.",
      },
      tags: ['logistics', 'attendee-growth', 'show-design'],
      targetRoles: ['show-organizer', 'corporate-events', 'executive'],
    },

    // ── Solutions (7) ─────────────────────────────────
    {
      id: 's1',
      title: 'Trade Show Management & Production',
      cardType: 'solution',
      icon: 'layout-dashboard',
      iconType: 'lucide',
      url: 'https://theexpogroup.com/services/',
      description: {
        small: 'End-to-end trade show management and production.',
        medium: 'The Expo Group manages every dimension of trade show production — from pre-show planning through on-site management and post-show reporting.',
        large: 'Full-service trade show management covering show strategy, vendor coordination, exhibitor services, floor management, on-site operations, and post-show analytics — all unified under the Single Source Solution® model.',
        overlay: "Trade show management at scale requires more than logistics coordination — it requires strategic alignment between the organizer's vision, the exhibitor experience, and the attendee journey. The Expo Group's trade show management service covers every dimension: pre-show strategy and planning, vendor procurement and coordination, exhibitor services and communication, floor operations, on-site management, and post-show reporting. The Single Source Solution® keeps every element aligned under one accountable team.",
      },
      tags: ['logistics', 'attendee-growth', 'show-design'],
      targetRoles: ['show-organizer', 'association-exec', 'corporate-events'],
    },
    {
      id: 's2',
      title: 'Custom Exhibit Design & Construction',
      cardType: 'solution',
      icon: 'palette',
      iconType: 'lucide',
      url: 'https://theexpogroup.com/services/',
      description: {
        small: 'Award-winning custom exhibit design and build.',
        medium: 'Custom exhibit design and construction from concept through installation — environments built to attract, engage, and convert.',
        large: "The Expo Group's design-build team creates custom exhibit environments from the first concept sketch through final installation — combining architectural creativity with deep trade show knowledge to produce spaces that perform.",
        overlay: "A trade show booth is a brand's most concentrated physical expression — and The Expo Group's design-build team treats it that way. Starting from your brand strategy and audience goals, the team develops concepts that balance visual impact with functional performance. The result is custom-built environments that attract foot traffic, facilitate meaningful conversations, and deliver measurable results for exhibitors of every size.",
      },
      tags: ['show-design', 'brand-experience', 'exhibitor-roi'],
      targetRoles: ['exhibitor', 'event-designer', 'marketing-director', 'corporate-events'],
    },
    {
      id: 's3',
      title: 'Community Intelligence (CROWDPulse)',
      cardType: 'solution',
      icon: 'activity',
      iconType: 'lucide',
      url: 'https://theexpogroup.com/community-intelligence/',
      description: {
        small: 'AI-powered market and attendee intelligence platform.',
        medium: 'CROWDPulse delivers AI-powered market intelligence and unified event data analysis for smarter event strategy.',
        large: 'CROWDPulse combines macro market intelligence (billions of signals from search, social, and competitive activity) with micro event data (AMS, CRM, registration, lead capture) to give event organizers a complete strategic picture.',
        overlay: "CROWDPulse is The Expo Group's proprietary community intelligence platform — and a genuine strategic differentiator for event organizers. At the macro level, it monitors billions of real-time market signals to identify industry trends, audience shifts, and competitive dynamics before they show up in your registration numbers. At the micro level, it consolidates all your event data sources into unified attendee and exhibitor intelligence. Three engagement tiers (Foundational, Growth, Transformational) serve organizations at every stage of data maturity.",
      },
      tags: ['community-intel', 'attendee-growth', 'exhibitor-roi'],
      targetRoles: ['show-organizer', 'association-exec', 'marketing-director', 'executive'],
    },
    {
      id: 's4',
      title: 'Event Management Services',
      cardType: 'solution',
      icon: 'calendar-days',
      iconType: 'lucide',
      url: 'https://theexpogroup.com/services/',
      description: {
        small: 'Strategic event management from concept through execution.',
        medium: 'End-to-end event management services — strategy, logistics, production, and on-site management for trade shows and corporate events.',
        large: "The Expo Group's event management services span concept development, pre-event logistics, exhibitor and attendee communications, floor management, and post-event reporting — anchored by extreme personal service at every touchpoint.",
        overlay: "Event management requires holding a hundred moving pieces together while keeping the experience seamless for attendees and exhibitors. The Expo Group's management team handles every layer: strategy and programming, vendor procurement and management, exhibitor services and support, on-site operations, real-time problem resolution, and post-event analytics. Extreme personal service is the standard — not a differentiator — for every account.",
      },
      tags: ['logistics', 'attendee-growth', 'sponsor-engagement'],
      targetRoles: ['show-organizer', 'association-exec', 'corporate-events'],
    },
    {
      id: 's5',
      title: 'Official Services Contracting',
      cardType: 'solution',
      icon: 'layers',
      iconType: 'lucide',
      url: 'https://theexpogroup.com/services/',
      description: {
        small: 'Official services contractor for large-scale industry events.',
        medium: 'The Expo Group serves as Official Services Contractor for large industry events, managing all show services under one accountable partner.',
        large: 'As Official Services Contractor, The Expo Group manages all show services for large industry events — coordinating every service provider, exhibitor interaction, and logistical element under the Single Source Solution® model.',
        overlay: "Serving as Official Services Contractor means owning every service touchpoint for the entire event — from exhibitor move-in coordination to electrical, material handling, signage, and all on-site services. The Expo Group's role as Official Services Contractor for events like PRINTING United Expo demonstrates the capability to manage large-scale show services at the industry flagship level. The Single Source Solution® ensures every service element is coordinated by one team with complete accountability.",
      },
      tags: ['logistics', 'show-design', 'attendee-growth'],
      targetRoles: ['show-organizer', 'association-exec', 'executive'],
    },
    {
      id: 's6',
      title: 'Corporate Event Design & Production',
      cardType: 'solution',
      icon: 'briefcase',
      iconType: 'lucide',
      url: 'https://theexpogroup.com/services/',
      description: {
        small: 'Immersive corporate event experiences that drive results.',
        medium: 'Custom corporate event design and production — from internal summits to external launches — anchored in experiential strategy.',
        large: 'The Expo Group brings trade show-grade design and production expertise to corporate events — creating immersive environments that strengthen culture, communicate brand vision, and drive measurable audience engagement.',
        overlay: "Corporate events carry brand-defining stakes: the annual sales kickoff, the customer summit, the industry launch. The Expo Group's corporate event design service applies the same immersive design philosophy and production discipline that produces award-winning trade show exhibits to internal and external corporate events. The result is environments that go beyond function to create experiences that strengthen relationships, communicate vision, and generate business results.",
      },
      tags: ['brand-experience', 'show-design', 'sponsor-engagement'],
      targetRoles: ['corporate-events', 'marketing-director', 'executive', 'event-designer'],
    },
    {
      id: 's7',
      title: 'Higher Education Events',
      cardType: 'solution',
      icon: 'graduation-cap',
      iconType: 'lucide',
      url: 'https://theexpogroup.com/services/',
      description: {
        small: 'Trade show expertise applied to higher education events.',
        medium: "The Expo Group's experience includes higher education events — bringing community-connecting expertise to university and academic environments.",
        large: "The Expo Group's higher education event practice brings trade show expertise to university and academic environments — from recruitment events to research showcases, applying community intelligence and design-build capabilities to education-sector goals.",
        overlay: "Higher education institutions face a unique events challenge: connecting prospective students, current students, faculty, alumni, industry partners, and donors through experiences that authentically represent institutional values. The Expo Group's higher education practice applies community intelligence, design-build expertise, and the Single Source Solution® model to the specific needs of academic events — creating environments that build community and advance institutional goals.",
      },
      tags: ['attendee-growth', 'brand-experience', 'show-design'],
      targetRoles: ['association-exec', 'corporate-events', 'newcomer'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
