// Explorer Config — VitalEdge Technologies
// The global leader in integrated, AI-driven, end-to-end software for
// equipment dealerships: e-Emphasys ERP, IntelliDealer DMS, Integrated
// Rental, VitalityAI, and LHP Telematics. $55B+ processed annually,
// 4,300 rooftops, 500+ dealers in 20+ countries, 40+ OEM integrations.
// Brand: red #DB1A21 + black. Site font is Geist (not in the curated
// loadable set) — Inter is the closest loadable match.
// Content sourced from vitaledge.com (solutions pages + case-study
// library, extracted 2026-07-28). All URLs are live routes.

import type { ExplorerConfig, ThemeColors } from '../types';

const VITAL_EDGE_DARK: ThemeColors = {
  // Brand-tinted near-black UI tones derived from the red hue so
  // dialogs and the Tools menu read distinctly VitalEdge.
  bg: '#0E0506',
  bgGradient: 'linear-gradient(135deg, #1F0A0B 0%, #140708 55%, #0E0506 100%)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceHover: 'rgba(255,255,255,0.10)',
  border: 'rgba(255,255,255,0.12)',
  borderFocus: '#F04B51',
  text1: '#FFFFFF',
  text2: 'rgba(255,255,255,0.78)',
  text3: 'rgba(255,255,255,0.52)',
  inputBg: 'rgba(255,255,255,0.08)',
  inputText: '#FFFFFF',
  inputPlaceholder: 'rgba(255,255,255,0.40)',
  logoText: '#FFFFFF',
  focusRing: 'rgba(219,26,33,0.28)',
};

const VITAL_EDGE_LIGHT: ThemeColors = {
  // Clean, crisp light theme — neutral cool gray so the red accent
  // carries the brand.
  bg: '#F5F5F7',
  bgGradient: 'linear-gradient(180deg, #F7F7F9 0%, #F1F1F4 100%)',
  surface: 'rgba(255,255,255,0.88)',
  surfaceHover: 'rgba(255,255,255,0.97)',
  border: 'rgba(20,10,10,0.10)',
  borderFocus: '#A31419',
  text1: '#140A0A',
  text2: 'rgba(20,10,10,0.68)',
  text3: 'rgba(20,10,10,0.45)',
  inputBg: '#FFFFFF',
  inputText: '#140A0A',
  inputPlaceholder: 'rgba(20,10,10,0.38)',
  logoText: '#140A0A',
  focusRing: 'rgba(219,26,33,0.15)',
};

export const VITAL_EDGE_CONFIG: ExplorerConfig = {
  id: 'vital-edge',
  name: 'VitalEdge Explorer',
  version: 1,
  createdAt: '2026-07-28T00:00:00.000Z',
  updatedAt: '2026-07-28T00:00:00.000Z',

  branding: {
    logo: {
      dark: '/brand/assets/vital-edge-logo-reverse.svg',  // white wordmark + red chevron for dark bg
      light: '/brand/assets/vital-edge-logo.svg',         // black wordmark + red chevron for light bg
    },
    // Wordmark lockup is ~3.5:1 (1247x354 viewBox). 34px keeps it
    // proportional in the top bar without crowding.
    logoHeight: 34,
    icon: '/brand/assets/vital-edge-icon.jpg',
    colors: {
      primary: '#DB1A21',   // VitalEdge red — main accent
      secondary: '#000000', // black — second anchor
      teal: '#F04B51',      // brighter red for hover/focus on dark
      blue: '#DB1A21',
      deepBlue: '#A31419',  // darker red
      // midnight + navy drive dialog backgrounds + overlay backdrop,
      // both pulled from the red hue so dialogs stay on-brand.
      navy: '#1F0A0B',
      midnight: '#120607',
      plum: '#3D1214',      // deep wine — gradient support
      bgDark: '#0E0506',
      dark: VITAL_EDGE_DARK,
      light: VITAL_EDGE_LIGHT,
    },
    // Site font is Geist — not in the curated loadable set; Inter is
    // the closest visual match and the platform default.
    font: "'Inter', -apple-system, sans-serif",
    backgroundPattern: 'none',
    auroraOrbs: {
      orb1: 'rgba(219,26,33,0.20)',   // VitalEdge red
      orb2: 'rgba(240,75,81,0.14)',   // bright red
      orb3: 'rgba(61,18,20,0.16)',    // deep wine
    },
    // CTA = VitalEdge red → dark red (white text stays legible)
    ctaGradient: 'linear-gradient(135deg, #DB1A21 0%, #8E1015 100%)',
    ctaTextColor: '#FFFFFF',
    // Headline gradient anchored on the logo red (per brand feedback:
    // true reds, not washed-out pinks)
    gradientWord: 'linear-gradient(135deg, #F4494F 0%, #DB1A21 60%, #A31419 100%)',
    // Per-role glows: red / wine / bright-red mixes so each role feels
    // like its own chapter.
    roleBackgrounds: {
      'dealer-principal': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(219,26,33,0.30) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(240,75,81,0.16) 0%, transparent 55%)',
      'service-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(163,20,25,0.28) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 15%, rgba(219,26,33,0.16) 0%, transparent 55%)',
      'parts-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(240,75,81,0.22) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 25% 15%, rgba(219,26,33,0.16) 0%, transparent 55%)',
      'rental-manager': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(219,26,33,0.26) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(61,18,20,0.16) 0%, transparent 55%)',
      'sales-leader': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(240,75,81,0.20) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 25%, rgba(163,20,25,0.16) 0%, transparent 55%)',
      'finance-leader': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(163,20,25,0.24) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 75% 15%, rgba(240,75,81,0.12) 0%, transparent 55%)',
      'it-leader': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(61,18,20,0.26) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 85% 25%, rgba(219,26,33,0.16) 0%, transparent 55%)',
      'browsing': 'radial-gradient(ellipse 90% 70% at 50% 70%, rgba(219,26,33,0.16) 0%, transparent 65%), radial-gradient(ellipse 70% 60% at 15% 15%, rgba(240,75,81,0.10) 0%, transparent 55%)',
    },
  },

  registration: {
    modes: ['form', 'scan', 'search'],
    defaultMode: 'form',
    formTitle: 'Welcome to VitalEdge',
    formSubtitle: 'Share a quick intro so we can tailor your tour to your dealership.',
    scanLabel: 'Scan Your Badge',
    scanHint: 'Hold the QR code in front of the camera',
    searchPlaceholder: 'Search by last name...',
    optInText: 'By sharing your information you consent to VitalEdge Technologies processing your data to fulfill your request and send relevant follow-up communications.',
    showLocaleButton: false,
    idleTimeoutMs: 10000,
    skipEnabled: true,
    fields: [
      { id: 'firstName', label: 'First Name', type: 'text', placeholder: 'First name', required: true, halfWidth: true },
      { id: 'lastName', label: 'Last Name', type: 'text', placeholder: 'Last name', required: true, halfWidth: true },
      { id: 'email', label: 'Work Email', type: 'email', placeholder: 'name@dealership.com', required: true, halfWidth: true },
      { id: 'phone', label: 'Phone', type: 'tel', placeholder: '(555) 555-5555', required: false, halfWidth: true },
      { id: 'company', label: 'Dealership', type: 'text', placeholder: 'Dealership name', required: false, halfWidth: true },
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your role', required: false, halfWidth: true },
    ],
  },

  steps: [
    {
      type: 'splash',
      id: 'welcome',
      title: 'Empowering Equipment',
      gradientWord: 'Dealerships for Growth.',
      subtitle: 'Integrated, AI-driven, end-to-end software built for equipment dealerships. $55B+ processed annually across 4,300 rooftops, 500+ dealers, and 40+ OEM integrations in 20+ countries. Tap to explore what VitalEdge can do for yours.',
      buttonText: 'Tap to Begin',
    },
    {
      type: 'registration',
      id: 'registration',
    },
    {
      type: 'trait-selection',
      id: 'role',
      selectionMode: 'single',
      title: 'What\'s your role at the dealership?',
      subtitle: 'Select the option that fits you best.',
      showGreeting: true,
      showSelectAll: false,
      options: [
        { value: 'dealer-principal', label: 'Dealer Principal / Executive', icon: 'building-2', iconType: 'lucide' },
        { value: 'service-manager', label: 'Service Manager', icon: 'wrench', iconType: 'lucide' },
        { value: 'parts-manager', label: 'Parts Manager', icon: 'package', iconType: 'lucide' },
        { value: 'rental-manager', label: 'Rental Manager', icon: 'calendar-clock', iconType: 'lucide' },
        { value: 'sales-leader', label: 'Sales Leader', icon: 'trending-up', iconType: 'lucide' },
        { value: 'finance-leader', label: 'Finance / CFO', icon: 'calculator', iconType: 'lucide' },
        { value: 'it-leader', label: 'IT / Systems Leader', icon: 'server', iconType: 'lucide' },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide' },
      ],
    },
    {
      type: 'trait-selection',
      id: 'interests',
      selectionMode: 'multi',
      title: 'What are you here to explore?',
      subtitle: 'Select all that apply.',
      showGreeting: false,
      showSelectAll: true,
      // Conditional mapping — role → relevant interests.
      options: [
        { value: 'erp', label: 'e-Emphasys ERP', icon: 'database', iconType: 'lucide',
          relevantRoles: ['dealer-principal', 'finance-leader', 'parts-manager', 'it-leader', 'service-manager', 'browsing'] },
        { value: 'dms', label: 'IntelliDealer DMS', icon: 'layout-dashboard', iconType: 'lucide',
          relevantRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'sales-leader', 'it-leader', 'browsing'] },
        { value: 'rental', label: 'Rental Management', icon: 'calendar-clock', iconType: 'lucide',
          relevantRoles: ['rental-manager', 'dealer-principal', 'finance-leader', 'browsing'] },
        { value: 'ai-intelligence', label: 'VitalityAI', icon: 'sparkles', iconType: 'lucide',
          relevantRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'sales-leader', 'finance-leader', 'it-leader', 'browsing'] },
        { value: 'telematics', label: 'Telematics & Machine Data', icon: 'satellite-dish', iconType: 'lucide',
          relevantRoles: ['service-manager', 'rental-manager', 'it-leader', 'dealer-principal', 'browsing'] },
        { value: 'oem-integrations', label: 'OEM Integrations', icon: 'plug-zap', iconType: 'lucide',
          relevantRoles: ['dealer-principal', 'it-leader', 'sales-leader', 'parts-manager', 'browsing'] },
        { value: 'dealer-ops', label: 'Dealer Operations & Growth', icon: 'trending-up', iconType: 'lucide',
          relevantRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'rental-manager', 'sales-leader', 'finance-leader', 'browsing'] },
        { value: 'browsing', label: 'Just Browsing', icon: 'compass', iconType: 'lucide',
          relevantRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'rental-manager', 'sales-leader', 'finance-leader', 'it-leader', 'browsing'] },
      ],
    },
    {
      type: 'results',
      id: 'results',
      title: 'Your Personalized Tour',
      subtitle: 'Platforms, proof, and dealer stories tailored to your role.',
      tabs: [
        { id: 'outcomes', label: 'Impact', icon: 'trending-up' },
        {
          id: 'learn',
          label: 'Discover',
          icon: 'book-open',
          filters: [
            { label: 'All', value: 'all' },
            { label: 'Video', value: 'video' },
            { label: 'PDF', value: 'pdf' },
            { label: 'Blog', value: 'blog' },
            { label: 'Website', value: 'website' },
          ],
        },
        { id: 'solutions', label: 'Solutions', icon: 'layers' },
      ],
      cardsPerPage: 6,
      defaultView: 'small',
    },
    {
      type: 'summary',
      id: 'summary',
      title: 'Your Saved Items',
      subtitle: 'Review your picks and a VitalEdge team member will follow up.',
    },
    {
      type: 'content-library',
      id: 'library',
      title: 'Explore Everything',
      subtitle: 'Browse all available content.',
    },
    {
      type: 'thank-you',
      id: 'thanks',
      title: 'Thank You!',
      subtitle: 'A VitalEdge team member will be in touch shortly.',
      showNewSessionButton: true,
      showAddNotesButton: true,
    },
  ],

  content: [
    // ─────────────────────────────────────────────────────────────────
    // Conditional trait-mapping graph
    //
    // Role → primary interests (mirrored on each interest option's
    // `relevantRoles`):
    //   dealer-principal : erp, dms, rental, ai-intelligence, telematics,
    //                      oem-integrations, dealer-ops, browsing
    //   service-manager  : erp, dms, ai-intelligence, telematics,
    //                      dealer-ops, browsing
    //   parts-manager    : erp, dms, ai-intelligence, oem-integrations,
    //                      dealer-ops, browsing
    //   rental-manager   : rental, telematics, dealer-ops, browsing
    //   sales-leader     : dms, ai-intelligence, oem-integrations,
    //                      dealer-ops, browsing
    //   finance-leader   : erp, rental, ai-intelligence, dealer-ops, browsing
    //   it-leader        : erp, dms, ai-intelligence, telematics,
    //                      oem-integrations, browsing
    //   browsing         : (catch-all — all interests)
    // ─────────────────────────────────────────────────────────────────

    // ── Outcomes / Impact (8) ─────────────────────────
    {
      id: 'o1',
      title: '$55B+ Processed Annually',
      cardType: 'outcome',
      icon: 'landmark',
      iconType: 'lucide',
      stat: '$55B+',
      url: 'https://vitaledge.com/about-us/',
      description: {
        small: 'More than $55 billion flows through VitalEdge solutions every year.',
        medium: 'Equipment dealers process more than $55 billion annually through VitalEdge platforms.',
        large: 'More than $55 billion in dealer business flows through VitalEdge solutions every year — parts, service, rental, and equipment sales running on one integrated software backbone.',
        overlay: 'Scale is its own proof point: more than $55 billion in equipment dealership business is processed through VitalEdge solutions annually — parts counters, service bays, rental fleets, and equipment sales floors all running on the same integrated backbone. When software carries that much of an industry\'s revenue, reliability and depth aren\'t features; they\'re table stakes.',
      },
      tags: ['dealer-ops'],
      targetRoles: ['dealer-principal', 'finance-leader', 'it-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'erp', 'browsing'],
    },
    {
      id: 'o2',
      title: '4,300 Rooftops, 500+ Dealers',
      cardType: 'outcome',
      icon: 'building-2',
      iconType: 'lucide',
      stat: '4,300',
      url: 'https://vitaledge.com/about-us/',
      description: {
        small: 'VitalEdge software runs 4,300 dealership locations worldwide.',
        medium: '500+ dealer customers run VitalEdge software across 4,300 rooftops in 20+ countries.',
        large: 'VitalEdge is the operating system for 4,300 dealership rooftops — 500+ dealer organizations across 20+ countries, supported by 800+ employees globally.',
        overlay: 'From single-store operations to multi-national dealer groups, 500+ dealers run their businesses on VitalEdge software across 4,300 rooftops in more than 20 countries. Behind them: 800+ VitalEdge employees globally, focused entirely on equipment dealership technology. That install base is why OEMs integrate with VitalEdge first — and why dealer best practices flow into the product.',
      },
      tags: ['dealer-ops'],
      targetRoles: ['dealer-principal', 'it-leader', 'sales-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'browsing'],
    },
    {
      id: 'o3',
      title: '40+ OEM Integrations',
      cardType: 'outcome',
      icon: 'plug-zap',
      iconType: 'lucide',
      stat: '40+',
      url: 'https://vitaledge.com/alliances/oem/',
      description: {
        small: 'Secure integrations with John Deere, Komatsu, Kubota, Volvo, and 40+ OEMs.',
        medium: 'VitalEdge maintains 40+ OEM integrations — John Deere, Komatsu, Kubota, CASE, New Holland, Volvo, Toyota, and more.',
        large: 'Forty-plus OEM integrations connect dealers directly to their manufacturers: John Deere, Komatsu, Kubota, CNH, CASE, New Holland, Volvo, Toyota, JCB, Liebherr, Manitou, and dozens more.',
        overlay: 'Dealer software is only as good as its manufacturer connections. VitalEdge maintains 40+ OEM integrations spanning agriculture, construction, material handling, and heavy truck — John Deere, Komatsu, Kubota, CNH Industrial, CASE, New Holland, Volvo, Toyota, JCB, Liebherr, Manitowoc, STIHL, Vermeer, and more — enabling secure warranty, parts, registration, and machine-data workflows straight from the dealership system to the OEM.',
      },
      tags: ['oem-integrations'],
      targetRoles: ['dealer-principal', 'it-leader', 'parts-manager', 'sales-leader', 'browsing'],
      targetInterests: ['oem-integrations', 'erp', 'dms'],
    },
    {
      id: 'o4',
      title: 'Margins Up 5 Points at Force TK',
      cardType: 'outcome',
      icon: 'trending-up',
      iconType: 'lucide',
      stat: '+5pts',
      url: 'https://vitaledge.com/case-study/force-tk-customer-success-story/',
      description: {
        small: 'Automated pricing controls lifted Force TK\'s margins 5 points.',
        medium: 'Nine-location Force TK improved margins by 5 points with e-Emphasys automated pricing controls and business intelligence.',
        large: 'Force TK, a nine-location dealer across six states, lifted margins by 5 points using e-Emphasys ERP — automated pricing controls, discount monitoring, and drill-down business intelligence on every order.',
        overlay: '"Just controlling pricing in a more automated way and preventing or monitoring discounts, we\'ve improved margins by 5 points," says Force TK\'s parts director. The nine-location dealer (Arizona, Texas, New Mexico, Maryland, Wyoming, Delaware) uses e-Emphasys automated pricing controls plus business intelligence that drills to the individual order — spotting missed-margin and mispriced deals that used to slip through. Back-order processing sped up too: the system links back orders to POs for faster turnaround when inventory lands.',
      },
      tags: ['erp', 'dealer-ops'],
      targetRoles: ['parts-manager', 'finance-leader', 'dealer-principal', 'browsing'],
      targetInterests: ['erp', 'dealer-ops'],
    },
    {
      id: 'o5',
      title: 'Time-to-Close Cut in Half',
      cardType: 'outcome',
      icon: 'timer',
      iconType: 'lucide',
      stat: '50%',
      url: 'https://vitaledge.com/case-study/force-tk-customer-success-story/',
      description: {
        small: 'Force TK halved time-to-completion-to-close with e-Emphasys.',
        medium: 'The e-Emphasys Digital Transformation Platform cut Force TK\'s completion-to-close cycle in half.',
        large: 'Real-time data and automated workflows on the e-Emphasys Digital Transformation Platform cut Force TK\'s time-from-completion-to-close in half — faster billing, faster cash.',
        overlay: 'Work that\'s finished but not closed is cash sitting on the table. On the e-Emphasys Digital Transformation Platform, Force TK cut its time-from-completion-to-close in half — automated workflows move finished work orders to invoice faster, and real-time visibility shows exactly where anything is stuck. Faster close means faster billing, faster cash, and cleaner month-end.',
      },
      tags: ['erp', 'dealer-ops'],
      targetRoles: ['finance-leader', 'service-manager', 'dealer-principal', 'browsing'],
      targetInterests: ['erp', 'dealer-ops'],
    },
    {
      id: 'o6',
      title: 'Sales 8x, Profit 15x at WC Tractor',
      cardType: 'outcome',
      icon: 'rocket',
      iconType: 'lucide',
      stat: '15x',
      url: 'https://vitaledge.com/case-study/wc-tractor-building-a-best-in-class-dealership-with-data-at-its-fingertips/',
      description: {
        small: 'WC Tractor grew sales 8x and profit 15x on IntelliDealer.',
        medium: 'Fourteen-location WC Tractor has grown sales eightfold and profit fifteenfold, with data at its fingertips.',
        large: 'WC Tractor grew store count 50% in four years while sales went up eightfold and profit fifteenfold — with API-driven data movement and leadership dashboards keeping the admin team lean the whole way.',
        overlay: 'WC Tractor is the compounding-growth story: 14 locations, sales up eightfold and profit up fifteenfold since acquisition, store count up 50% in just four years. The engine underneath: API-driven data movement that eliminated manual entry, real-time leadership dashboards, and month-end book closing cut from weeks to days. Revenue more than doubled while the administrative operation stayed lean — a better work product, produced more efficiently, with reduced headcount.',
      },
      tags: ['dms', 'dealer-ops'],
      targetRoles: ['dealer-principal', 'finance-leader', 'sales-leader', 'browsing'],
      targetInterests: ['dms', 'dealer-ops'],
    },
    {
      id: 'o7',
      title: 'Month-End Close: Weeks to Days',
      cardType: 'outcome',
      icon: 'calendar-check',
      iconType: 'lucide',
      stat: 'Days',
      url: 'https://vitaledge.com/case-study/wc-tractor-building-a-best-in-class-dealership-with-data-at-its-fingertips/',
      description: {
        small: 'WC Tractor cut month-end book closing from weeks to days.',
        medium: 'API-driven data movement and dashboards cut WC Tractor\'s month-end close from weeks to days.',
        large: 'By replacing manual entry with API-driven data movement and giving leadership real-time dashboard visibility, WC Tractor reduced month-end book closing from weeks to days.',
        overlay: 'A month-end close that takes weeks means leadership is always steering with stale numbers. WC Tractor\'s move to API-driven data movement eliminated manual entry across the organization, and real-time dashboards put the metrics that matter in front of leadership continuously — cutting the monthly book close from weeks to days even as the dealership grew store count 50% and more than doubled revenue.',
      },
      tags: ['dms', 'dealer-ops'],
      targetRoles: ['finance-leader', 'dealer-principal', 'browsing'],
      targetInterests: ['dms', 'dealer-ops', 'erp'],
    },
    {
      id: 'o8',
      title: 'World\'s Largest Komatsu Distributor Standardized',
      cardType: 'outcome',
      icon: 'globe',
      iconType: 'lucide',
      stat: '40+',
      url: 'https://vitaledge.com/case-study/sms-equipment-customer-success-story/',
      description: {
        small: 'SMS Equipment unified 40+ branches on e-Emphasys ERP.',
        medium: 'SMS Equipment, among the world\'s largest Komatsu distributors, replaced multiple legacy systems with e-Emphasys across 40+ Canadian branches.',
        large: 'SMS Equipment — one of the world\'s largest Komatsu distributors, with 40+ branches across Canada — replaced multiple legacy systems with e-Emphasys ERP, aligning operations and cutting costs through standardization.',
        overlay: 'SMS Equipment, one of the world\'s largest Komatsu distributors with more than 40 branches across Canada, ran a disciplined replacement of multiple legacy systems with e-Emphasys ERP. The payoff, in their words: improved alignment of operations, reduced costs through efficiencies, and standardization across the company. Enterprise-scale dealer groups don\'t consolidate on a platform unless it can carry every branch — this one does.',
      },
      tags: ['erp', 'dealer-ops'],
      targetRoles: ['dealer-principal', 'it-leader', 'finance-leader', 'browsing'],
      targetInterests: ['erp', 'dealer-ops', 'oem-integrations'],
    },

    // ── Learn / Discover (12) — real videos, PDFs, and posts ─────────
    // Videos are YouTube (@vitaledgetechnologies) — the overlay renders
    // them as scan-to-watch QR cards. PDFs are HubSpot-hosted
    // (pages.vitaledge.com) — verified no X-Frame-Options, so they
    // render inline in the overlay iframe.
    {
      id: 'l1',
      title: 'Dealer Case Study Library',
      cardType: 'learn',
      mediaType: 'website',
      icon: 'library',
      iconType: 'lucide',
      url: 'https://vitaledge.com/resources/case-studies/',
      description: {
        small: 'A dozen dealer success stories, from Force TK to SMS Equipment.',
        medium: 'Twelve dealer success stories: Force TK, WC Tractor, SMS Equipment, Darr, Ahearn, Van Keppel, Molson Group, and more.',
        large: 'Browse the full case study library — Force TK, WC Tractor, SMS Equipment, Darr Equipment, Ahearn, ASCO, Construmac, Cowin, Great West, Molson Group, Scott-Macon, and Van Keppel — real dealers, real numbers.',
        overlay: 'The VitalEdge case study library covers a dozen dealerships across agriculture, construction, and material handling: Force TK (margins +5 points), WC Tractor (profit 15x), SMS Equipment (40+ branches standardized), Darr Equipment (modernizing to scale with confidence), Ahearn (scaling with service technology and trust), plus ASCO, Construmac, Cowin, Great West, Molson Group, Scott-Macon, and Van Keppel. Every story names the dealer and the outcome.',
      },
      tags: ['dealer-ops'],
      targetRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'rental-manager', 'sales-leader', 'finance-leader', 'it-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'browsing'],
    },
    {
      id: 'l2',
      title: 'The VitalEdge Brand Video',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'play-circle',
      iconType: 'lucide',
      url: 'https://www.youtube.com/watch?v=_R_dPQ1Af-k',
      description: {
        small: 'Who VitalEdge is, in two minutes.',
        medium: 'The VitalEdge brand video — the company, the platform, and the dealers it powers, in two minutes.',
        large: 'The official VitalEdge brand video: who the company is, what the integrated platform does, and why 500+ dealers across 4,300 rooftops run their businesses on it.',
        overlay: 'Start here: the official VitalEdge brand film introduces the company behind e-Emphasys, IntelliDealer, and VitalityAI — the integrated, AI-driven platform processing $55B+ of equipment dealership business annually. Save the card and the video will be in your follow-up email.',
      },
      tags: ['dealer-ops'],
      targetRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'rental-manager', 'sales-leader', 'finance-leader', 'it-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'browsing'],
    },
    {
      id: 'l3',
      title: 'IntelliDealer DMS Platform Tour',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'monitor-play',
      iconType: 'lucide',
      url: 'https://www.youtube.com/watch?v=6KCynVeDbRo',
      description: {
        small: 'See the IntelliDealer DMS platform in action.',
        medium: 'A video tour of the IntelliDealer DMS — the workflows, dashboards, and daily operations view.',
        large: 'The IntelliDealer platform video walks through the DMS dealers use every day: service and parts workflows, real-time dashboards, and the intuitive design behind WC Tractor\'s growth story.',
        overlay: 'Before the demo, watch the tour: the IntelliDealer DMS platform video shows the daily-driver workflows — service writing, parts counter, dashboards, and mobile access — that make it the DMS behind dealers like WC Tractor (sales 8x, profit 15x). Save the card and the tour video arrives in your follow-up email.',
      },
      tags: ['dms'],
      targetRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'sales-leader', 'it-leader', 'browsing'],
      targetInterests: ['dms', 'dealer-ops'],
    },
    {
      id: 'l4',
      title: 'ASCO Equipment: In Their Words',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://www.youtube.com/watch?v=VNijFwEkVNY',
      description: {
        small: 'ASCO Equipment\'s testimonial on partnering with VitalEdge.',
        medium: 'Texas-based ASCO Equipment shares its experience running the dealership on VitalEdge in this testimonial video.',
        large: 'ASCO Equipment tells its own story: why the Texas CASE dealer chose VitalEdge, what the transition looked like, and what changed in daily operations. A written case study is also on the site.',
        overlay: 'Hear it from a dealer, not a brochure: ASCO Equipment\'s leadership shares why they chose the VitalEdge platform, how the implementation went, and what changed across their Texas locations. Pairs with the written ASCO case study on vitaledge.com. Save the card and both links arrive in your follow-up email.',
      },
      tags: ['dealer-ops', 'erp'],
      targetRoles: ['dealer-principal', 'sales-leader', 'finance-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'erp', 'browsing'],
    },
    {
      id: 'l5',
      title: 'Molson Group: Success Story',
      cardType: 'learn',
      mediaType: 'video',
      icon: 'video',
      iconType: 'lucide',
      url: 'https://www.youtube.com/watch?v=cuxoBc_6P8Y',
      description: {
        small: 'How the UK\'s Molson Group runs on VitalEdge.',
        medium: 'The Molson Group — one of the UK\'s largest independent equipment dealers — shares its VitalEdge story on video.',
        large: 'Molson Group, one of the UK\'s largest independent equipment dealer groups, tells its VitalEdge success story — proof the platform crosses borders as well as verticals.',
        overlay: 'The Molson Group is one of the UK\'s largest independent equipment dealer groups, and its success story video shows the VitalEdge platform working outside North America — same integrated operations, different continent. Part of why 500+ dealers across 20+ countries run on the platform. Save the card and the video arrives in your follow-up email.',
      },
      tags: ['dealer-ops'],
      targetRoles: ['dealer-principal', 'it-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'browsing'],
    },
    {
      id: 'l6',
      title: 'Five Questions Before Buying a Branch',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-text',
      iconType: 'lucide',
      url: 'https://pages.vitaledge.com/hubfs/VE%20Website%20Content%20Files/The%20Five%20Critical%20Questions%20to%20Ask%20Before%20Buying%20a%20Branch.pdf',
      description: {
        small: 'The five critical systems questions before a branch acquisition.',
        medium: 'A VitalEdge guide: the five critical questions dealership leaders should ask before buying a branch.',
        large: 'Branch acquisitions live or die on integration. This VitalEdge guide walks through the five critical questions — systems, data, people, and process — to answer before the deal closes.',
        overlay: 'Growth by acquisition is the dealership playbook right now, and most of the pain shows up after closing — in systems, data migration, and process alignment. This VitalEdge guide lays out the five critical questions to ask before buying a branch, so the integration plan exists before the ink dries. Read it right here on the kiosk, or save the card to get the PDF in your follow-up email.',
      },
      tags: ['dealer-ops'],
      targetRoles: ['dealer-principal', 'finance-leader', 'it-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'erp'],
    },
    {
      id: 'l7',
      title: 'Top 10 Systems Mistakes in Dealership M&A',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'file-warning',
      iconType: 'lucide',
      url: 'https://pages.vitaledge.com/hubfs/VE%20Website%20Content%20Files/The%20Top%2010%20Systems%20Mistakes%20%20to%20Avoid%20in%20Dealership%20M&A.pdf',
      description: {
        small: 'The ten systems mistakes that sink dealership acquisitions.',
        medium: 'VitalEdge\'s guide to the top 10 systems mistakes in dealership M&A — and how to avoid each one.',
        large: 'Consolidation is reshaping the equipment dealer landscape. This guide catalogs the ten systems mistakes that derail dealership M&A — data migration traps, integration debt, process mismatches — with the fix for each.',
        overlay: 'Dealership consolidation is accelerating, and the deals that go sideways usually break on systems, not strategy. This VitalEdge guide catalogs the top ten systems mistakes in dealership M&A — from underestimating data migration to running two DMS platforms indefinitely — and what the dealers who integrate cleanly do differently. Read it inline, or save the card for the PDF link.',
      },
      tags: ['dealer-ops'],
      targetRoles: ['dealer-principal', 'finance-leader', 'it-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'erp'],
    },
    {
      id: 'l8',
      title: 'Insights Agent, Powered by Copilot',
      cardType: 'learn',
      mediaType: 'pdf',
      icon: 'sparkles',
      iconType: 'lucide',
      url: 'https://pages.vitaledge.com/hubfs/VE%20Website%20Content%20Files/e-Emphasys/VitalEdge-EE-Insights%20Agent%20powered%20by%20Copilot-Solution%20Overview-November%202025.pdf',
      description: {
        small: 'The e-Emphasys Insights Agent solution overview.',
        medium: 'Solution overview for the e-Emphasys Insights Agent powered by Copilot — conversational AI over dealership data.',
        large: 'The Insights Agent brings Copilot-powered conversational AI to e-Emphasys: ask questions of your dealership data in plain English and get answers grounded in your ERP. Full solution overview PDF.',
        overlay: 'The newest face of VitalityAI in the ERP: the e-Emphasys Insights Agent, powered by Copilot, lets dealership teams ask questions of their own operational data in plain English — no report builder required. This solution overview covers what it answers, how it grounds responses in your ERP data, and how dealers roll it out. Read it inline on the kiosk, or save the card for the PDF.',
      },
      tags: ['ai-intelligence', 'erp'],
      targetRoles: ['dealer-principal', 'finance-leader', 'it-leader', 'service-manager', 'parts-manager', 'browsing'],
      targetInterests: ['ai-intelligence', 'erp'],
    },
    {
      id: 'l9',
      title: 'DMS vs ERP: Which Is Right for You?',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'scale',
      iconType: 'lucide',
      url: 'https://vitaledge.com/resources/blog/dms-vs-erp-which-system-is-right-for-your-equipment-dealership/',
      description: {
        small: 'The honest breakdown of DMS vs ERP for equipment dealers.',
        medium: 'VitalEdge\'s guide to the DMS-vs-ERP decision — which system fits which dealership, and when to step up.',
        large: 'The question every growing dealer asks: DMS or ERP? This guide breaks down what each platform does, where the line sits, and how dealership size, complexity, and growth plans drive the answer.',
        overlay: 'VitalEdge sells both a DMS (IntelliDealer) and an ERP (e-Emphasys), which makes this guide unusually honest: what a DMS does well, what an ERP adds, where the crossover point sits, and how location count, rental mix, and OEM complexity should drive the decision. The right first read if you\'re sizing up a systems change.',
      },
      tags: ['dms', 'erp'],
      targetRoles: ['dealer-principal', 'it-leader', 'finance-leader', 'browsing'],
      targetInterests: ['dms', 'erp', 'dealer-ops'],
    },
    {
      id: 'l10',
      title: '5 Ways AI Drives Dealership Profit',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'brain',
      iconType: 'lucide',
      url: 'https://vitaledge.com/resources/blog/5-practical-ways-ai-can-drive-profit-in-your-dealership/',
      description: {
        small: 'Five practical, profit-first uses of AI in dealerships.',
        medium: 'Five practical ways AI drives profit in equipment dealerships — from service planning to parts and pricing.',
        large: 'No hype, just the five places AI is already making dealers money: smarter service planning, parts intelligence, pricing discipline, workflow automation, and decision support.',
        overlay: 'The AI conversation in dealerships gets practical fast when it\'s framed as profit: this post walks through five working use cases — service planning, parts inventory intelligence, pricing discipline, workflow automation, and executive decision support — with what each one needs from your data to deliver. A companion read to the VitalityAI platform story.',
      },
      tags: ['ai-intelligence'],
      targetRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'sales-leader', 'finance-leader', 'browsing'],
      targetInterests: ['ai-intelligence', 'dealer-ops'],
    },
    {
      id: 'l11',
      title: 'From Reactive to Predictive Service',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'satellite-dish',
      iconType: 'lucide',
      url: 'https://vitaledge.com/resources/blog/from-reactive-to-predictive-how-real-time-field-data-becomes-the-foundation-for-smarter-service-planning/',
      description: {
        small: 'How real-time field data powers predictive service planning.',
        medium: 'How real-time machine data moves dealership service from reactive repairs to predictive planning.',
        large: 'Real-time field data — hours, fault codes, utilization — is the foundation for predictive service planning. This post maps the shift from break-fix to proactive outreach, and the revenue that follows.',
        overlay: 'The service department\'s future is scheduled before the machine breaks. This post walks through how real-time field data — machine hours, fault codes, utilization streamed via telematics — becomes the foundation for predictive service planning: proactive customer outreach, smarter shop loading, higher absorption, and machine uptime dealers can sell. The operational case for the LHP Telematics layer.',
      },
      tags: ['telematics', 'ai-intelligence'],
      targetRoles: ['service-manager', 'rental-manager', 'dealer-principal', 'browsing'],
      targetInterests: ['telematics', 'ai-intelligence', 'dealer-ops'],
    },
    {
      id: 'l12',
      title: 'Future-Proofing Your CNH Dealership',
      cardType: 'learn',
      mediaType: 'blog',
      icon: 'tractor',
      iconType: 'lucide',
      url: 'https://vitaledge.com/resources/blog/3-ways-to-future-proof-your-cnh-dealership-with-a-modern-tech-platform/',
      description: {
        small: 'Three ways CNH dealers future-proof with a modern platform.',
        medium: 'Three ways CNH dealers use a modern tech platform to future-proof the dealership.',
        large: 'Written for CASE and New Holland dealers: three ways a modern, OEM-integrated platform future-proofs the dealership as CNH\'s technology expectations rise.',
        overlay: 'OEM technology expectations are rising fastest in the ag and construction channels, and CNH dealers feel it first. This post lays out three ways a modern, OEM-integrated dealer platform future-proofs the business — meeting CNH\'s digital requirements, unifying multi-store operations, and turning OEM data flows into an advantage instead of an obligation. The same logic applies across VitalEdge\'s 40+ OEM integrations.',
      },
      tags: ['oem-integrations'],
      targetRoles: ['dealer-principal', 'it-leader', 'sales-leader', 'browsing'],
      targetInterests: ['oem-integrations', 'dealer-ops'],
    },

    // ── Solutions (8) ─────────────────────────
    {
      id: 's1',
      title: 'e-Emphasys ERP',
      cardType: 'solution',
      icon: 'database',
      iconType: 'lucide',
      url: 'https://vitaledge.com/solutions/e-emphasys/',
      description: {
        small: 'The enterprise ERP built for equipment dealerships.',
        medium: 'e-Emphasys is the enterprise ERP for equipment dealers — parts, service, rental, sales, and finance on one integrated platform.',
        large: 'e-Emphasys ERP runs the whole dealership: parts, service, rental, sales, and finance in one system, with business intelligence, automated pricing controls, and 40+ OEM integrations.',
        overlay: 'e-Emphasys is the enterprise-grade ERP for multi-location equipment dealer groups: parts, service, rental, equipment sales, and finance unified in one platform with drill-down business intelligence, automated pricing and discount controls, and deep OEM integration. It\'s the system behind Force TK\'s 5-point margin gain and SMS Equipment\'s 40-branch standardization — built to carry dealerships measured in billions, not millions.',
      },
      tags: ['erp'],
      targetRoles: ['dealer-principal', 'finance-leader', 'parts-manager', 'it-leader', 'service-manager', 'browsing'],
      targetInterests: ['erp', 'dealer-ops'],
    },
    {
      id: 's2',
      title: 'IntelliDealer DMS',
      cardType: 'solution',
      icon: 'layout-dashboard',
      iconType: 'lucide',
      url: 'https://vitaledge.com/solutions/intellidealer/',
      description: {
        small: 'The dealer management system with intuitive workflows.',
        medium: 'IntelliDealer is the DMS focused on intuitive workflows and streamlined daily dealership operations.',
        large: 'IntelliDealer DMS streamlines daily dealership operations with intuitive workflows, API-driven data movement, and real-time dashboards — the platform behind WC Tractor\'s 15x profit growth.',
        overlay: 'IntelliDealer is the dealer management system designed around how dealership teams actually work: intuitive workflows for service, parts, and sales; API-driven data movement that kills manual re-entry; and real-time dashboards that put leadership metrics at your fingertips. It\'s the platform WC Tractor used to grow sales 8x and profit 15x while cutting month-end close from weeks to days.',
      },
      tags: ['dms'],
      targetRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'sales-leader', 'it-leader', 'browsing'],
      targetInterests: ['dms', 'dealer-ops'],
    },
    {
      id: 's3',
      title: 'Integrated Rental',
      cardType: 'solution',
      icon: 'calendar-clock',
      iconType: 'lucide',
      url: 'https://vitaledge.com/solutions/integrated-rental/',
      description: {
        small: 'Purpose-built rental management, quote to return.',
        medium: 'Integrated Rental connects quoting, dispatch, billing, and returns in one purpose-built rental platform.',
        large: 'Integrated Rental is purpose-built rental management: quoting, dispatch, utilization tracking, billing, and returns connected end-to-end, feeding the same platform as parts, service, and finance.',
        overlay: 'Rental has its own physics — utilization, availability, dispatch, damage, returns — and Integrated Rental is purpose-built for it. Quoting through dispatch through billing through return runs as one connected flow, and because it lives on the VitalEdge platform, rental utilization data feeds finance, service schedules, and fleet decisions instead of living in a silo. For dealers where rental is a growth engine, not an afterthought.',
      },
      tags: ['rental'],
      targetRoles: ['rental-manager', 'dealer-principal', 'finance-leader', 'browsing'],
      targetInterests: ['rental', 'dealer-ops'],
    },
    {
      id: 's4',
      title: 'VitalityAI',
      cardType: 'solution',
      icon: 'sparkles',
      iconType: 'lucide',
      url: 'https://vitaledge.com/vitalityai/',
      description: {
        small: 'Orchestrated AI agents for dealership intelligence.',
        medium: 'VitalityAI embeds orchestrated AI agents across service, parts, rental, and sales workflows.',
        large: 'VitalityAI is the AI layer of the VitalEdge platform — orchestrated agents embedded in dealer workflows that surface risks, flag anomalies, and support faster operational decisions.',
        overlay: 'VitalityAI turns the dealership\'s own operational data into an active advisor: orchestrated AI agents embedded across service, parts, rental, and sales workflows surface risks before they become losses, flag anomalies worth a manager\'s attention, and support faster decisions in the flow of daily work. Because it runs inside the platform processing $55B+ of dealer business annually, it learns from dealership operations at industry scale.',
      },
      tags: ['ai-intelligence'],
      targetRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'sales-leader', 'finance-leader', 'it-leader', 'browsing'],
      targetInterests: ['ai-intelligence', 'dealer-ops'],
    },
    {
      id: 's5',
      title: 'LHP Telematics',
      cardType: 'solution',
      icon: 'satellite-dish',
      iconType: 'lucide',
      url: 'https://vitaledge.com/resources/news/vitaledge-technologies-acquires-lhp-telematics-to-expand-machine-intelligence-for-heavy-equipment-dealers/',
      description: {
        small: 'Mixed-fleet machine intelligence and telematics.',
        medium: 'LHP Telematics brings mixed-fleet machine data — hours, location, fault codes — into dealership workflows.',
        large: 'LHP Telematics connects the machines to the dealership: mixed-fleet telematics streaming hours, location, utilization, and fault codes into service and rental workflows.',
        overlay: 'LHP Telematics is VitalEdge\'s machine-intelligence arm: mixed-fleet telematics that streams machine hours, location, utilization, and fault codes from the field into dealership workflows. Service teams get proactive maintenance triggers instead of waiting for breakdowns; rental teams see real utilization; dealers turn machine data into service revenue and customer uptime. Acquired by VitalEdge to make machine intelligence a native platform capability.',
      },
      tags: ['telematics'],
      targetRoles: ['service-manager', 'rental-manager', 'it-leader', 'dealer-principal', 'browsing'],
      targetInterests: ['telematics', 'ai-intelligence'],
    },
    {
      id: 's6',
      title: 'The Edge Suites',
      cardType: 'solution',
      icon: 'layers',
      iconType: 'lucide',
      url: 'https://vitaledge.com/solutions/',
      description: {
        small: 'SalesEdge, ServiceEdge, PartsEdge, RentalEdge, FinanceEdge.',
        medium: 'Five advanced suites sharpen each department: SalesEdge, ServiceEdge, PartsEdge, RentalEdge, and FinanceEdge.',
        large: 'The Edge suites layer advanced, department-specific capability onto the platform: SalesEdge for pipeline, ServiceEdge for the shop, PartsEdge for inventory, RentalEdge for the fleet, FinanceEdge for the books.',
        overlay: 'Every dealership department gets its own edge: SalesEdge (pipeline and quoting optimization), ServiceEdge (shop scheduling and technician productivity), PartsEdge (inventory intelligence and fill rates), RentalEdge (fleet utilization and rental profitability), and FinanceEdge (financial management and controls). Each suite deepens one department while staying native to the integrated platform — no bolt-on integrations to maintain.',
      },
      tags: ['dealer-ops'],
      targetRoles: ['dealer-principal', 'service-manager', 'parts-manager', 'rental-manager', 'sales-leader', 'finance-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'erp', 'dms'],
    },
    {
      id: 's7',
      title: 'OEM Exchange',
      cardType: 'solution',
      icon: 'plug-zap',
      iconType: 'lucide',
      url: 'https://vitaledge.com/alliances/oem-exchange/',
      description: {
        small: 'Secure dealer-to-manufacturer connectivity.',
        medium: 'The OEM Exchange is the secure integration layer connecting dealerships to 40+ manufacturers.',
        large: 'The OEM Exchange handles secure, structured data flow between dealership systems and 40+ OEMs — warranty claims, parts orders, machine registrations, and telematics without re-keying.',
        overlay: 'Every OEM wants data its own way, and the OEM Exchange absorbs that complexity: secure, structured integration between the dealership platform and 40+ manufacturers covering warranty claims, parts ordering, machine registration, and telematics data. Dealers work in one system; the Exchange speaks each OEM\'s language on the other side. It\'s the connectivity layer that makes a 40-brand mixed dealership operable.',
      },
      tags: ['oem-integrations'],
      targetRoles: ['it-leader', 'parts-manager', 'dealer-principal', 'browsing'],
      targetInterests: ['oem-integrations', 'erp', 'dms'],
    },
    {
      id: 's8',
      title: 'Request a Consultation',
      cardType: 'solution',
      icon: 'messages-square',
      iconType: 'lucide',
      url: 'https://vitaledge.com/request-a-consultation/',
      description: {
        small: 'Map your dealership\'s path with a VitalEdge expert.',
        medium: 'A consultation maps your dealership\'s current systems and growth goals to the right VitalEdge platform path.',
        large: 'The consultation is where it gets specific: a VitalEdge expert maps your dealership\'s locations, OEM mix, and growth goals to the right platform path — ERP, DMS, rental, AI, or all of it.',
        overlay: 'Every dealership arrives with a different starting point — legacy DMS, spreadsheet rental, an OEM mix spanning five manufacturers. The consultation maps yours: a VitalEdge expert walks through your locations, systems, OEM relationships, and growth plans, then lays out the platform path that fits, with references from dealers who made the same move. Save this card and the follow-up email will get it scheduled.',
      },
      tags: ['dealer-ops'],
      targetRoles: ['dealer-principal', 'finance-leader', 'it-leader', 'browsing'],
      targetInterests: ['dealer-ops', 'browsing'],
    },
  ],

  features: {
    screensaver: false,
    darkMode: true,
    lightMode: true,
    defaultTheme: 'dark',
    briefcase: true,
    share: { email: true, text: true, qr: true },
    notes: true,
    voiceCapture: true,
    mediaCapture: true,
    calculator: false,
    captureInfo: true,
  },
};
