export interface ExplorerInstance {
  slug: string;
  name: string;
  company: string;
  industry: string;
  prototypeFile: string;
  logo?: string;
  accentColor: string;
  createdAt: string;
  password?: string;
  bezel?: "ipad-landscape" | "dual-iphone-ipad";
  gateLogo?: string;
}

export const instances: ExplorerInstance[] = [
  {
    slug: "momentify",
    name: "Momentify Explorer",
    company: "Momentify",
    industry: "Demo",
    prototypeFile: "/brand/explorer-prototype_momentify.html",
    logo: "/brand/assets/Momentify-Icon.svg",
    accentColor: "#0CF4DF",
    createdAt: "2025-01-01",
  },
  {
    slug: "phil",
    name: "PHIL Aggregates",
    company: "Philippi-Hagenbuch",
    industry: "Aggregates",
    prototypeFile: "/brand/explorer-prototype_phil.html",
    logo: "/brand/phil-logo.png",
    accentColor: "#F16A21",
    createdAt: "2025-03-15",
    password: "philsystems",
  },
  {
    slug: "cat",
    name: "CAT Electric Power",
    company: "Caterpillar",
    industry: "Electric Power",
    prototypeFile: "/brand/explorer-prototype_cat.html",
    logo: "/brand/assets/cat-icon.png",
    accentColor: "#FFCC00",
    createdAt: "2025-02-20",
    password: "electricpower",
    bezel: "ipad-landscape",
  },
  {
    slug: "cat-gdl",
    name: "CAT GDL - SkillsUSA IPEX",
    company: "Caterpillar",
    industry: "Global Dealer Learning",
    prototypeFile: "/brand/explorer-prototype_catgdl-dashboard.html",
    logo: "/brand/assets/cat-icon.png",
    accentColor: "#FFCC00",
    createdAt: "2025-03-23",
    password: "skillsusaIPEX",
  },
  {
    slug: "freeman",
    name: "Freeman Explorer",
    company: "Freeman",
    industry: "Event Services",
    prototypeFile: "/brand/explorer-prototype_freeman_explorer.html",
    logo: "/brand/assets/freeman-icon.png",
    gateLogo: "/brand/assets/freeman-logo.svg",
    accentColor: "#5ED6FF",
    createdAt: "2025-03-24",
    password: "freeman2026",
    bezel: "ipad-landscape",
  },
  {
    slug: "pac",
    name: "PAC Explorer",
    company: "Pacific Aerospace Consulting",
    industry: "Defense & Aerospace",
    prototypeFile: "/brand/explorer-prototype_pac.html",
    logo: "/brand/assets/pac-icon.svg",
    accentColor: "#4db8ff",
    createdAt: "2025-03-25",
    password: "pac2026",
    bezel: "ipad-landscape",
  },
  {
    slug: "tradegroup",
    name: "The Trade Group Explorer",
    company: "The Trade Group",
    industry: "Exhibits & Events",
    prototypeFile: "/brand/explorer-prototype_tradegroup_explorer.html",
    logo: "/brand/assets/tradegroup-icon.svg",
    gateLogo: "/brand/assets/tradegroup-logo.svg",
    accentColor: "#CD9F26",
    createdAt: "2025-03-25",
    password: "tradegroup2026",
    bezel: "ipad-landscape",
  },
  {
    slug: "mustangcat-interview",
    name: "Open Interview Walk-In",
    company: "Mustang CAT",
    industry: "Heavy Equipment",
    prototypeFile: "/brand/mustangcat-interview.html",
    logo: "/brand/assets/mustang-cat-logo.png",
    accentColor: "#FFCC00",
    createdAt: "2025-03-27",
    password: "mustangcat",
    bezel: "dual-iphone-ipad",
  },
  {
    slug: "catdefense",
    name: "CAT Defense & Security",
    company: "Caterpillar",
    industry: "Defense & Security",
    prototypeFile: "/brand/catdefense/explorer-catdefense.html",
    logo: "/brand/assets/cat-icon.png",
    gateLogo: "/brand/assets/Caterpillar_logo.svg",
    accentColor: "#FFCC00",
    createdAt: "2025-04-01",
    password: "catdefense",
    bezel: "ipad-landscape",
  },
  {
    slug: "clarium",
    name: "Clarium Health Explorer",
    company: "Clarium Health",
    industry: "Healthcare Supply Chain",
    prototypeFile: "/explorer/clarium",
    logo: "/brand/assets/clarium-icon.png",
    gateLogo: "/brand/assets/clarium-dark.png",
    accentColor: "#4F46E5",
    createdAt: "2026-04-07",
    password: "clarium2026",
  },
];
