export interface ExplorerInstance {
  slug: string;
  name: string;
  company: string;
  industry: string;
  prototypeFile: string;
  logo?: string;
  accentColor: string;
  createdAt: string;
  password?: string;
  bezel?: "ipad-landscape" | "iphone-portrait" | "dual-iphone-ipad";
  gateLogo?: string;
  /** UI form factor of the experience. Purely informational for the dashboard —
   * the actual layout is driven by ExplorerConfig.formFactor (for React routes)
   * or the static HTML itself. Default 'tablet'. */
  formFactor?: "tablet" | "mobile";
  /** If set, renders an extra "Mobile" link in this card that opens the given slug.
   * Use this to pair a tablet instance with its mobile companion. */
  mobileSlug?: string;
  /** Hide this instance from the dashboard listing. Still accessible by URL. */
  hidden?: boolean;
}

export const instances: ExplorerInstance[] = [
  {
    slug: "friends-of-medicine",
    name: "Friends of Medicine Explorer",
    company: "Friends of Medicine",
    industry: "Healthcare Network",
    prototypeFile: "/explorer/friends-of-medicine",
    logo: "/brand/assets/friends-of-medicine-icon.png",
    gateLogo: "/brand/assets/friends-of-medicine-logo-dark.png",
    accentColor: "#1D9DAA",
    createdAt: "2026-06-22",
    password: "fom2026",
    mobileSlug: "friends-of-medicine-mobile",
  },
  {
    slug: "friends-of-medicine-mobile",
    name: "Friends of Medicine Explorer (Mobile)",
    company: "Friends of Medicine",
    industry: "Healthcare Network",
    prototypeFile: "/explorer/friends-of-medicine-mobile",
    logo: "/brand/assets/friends-of-medicine-icon.png",
    gateLogo: "/brand/assets/friends-of-medicine-logo-dark.png",
    accentColor: "#1D9DAA",
    createdAt: "2026-06-22",
    password: "fom2026",
    formFactor: "mobile",
    hidden: true,
  },
  {
    slug: "airpro",
    name: "AirPro Fan & Blower Explorer",
    company: "AirPro",
    industry: "Manufacturing",
    prototypeFile: "/explorer/airpro",
    logo: "/brand/assets/airpro-icon.png",
    gateLogo: "/brand/assets/airpro-logo-dark.png",
    accentColor: "#FFD940",
    createdAt: "2026-06-17",
    password: "airpro2026",
  },
  {
    slug: "mustang-cat-mtp",
    name: "Mustang CAT — MTP Recruiting",
    company: "Mustang CAT",
    industry: "Construction / Recruiting",
    prototypeFile: "/explorer/mustang-cat-mtp",
    logo: "/brand/assets/mustang-cat-mtp-light.png",
    gateLogo: "/brand/assets/mustang-cat-mtp-dark.png",
    accentColor: "#FFCC00",
    createdAt: "2026-06-16",
    password: "mustang2026",
  },
  {
    slug: "momentify",
    name: "Momentify Explorer v2",
    company: "Momentify",
    industry: "Technology",
    prototypeFile: "/explorer/momentify",
    logo: "/brand/assets/Momentify-Icon.svg",
    gateLogo: "/brand/assets/Momentify-Logo_Reverse.svg",
    accentColor: "#0CF4DF",
    createdAt: "2026-05-25",
    password: "momentify2026",
  },
  {
    slug: "phil",
    name: "PHIL Aggregates",
    company: "Philippi-Hagenbuch",
    industry: "Aggregates",
    prototypeFile: "/brand/explorer-prototype_phil.html",
    logo: "/brand/phil-logo.png",
    accentColor: "#F16A21",
    createdAt: "2025-03-15",
    password: "philsystems",
  },
  {
    slug: "cat",
    name: "CAT Electric Power",
    company: "Caterpillar",
    industry: "Electric Power",
    prototypeFile: "/brand/explorer-prototype_cat.html",
    logo: "/brand/assets/cat-icon.png",
    accentColor: "#FFCC00",
    createdAt: "2025-02-20",
    password: "electricpower",
    bezel: "ipad-landscape",
  },
  {
    slug: "cat-gdl",
    name: "CAT GDL - SkillsUSA IPEX",
    company: "Caterpillar",
    industry: "Global Dealer Learning",
    prototypeFile: "/brand/explorer-prototype_catgdl-dashboard.html",
    logo: "/brand/assets/cat-icon.png",
    accentColor: "#FFCC00",
    createdAt: "2025-03-23",
    password: "skillsusaIPEX",
  },
  {
    slug: "freeman",
    name: "Freeman Explorer",
    company: "Freeman",
    industry: "Event Services",
    prototypeFile: "/brand/explorer-prototype_freeman_explorer.html",
    logo: "/brand/assets/freeman-icon.png",
    gateLogo: "/brand/assets/freeman-logo.svg",
    accentColor: "#5ED6FF",
    createdAt: "2025-03-24",
    password: "freeman2026",
    bezel: "ipad-landscape",
  },
  {
    slug: "pac",
    name: "PAC Explorer",
    company: "Pacific Aerospace Consulting",
    industry: "Defense & Aerospace",
    prototypeFile: "/brand/explorer-prototype_pac.html",
    logo: "/brand/assets/pac-icon.svg",
    accentColor: "#4db8ff",
    createdAt: "2025-03-25",
    password: "pac2026",
    bezel: "ipad-landscape",
  },
  {
    slug: "tradegroup",
    name: "The Trade Group Explorer",
    company: "The Trade Group",
    industry: "Exhibits & Events",
    prototypeFile: "/brand/explorer-prototype_tradegroup_explorer.html",
    logo: "/brand/assets/tradegroup-icon.svg",
    gateLogo: "/brand/assets/tradegroup-logo.svg",
    accentColor: "#CD9F26",
    createdAt: "2025-03-25",
    password: "tradegroup2026",
    bezel: "ipad-landscape",
  },
  {
    slug: "mustangcat-interview",
    name: "Open Interview Walk-In",
    company: "Mustang CAT",
    industry: "Heavy Equipment",
    prototypeFile: "/brand/mustangcat-interview.html",
    logo: "/brand/assets/mustang-cat-logo.png",
    accentColor: "#FFCC00",
    createdAt: "2025-03-27",
    password: "mustangcat",
    bezel: "dual-iphone-ipad",
  },
  {
    slug: "catdefense",
    name: "CAT Defense & Security",
    company: "Caterpillar",
    industry: "Defense & Security",
    prototypeFile: "/brand/catdefense/explorer-catdefense.html",
    logo: "/brand/assets/cat-icon.png",
    gateLogo: "/brand/assets/Caterpillar_logo_reverse.svg",
    accentColor: "#FFCC00",
    createdAt: "2025-04-01",
    password: "catdefense",
    bezel: "ipad-landscape",
  },
  {
    slug: "clarium",
    name: "Clarium Health Explorer",
    company: "Clarium Health",
    industry: "Healthcare Supply Chain",
    prototypeFile: "/explorer/clarium",
    logo: "/brand/assets/clarium-icon.png",
    gateLogo: "/brand/assets/clarium-dark.png",
    accentColor: "#4F46E5",
    createdAt: "2026-04-07",
    password: "clarium2026",
    mobileSlug: "clarium-mobile",
  },
  {
    slug: "clarium-mobile",
    name: "Clarium Health Explorer (Mobile)",
    company: "Clarium Health",
    industry: "Healthcare Supply Chain",
    prototypeFile: "/explorer/clarium-mobile",
    logo: "/brand/assets/clarium-icon.png",
    gateLogo: "/brand/assets/clarium-dark.png",
    accentColor: "#4F46E5",
    createdAt: "2026-04-23",
    password: "clarium2026",
    formFactor: "mobile",
    hidden: true,
  },
  {
    slug: "maven-fp",
    name: "Maven Financial Partners Explorer",
    company: "Maven Financial Partners",
    industry: "Financial Advisory",
    prototypeFile: "/explorer/maven-fp",
    logo: "/brand/assets/maven-fp-icon.png",
    gateLogo: "/brand/assets/maven-fp-logo-reverse.png",
    accentColor: "#7B9DAE",
    createdAt: "2026-04-07",
    password: "mavenfp2026",
  },
  {
    slug: "cdk",
    name: "CDK Global Explorer",
    company: "CDK Global",
    industry: "Automotive Technology",
    prototypeFile: "/explorer/cdk",
    logo: "/brand/assets/cdk-icon.jpeg",
    gateLogo: "/brand/assets/cdk-logo-reverse.png",
    accentColor: "#FFFFFF",
    createdAt: "2026-04-08",
    password: "cdk2026",
  },
  {
    slug: "salesflowiq",
    name: "SalesFlowIQ Explorer",
    company: "SalesFlowIQ",
    industry: "Sales Enablement",
    prototypeFile: "/explorer/salesflowiq",
    logo: "/brand/assets/salesflowiq-icon.png",
    gateLogo: "/brand/assets/salesflowiq-logo-reverse.png",
    accentColor: "#31B0E5",
    createdAt: "2026-04-14",
    password: "salesflowiq2026",
  },
  {
    slug: "dealroom",
    name: "DealRoom Explorer",
    company: "DealRoom",
    industry: "M&A Management",
    prototypeFile: "/explorer/dealroom",
    logo: "/brand/assets/dealroom-icon.png",
    gateLogo: "/brand/assets/dealroom-logo-reverse.svg",
    accentColor: "#0278DB",
    createdAt: "2026-04-26",
    password: "dealroom2026",
    mobileSlug: "dealroom-mobile",
  },
  {
    slug: "dealroom-mobile",
    name: "DealRoom Explorer (Mobile)",
    company: "DealRoom",
    industry: "M&A Management",
    prototypeFile: "/explorer/dealroom-mobile",
    logo: "/brand/assets/dealroom-icon.png",
    gateLogo: "/brand/assets/dealroom-logo-reverse.svg",
    accentColor: "#0278DB",
    createdAt: "2026-04-26",
    password: "dealroom2026",
    formFactor: "mobile",
    hidden: true,
  },
  {
    slug: "salas-o-brien",
    name: "Salas O'Brien Explorer",
    company: "Salas O'Brien",
    industry: "Engineering & Design",
    prototypeFile: "/explorer/salas-o-brien",
    logo: "/brand/assets/salas-obrien-icon.png",
    gateLogo: "/brand/assets/salas-obrien-logo-reverse.svg",
    accentColor: "#009DE0",
    createdAt: "2026-04-28",
    password: "salasobrien2026",
    mobileSlug: "salas-o-brien-mobile",
  },
  {
    slug: "salas-o-brien-mobile",
    name: "Salas O'Brien Explorer (Mobile)",
    company: "Salas O'Brien",
    industry: "Engineering & Design",
    prototypeFile: "/explorer/salas-o-brien-mobile",
    logo: "/brand/assets/salas-obrien-icon.png",
    gateLogo: "/brand/assets/salas-obrien-logo-reverse.svg",
    accentColor: "#009DE0",
    createdAt: "2026-04-28",
    password: "salasobrien2026",
    formFactor: "mobile",
    hidden: true,
  },
  {
    slug: "empire-jobfair",
    name: "Empire CAT Job Fair",
    company: "Empire CAT",
    industry: "Heavy Equipment",
    prototypeFile: "/brand/explorer-prototype_empire-jobfair.html",
    logo: "/brand/assets/empire-cat-logo.png",
    gateLogo: "/brand/assets/empire-cat-logo.png",
    accentColor: "#FFCC00",
    createdAt: "2026-04-15",
    password: "empirecat2026",
    bezel: "ipad-landscape",
  },
  {
    slug: "dfwpb-pickleball-may132026",
    name: "DFWTPB Explorer",
    company: "DFW Technology Prayer Breakfast",
    industry: "Technology",
    prototypeFile: "/explorer/dfwpb-pickleball-may132026",
    logo: "/dfwtpb.png",
    gateLogo: "/dfwtpb.png",
    accentColor: "#BF353D",
    createdAt: "2026-05-04",
    password: "dfwtpb2026",
    mobileSlug: "dfwpb-pickleball-may132026-mobile",
  },
  {
    slug: "dfwpb-pickleball-may132026-mobile",
    name: "DFWTPB Explorer (Mobile)",
    company: "DFW Technology Prayer Breakfast",
    industry: "Technology",
    prototypeFile: "/explorer/dfwpb-pickleball-may132026-mobile",
    logo: "/dfwtpb.png",
    gateLogo: "/dfwtpb.png",
    accentColor: "#BF353D",
    createdAt: "2026-05-04",
    password: "dfwtpb2026",
    formFactor: "mobile",
    hidden: true,
  },
  {
    slug: "carter-machinery",
    name: "Carter Machinery Careers",
    company: "Carter Machinery",
    industry: "Energy & Utilities",
    prototypeFile: "/explorer/carter-machinery",
    logo: "/brand/assets/carter-machinery-logo.jpg",
    gateLogo: "/brand/assets/carter-machinery-logo.jpg",
    accentColor: "#FFCC00",
    createdAt: "2026-05-05",
    password: "cartercat2026",
    mobileSlug: "carter-machinery-mobile",
  },
  {
    slug: "carter-machinery-mobile",
    name: "Carter Machinery Careers (Mobile)",
    company: "Carter Machinery",
    industry: "Energy & Utilities",
    prototypeFile: "/explorer/carter-machinery-mobile",
    logo: "/brand/assets/carter-machinery-logo.jpg",
    gateLogo: "/brand/assets/carter-machinery-logo.jpg",
    accentColor: "#FFCC00",
    createdAt: "2026-05-05",
    password: "cartercat2026",
    formFactor: "mobile",
    hidden: true,
  },
  {
    slug: "fortune-tire",
    name: "Fortune Tire Explorer",
    company: "Fortune Tire",
    industry: "Automotive",
    prototypeFile: "/explorer/fortune-tire",
    logo: "/brand/assets/fortune-tire-icon.png",
    gateLogo: "/brand/assets/fortune-tire-logo-reverse.png",
    accentColor: "#0067C0",
    createdAt: "2026-05-05",
    password: "fortune-tire2026",
    mobileSlug: "fortune-tire-mobile",
  },
  {
    slug: "fortune-tire-mobile",
    name: "Fortune Tire Explorer (Mobile)",
    company: "Fortune Tire",
    industry: "Automotive",
    prototypeFile: "/explorer/fortune-tire-mobile",
    logo: "/brand/assets/fortune-tire-icon.png",
    gateLogo: "/brand/assets/fortune-tire-logo-reverse.png",
    accentColor: "#0067C0",
    createdAt: "2026-05-05",
    password: "fortune-tire2026",
    formFactor: "mobile",
    hidden: true,
  },
  {
    slug: "formation",
    name: "Formation Explorer",
    company: "Formation at The Star",
    industry: "Hospitality",
    prototypeFile: "/explorer/formation",
    logo: "/brand/assets/formation-icon.png",
    gateLogo: "/brand/assets/formation-logo-reverse.png",
    accentColor: "#869397",
    createdAt: "2026-05-26",
    password: "formation2026",
  },
  {
    slug: "proven",
    name: "PROVEN Explorer",
    company: "PROVEN",
    industry: "Sports Technology",
    prototypeFile: "/explorer/proven",
    logo: "/brand/assets/proven-icon.png",
    gateLogo: "/brand/assets/proven-logo-reverse.png",
    accentColor: "#50C8EC",
    createdAt: "2026-05-29",
    password: "proven2026",
    mobileSlug: "proven-mobile",
  },
  {
    slug: "proven-mobile",
    name: "PROVEN Explorer (Mobile)",
    company: "PROVEN",
    industry: "Sports Technology",
    prototypeFile: "/explorer/proven-mobile",
    logo: "/brand/assets/proven-icon.png",
    gateLogo: "/brand/assets/proven-logo-reverse.png",
    accentColor: "#50C8EC",
    createdAt: "2026-05-29",
    password: "proven2026",
    formFactor: "mobile",
    hidden: true,
  },
  {
    slug: "poweringu",
    name: "PoweringU Foundation Explorer",
    company: "PoweringU Foundation",
    industry: "Education",
    prototypeFile: "/explorer/poweringu",
    logo: "/brand/assets/poweringu-icon.png",
    gateLogo: "/brand/assets/poweringu-logo-reverse.png",
    accentColor: "#14669A",
    createdAt: "2026-06-02",
    password: "poweringu2026",
  },
  {
    slug: "dossani-paradise",
    name: "Dossani Paradise Explorer",
    company: "Dossani Paradise Management",
    industry: "Retail",
    prototypeFile: "/explorer/dossani-paradise",
    logo: "/brand/assets/dossani-paradise-icon.png",
    gateLogo: "/brand/assets/dossani-paradise-logo-reverse.png",
    accentColor: "#FF0404",
    createdAt: "2026-06-03",
    password: "dossani2026",
  },
  {
    slug: "cutx",
    name: "CUTX Explorer",
    company: "Credit Union of Texas",
    industry: "Financial Services",
    prototypeFile: "/explorer/cutx",
    logo: "/brand/assets/cutx-icon.jpg",
    gateLogo: "/brand/assets/cutx-logo-reverse.png",
    accentColor: "#005290",
    createdAt: "2026-06-03",
    password: "cutx2026",
  },
];
